BEGIN TRANSACTION;
INSERT INTO Pokemon (pokedex_number, region_id, name, image, species, pri_type, sec_type, description)
VALUES 
(1, NULL, 'Bulbasaur', '1.png', 'Seed Pokemon', 'Grass', 'Poison', 'For some time after its birth, it grows by taking nourishment from the seed on its back.'),
(2, NULL, 'Ivysaur', '2.png', 'Seed Pokemon', 'Grass', 'Poison', 'When the bud on its back starts swelling, a sweet aroma wafts to indicate the flower''s coming bloom.'),
(3, NULL, 'Venusaur', '3.png', 'Seed Pokemon', 'Grass', 'Poison', 'After a rainy day, the flower on its back smells stronger. The scent attracts other Pokemon.'),
(4, NULL, 'Charmander', '4.png', 'Lizard Pokemon', 'Fire', NULL, 'The fire on the tip of its tail is a measure of its life. If the Pokemon is healthy, its tail burns intensely.'),
(5, NULL, 'Charmeleon', '5.png', 'Flame Pokemon', 'Fire', NULL, 'In the rocky mountains where Charmeleon live, their fiery tails shine at night like stars.'),
(6, NULL, 'Charizard', '6.png', 'Flame Pokemon', 'Fire', 'Flying', 'It is said that Charizard''s fire burns hotter if it has experienced harsh battles.'),
(7, NULL, 'Squirtle', '7.png', 'Tiny Turtle Pokemon', 'Water', NULL, 'It hides in its shell to protect itself, then strikes back with spouts of water at every opportunity.'),
(8, NULL, 'Wartortle', '8.png', 'Turtle Pokemon', 'Water', NULL, 'It is said to live 10,000 years. Its furry tail is popular as a symbol of longevity.'),
(9, NULL, 'Blastoise', '9.png', 'Shellfish Pokemon', 'Water', NULL, 'The jets of water it spouts from the rocket cannons on its shell can punch through thick steel.'),
(10, NULL, 'Caterpie', '10.png', 'Worm Pokemon', 'Bug', NULL, 'It releases a stench from its red antennae to repel enemies. It grows by molting repeatedly.'),
(11, NULL, 'Metapod', '11.png', 'Cocoon Pokemon', 'Bug', NULL, 'A steel-hard shell protects its tender body. The Pokemon quietly endures hardships while awaiting evolution.'),
(12, NULL, 'Butterfree', '12.png', 'Butterfly Pokemon', 'Bug', 'Flying', 'It loves the nectar of flowers and can locate flower patches that have even tiny amounts of pollen.'),
(13, NULL, 'Weedle', '13.png', 'Hairy Bug Pokemon', 'Bug', 'Poison', 'It eats its weight in leaves every day. It fends off attackers with the needle on its head.'),
(14, NULL, 'Kakuna', '14.png', 'Cocoon Pokemon', 'Bug', 'Poison', 'While awaiting evolution, it hides from predators under leaves and in nooks of branches.'),
(15, NULL, 'Beedrill', '15.png', 'Poison Bee Pokemon', 'Bug', 'Poison', 'Its best attack involves flying around at high speed, striking with poison needles, then flying off.'),
(16, NULL, 'Pidgey', '16.png', 'Tiny Bird Pokemon', 'Normal', 'Flying', 'It is docile and prefers to avoid conflict. If disturbed, however, it can ferociously strike back.'),
(17, NULL, 'Pidgeotto', '17.png', 'Bird Pokemon', 'Normal', 'Flying', 'It flies over its wide territory in search of prey, downing it with its highly developed claws.'),
(18, NULL, 'Pidgeot', '18.png', 'Bird Pokemon', 'Normal', 'Flying', 'By flapping its wings with all its might, Pidgeot can make a gust of wind capable of bending tall trees.'),
(19, NULL, 'Rattata', '19.png', 'Mouse Pokemon', 'Normal', NULL, 'It''s cautious in the extreme, and its hardy vitality lets it live in any kind of environment.'),
(19, 1, 'Rattata', '19-alolalola.png', 'Mouse Pokemon', 'Dark', 'Normal', 'Its whiskers provide it with a keen sense of smell, enabling it to pick up the scent of hidden food and locate it instantly.'),
(20, NULL, 'Raticate', '20.png', 'Mouse Pokemon', 'Normal', NULL, 'It whittles down its constantly growing fangs by gnawing on hard things. It can chew apart cinder block walls.'),
(20, 1, 'Raticate', '20-alola.png', 'Mouse Pokemon', 'Dark', 'Normal', 'It makes its Rattata underlings gather food for it, dining solely on the most nutritious and delicious fare.'),
(21, NULL, 'Spearow', '21.png', 'Tiny Bird Pokemon', 'Normal', 'Flying', 'It flaps its small wings busily to fly. Using its beak, it searches in grass for prey.'),
(22, NULL, 'Fearow', '22.png', 'Beak Pokemon', 'Normal', 'Flying', 'It has the stamina to fly all day on its broad wings. It fights by using its sharp beak.'),
(23, NULL, 'Ekans', '23.png', 'Snake Pokemon', 'Poison', NULL, 'It sneaks through grass without making a sound and strikes unsuspecting prey from behind.'),
(24, NULL, 'Arbok', '24.png', 'Cobra Pokemon', 'Poison', NULL, 'The pattern on its belly is for intimidation. It constricts foes while they are frozen in fear.'),
(25, NULL, 'Pikachu', '25.png', 'Mouse Pokemon', 'Electric', NULL, 'When it is angered, it immediately discharges the energy stored in the pouches in its cheeks.'),
(26, NULL, 'Raichu', '26.png', 'Mouse Pokemon', 'Electric', NULL, 'Its tail discharges electricity into the ground, protecting it from getting shocked.'),
(26, 1, 'Raichu', '26-alola.png', 'Mouse Pokemon', 'Electric', 'Psychic', 'This Pokemon rides on its tail while it uses its psychic powers to levitate. It attacks with star-shaped thunderbolts.'),
(27, NULL, 'Sandshrew', '27.png', 'Mouse Pokemon', 'Ground', NULL, 'To protect itself from attackers, it curls up into a ball. It lives in arid regions with minimal rainfall.'),
(27, 1, 'Sandshrew', '27-alola.png', 'Mouse Pokemon', 'Ice', 'Steel', 'It lives in snowy mountains on southern islands. When a blizzard rolls in, this Pokemon hunkers down in the snow to avoid getting blown away.'),
(28, NULL, 'Sandslash', '28.png', 'Mouse Pokemon', 'Ground', NULL, 'It curls up, then rolls into foes with its back. Its sharp spines inflict severe damage.'),
(28, 1, 'Sandslash', '28-alola.png', 'Mouse Pokemon', 'Ice', 'Steel', 'Many people climb snowy mountains, hoping to see the icy spikes of these Pokemon glistening in the light of dawn.'),
(29, NULL, 'Nidoran (female)', '29.png', 'Poison Pin Pokemon', 'Poison', NULL, 'While this Pokemon does not prefer to fight, even one drop of the venom it secretes from its barbs can be fatal.'),
(30, NULL, 'Nidorina', '30.png', 'Poison Pin Pokemon', 'Poison', NULL, 'When it senses danger, it raises all the barbs on its body. These barbs grow more slowly than Nidorino''s.'),
(31, NULL, 'Nidoqueen', '31.png', 'Drill Pokemon', 'Poison', 'Ground', 'Its entire body is armored with hard scales. It will protect the young in its burrow with its life.'),
(32, NULL, 'Nidoran (male)', '32.png', 'Poison Pin Pokemon', 'Poison', NULL, 'It scans its surroundings by raising its ears out of the grass. Its toxic horn is for protection.'),
(33, NULL, 'Nidorino', '33.png', 'Poison Pin Pokemon', 'Poison', NULL, 'It has a violent disposition and stabs foes with its horn, which oozes venom upon impact.'),
(34, NULL, 'Nidoking', '34.png', 'Drill Pokemon', 'Poison', 'Ground', 'One swing of its mighty tail can snap a telephone pole as if it were a matchstick.'),
(35, NULL, 'Clefairy', '35.png', 'Fairy Pokemon', 'Fairy', NULL, 'It can be found in quiet mountain areas on a full moon''s night. Its dancing and its tiny, faintly glowing wings confer upon it a lovely fairylike quality.'),
(36, NULL, 'Clefable', '36.png', 'Fairy Pokemon', 'Fairy', NULL, 'Legend says that on clear, quiet nights, it listens for the voices of its kin living on the moon. I, too, often think of my homeland, so far away.'),
(37, NULL, 'Vulpix', '37.png', 'Fox Pokemon', 'Fire', NULL, 'In its belly burns a fire, which Vulpix spits out in the form of fireballs. When young, this Pokemon has but one white tail. As the Pokemon matures, this single tail splits into six.'),
(37, 1, 'Vulpix', '37-alola.png', 'Fox Pokemon', 'Ice', NULL, 'These Pokemon live in packs in the snowy mountains and defend themselves with icy breath. I suspect this species changed its form to adapt to the frigid climate.'),
(38, NULL, 'Ninetales', '38.png', 'Fox Pokemon', 'Fire', NULL, 'The coat of gleaming golden fur is quite magnificent. This species is said to store sacred power in its nine long tails and to live for a millennium.'),
(38, 1, 'Ninetales', '38-alola.png', 'Fox Pokemon', 'Ice', NULL, 'Dwells on sacred peaks perpetually covered in snow. Said to appear to virtuous people who have lost their way on mountain paths—it then guides them back down to the mountain''s base.'),
(39, NULL, 'Jigglypuff', '39.png', 'Balloon Pokemon', 'Normal', 'Fairy', 'When its huge eyes waver, it sings a mysteriously soothing melody that lulls its enemies to sleep.'),
(40, NULL, 'Wigglytuff', '40.png', 'Balloon Pokemon', 'Normal', 'Fairy', 'The rich, fluffy fur that covers its body feels so good that anyone who feels it can''t stop touching it.'),
(41, NULL, 'Zubat', '41.png', 'Bat Pokemon', 'Poison', 'Flying', 'Makes its home in gloomy caves. Atrophied eyes have left this Pokemon blind, so it scans its surroundings via sound waves that it emits from its mouth as it flies.'),
(42, NULL, 'Golbat', '42.png', 'Bat Pokemon', 'Poison', 'Flying', 'It sinks its sharp fangs into other creatures and slurps up their blood. A closer look at the fangs reveals that they are hollow and akin to straws.'),
(43, NULL, 'Oddish', '43.png', 'Weed Pokemon', 'Grass', 'Poison', 'It often plants its root feet in the ground during the day and sows seeds as it walks about at night.'),
(44, NULL, 'Gloom', '44.png', 'Weed Pokemon', 'Grass', 'Poison', 'The nectar it drools from its mouth smells so atrocious that it can make noses curl from more than a mile away.'),
(45, NULL, 'Vileplume', '45.png', 'Flower Pokemon', 'Grass', 'Poison', 'Its petals are the largest in the world. As it walks, it scatters extremely allergenic pollen.'),
(46, NULL, 'Paras', '46.png', 'Mushroom Pokemon', 'Bug', 'Grass', 'Sometimes seen at the foot of trees in humid forests. The mushrooms on its back—called tochukaso—are not present on infant specimens and instead emerge as Paras matures.'),
(47, NULL, 'Parasect', '47.png', 'Mushroom Pokemon', 'Bug', 'Grass', 'Mushroom-lacking specimens of this Pokemon lie unmoving in the forest, lending credence to the hypothesis that the large mushroom is in control of Parasect''s actions.'),
(48, NULL, 'Venonat', '48.png', 'Insect Pokemon', 'Bug', 'Poison', 'Its eyes act as radar, enabling it to be active in darkness. The eyes can also shoot powerful beams.'),
(49, NULL, 'Venomoth', '49.png', 'Poison Moth Pokemon', 'Bug', 'Poison', 'The wings are covered with dustlike scales. Every time it flaps its wings, it looses highly toxic dust.'),
(50, NULL, 'Diglett', '50.png', 'Mole Pokemon', 'Ground', NULL, 'It lives about one yard underground, where it feeds on plant roots. It sometimes appears aboveground.'),
(50, NULL, 'Diglett', '50-alola.png', 'Mole Pokemon', 'Ground', 'Steel', 'Its three hairs change shape depending on Diglett''s mood. They''re a useful communication tool among these Pokemon.'),
(51, NULL, 'Dugtrio', '51.png', 'Mole Pokemon', 'Ground', NULL, 'Its three heads bob separately up and down to loosen the soil nearby, making it easier for it to burrow.'),
(51, NULL, 'Dugtrio', '51-alola.png', 'Mole Pokemon', 'Ground', 'Steel', 'Their beautiful, metallic whiskers create a sort of protective helmet on their heads, and they also function as highly precise sensors.'),
(52, NULL, 'Meowth', '52.png', 'Scratch Cat Pokemon', 'Normal', NULL, 'It loves things that sparkle. When it sees a shiny object, the gold coin on its head shines, too.'),
(52, 1, 'Meowth', '52-alola.png', 'Scratch Cat Pokemon', 'Dark', NULL, 'Deeply proud and keenly smart, this Pokemon moves with cunning during battle and relentlessly attacks enemies'' weak points.'),
(52, 2, 'Meowth', '52-galar.png', 'Scratch Cat Pokemon', 'Steel', NULL, 'These daring Pokemon have coins on their foreheads. Darker coins are harder, and harder coins garner more respect among Meowth.'),
(53, NULL, 'Persian', '53.png', 'Classy Cat Pokemon', 'Normal', NULL, 'It has a vicious temperament. Beware if it raises its tail straight up. This is a signal that it is about to pounce and bite.'),
(53, 1, 'Persian', '53-alola.png', 'Classy Cat Pokemon', 'Dark', NULL, 'This Pokemon is one tough opponent. Not only does it have formidable physical abilities, but it''s also not above fighting dirty.'),
(54, NULL, 'Psyduck', '54.png', 'Duck Pokemon', 'Water', NULL, 'It is constantly wracked by a headache. When the headache turns intense, it begins using mysterious powers.'),
(55, NULL, 'Golduck', '55.png', 'Duck Pokemon', 'Water', NULL, 'When it swims at full speed using its long, webbed limbs, its forehead somehow begins to glow.'),
(56, NULL, 'Mankey', '56.png', 'Pig Monkey Pokemon', 'Fighting', NULL, 'It is extremely quick to anger. It could be docile one moment, then thrashing away the next instant.'),
(57, NULL, 'Primeape', '57.png', 'Pig Monkey Pokemon', 'Fighting', NULL, 'It becomes wildly furious if it even senses someone looking at it. It chases anyone that meets its glare.'),
(58, NULL, 'Growlithe', '58.png', 'Puppy Pokemon', 'Fire', NULL, 'It has a brave and trustworthy nature. It fearlessly stands up to bigger and stronger foes.'),
(58, 3, 'Growlithe', '58-hisui.png', 'Scout Pokemon', 'Fire', 'Rock', 'They patrol their territory in pairs. I believe the igneous rock components in the fur of this species are the result of volcanic activity in its habitat.'),
(59, NULL, 'Arcanine', '59.png', ' Pokemon', 'Fire', NULL, 'Its magnificent bark conveys a sense of majesty. Anyone hearing it can''t help but grovel before it.'),
(59, 3, 'Arcanine', '59-hisui.png', ' Pokemon', 'Fire', 'Rock', 'Snaps at its foes with fangs cloaked in blazing flame. Despite its bulk, it deftly feints every which way, leading opponents on a deceptively merry chase as it all but dances around them.'),
(60, NULL, 'Poliwag', '60.png', 'Tadpole Pokemon', 'Water', NULL, 'Its skin is so thin, its internal organs are visible. It has trouble walking on its newly grown feet.'),
(61, NULL, 'Poliwhirl', '61.png', 'Tadpole Pokemon', 'Water', NULL, 'The spiral pattern on its belly subtly undulates. Staring at it gradually causes drowsiness.'),
(62, NULL, 'Poliwrath', '62.png', 'Tadpole Pokemon', 'Water', 'Fighting', 'With its extremely tough muscles, it could keep swimming in the Pacific Ocean without resting.'),
(63, NULL, 'Abra', '63.png', 'Psi Pokemon', 'Psychic', NULL, 'Spends 18 hours of the day sleeping. Even while asleep, Abra can control its psychic powers—should danger approach, the Pokemon will simply teleport away.'),
(64, NULL, 'Kadabra', '64.png', 'Psi Pokemon', 'Psychic', NULL, 'There are rumors that a child with mystical powers became a Kadabra; however, this remains unverified. I suspect that the spoon Kadabra holds enhances its brain waves.'),
(65, NULL, 'Alakazam', '65.png', 'Psi Pokemon', 'Psychic', NULL, 'The longer Alakazam lives, the larger and heavier its head becomes. Our tests have shown that the strength of its psychic powers correlates positively to the weight of its head.'),
(66, NULL, 'Machop', '66.png', 'Superpower Pokemon', 'Fighting', NULL, 'Though as small as a child, it has strength enough to easily throw a well-built adult. Striving to become ever stronger, Machop trains by carrying a Graveler on its shoulders.'),
(67, NULL, 'Machoke', '67.png', 'Superpower Pokemon', 'Fighting', NULL, 'A sturdy creature boasting a robust physique and boundless stamina. Loves training above all else and voluntarily assists with tasks such as construction and clearing land.'),
(68, NULL, 'Machamp', '68.png', 'Superpower Pokemon', 'Fighting', NULL, 'In close combat, its four arms afford it offensive and defensive supremacy. In but a blink, this valiant Pokemon can overwhelm its foes with more than 1,000 blows from its fists.'),
(69, NULL, 'Bellsprout', '69.png', 'Flower Pokemon', 'Grass', 'Poison', 'It prefers hot and humid environments. It is quick at capturing prey with its vines.'),
(70, NULL, 'Weepinbell', '70.png', 'Flycatcher Pokemon', 'Grass', 'Poison', 'This Pokemon has the appearance of a plant. It captures unwary prey by dousing them with a toxic powder.'),
(71, NULL, 'Victreebel', '71.png', 'Flycatcher Pokemon', 'Grass', 'Poison', 'In its mouth, it pools a fragrant nectar-like fluid. The fluid is really an acid that dissolves anything.'),
(72, NULL, 'Tentacool', '72.png', 'Jellyfish Pokemon', 'Water', 'Poison', 'They fire beams from the glassy, magenta orbs that resemble eyes atop their heads, and they drift in shallow seas. During low tide, they can sometimes be found on beaches, desiccated.'),
(73, NULL, 'Tentacruel', '73.png', 'Jellyfish Pokemon', 'Water', 'Poison', 'It has 80 tentacles, each with a venomous tip. These tentacles are also extendible, lengthening when Tentacruel attempts to catch prey. Use caution.'),
(74, NULL, 'Geodude', '74.png', 'Rock Pokemon', 'Rock', 'Ground', 'Makes its home in mountainous regions, using its arms to climb along harsh mountain roads. Can be troublesome—carelessly kicking one will cause it to fly into a rage and chase after you.'),
(74, 1, 'Geodude', '74-alola.png', 'Rock Pokemon', 'Rock', 'Electric', 'Its stone head is imbued with electricity and magnetism. If you carelessly step on one, you''ll be in for a painful shock.'),
(75, NULL, 'Graveler', '75.png', 'Rock Pokemon', 'Rock', 'Ground', 'Dwells in holes dug into sheer walls of stone. It enjoys rolling down slopes as though it were a boulder during a rockfall, so keep an eye upward while traversing mountain roads.'),
(75, 1, 'Graveler', '75-alola.png', 'Rock Pokemon', 'Rock', 'Electric', 'When it comes rolling down a mountain path, anything in its way gets zapped by electricity and sent flying.'),
(76, NULL, 'Golem', '76.png', 'Rock Pokemon', 'Rock', 'Ground', 'The rocklike shell is shed each year. The cast-off shell then crumbles, reverting to a mass of soil, which can be spread across fields to promote crop growth.'),
(76, 1, 'Golem', '76-alola.png', 'Rock Pokemon', 'Rock', 'Electric', 'It uses magnetism to accelerate and fire off rocks tinged with electricity. Even if it doesn''t score a direct hit, the jolt of electricity will do the job.'),
(77, NULL, 'Ponyta', '77.png', 'Fire Horse Pokemon', 'Fire', NULL, 'These Pokemon live in herds out in the grassland. Newborn foals lack their fiery manes, which will develop about an hour after birth.'),
(77, 2, 'Ponyta', '77-galar.png', 'Unique Horn Pokemon', 'Psychic', NULL, 'This Pokemon will look into your eyes and read the contents of your heart. If it finds evil there, it promptly hides away.'),
(78, NULL, 'Rapidash', '78.png', 'Fire Horse Pokemon', 'Fire', NULL, 'Fiery mane aglow, Rapidash darts like an arrow across the land. This prodigiously swift creature can traverse the vast region of Hisui in a day and a half.'),
(78, 2, 'Rapidash', '78-galar.png', 'Unique Horn Pokemon', 'Psychic', 'Fairy', 'Brave and prideful, this Pokemon dashes airily through the forest, its steps aided by the psychic power stored in the fur on its fetlocks.'),
(79, NULL, 'Slowpoke', '79.png', 'Dopey Pokemon', 'Water', 'Psychic', 'It is always vacantly lost in thought, but no one knows what it is thinking about. It is good at fishing with its tail.'),
(79, 2, 'Slowpoke', '79-galar.png', 'Dopey Pokemon', 'Psychic', NULL, 'Because Galarian Slowpoke eat the seeds of a plant that grows only in Galar, their tails have developed a spicy flavor.'),
(80, NULL, 'Slowbro', '80.png', 'Hermit Crab Pokemon', 'Water', 'Psychic', 'If the tail-biting Shellder is thrown off in a harsh battle, this Pokemon reverts to being an ordinary Slowpoke.'),
(80, 2, 'Slowbro', '80-galar.png', 'Hermit Crab Pokemon', 'Poison', 'Psychic', 'If this Pokemon squeezes the tongue of the Shellder biting it, the Shellder will launch a toxic liquid from the tip of its shell.'),
(81, NULL, 'Magnemite', '81.png', 'Magnet Pokemon', 'Electric', 'Steel', 'It moves while constantly hovering. It discharges electromagnetic waves and so on from the units at its sides.'),
(28, NULL, 'Magneton', '82.png', 'Magnet Pokemon', 'Electric', 'Steel', 'Three Magnemite are linked by a strong magnetic force. Earaches will occur if you get too close.'),
(83, NULL, 'Farfetch''d', '83.png', 'Wild Duck Pokemon', 'Normal', 'Flying', 'It can''t live without the stalk it holds. That''s why it defends the stalk from attackers with its life.'),
(83, 2, 'Farfetch''d', '83-galar.png', 'Wild Duck Pokemon', 'Fighting', NULL, 'The Farfetch''d of the Galar region are brave warriors, and they wield thick, tough leeks in battle.'),
(84, NULL, 'Doduo', '84.png', 'Twin Bird Pokemon', 'Normal', 'Flying', 'The brains in its two heads appear to communicate emotions to each other with a telepathic power.'),
(85, NULL, 'Dodrio', '85.png', 'Triple Bird Pokemon', 'Normal', 'Flying', 'When Doduo evolves into this odd breed, one of its heads splits into two. This Pokemon runs at nearly 40 mph.'),
(86, NULL, 'Seel', '86.png', 'Sea Lion Pokemon', 'Water', NULL, 'This Pokemon lives on icebergs. It uses the sharp point on its head to break up ice as it swims in the sea.'),
(87, NULL, 'Dewgong', '87.png', 'Sea Lion Pokemon', 'Water', 'Ice', 'In snow, the pure white coat covering its body obscures it from predators.'),
(88, NULL, 'Grimer', '88.png', 'Sludge Pokemon', 'Poison', NULL, 'Born from sludge, these Pokemon now gather in polluted places and increase the bacteria in their bodies.'),
(88, 1, 'Grimer', '88-alola.png', 'Sludge Pokemon', 'Poison', 'Dark', 'It has a passion for trash above all else, speedily digesting it and creating brilliant crystals of sparkling poison.'),
(89, NULL, 'Muk', '89.png', 'Sludge Pokemon', 'Poison', NULL, 'It''s thickly covered with a filthy, vile sludge. It is so toxic, even its footprints contain poison.'),
(89, 1, 'Muk', '89-alola.png', 'Sludge Pokemon', 'Poison', 'Dark', 'What look like fangs and claws are actually crystallized poison that will afflict you at a mere touch, so don''t get too close.'),
(90, NULL, 'Shellder', '90.png', 'Bivalve Pokemon', 'Water', NULL, 'Clamping on to an opponent reveals its vulnerable parts, so it uses this move only as a last resort.'),
(91, NULL, 'Cloyster', '91.png', 'Bivalve Pokemon', 'Water', 'Ice', 'When attacked, it launches its spikes in quick volleys. Its innards have never been seen.'),
(92, NULL, 'Gastly', '92.png', 'Gas Pokemon', 'Ghost', 'Poison', 'Its body is made of gas. Despite lacking substance, it can envelop an opponent of any size and cause suffocation.'),
(93, NULL, 'Haunter', '93.png', 'Gas Pokemon', 'Ghost', 'Poison', 'It likes to lurk in the dark and tap shoulders with a gaseous hand. Its touch causes endless shuddering.'),
(94, NULL, 'Gengar', '94.png', 'Shadow Pokemon', 'Ghost', 'Poison', 'To steal the life of its target, it slips into the prey''s shadow and silently waits for an opportunity.'),
(95, NULL, 'Onix', '95.png', 'Rock Snake Pokemon', 'Rock', 'Ground', 'This chain of immense stones resembles a giant serpent. Tremors shake the earth above as it burrows deep beneath the ground, feeding on boulders as it goes.'),
(96, NULL, 'Drowzee', '96.png', 'Hypnosis Pokemon', 'Psychic', NULL, 'It remembers every dream it eats. It rarely eats the dreams of adults because children''s are much tastier.'),
(97, NULL, 'Hypno', '97.png', 'Hypnosis Pokemon', 'Psychic', NULL, 'Always holding a pendulum that it swings at a steady rhythm, it causes drowsiness in anyone nearby.'),
(98, NULL, 'Krabby', '98.png', 'River Crab Pokemon', 'Water', NULL, 'It lives in burrows dug on sandy beaches. Its pincers fully grow back if they are lost in battle.'),
(99, NULL, 'Kingler', '99.png', 'Pincer Pokemon', 'Water', NULL, 'The larger pincer has 10,000-horsepower strength. However, it is so heavy, it is difficult to aim.'),
(100, NULL, 'Voltorb', '100.png', 'Ball Pokemon', 'Electric', NULL, 'It rolls to move. If the ground is uneven, a sudden jolt from hitting a bump can cause it to explode.'),
(100, 3, 'Voltorb', '100-hisui.png', 'Sphere Pokemon', 'Electric', 'Grass', 'An enigmatic Pokemon that happens to bear a resemblance to a Poké Ball. When excited, it discharges the electric current it has stored in its belly, then lets out a great, uproarious laugh.'),
(101, NULL, 'Electrode', '101.png', 'Ball Pokemon', 'Electric', NULL, 'It explodes in response to even minor stimuli. It is feared, with the nickname of the Bomb Ball.'),
(101, 3, 'Electrode', '101-hisui.png', 'Sphere Pokemon', 'Electric', 'Grass', 'The tissue on the surface of its body is curiously similar in composition to an Apricorn. When irritated, this Pokemon lets loose an electric current equal to 20 lightning bolts.'),
(102, NULL, 'Exeggcute', '102.png', 'Egg Pokemon', 'Grass', 'Psychic', 'Its six eggs converse using telepathy. They can quickly gather if they become separated.'),
(103, NULL, 'Exeggutor', '103.png', 'Coconut Pokemon', 'Grass', 'Psychic', 'It is called the Walking Jungle. If a head grows too big, it falls off and becomes an Exeggcute.'),
(103, 1, 'Exeggutor', '103-alola.png', 'Coconut Pokemon', 'Grass', 'Dragon', 'This Pokemon''s psychic powers aren''t as strong as they once were. The head on this Exeggutor''s tail scans surrounding areas with weak telepathy.'),
(104, NULL, 'Cubone', '104.png', 'Lonely Pokemon', 'Ground', NULL, 'This Pokemon wears the skull of its deceased mother. Sometimes Cubone''s dreams make it cry, but each tear Cubone sheds makes it stronger.'),
(105, NULL, 'Marowak', '105.png', 'Bone Keeper Pokemon', 'Ground', NULL, 'The bones it uses have been in its possession since it was born. It has a ferocious nature.'),
(105, 1, 'Marowak', '105-alola.png', 'Bone Keeper Pokemon', 'Fire', 'Ghost', 'The cursed flames that light up the bone carried by this Pokemon are said to cause both mental and physical pain that will never fade.'),
(106, NULL, 'Hitmonlee', '106.png', 'Kicking Pokemon', 'Fighting', NULL, 'Its legs can stretch to double their length. First-time foes are startled by Hitmonlee''s extensible reach.'),
(107, NULL, 'Hitmonchan', '107.png', 'Punching Pokemon', 'Fighting', NULL, 'When Hitmonchan twists its arm while throwing a punch, the blow will pulverize even concrete. The Pokemon rests after three minutes of fighting.'),
(108, NULL, 'Lickitung', '108.png', 'Licking Pokemon', 'Normal', NULL, 'Wields its long tongue deftly, as though it were an arm. The Pokemon''s viscous saliva, once it has been collected and boiled down, yields a strong and highly useful adhesive.'),
(109, NULL, 'Koffing', '109.png', 'Poison Gas Pokemon', 'Poison', NULL, 'Toxic gas is held within its thin, balloon-shaped body, so it can cause massive explosions.'),
(110, NULL, 'Weezing', '110.png', 'Poison Gas Pokemon', 'Poison', NULL, 'It grows by feeding on gases released by garbage. Though very rare, triplets have been found.'),
(110, 2, 'Weezing', '110-galar.png', 'Poison Gas Pokemon', 'Poison', 'Fairy', 'Long ago, during a time when droves of factories fouled the air with pollution, Weezing changed into this form for some reason.'),
(111, NULL, 'Rhyhorn', '111.png', 'Spikes Pokemon', 'Ground', 'Rock', 'Ludicrously strong—when it butts heads with a mountain, it is the mountain that shatters. But its short legs struggle with turns, and it is incapable of stopping unless it collides with something.'),
(112, NULL, 'Rhydon', '112.png', 'Drill Pokemon', 'Ground', 'Rock', 'Rapidly rotates its horn to bore through bedrock. It swaggers around volcanic regions, protected from the lava''s heat by its tough, armorlike hide.'),
(113, NULL, 'Chansey', '113.png', 'Egg Pokemon', 'Normal', NULL, 'This kindly Pokemon lays highly nutritious eggs and shares them with injured Pokemon or people.'),
(114, NULL, 'Tangela', '114.png', 'Vine Pokemon', 'Grass', NULL, 'It is cloaked entirely in blue vines, preventing any glimpse of its true identity. The vines impart a refreshing sensation when chewed—they''re useful as a spice.'),
(115, NULL, 'Kangaskhan', '115.png', 'Parent Pokemon', 'Normal', NULL, 'It raises its offspring in its belly pouch. It lets its baby out to play only when it feels safe to do so.'),
(116, NULL, 'Horsea', '116.png', 'Dragon Pokemon', 'Water', NULL, 'It makes its nest in the shade of corals. If it senses danger, it spits black ink and flees.'),
(117, NULL, 'Seadra', '117.png', 'Dragon Pokemon', 'Water', NULL, 'Its spines provide protection. Its fins and bones are prized as traditional medicine ingredients.'),
(118, NULL, 'Goldeen', '118.png', 'Goldfish Pokemon', 'Water', NULL, 'It swims at a steady five knots. If it senses danger, it will strike back with its sharp horn.'),
(119, NULL, 'Seaking', '119.png', 'Goldfish Pokemon', 'Water', NULL, 'To protect its family, it will fight with its drill-sharp horn. It lives in hollowed rocks in streams.'),
(120, NULL, 'Staryu', '120.png', 'Star Shape Pokemon', 'Water', NULL, 'If Staryu''s body is damaged, it will regenerate as long as the red core remains. The core flashes at midnight.'),
(121, NULL, 'Starmie', '121.png', 'Mysterious Pokemon', 'Water', NULL, 'At the center of its body is a red core that sends mysterious radio signals into the night sky.'),
(122, NULL, 'Mr. Mime', '122.png', 'Barrier Pokemon', 'Psychic', 'Fairy', 'The behavior of this clown-like Pokemon reminds one of pantomime. It creates invisible walls using a force emitted from its fingertips.'),
(122, 2, 'Mr. Mime', '122-galar.png', 'Dancing Pokemon', 'Ice', 'Psychic', 'Its talent is tap-dancing. It can also manipulate temperatures to create a floor of ice, which this Pokemon can kick up to use as a barrier.'),
(123, NULL, 'Scyther', '123.png', 'Mantis Pokemon', 'Bug', 'Flying', 'The sharp scythes on its forearms become increasingly sharp by cutting through hard objects.'),
(124, NULL, 'Jynx', '124.png', 'Human Shape Pokemon', 'Ice', 'Psychic', 'Its cries sound like human speech. However, it is impossible to tell what it is trying to say.'),
(125, NULL, 'Electabuzz', '125.png', 'Electric Pokemon', 'Electric', NULL, 'Feeds on electrical energy. During sudden showers beneath looming thunderclouds, one can observe Electabuzz scaling tall trees, where the Pokemon will then wait for lightning to strike.'),
(126, NULL, 'Magmar', '126.png', 'Spitfire Pokemon', 'Fire', NULL, 'Legend has it that this Pokemon was born from the crater of a volcano. When wounded, it bathes in lava to heal its body, much as one would soak in a hot spring.'),
(127, NULL, 'Pinsir', '127.png', 'Stag Beetle Pokemon', 'Bug', NULL, 'It grips prey with its pincers until the prey is torn apart. What it can''t tear, it tosses far away.'),
(128, NULL, 'Tauros', '128.png', 'Wild Bull Pokemon', 'Normal', NULL, 'When it targets an enemy, it charges furiously while whipping its body with its long tails.'),
(128, 4, 'Tauros', '128.png', 'Wild Bull Pokemon', 'Fighting', NULL, 'This kind of Tauros, known as the Combat Breed, is distinguished by its thick, powerful muscles and its fierce disposition.'),
(129, NULL, 'Magikarp', '129.png', 'Fish Pokemon', 'Water', NULL, 'An underpowered, pathetic Pokemon. It may jump high on rare occasions but never more than seven feet.'),
(130, NULL, 'Gyarados', '130.png', 'Atrocious Pokemon', 'Water', 'Flying', 'Once it appears, it goes on a rampage. It remains enraged until it demolishes everything around it.'),
(131, NULL, 'Lapras', '131.png', 'Transport Pokemon', 'Water', 'Ice', 'It loves crossing the sea with people and Pokemon on its back. It understands human speech.'),
(132, NULL, 'Ditto', '132.png', 'Transform Pokemon', 'Normal', NULL, 'It can freely recombine its own cellular structure to transform into other life-forms.'),
(133, NULL, 'Eevee', '133.png', 'Evolution Pokemon', 'Normal', NULL, 'Its ability to evolve into many forms allows it to adapt smoothly and perfectly to any environment.'),
(134, NULL, 'Vaporeon', '134.png', 'Bubble Jet Pokemon', 'Water', NULL, 'Its cell composition is similar to water molecules. As a result, it can''t be seen when it melts away into water.'),
(135, NULL, 'Jolteon', '135.png', 'Lightning Pokemon', 'Electric', NULL, 'If agitated, it uses electricity to straighten out its fur and launch it in small bunches.'),
(136, NULL, 'Flareon', '136.png', 'Flame Pokemon', 'Fire', NULL, 'Inhaled air is carried to its flame sac, heated, and exhaled as fire that reaches over 3,000 degrees Fahrenheit.'),
(137, NULL, 'Porygon', '137.png', 'Virtual Pokemon', 'Normal', NULL, 'The world''s first artificially created Pokemon. It can travel through electronic space.'),
(138, NULL, 'Omanyte', '138.png', 'Spiral Pokemon', 'Rock', 'Water', 'It''s a Pokemon that was resurrected from a fossil using modern science. It swam in ancient seas.'),
(139, NULL, 'Omastar', '139.png', 'Spiral Pokemon', 'Rock', 'Water', 'It is thought that this Pokemon became extinct because its spiral shell grew too large.'),
(140, NULL, 'Kabuto', '140.png', 'Shellfish Pokemon', 'Rock', 'Water', 'It is thought to have inhabited beaches 300 million years ago. It is protected by a sturdy shell.'),
(141, NULL, 'Kabutops', '141.png', 'Shellfish Pokemon', 'Rock', 'Water', 'It is thought that this Pokemon came onto land because its prey adapted to life on land.'),
(142, NULL, 'Aerodactyl', '142.png', 'Fossil Pokemon', 'Rock', 'Flying', 'It''s a Pokemon that roamed the skies in the dinosaur era. Its teeth are like saw blades.'),
(143, NULL, 'Snorlax', '143.png', 'Sleeping Pokemon', 'Normal', NULL, 'This glutton appears in villages without warning and devours the entirety of their rice granaries—such occurrences have long been counted among the gravest of disasters.'),
(144, NULL, 'Articuno', '144.png', 'Freeze Pokemon', 'Ice', 'Flying', 'This legendary bird Pokemon can create blizzards by freezing moisture in the air.'),
(144, 2, 'Articuno', '144.png', 'Cruel Pokemon', 'Psychic', 'Flying', 'Known as Articuno, this Pokemon fires beams that can immobilize opponents as if they had been frozen solid.'),
(145, NULL, 'Zapdos', '145.png', 'Electric Pokemon', 'Electric', 'Flying', 'This legendary Pokemon is said to live in thunderclouds. It freely controls lightning bolts.'),
(145, 2, 'Zapdos', '145.png', 'Strong Legs Pokemon', 'Fighting', 'Flying', 'One kick from its powerful legs will pulverize a dump truck. Supposedly, this Pokemon runs through the mountains at over 180 mph.'),
(146, NULL, 'Moltres', '146.png', 'Flame Pokemon', 'Fire', 'Flying', 'It is one of the legendary bird Pokemon. Its appearance is said to indicate the coming of spring.'),
(146, 2, 'Moltres', '146.png', 'Malevolent Pokemon', 'Dark', 'Flying', 'This Pokemon''s sinister, flame-like aura will consume the spirit of any creature it hits. Victims become burned-out shadows of themselves.'),
(147, NULL, 'Dratini', '147.png', 'Dragon Pokemon', 'Dragon', NULL, 'It is born large to start with. It repeatedly sheds its skin as it steadily grows longer.'),
(148, NULL, 'Dragonair', '148.png', 'Dragon Pokemon', 'Dragon', NULL, 'It is called the divine Pokemon. When its entire body brightens slightly, the weather changes.'),
(149, NULL, 'Dragonite', '149.png', 'Dragon Pokemon', 'Dragon', 'Flying', 'It can fly in spite of its big and bulky physique. It circles the globe in just 16 hours.'),
(150, NULL, 'Mewtwo', '150.png', 'Genetic Pokemon', 'Psychic', NULL, 'Mewtwo was created by recombining Mew''s genes. It''s said to have the most savage heart among Pokemon.'),
(151, NULL, 'Mew', '151.png', 'New Species Pokemon', 'Psychic', NULL, 'Because it can use all kinds of moves, many scientists believe Mew to be the ancestor of Pokemon.'),
(152, NULL, '', '152.png', ' Pokemon', '', '', ''),
(153, NULL, '', '153.png', ' Pokemon', '', '', ''),
(154, NULL, '', '154.png', ' Pokemon', '', '', ''),
(155, NULL, '', '155.png', ' Pokemon', '', '', ''),
(156, NULL, '', '156.png', ' Pokemon', '', '', ''),
(157, NULL, '', '157.png', ' Pokemon', '', '', ''),
(158, NULL, '', '158.png', ' Pokemon', '', '', ''),
(159, NULL, '', '159.png', ' Pokemon', '', '', ''),
(160, NULL, '', '160.png', ' Pokemon', '', '', ''),
(161, NULL, '', '161.png', ' Pokemon', '', '', ''),
(162, NULL, '', '162.png', ' Pokemon', '', '', ''),
(163, NULL, '', '163.png', ' Pokemon', '', '', ''),
(164, NULL, '', '164.png', ' Pokemon', '', '', ''),
(165, NULL, '', '165.png', ' Pokemon', '', '', ''),
(166, NULL, '', '166.png', ' Pokemon', '', '', ''),
(167, NULL, '', '167.png', ' Pokemon', '', '', ''),
(168, NULL, '', '168.png', ' Pokemon', '', '', ''),
(169, NULL, '', '169.png', ' Pokemon', '', '', ''),
(170, NULL, '', '170.png', ' Pokemon', '', '', ''),
(171, NULL, '', '171.png', ' Pokemon', '', '', ''),
(172, NULL, '', '172.png', ' Pokemon', '', '', ''),
(173, NULL, '', '173.png', ' Pokemon', '', '', ''),
(174, NULL, '', '174.png', ' Pokemon', '', '', ''),
(175, NULL, '', '175.png', ' Pokemon', '', '', ''),
(176, NULL, '', '176.png', ' Pokemon', '', '', ''),
(177, NULL, '', '177.png', ' Pokemon', '', '', ''),
(178, NULL, '', '178.png', ' Pokemon', '', '', ''),
(179, NULL, '', '179.png', ' Pokemon', '', '', ''),
(180, NULL, '', '180.png', ' Pokemon', '', '', ''),
(181, NULL, '', '181.png', ' Pokemon', '', '', ''),
(182, NULL, '', '182.png', ' Pokemon', '', '', ''),
(183, NULL, '', '183.png', ' Pokemon', '', '', ''),
(184, NULL, '', '184.png', ' Pokemon', '', '', ''),
(185, NULL, '', '185.png', ' Pokemon', '', '', ''),
(186, NULL, '', '186.png', ' Pokemon', '', '', ''),
(187, NULL, '', '187.png', ' Pokemon', '', '', ''),
(188, NULL, '', '188.png', ' Pokemon', '', '', ''),
(189, NULL, '', '189.png', ' Pokemon', '', '', ''),
(190, NULL, '', '190.png', ' Pokemon', '', '', ''),
(191, NULL, '', '191.png', ' Pokemon', '', '', ''),
(192, NULL, '', '192.png', ' Pokemon', '', '', ''),
(193, NULL, '', '193.png', ' Pokemon', '', '', ''),
(194, NULL, '', '194.png', ' Pokemon', '', '', ''),
(195, NULL, '', '195.png', ' Pokemon', '', '', ''),
(196, NULL, '', '196.png', ' Pokemon', '', '', ''),
(197, NULL, '', '197.png', ' Pokemon', '', '', ''),
(198, NULL, '', '198.png', ' Pokemon', '', '', ''),
(199, NULL, '', '199.png', ' Pokemon', '', '', ''),
(200, NULL, '', '200.png', ' Pokemon', '', '', ''),
(201, NULL, '', '201.png', ' Pokemon', '', '', ''),
(202, NULL, '', '202.png', ' Pokemon', '', '', ''),
(203, NULL, '', '203.png', ' Pokemon', '', '', ''),
(204, NULL, '', '204.png', ' Pokemon', '', '', ''),
(205, NULL, '', '205.png', ' Pokemon', '', '', ''),
(206, NULL, '', '206.png', ' Pokemon', '', '', ''),
(207, NULL, '', '207.png', ' Pokemon', '', '', ''),
(208, NULL, '', '208.png', ' Pokemon', '', '', ''),
(209, NULL, '', '209.png', ' Pokemon', '', '', ''),
(210, NULL, '', '210.png', ' Pokemon', '', '', ''),
(211, NULL, '', '211.png', ' Pokemon', '', '', ''),
(212, NULL, '', '212.png', ' Pokemon', '', '', ''),
(213, NULL, '', '213.png', ' Pokemon', '', '', ''),
(214, NULL, '', '214.png', ' Pokemon', '', '', ''),
(215, NULL, '', '215.png', ' Pokemon', '', '', ''),
(216, NULL, '', '216.png', ' Pokemon', '', '', ''),
(217, NULL, '', '217.png', ' Pokemon', '', '', ''),
(218, NULL, '', '218.png', ' Pokemon', '', '', ''),
(219, NULL, '', '219.png', ' Pokemon', '', '', ''),
(220, NULL, '', '220.png', ' Pokemon', '', '', ''),
(221, NULL, '', '221.png', ' Pokemon', '', '', ''),
(222, NULL, '', '222.png', ' Pokemon', '', '', ''),
(223, NULL, '', '223.png', ' Pokemon', '', '', ''),
(224, NULL, '', '224.png', ' Pokemon', '', '', ''),
(225, NULL, '', '225.png', ' Pokemon', '', '', ''),
(226, NULL, '', '226.png', ' Pokemon', '', '', ''),
(227, NULL, '', '227.png', ' Pokemon', '', '', ''),
(228, NULL, '', '228.png', ' Pokemon', '', '', ''),
(229, NULL, '', '229.png', ' Pokemon', '', '', ''),
(230, NULL, '', '230.png', ' Pokemon', '', '', ''),
(231, NULL, '', '231.png', ' Pokemon', '', '', ''),
(232, NULL, '', '232.png', ' Pokemon', '', '', ''),
(233, NULL, '', '233.png', ' Pokemon', '', '', ''),
(234, NULL, '', '234.png', ' Pokemon', '', '', ''),
(235, NULL, '', '235.png', ' Pokemon', '', '', ''),
(236, NULL, '', '236.png', ' Pokemon', '', '', ''),
(237, NULL, '', '237.png', ' Pokemon', '', '', ''),
(238, NULL, '', '238.png', ' Pokemon', '', '', ''),
(239, NULL, '', '239.png', ' Pokemon', '', '', ''),
(240, NULL, '', '240.png', ' Pokemon', '', '', ''),
(241, NULL, '', '241.png', ' Pokemon', '', '', ''),
(242, NULL, '', '242.png', ' Pokemon', '', '', ''),
(243, NULL, '', '243.png', ' Pokemon', '', '', ''),
(244, NULL, '', '244.png', ' Pokemon', '', '', ''),
(245, NULL, '', '245.png', ' Pokemon', '', '', ''),
(246, NULL, '', '246.png', ' Pokemon', '', '', ''),
(247, NULL, '', '247.png', ' Pokemon', '', '', ''),
(248, NULL, '', '248.png', ' Pokemon', '', '', ''),
(249, NULL, '', '249.png', ' Pokemon', '', '', ''),
(250, NULL, '', '250.png', ' Pokemon', '', '', ''),
(251, NULL, '', '251.png', ' Pokemon', '', '', ''),
(252, NULL, '', '252.png', ' Pokemon', '', '', ''),
(253, NULL, '', '253.png', ' Pokemon', '', '', ''),
(254, NULL, '', '254.png', ' Pokemon', '', '', ''),
(255, NULL, '', '255.png', ' Pokemon', '', '', ''),
(256, NULL, '', '256.png', ' Pokemon', '', '', ''),
(257, NULL, '', '257.png', ' Pokemon', '', '', ''),
(258, NULL, '', '258.png', ' Pokemon', '', '', ''),
(259, NULL, '', '259.png', ' Pokemon', '', '', ''),
(260, NULL, '', '260.png', ' Pokemon', '', '', ''),
(261, NULL, '', '261.png', ' Pokemon', '', '', ''),
(262, NULL, '', '262.png', ' Pokemon', '', '', ''),
(263, NULL, '', '263.png', ' Pokemon', '', '', ''),
(264, NULL, '', '264.png', ' Pokemon', '', '', ''),
(265, NULL, '', '265.png', ' Pokemon', '', '', ''),
(266, NULL, '', '266.png', ' Pokemon', '', '', ''),
(267, NULL, '', '267.png', ' Pokemon', '', '', ''),
(268, NULL, '', '268.png', ' Pokemon', '', '', ''),
(269, NULL, '', '269.png', ' Pokemon', '', '', ''),
(270, NULL, '', '270.png', ' Pokemon', '', '', ''),
(271, NULL, '', '271.png', ' Pokemon', '', '', ''),
(272, NULL, '', '272.png', ' Pokemon', '', '', ''),
(273, NULL, '', '273.png', ' Pokemon', '', '', ''),
(274, NULL, '', '274.png', ' Pokemon', '', '', ''),
(275, NULL, '', '275.png', ' Pokemon', '', '', ''),
(276, NULL, '', '276.png', ' Pokemon', '', '', ''),
(277, NULL, '', '277.png', ' Pokemon', '', '', ''),
(278, NULL, '', '278.png', ' Pokemon', '', '', ''),
(279, NULL, '', '279.png', ' Pokemon', '', '', ''),
(280, NULL, '', '280.png', ' Pokemon', '', '', ''),
(281, NULL, '', '281.png', ' Pokemon', '', '', ''),
(282, NULL, '', '282.png', ' Pokemon', '', '', ''),
(283, NULL, '', '283.png', ' Pokemon', '', '', ''),
(284, NULL, '', '284.png', ' Pokemon', '', '', ''),
(285, NULL, '', '285.png', ' Pokemon', '', '', ''),
(286, NULL, '', '286.png', ' Pokemon', '', '', ''),
(287, NULL, '', '287.png', ' Pokemon', '', '', ''),
(288, NULL, '', '288.png', ' Pokemon', '', '', ''),
(289, NULL, '', '289.png', ' Pokemon', '', '', ''),
(290, NULL, '', '290.png', ' Pokemon', '', '', ''),
(291, NULL, '', '291.png', ' Pokemon', '', '', ''),
(292, NULL, '', '292.png', ' Pokemon', '', '', ''),
(293, NULL, '', '293.png', ' Pokemon', '', '', ''),
(294, NULL, '', '294.png', ' Pokemon', '', '', ''),
(295, NULL, '', '295.png', ' Pokemon', '', '', ''),
(296, NULL, '', '296.png', ' Pokemon', '', '', ''),
(297, NULL, '', '297.png', ' Pokemon', '', '', ''),
(298, NULL, '', '298.png', ' Pokemon', '', '', ''),
(299, NULL, '', '299.png', ' Pokemon', '', '', ''),
(300, NULL, '', '300.png', ' Pokemon', '', '', ''),
(301, NULL, '', '301.png', ' Pokemon', '', '', ''),
(302, NULL, '', '302.png', ' Pokemon', '', '', ''),
(303, NULL, '', '303.png', ' Pokemon', '', '', ''),
(304, NULL, '', '304.png', ' Pokemon', '', '', ''),
(305, NULL, '', '305.png', ' Pokemon', '', '', ''),
(306, NULL, '', '306.png', ' Pokemon', '', '', ''),
(307, NULL, '', '307.png', ' Pokemon', '', '', ''),
(308, NULL, '', '308.png', ' Pokemon', '', '', ''),
(309, NULL, '', '309.png', ' Pokemon', '', '', ''),
(310, NULL, '', '310.png', ' Pokemon', '', '', ''),
(311, NULL, '', '311.png', ' Pokemon', '', '', ''),
(312, NULL, '', '312.png', ' Pokemon', '', '', ''),
(313, NULL, '', '313.png', ' Pokemon', '', '', ''),
(314, NULL, '', '314.png', ' Pokemon', '', '', ''),
(315, NULL, '', '315.png', ' Pokemon', '', '', ''),
(316, NULL, '', '316.png', ' Pokemon', '', '', ''),
(317, NULL, '', '317.png', ' Pokemon', '', '', ''),
(318, NULL, '', '318.png', ' Pokemon', '', '', ''),
(319, NULL, '', '319.png', ' Pokemon', '', '', ''),
(320, NULL, '', '320.png', ' Pokemon', '', '', ''),
(321, NULL, '', '321.png', ' Pokemon', '', '', ''),
(322, NULL, '', '322.png', ' Pokemon', '', '', ''),
(323, NULL, '', '323.png', ' Pokemon', '', '', ''),
(324, NULL, '', '324.png', ' Pokemon', '', '', ''),
(325, NULL, '', '325.png', ' Pokemon', '', '', ''),
(326, NULL, '', '326.png', ' Pokemon', '', '', ''),
(327, NULL, '', '327.png', ' Pokemon', '', '', ''),
(328, NULL, '', '328.png', ' Pokemon', '', '', ''),
(329, NULL, '', '329.png', ' Pokemon', '', '', ''),
(330, NULL, '', '330.png', ' Pokemon', '', '', ''),
(331, NULL, '', '331.png', ' Pokemon', '', '', ''),
(332, NULL, '', '332.png', ' Pokemon', '', '', ''),
(333, NULL, '', '333.png', ' Pokemon', '', '', ''),
(334, NULL, '', '334.png', ' Pokemon', '', '', ''),
(335, NULL, '', '335.png', ' Pokemon', '', '', ''),
(336, NULL, '', '336.png', ' Pokemon', '', '', ''),
(337, NULL, '', '337.png', ' Pokemon', '', '', ''),
(338, NULL, '', '338.png', ' Pokemon', '', '', ''),
(339, NULL, '', '339.png', ' Pokemon', '', '', ''),
(340, NULL, '', '340.png', ' Pokemon', '', '', ''),
(341, NULL, '', '341.png', ' Pokemon', '', '', ''),
(342, NULL, '', '342.png', ' Pokemon', '', '', ''),
(343, NULL, '', '343.png', ' Pokemon', '', '', ''),
(344, NULL, '', '344.png', ' Pokemon', '', '', ''),
(345, NULL, '', '345.png', ' Pokemon', '', '', ''),
(346, NULL, '', '346.png', ' Pokemon', '', '', ''),
(347, NULL, '', '347.png', ' Pokemon', '', '', ''),
(348, NULL, '', '348.png', ' Pokemon', '', '', ''),
(349, NULL, '', '349.png', ' Pokemon', '', '', ''),
(350, NULL, '', '350.png', ' Pokemon', '', '', ''),
(351, NULL, '', '351.png', ' Pokemon', '', '', ''),
(352, NULL, '', '352.png', ' Pokemon', '', '', ''),
(353, NULL, '', '353.png', ' Pokemon', '', '', ''),
(354, NULL, '', '354.png', ' Pokemon', '', '', ''),
(355, NULL, '', '355.png', ' Pokemon', '', '', ''),
(356, NULL, '', '356.png', ' Pokemon', '', '', ''),
(357, NULL, '', '357.png', ' Pokemon', '', '', ''),
(358, NULL, '', '358.png', ' Pokemon', '', '', ''),
(359, NULL, '', '359.png', ' Pokemon', '', '', ''),
(360, NULL, '', '360.png', ' Pokemon', '', '', ''),
(361, NULL, '', '361.png', ' Pokemon', '', '', ''),
(362, NULL, '', '362.png', ' Pokemon', '', '', ''),
(363, NULL, '', '363.png', ' Pokemon', '', '', ''),
(364, NULL, '', '364.png', ' Pokemon', '', '', ''),
(365, NULL, '', '365.png', ' Pokemon', '', '', ''),
(366, NULL, '', '366.png', ' Pokemon', '', '', ''),
(367, NULL, '', '367.png', ' Pokemon', '', '', ''),
(368, NULL, '', '368.png', ' Pokemon', '', '', ''),
(369, NULL, '', '369.png', ' Pokemon', '', '', ''),
(370, NULL, '', '370.png', ' Pokemon', '', '', ''),
(371, NULL, '', '371.png', ' Pokemon', '', '', ''),
(372, NULL, '', '372.png', ' Pokemon', '', '', ''),
(373, NULL, '', '373.png', ' Pokemon', '', '', ''),
(374, NULL, '', '374.png', ' Pokemon', '', '', ''),
(375, NULL, '', '375.png', ' Pokemon', '', '', ''),
(376, NULL, '', '376.png', ' Pokemon', '', '', ''),
(377, NULL, '', '377.png', ' Pokemon', '', '', ''),
(378, NULL, '', '378.png', ' Pokemon', '', '', ''),
(379, NULL, '', '379.png', ' Pokemon', '', '', ''),
(380, NULL, '', '380.png', ' Pokemon', '', '', ''),
(381, NULL, '', '381.png', ' Pokemon', '', '', ''),
(382, NULL, '', '382.png', ' Pokemon', '', '', ''),
(383, NULL, '', '383.png', ' Pokemon', '', '', ''),
(384, NULL, '', '384.png', ' Pokemon', '', '', ''),
(385, NULL, '', '385.png', ' Pokemon', '', '', ''),
(386, NULL, '', '386.png', ' Pokemon', '', '', ''),
(387, NULL, '', '387.png', ' Pokemon', '', '', ''),
(388, NULL, '', '388.png', ' Pokemon', '', '', ''),
(389, NULL, '', '389.png', ' Pokemon', '', '', ''),
(390, NULL, '', '390.png', ' Pokemon', '', '', ''),
(391, NULL, '', '391.png', ' Pokemon', '', '', ''),
(392, NULL, '', '392.png', ' Pokemon', '', '', ''),
(393, NULL, '', '393.png', ' Pokemon', '', '', ''),
(394, NULL, '', '394.png', ' Pokemon', '', '', ''),
(395, NULL, '', '395.png', ' Pokemon', '', '', ''),
(396, NULL, '', '396.png', ' Pokemon', '', '', ''),
(397, NULL, '', '397.png', ' Pokemon', '', '', ''),
(398, NULL, '', '398.png', ' Pokemon', '', '', ''),
(399, NULL, '', '399.png', ' Pokemon', '', '', ''),
(400, NULL, '', '400.png', ' Pokemon', '', '', ''),
(401, NULL, '', '401.png', ' Pokemon', '', '', ''),
(402, NULL, '', '402.png', ' Pokemon', '', '', ''),
(403, NULL, '', '403.png', ' Pokemon', '', '', ''),
(404, NULL, '', '404.png', ' Pokemon', '', '', ''),
(405, NULL, '', '405.png', ' Pokemon', '', '', ''),
(406, NULL, '', '406.png', ' Pokemon', '', '', ''),
(407, NULL, '', '407.png', ' Pokemon', '', '', ''),
(408, NULL, '', '408.png', ' Pokemon', '', '', ''),
(409, NULL, '', '409.png', ' Pokemon', '', '', ''),
(410, NULL, '', '410.png', ' Pokemon', '', '', ''),
(411, NULL, '', '411.png', ' Pokemon', '', '', ''),
(412, NULL, '', '412.png', ' Pokemon', '', '', ''),
(413, NULL, '', '413.png', ' Pokemon', '', '', ''),
(414, NULL, '', '414.png', ' Pokemon', '', '', ''),
(415, NULL, '', '415.png', ' Pokemon', '', '', ''),
(416, NULL, '', '416.png', ' Pokemon', '', '', ''),
(417, NULL, '', '417.png', ' Pokemon', '', '', ''),
(418, NULL, '', '418.png', ' Pokemon', '', '', ''),
(419, NULL, '', '419.png', ' Pokemon', '', '', ''),
(420, NULL, '', '420.png', ' Pokemon', '', '', ''),
(421, NULL, '', '421.png', ' Pokemon', '', '', ''),
(422, NULL, '', '422.png', ' Pokemon', '', '', ''),
(423, NULL, '', '423.png', ' Pokemon', '', '', ''),
(424, NULL, '', '424.png', ' Pokemon', '', '', ''),
(425, NULL, '', '425.png', ' Pokemon', '', '', ''),
(426, NULL, '', '426.png', ' Pokemon', '', '', ''),
(427, NULL, '', '427.png', ' Pokemon', '', '', ''),
(428, NULL, '', '428.png', ' Pokemon', '', '', ''),
(429, NULL, '', '429.png', ' Pokemon', '', '', ''),
(430, NULL, '', '430.png', ' Pokemon', '', '', ''),
(431, NULL, '', '431.png', ' Pokemon', '', '', ''),
(432, NULL, '', '432.png', ' Pokemon', '', '', ''),
(433, NULL, '', '433.png', ' Pokemon', '', '', ''),
(434, NULL, '', '434.png', ' Pokemon', '', '', ''),
(435, NULL, '', '435.png', ' Pokemon', '', '', ''),
(436, NULL, '', '436.png', ' Pokemon', '', '', ''),
(437, NULL, '', '437.png', ' Pokemon', '', '', ''),
(438, NULL, '', '438.png', ' Pokemon', '', '', ''),
(439, NULL, '', '439.png', ' Pokemon', '', '', ''),
(440, NULL, '', '440.png', ' Pokemon', '', '', ''),
(441, NULL, '', '441.png', ' Pokemon', '', '', ''),
(442, NULL, '', '442.png', ' Pokemon', '', '', ''),
(443, NULL, '', '443.png', ' Pokemon', '', '', ''),
(444, NULL, '', '444.png', ' Pokemon', '', '', ''),
(445, NULL, '', '445.png', ' Pokemon', '', '', ''),
(446, NULL, '', '446.png', ' Pokemon', '', '', ''),
(447, NULL, '', '447.png', ' Pokemon', '', '', ''),
(448, NULL, '', '448.png', ' Pokemon', '', '', ''),
(449, NULL, '', '449.png', ' Pokemon', '', '', ''),
(450, NULL, '', '450.png', ' Pokemon', '', '', ''),
(451, NULL, '', '451.png', ' Pokemon', '', '', ''),
(452, NULL, '', '452.png', ' Pokemon', '', '', ''),
(453, NULL, '', '453.png', ' Pokemon', '', '', ''),
(454, NULL, '', '454.png', ' Pokemon', '', '', ''),
(455, NULL, '', '455.png', ' Pokemon', '', '', ''),
(456, NULL, '', '456.png', ' Pokemon', '', '', ''),
(457, NULL, '', '457.png', ' Pokemon', '', '', ''),
(458, NULL, '', '458.png', ' Pokemon', '', '', ''),
(459, NULL, '', '459.png', ' Pokemon', '', '', ''),
(460, NULL, '', '460.png', ' Pokemon', '', '', ''),
(461, NULL, '', '461.png', ' Pokemon', '', '', ''),
(462, NULL, '', '462.png', ' Pokemon', '', '', ''),
(463, NULL, '', '463.png', ' Pokemon', '', '', ''),
(464, NULL, '', '464.png', ' Pokemon', '', '', ''),
(465, NULL, '', '465.png', ' Pokemon', '', '', ''),
(466, NULL, '', '466.png', ' Pokemon', '', '', ''),
(467, NULL, '', '467.png', ' Pokemon', '', '', ''),
(468, NULL, '', '468.png', ' Pokemon', '', '', ''),
(469, NULL, '', '469.png', ' Pokemon', '', '', ''),
(470, NULL, '', '470.png', ' Pokemon', '', '', ''),
(471, NULL, '', '471.png', ' Pokemon', '', '', ''),
(472, NULL, '', '472.png', ' Pokemon', '', '', ''),
(473, NULL, '', '473.png', ' Pokemon', '', '', ''),
(474, NULL, '', '474.png', ' Pokemon', '', '', ''),
(475, NULL, '', '475.png', ' Pokemon', '', '', ''),
(476, NULL, '', '476.png', ' Pokemon', '', '', ''),
(477, NULL, '', '477.png', ' Pokemon', '', '', ''),
(478, NULL, '', '478.png', ' Pokemon', '', '', ''),
(479, NULL, '', '479.png', ' Pokemon', '', '', ''),
(480, NULL, '', '480.png', ' Pokemon', '', '', ''),
(481, NULL, '', '481.png', ' Pokemon', '', '', ''),
(482, NULL, '', '482.png', ' Pokemon', '', '', ''),
(483, NULL, '', '483.png', ' Pokemon', '', '', ''),
(484, NULL, '', '484.png', ' Pokemon', '', '', ''),
(485, NULL, '', '485.png', ' Pokemon', '', '', ''),
(486, NULL, '', '486.png', ' Pokemon', '', '', ''),
(487, NULL, '', '487.png', ' Pokemon', '', '', ''),
(488, NULL, '', '488.png', ' Pokemon', '', '', ''),
(489, NULL, '', '489.png', ' Pokemon', '', '', ''),
(490, NULL, '', '490.png', ' Pokemon', '', '', ''),
(491, NULL, '', '491.png', ' Pokemon', '', '', ''),
(492, NULL, '', '492.png', ' Pokemon', '', '', ''),
(493, NULL, '', '493.png', ' Pokemon', '', '', ''),
(494, NULL, '', '494.png', ' Pokemon', '', '', ''),
(495, NULL, '', '495.png', ' Pokemon', '', '', ''),
(496, NULL, '', '496.png', ' Pokemon', '', '', ''),
(497, NULL, '', '497.png', ' Pokemon', '', '', ''),
(498, NULL, '', '498.png', ' Pokemon', '', '', ''),
(499, NULL, '', '499.png', ' Pokemon', '', '', ''),
(500, NULL, '', '500.png', ' Pokemon', '', '', ''),
(501, NULL, '', '501.png', ' Pokemon', '', '', ''),
(502, NULL, '', '502.png', ' Pokemon', '', '', ''),
(503, NULL, '', '503.png', ' Pokemon', '', '', ''),
(504, NULL, '', '504.png', ' Pokemon', '', '', ''),
(505, NULL, '', '505.png', ' Pokemon', '', '', ''),
(506, NULL, '', '506.png', ' Pokemon', '', '', ''),
(507, NULL, '', '507.png', ' Pokemon', '', '', ''),
(508, NULL, '', '508.png', ' Pokemon', '', '', ''),
(509, NULL, '', '509.png', ' Pokemon', '', '', ''),
(510, NULL, '', '510.png', ' Pokemon', '', '', ''),
(511, NULL, '', '511.png', ' Pokemon', '', '', ''),
(512, NULL, '', '512.png', ' Pokemon', '', '', ''),
(513, NULL, '', '513.png', ' Pokemon', '', '', ''),
(514, NULL, '', '514.png', ' Pokemon', '', '', ''),
(515, NULL, '', '515.png', ' Pokemon', '', '', ''),
(516, NULL, '', '516.png', ' Pokemon', '', '', ''),
(517, NULL, '', '517.png', ' Pokemon', '', '', ''),
(518, NULL, '', '518.png', ' Pokemon', '', '', ''),
(519, NULL, '', '519.png', ' Pokemon', '', '', ''),
(520, NULL, '', '520.png', ' Pokemon', '', '', ''),
(521, NULL, '', '521.png', ' Pokemon', '', '', ''),
(522, NULL, '', '522.png', ' Pokemon', '', '', ''),
(523, NULL, '', '523.png', ' Pokemon', '', '', ''),
(524, NULL, '', '524.png', ' Pokemon', '', '', ''),
(525, NULL, '', '525.png', ' Pokemon', '', '', ''),
(526, NULL, '', '526.png', ' Pokemon', '', '', ''),
(527, NULL, '', '527.png', ' Pokemon', '', '', ''),
(528, NULL, '', '528.png', ' Pokemon', '', '', ''),
(529, NULL, '', '529.png', ' Pokemon', '', '', ''),
(530, NULL, '', '530.png', ' Pokemon', '', '', ''),
(531, NULL, '', '531.png', ' Pokemon', '', '', ''),
(532, NULL, '', '532.png', ' Pokemon', '', '', ''),
(533, NULL, '', '533.png', ' Pokemon', '', '', ''),
(534, NULL, '', '534.png', ' Pokemon', '', '', ''),
(535, NULL, '', '535.png', ' Pokemon', '', '', ''),
(536, NULL, '', '536.png', ' Pokemon', '', '', ''),
(537, NULL, '', '537.png', ' Pokemon', '', '', ''),
(538, NULL, '', '538.png', ' Pokemon', '', '', ''),
(539, NULL, '', '539.png', ' Pokemon', '', '', ''),
(540, NULL, '', '540.png', ' Pokemon', '', '', ''),
(541, NULL, '', '541.png', ' Pokemon', '', '', ''),
(542, NULL, '', '542.png', ' Pokemon', '', '', ''),
(543, NULL, '', '543.png', ' Pokemon', '', '', ''),
(544, NULL, '', '544.png', ' Pokemon', '', '', ''),
(545, NULL, '', '545.png', ' Pokemon', '', '', ''),
(546, NULL, '', '546.png', ' Pokemon', '', '', ''),
(547, NULL, '', '547.png', ' Pokemon', '', '', ''),
(548, NULL, '', '548.png', ' Pokemon', '', '', ''),
(549, NULL, '', '549.png', ' Pokemon', '', '', ''),
(550, NULL, '', '550.png', ' Pokemon', '', '', ''),
(551, NULL, '', '551.png', ' Pokemon', '', '', ''),
(552, NULL, '', '552.png', ' Pokemon', '', '', ''),
(553, NULL, '', '553.png', ' Pokemon', '', '', ''),
(554, NULL, '', '554.png', ' Pokemon', '', '', ''),
(555, NULL, '', '555.png', ' Pokemon', '', '', ''),
(556, NULL, '', '556.png', ' Pokemon', '', '', ''),
(557, NULL, '', '557.png', ' Pokemon', '', '', ''),
(558, NULL, '', '558.png', ' Pokemon', '', '', ''),
(559, NULL, '', '559.png', ' Pokemon', '', '', ''),
(560, NULL, '', '560.png', ' Pokemon', '', '', ''),
(561, NULL, '', '561.png', ' Pokemon', '', '', ''),
(562, NULL, '', '562.png', ' Pokemon', '', '', ''),
(563, NULL, '', '563.png', ' Pokemon', '', '', ''),
(564, NULL, '', '564.png', ' Pokemon', '', '', ''),
(565, NULL, '', '565.png', ' Pokemon', '', '', ''),
(566, NULL, '', '566.png', ' Pokemon', '', '', ''),
(567, NULL, '', '567.png', ' Pokemon', '', '', ''),
(568, NULL, '', '568.png', ' Pokemon', '', '', ''),
(569, NULL, '', '569.png', ' Pokemon', '', '', ''),
(570, NULL, '', '570.png', ' Pokemon', '', '', ''),
(571, NULL, '', '571.png', ' Pokemon', '', '', ''),
(572, NULL, '', '572.png', ' Pokemon', '', '', ''),
(573, NULL, '', '573.png', ' Pokemon', '', '', ''),
(574, NULL, '', '574.png', ' Pokemon', '', '', ''),
(575, NULL, '', '575.png', ' Pokemon', '', '', ''),
(576, NULL, '', '576.png', ' Pokemon', '', '', ''),
(577, NULL, '', '577.png', ' Pokemon', '', '', ''),
(578, NULL, '', '578.png', ' Pokemon', '', '', ''),
(579, NULL, '', '579.png', ' Pokemon', '', '', ''),
(580, NULL, '', '580.png', ' Pokemon', '', '', ''),
(581, NULL, '', '581.png', ' Pokemon', '', '', ''),
(582, NULL, '', '582.png', ' Pokemon', '', '', ''),
(583, NULL, '', '583.png', ' Pokemon', '', '', ''),
(584, NULL, '', '584.png', ' Pokemon', '', '', ''),
(585, NULL, '', '585.png', ' Pokemon', '', '', ''),
(586, NULL, '', '586.png', ' Pokemon', '', '', ''),
(587, NULL, '', '587.png', ' Pokemon', '', '', ''),
(588, NULL, '', '588.png', ' Pokemon', '', '', ''),
(589, NULL, '', '589.png', ' Pokemon', '', '', ''),
(590, NULL, '', '590.png', ' Pokemon', '', '', ''),
(591, NULL, '', '591.png', ' Pokemon', '', '', ''),
(592, NULL, '', '592.png', ' Pokemon', '', '', ''),
(593, NULL, '', '593.png', ' Pokemon', '', '', ''),
(594, NULL, '', '594.png', ' Pokemon', '', '', ''),
(595, NULL, '', '595.png', ' Pokemon', '', '', ''),
(596, NULL, '', '596.png', ' Pokemon', '', '', ''),
(597, NULL, '', '597.png', ' Pokemon', '', '', ''),
(598, NULL, '', '598.png', ' Pokemon', '', '', ''),
(599, NULL, '', '599.png', ' Pokemon', '', '', ''),
(600, NULL, '', '600.png', ' Pokemon', '', '', ''),
(601, NULL, '', '601.png', ' Pokemon', '', '', ''),
(602, NULL, '', '602.png', ' Pokemon', '', '', ''),
(603, NULL, '', '603.png', ' Pokemon', '', '', ''),
(604, NULL, '', '604.png', ' Pokemon', '', '', ''),
(605, NULL, '', '605.png', ' Pokemon', '', '', ''),
(606, NULL, '', '606.png', ' Pokemon', '', '', ''),
(607, NULL, '', '607.png', ' Pokemon', '', '', ''),
(608, NULL, '', '608.png', ' Pokemon', '', '', ''),
(609, NULL, '', '609.png', ' Pokemon', '', '', ''),
(610, NULL, '', '610.png', ' Pokemon', '', '', ''),
(611, NULL, '', '611.png', ' Pokemon', '', '', ''),
(612, NULL, '', '612.png', ' Pokemon', '', '', ''),
(613, NULL, '', '613.png', ' Pokemon', '', '', ''),
(614, NULL, '', '614.png', ' Pokemon', '', '', ''),
(615, NULL, '', '615.png', ' Pokemon', '', '', ''),
(616, NULL, '', '616.png', ' Pokemon', '', '', ''),
(617, NULL, '', '617.png', ' Pokemon', '', '', ''),
(618, NULL, '', '618.png', ' Pokemon', '', '', ''),
(619, NULL, '', '619.png', ' Pokemon', '', '', ''),
(620, NULL, '', '620.png', ' Pokemon', '', '', ''),
(621, NULL, '', '621.png', ' Pokemon', '', '', ''),
(622, NULL, '', '622.png', ' Pokemon', '', '', ''),
(623, NULL, '', '623.png', ' Pokemon', '', '', ''),
(624, NULL, '', '624.png', ' Pokemon', '', '', ''),
(625, NULL, '', '625.png', ' Pokemon', '', '', ''),
(626, NULL, '', '626.png', ' Pokemon', '', '', ''),
(627, NULL, '', '627.png', ' Pokemon', '', '', ''),
(628, NULL, '', '628.png', ' Pokemon', '', '', ''),
(629, NULL, '', '629.png', ' Pokemon', '', '', ''),
(630, NULL, '', '630.png', ' Pokemon', '', '', ''),
(631, NULL, '', '631.png', ' Pokemon', '', '', ''),
(632, NULL, '', '632.png', ' Pokemon', '', '', ''),
(633, NULL, '', '633.png', ' Pokemon', '', '', ''),
(634, NULL, '', '634.png', ' Pokemon', '', '', ''),
(635, NULL, '', '635.png', ' Pokemon', '', '', ''),
(636, NULL, '', '636.png', ' Pokemon', '', '', ''),
(637, NULL, '', '637.png', ' Pokemon', '', '', ''),
(638, NULL, '', '638.png', ' Pokemon', '', '', ''),
(639, NULL, '', '639.png', ' Pokemon', '', '', ''),
(640, NULL, '', '640.png', ' Pokemon', '', '', ''),
(641, NULL, '', '641.png', ' Pokemon', '', '', ''),
(642, NULL, '', '642.png', ' Pokemon', '', '', ''),
(643, NULL, '', '643.png', ' Pokemon', '', '', ''),
(644, NULL, '', '644.png', ' Pokemon', '', '', ''),
(645, NULL, '', '645.png', ' Pokemon', '', '', ''),
(646, NULL, '', '646.png', ' Pokemon', '', '', ''),
(647, NULL, '', '647.png', ' Pokemon', '', '', ''),
(648, NULL, '', '648.png', ' Pokemon', '', '', ''),
(649, NULL, '', '649.png', ' Pokemon', '', '', ''),
(650, NULL, '', '650.png', ' Pokemon', '', '', ''),
(651, NULL, '', '651.png', ' Pokemon', '', '', ''),
(652, NULL, '', '652.png', ' Pokemon', '', '', ''),
(653, NULL, '', '653.png', ' Pokemon', '', '', ''),
(654, NULL, '', '654.png', ' Pokemon', '', '', ''),
(655, NULL, '', '655.png', ' Pokemon', '', '', ''),
(656, NULL, '', '656.png', ' Pokemon', '', '', ''),
(657, NULL, '', '657.png', ' Pokemon', '', '', ''),
(658, NULL, '', '658.png', ' Pokemon', '', '', ''),
(659, NULL, '', '659.png', ' Pokemon', '', '', ''),
(660, NULL, '', '660.png', ' Pokemon', '', '', ''),
(661, NULL, '', '661.png', ' Pokemon', '', '', ''),
(662, NULL, '', '662.png', ' Pokemon', '', '', ''),
(663, NULL, '', '663.png', ' Pokemon', '', '', ''),
(664, NULL, '', '664.png', ' Pokemon', '', '', ''),
(665, NULL, '', '665.png', ' Pokemon', '', '', ''),
(666, NULL, '', '666.png', ' Pokemon', '', '', ''),
(667, NULL, '', '667.png', ' Pokemon', '', '', ''),
(668, NULL, '', '668.png', ' Pokemon', '', '', ''),
(669, NULL, '', '669.png', ' Pokemon', '', '', ''),
(670, NULL, '', '670.png', ' Pokemon', '', '', ''),
(671, NULL, '', '671.png', ' Pokemon', '', '', ''),
(672, NULL, '', '672.png', ' Pokemon', '', '', ''),
(673, NULL, '', '673.png', ' Pokemon', '', '', ''),
(674, NULL, '', '674.png', ' Pokemon', '', '', ''),
(675, NULL, '', '675.png', ' Pokemon', '', '', ''),
(676, NULL, '', '676.png', ' Pokemon', '', '', ''),
(677, NULL, '', '677.png', ' Pokemon', '', '', ''),
(678, NULL, '', '678.png', ' Pokemon', '', '', ''),
(679, NULL, '', '679.png', ' Pokemon', '', '', ''),
(680, NULL, '', '680.png', ' Pokemon', '', '', ''),
(681, NULL, '', '681.png', ' Pokemon', '', '', ''),
(682, NULL, '', '682.png', ' Pokemon', '', '', ''),
(683, NULL, '', '683.png', ' Pokemon', '', '', ''),
(684, NULL, '', '684.png', ' Pokemon', '', '', ''),
(685, NULL, '', '685.png', ' Pokemon', '', '', ''),
(686, NULL, '', '686.png', ' Pokemon', '', '', ''),
(687, NULL, '', '687.png', ' Pokemon', '', '', ''),
(688, NULL, '', '688.png', ' Pokemon', '', '', ''),
(689, NULL, '', '689.png', ' Pokemon', '', '', ''),
(690, NULL, '', '690.png', ' Pokemon', '', '', ''),
(691, NULL, '', '691.png', ' Pokemon', '', '', ''),
(692, NULL, '', '692.png', ' Pokemon', '', '', ''),
(693, NULL, '', '693.png', ' Pokemon', '', '', ''),
(694, NULL, '', '694.png', ' Pokemon', '', '', ''),
(695, NULL, '', '695.png', ' Pokemon', '', '', ''),
(696, NULL, '', '696.png', ' Pokemon', '', '', ''),
(697, NULL, '', '697.png', ' Pokemon', '', '', ''),
(698, NULL, '', '698.png', ' Pokemon', '', '', ''),
(699, NULL, '', '699.png', ' Pokemon', '', '', ''),
(700, NULL, '', '700.png', ' Pokemon', '', '', ''),
(701, NULL, '', '701.png', ' Pokemon', '', '', ''),
(702, NULL, '', '702.png', ' Pokemon', '', '', ''),
(703, NULL, '', '703.png', ' Pokemon', '', '', ''),
(704, NULL, '', '704.png', ' Pokemon', '', '', ''),
(705, NULL, '', '705.png', ' Pokemon', '', '', ''),
(706, NULL, '', '706.png', ' Pokemon', '', '', ''),
(707, NULL, '', '707.png', ' Pokemon', '', '', ''),
(708, NULL, '', '708.png', ' Pokemon', '', '', ''),
(709, NULL, '', '709.png', ' Pokemon', '', '', ''),
(710, NULL, '', '710.png', ' Pokemon', '', '', ''),
(711, NULL, '', '711.png', ' Pokemon', '', '', ''),
(712, NULL, '', '712.png', ' Pokemon', '', '', ''),
(713, NULL, '', '713.png', ' Pokemon', '', '', ''),
(714, NULL, '', '714.png', ' Pokemon', '', '', ''),
(715, NULL, '', '715.png', ' Pokemon', '', '', ''),
(716, NULL, '', '716.png', ' Pokemon', '', '', ''),
(717, NULL, '', '717.png', ' Pokemon', '', '', ''),
(718, NULL, '', '718.png', ' Pokemon', '', '', ''),
(719, NULL, '', '719.png', ' Pokemon', '', '', ''),
(720, NULL, '', '720.png', ' Pokemon', '', '', ''),
(721, NULL, '', '721.png', ' Pokemon', '', '', ''),
(722, NULL, '', '722.png', ' Pokemon', '', '', ''),
(723, NULL, '', '723.png', ' Pokemon', '', '', ''),
(724, NULL, '', '724.png', ' Pokemon', '', '', ''),
(725, NULL, '', '725.png', ' Pokemon', '', '', ''),
(726, NULL, '', '726.png', ' Pokemon', '', '', ''),
(727, NULL, '', '727.png', ' Pokemon', '', '', ''),
(728, NULL, '', '728.png', ' Pokemon', '', '', ''),
(729, NULL, '', '729.png', ' Pokemon', '', '', ''),
(730, NULL, '', '730.png', ' Pokemon', '', '', ''),
(731, NULL, '', '731.png', ' Pokemon', '', '', ''),
(732, NULL, '', '732.png', ' Pokemon', '', '', ''),
(733, NULL, '', '733.png', ' Pokemon', '', '', ''),
(734, NULL, '', '734.png', ' Pokemon', '', '', ''),
(735, NULL, '', '735.png', ' Pokemon', '', '', ''),
(736, NULL, '', '736.png', ' Pokemon', '', '', ''),
(737, NULL, '', '737.png', ' Pokemon', '', '', ''),
(738, NULL, '', '738.png', ' Pokemon', '', '', ''),
(739, NULL, '', '739.png', ' Pokemon', '', '', ''),
(740, NULL, '', '740.png', ' Pokemon', '', '', ''),
(741, NULL, '', '741.png', ' Pokemon', '', '', ''),
(742, NULL, '', '742.png', ' Pokemon', '', '', ''),
(743, NULL, '', '743.png', ' Pokemon', '', '', ''),
(744, NULL, '', '744.png', ' Pokemon', '', '', ''),
(745, NULL, '', '745.png', ' Pokemon', '', '', ''),
(746, NULL, '', '746.png', ' Pokemon', '', '', ''),
(747, NULL, '', '747.png', ' Pokemon', '', '', ''),
(748, NULL, '', '748.png', ' Pokemon', '', '', ''),
(749, NULL, '', '749.png', ' Pokemon', '', '', ''),
(750, NULL, '', '750.png', ' Pokemon', '', '', ''),
(751, NULL, '', '751.png', ' Pokemon', '', '', ''),
(752, NULL, '', '752.png', ' Pokemon', '', '', ''),
(753, NULL, '', '753.png', ' Pokemon', '', '', ''),
(754, NULL, '', '754.png', ' Pokemon', '', '', ''),
(755, NULL, '', '755.png', ' Pokemon', '', '', ''),
(756, NULL, '', '756.png', ' Pokemon', '', '', ''),
(757, NULL, '', '757.png', ' Pokemon', '', '', ''),
(758, NULL, '', '758.png', ' Pokemon', '', '', ''),
(759, NULL, '', '759.png', ' Pokemon', '', '', ''),
(760, NULL, '', '760.png', ' Pokemon', '', '', ''),
(761, NULL, '', '761.png', ' Pokemon', '', '', ''),
(762, NULL, '', '762.png', ' Pokemon', '', '', ''),
(763, NULL, '', '763.png', ' Pokemon', '', '', ''),
(764, NULL, '', '764.png', ' Pokemon', '', '', ''),
(765, NULL, '', '765.png', ' Pokemon', '', '', ''),
(766, NULL, '', '766.png', ' Pokemon', '', '', ''),
(767, NULL, '', '767.png', ' Pokemon', '', '', ''),
(768, NULL, '', '768.png', ' Pokemon', '', '', ''),
(769, NULL, '', '769.png', ' Pokemon', '', '', ''),
(770, NULL, '', '770.png', ' Pokemon', '', '', ''),
(771, NULL, '', '771.png', ' Pokemon', '', '', ''),
(772, NULL, '', '772.png', ' Pokemon', '', '', ''),
(773, NULL, '', '773.png', ' Pokemon', '', '', ''),
(774, NULL, '', '774.png', ' Pokemon', '', '', ''),
(775, NULL, '', '775.png', ' Pokemon', '', '', ''),
(776, NULL, '', '776.png', ' Pokemon', '', '', ''),
(777, NULL, '', '777.png', ' Pokemon', '', '', ''),
(778, NULL, '', '778.png', ' Pokemon', '', '', ''),
(779, NULL, '', '779.png', ' Pokemon', '', '', ''),
(780, NULL, '', '780.png', ' Pokemon', '', '', ''),
(781, NULL, '', '781.png', ' Pokemon', '', '', ''),
(782, NULL, '', '782.png', ' Pokemon', '', '', ''),
(783, NULL, '', '783.png', ' Pokemon', '', '', ''),
(784, NULL, '', '784.png', ' Pokemon', '', '', ''),
(785, NULL, '', '785.png', ' Pokemon', '', '', ''),
(786, NULL, '', '786.png', ' Pokemon', '', '', ''),
(787, NULL, '', '787.png', ' Pokemon', '', '', ''),
(788, NULL, '', '788.png', ' Pokemon', '', '', ''),
(789, NULL, '', '789.png', ' Pokemon', '', '', ''),
(790, NULL, '', '790.png', ' Pokemon', '', '', ''),
(791, NULL, '', '791.png', ' Pokemon', '', '', ''),
(792, NULL, '', '792.png', ' Pokemon', '', '', ''),
(793, NULL, '', '793.png', ' Pokemon', '', '', ''),
(794, NULL, '', '794.png', ' Pokemon', '', '', ''),
(795, NULL, '', '795.png', ' Pokemon', '', '', ''),
(796, NULL, '', '796.png', ' Pokemon', '', '', ''),
(797, NULL, '', '797.png', ' Pokemon', '', '', ''),
(798, NULL, '', '798.png', ' Pokemon', '', '', ''),
(799, NULL, '', '799.png', ' Pokemon', '', '', ''),
(800, NULL, '', '800.png', ' Pokemon', '', '', ''),
(801, NULL, '', '801.png', ' Pokemon', '', '', ''),
(802, NULL, '', '802.png', ' Pokemon', '', '', ''),
(803, NULL, '', '803.png', ' Pokemon', '', '', ''),
(804, NULL, '', '804.png', ' Pokemon', '', '', ''),
(805, NULL, '', '805.png', ' Pokemon', '', '', ''),
(806, NULL, '', '806.png', ' Pokemon', '', '', ''),
(807, NULL, '', '807.png', ' Pokemon', '', '', ''),
(808, NULL, '', '808.png', ' Pokemon', '', '', ''),
(809, NULL, '', '809.png', ' Pokemon', '', '', ''),
(810, NULL, '', '810.png', ' Pokemon', '', '', ''),
(811, NULL, '', '811.png', ' Pokemon', '', '', ''),
(812, NULL, '', '812.png', ' Pokemon', '', '', ''),
(813, NULL, '', '813.png', ' Pokemon', '', '', ''),
(814, NULL, '', '814.png', ' Pokemon', '', '', ''),
(815, NULL, '', '815.png', ' Pokemon', '', '', ''),
(816, NULL, '', '816.png', ' Pokemon', '', '', ''),
(817, NULL, '', '817.png', ' Pokemon', '', '', ''),
(818, NULL, '', '818.png', ' Pokemon', '', '', ''),
(819, NULL, '', '819.png', ' Pokemon', '', '', ''),
(820, NULL, '', '820.png', ' Pokemon', '', '', ''),
(821, NULL, '', '821.png', ' Pokemon', '', '', ''),
(822, NULL, '', '822.png', ' Pokemon', '', '', ''),
(823, NULL, '', '823.png', ' Pokemon', '', '', ''),
(824, NULL, '', '824.png', ' Pokemon', '', '', ''),
(825, NULL, '', '825.png', ' Pokemon', '', '', ''),
(826, NULL, '', '826.png', ' Pokemon', '', '', ''),
(827, NULL, '', '827.png', ' Pokemon', '', '', ''),
(828, NULL, '', '828.png', ' Pokemon', '', '', ''),
(829, NULL, '', '829.png', ' Pokemon', '', '', ''),
(830, NULL, '', '830.png', ' Pokemon', '', '', ''),
(831, NULL, '', '831.png', ' Pokemon', '', '', ''),
(832, NULL, '', '832.png', ' Pokemon', '', '', ''),
(833, NULL, '', '833.png', ' Pokemon', '', '', ''),
(834, NULL, '', '834.png', ' Pokemon', '', '', ''),
(835, NULL, '', '835.png', ' Pokemon', '', '', ''),
(836, NULL, '', '836.png', ' Pokemon', '', '', ''),
(837, NULL, '', '837.png', ' Pokemon', '', '', ''),
(838, NULL, '', '838.png', ' Pokemon', '', '', ''),
(839, NULL, '', '839.png', ' Pokemon', '', '', ''),
(840, NULL, '', '840.png', ' Pokemon', '', '', ''),
(841, NULL, '', '841.png', ' Pokemon', '', '', ''),
(842, NULL, '', '842.png', ' Pokemon', '', '', ''),
(843, NULL, '', '843.png', ' Pokemon', '', '', ''),
(844, NULL, '', '844.png', ' Pokemon', '', '', ''),
(845, NULL, '', '845.png', ' Pokemon', '', '', ''),
(846, NULL, '', '846.png', ' Pokemon', '', '', ''),
(847, NULL, '', '847.png', ' Pokemon', '', '', ''),
(848, NULL, '', '848.png', ' Pokemon', '', '', ''),
(849, NULL, '', '849.png', ' Pokemon', '', '', ''),
(850, NULL, '', '850.png', ' Pokemon', '', '', ''),
(851, NULL, '', '851.png', ' Pokemon', '', '', ''),
(852, NULL, '', '852.png', ' Pokemon', '', '', ''),
(853, NULL, '', '853.png', ' Pokemon', '', '', ''),
(854, NULL, '', '854.png', ' Pokemon', '', '', ''),
(855, NULL, '', '855.png', ' Pokemon', '', '', ''),
(856, NULL, '', '856.png', ' Pokemon', '', '', ''),
(857, NULL, '', '857.png', ' Pokemon', '', '', ''),
(858, NULL, '', '858.png', ' Pokemon', '', '', ''),
(859, NULL, '', '859.png', ' Pokemon', '', '', ''),
(860, NULL, '', '860.png', ' Pokemon', '', '', ''),
(861, NULL, '', '861.png', ' Pokemon', '', '', ''),
(862, NULL, '', '862.png', ' Pokemon', '', '', ''),
(863, NULL, '', '863.png', ' Pokemon', '', '', ''),
(864, NULL, '', '864.png', ' Pokemon', '', '', ''),
(865, NULL, '', '865.png', ' Pokemon', '', '', ''),
(866, NULL, '', '866.png', ' Pokemon', '', '', ''),
(867, NULL, '', '867.png', ' Pokemon', '', '', ''),
(868, NULL, '', '868.png', ' Pokemon', '', '', ''),
(869, NULL, '', '869.png', ' Pokemon', '', '', ''),
(870, NULL, '', '870.png', ' Pokemon', '', '', ''),
(871, NULL, '', '871.png', ' Pokemon', '', '', ''),
(872, NULL, '', '872.png', ' Pokemon', '', '', ''),
(873, NULL, '', '873.png', ' Pokemon', '', '', ''),
(874, NULL, '', '874.png', ' Pokemon', '', '', ''),
(875, NULL, '', '875.png', ' Pokemon', '', '', ''),
(876, NULL, '', '876.png', ' Pokemon', '', '', ''),
(877, NULL, '', '877.png', ' Pokemon', '', '', ''),
(878, NULL, '', '878.png', ' Pokemon', '', '', ''),
(879, NULL, '', '879.png', ' Pokemon', '', '', ''),
(880, NULL, '', '880.png', ' Pokemon', '', '', ''),
(881, NULL, '', '881.png', ' Pokemon', '', '', ''),
(882, NULL, '', '882.png', ' Pokemon', '', '', ''),
(883, NULL, '', '883.png', ' Pokemon', '', '', ''),
(884, NULL, '', '884.png', ' Pokemon', '', '', ''),
(885, NULL, '', '885.png', ' Pokemon', '', '', ''),
(886, NULL, '', '886.png', ' Pokemon', '', '', ''),
(887, NULL, '', '887.png', ' Pokemon', '', '', ''),
(888, NULL, '', '888.png', ' Pokemon', '', '', ''),
(889, NULL, '', '889.png', ' Pokemon', '', '', ''),
(890, NULL, '', '890.png', ' Pokemon', '', '', ''),
(891, NULL, '', '891.png', ' Pokemon', '', '', ''),
(892, NULL, '', '892.png', ' Pokemon', '', '', ''),
(893, NULL, '', '893.png', ' Pokemon', '', '', ''),
(894, NULL, '', '894.png', ' Pokemon', '', '', ''),
(895, NULL, '', '895.png', ' Pokemon', '', '', ''),
(896, NULL, '', '896.png', ' Pokemon', '', '', ''),
(897, NULL, '', '897.png', ' Pokemon', '', '', ''),
(898, NULL, '', '898.png', ' Pokemon', '', '', ''),
(899, NULL, '', '899.png', ' Pokemon', '', '', ''),
(900, NULL, '', '900.png', ' Pokemon', '', '', ''),
(901, NULL, '', '901.png', ' Pokemon', '', '', ''),
(902, NULL, '', '902.png', ' Pokemon', '', '', ''),
(903, NULL, '', '903.png', ' Pokemon', '', '', ''),
(904, NULL, '', '904.png', ' Pokemon', '', '', ''),
(905, NULL, '', '905.png', ' Pokemon', '', '', ''),
(906, NULL, '', '906.png', ' Pokemon', '', '', ''),
(907, NULL, '', '907.png', ' Pokemon', '', '', ''),
(908, NULL, '', '908.png', ' Pokemon', '', '', ''),
(909, NULL, '', '909.png', ' Pokemon', '', '', ''),
(910, NULL, '', '910.png', ' Pokemon', '', '', ''),
(911, NULL, '', '911.png', ' Pokemon', '', '', ''),
(912, NULL, '', '912.png', ' Pokemon', '', '', ''),
(913, NULL, '', '913.png', ' Pokemon', '', '', ''),
(914, NULL, '', '914.png', ' Pokemon', '', '', ''),
(915, NULL, '', '915.png', ' Pokemon', '', '', ''),
(916, NULL, '', '916.png', ' Pokemon', '', '', ''),
(917, NULL, '', '917.png', ' Pokemon', '', '', ''),
(918, NULL, '', '918.png', ' Pokemon', '', '', ''),
(919, NULL, '', '919.png', ' Pokemon', '', '', ''),
(920, NULL, '', '920.png', ' Pokemon', '', '', ''),
(921, NULL, '', '921.png', ' Pokemon', '', '', ''),
(922, NULL, '', '922.png', ' Pokemon', '', '', ''),
(923, NULL, '', '923.png', ' Pokemon', '', '', ''),
(924, NULL, '', '924.png', ' Pokemon', '', '', ''),
(925, NULL, '', '925.png', ' Pokemon', '', '', ''),
(926, NULL, '', '926.png', ' Pokemon', '', '', ''),
(927, NULL, '', '927.png', ' Pokemon', '', '', ''),
(928, NULL, '', '928.png', ' Pokemon', '', '', ''),
(929, NULL, '', '929.png', ' Pokemon', '', '', ''),
(930, NULL, '', '930.png', ' Pokemon', '', '', ''),
(931, NULL, '', '931.png', ' Pokemon', '', '', ''),
(932, NULL, '', '932.png', ' Pokemon', '', '', ''),
(933, NULL, '', '933.png', ' Pokemon', '', '', ''),
(934, NULL, '', '934.png', ' Pokemon', '', '', ''),
(935, NULL, '', '935.png', ' Pokemon', '', '', ''),
(936, NULL, '', '936.png', ' Pokemon', '', '', ''),
(937, NULL, '', '937.png', ' Pokemon', '', '', ''),
(938, NULL, '', '938.png', ' Pokemon', '', '', ''),
(939, NULL, '', '939.png', ' Pokemon', '', '', ''),
(940, NULL, '', '940.png', ' Pokemon', '', '', ''),
(941, NULL, '', '941.png', ' Pokemon', '', '', ''),
(942, NULL, '', '942.png', ' Pokemon', '', '', ''),
(943, NULL, '', '943.png', ' Pokemon', '', '', ''),
(944, NULL, '', '944.png', ' Pokemon', '', '', ''),
(945, NULL, '', '945.png', ' Pokemon', '', '', ''),
(946, NULL, '', '946.png', ' Pokemon', '', '', ''),
(947, NULL, '', '947.png', ' Pokemon', '', '', ''),
(948, NULL, '', '948.png', ' Pokemon', '', '', ''),
(949, NULL, '', '949.png', ' Pokemon', '', '', ''),
(950, NULL, '', '950.png', ' Pokemon', '', '', ''),
(951, NULL, '', '951.png', ' Pokemon', '', '', ''),
(952, NULL, '', '952.png', ' Pokemon', '', '', ''),
(953, NULL, '', '953.png', ' Pokemon', '', '', ''),
(954, NULL, '', '954.png', ' Pokemon', '', '', ''),
(955, NULL, '', '955.png', ' Pokemon', '', '', ''),
(956, NULL, '', '956.png', ' Pokemon', '', '', ''),
(957, NULL, '', '957.png', ' Pokemon', '', '', ''),
(958, NULL, '', '958.png', ' Pokemon', '', '', ''),
(959, NULL, '', '959.png', ' Pokemon', '', '', ''),
(960, NULL, '', '960.png', ' Pokemon', '', '', ''),
(961, NULL, '', '961.png', ' Pokemon', '', '', ''),
(962, NULL, '', '962.png', ' Pokemon', '', '', ''),
(963, NULL, '', '963.png', ' Pokemon', '', '', ''),
(964, NULL, '', '964.png', ' Pokemon', '', '', ''),
(965, NULL, '', '965.png', ' Pokemon', '', '', ''),
(966, NULL, '', '966.png', ' Pokemon', '', '', ''),
(967, NULL, '', '967.png', ' Pokemon', '', '', ''),
(968, NULL, '', '968.png', ' Pokemon', '', '', ''),
(969, NULL, '', '969.png', ' Pokemon', '', '', ''),
(970, NULL, '', '970.png', ' Pokemon', '', '', ''),
(971, NULL, '', '971.png', ' Pokemon', '', '', ''),
(972, NULL, '', '972.png', ' Pokemon', '', '', ''),
(973, NULL, '', '973.png', ' Pokemon', '', '', ''),
(974, NULL, '', '974.png', ' Pokemon', '', '', ''),
(975, NULL, '', '975.png', ' Pokemon', '', '', ''),
(976, NULL, '', '976.png', ' Pokemon', '', '', ''),
(977, NULL, '', '977.png', ' Pokemon', '', '', ''),
(978, NULL, '', '978.png', ' Pokemon', '', '', ''),
(979, NULL, '', '979.png', ' Pokemon', '', '', ''),
(980, NULL, '', '980.png', ' Pokemon', '', '', ''),
(981, NULL, '', '981.png', ' Pokemon', '', '', ''),
(982, NULL, '', '982.png', ' Pokemon', '', '', ''),
(983, NULL, '', '983.png', ' Pokemon', '', '', ''),
(984, NULL, '', '984.png', ' Pokemon', '', '', ''),
(985, NULL, '', '985.png', ' Pokemon', '', '', ''),
(986, NULL, '', '986.png', ' Pokemon', '', '', ''),
(987, NULL, '', '987.png', ' Pokemon', '', '', ''),
(988, NULL, '', '988.png', ' Pokemon', '', '', ''),
(989, NULL, '', '989.png', ' Pokemon', '', '', ''),
(990, NULL, '', '990.png', ' Pokemon', '', '', ''),
(991, NULL, '', '991.png', ' Pokemon', '', '', ''),
(992, NULL, '', '992.png', ' Pokemon', '', '', ''),
(993, NULL, '', '993.png', ' Pokemon', '', '', ''),
(994, NULL, '', '994.png', ' Pokemon', '', '', ''),
(995, NULL, '', '995.png', ' Pokemon', '', '', ''),
(996, NULL, '', '996.png', ' Pokemon', '', '', ''),
(997, NULL, '', '997.png', ' Pokemon', '', '', ''),
(998, NULL, '', '998.png', ' Pokemon', '', '', ''),
(999, NULL, '', '999.png', ' Pokemon', '', '', ''),
(1000, NULL, '', '1000.png', ' Pokemon', '', '', ''),
(1001, NULL, '', '1001.png', ' Pokemon', '', '', ''),
(1002, NULL, '', '1002.png', ' Pokemon', '', '', ''),
(1003, NULL, '', '1003.png', ' Pokemon', '', '', ''),
(1004, NULL, '', '1004.png', ' Pokemon', '', '', ''),
(1005, NULL, '', '1005.png', ' Pokemon', '', '', ''),
(1006, NULL, '', '1006.png', ' Pokemon', '', '', ''),
(1007, NULL, '', '1007.png', ' Pokemon', '', '', ''),
(1008, NULL, '', '1008.png', ' Pokemon', '', '', ''),
(1009, NULL, '', '1009.png', ' Pokemon', '', '', ''),
(1010, NULL, '', '1010.png', ' Pokemon', '', '', ''),
(1011, NULL, '', '1011.png', ' Pokemon', '', '', ''),
(1012, NULL, '', '1012.png', ' Pokemon', '', '', ''),
(1013, NULL, '', '1013.png', ' Pokemon', '', '', ''),
(1014, NULL, '', '1014.png', ' Pokemon', '', '', ''),
(1015, NULL, '', '1015.png', ' Pokemon', '', '', ''),
(1016, NULL, '', '1016.png', ' Pokemon', '', '', ''),
(1017, NULL, '', '1017.png', ' Pokemon', '', '', ''),
(1018, NULL, '', '1018.png', ' Pokemon', '', '', ''),
(1019, NULL, '', '1019.png', ' Pokemon', '', '', ''),
(1020, NULL, '', '1020.png', ' Pokemon', '', '', ''),
(1021, NULL, '', '1021.png', ' Pokemon', '', '', ''),
(1022, NULL, '', '1022.png', ' Pokemon', '', '', ''),
(1023, NULL, '', '1023.png', ' Pokemon', '', '', ''),
(1024, NULL, '', '1024.png', ' Pokemon', '', '', ''),
(1025, NULL, '', '1025.png', ' Pokemon', '', '', ''),
(1026, NULL, '', '1026.png', ' Pokemon', '', '', ''),
(1027, NULL, '', '1027.png', ' Pokemon', '', '', ''),
(1028, NULL, '', '1028.png', ' Pokemon', '', '', ''),
(1029, NULL, '', '1029.png', ' Pokemon', '', '', ''),
(1030, NULL, '', '1030.png', ' Pokemon', '', '', ''),
(1031, NULL, '', '1031.png', ' Pokemon', '', '', ''),
(1032, NULL, '', '1032.png', ' Pokemon', '', '', ''),
(1033, NULL, '', '1033.png', ' Pokemon', '', '', ''),
(1034, NULL, '', '1034.png', ' Pokemon', '', '', ''),
(1035, NULL, '', '1035.png', ' Pokemon', '', '', ''),
(1036, NULL, '', '1036.png', ' Pokemon', '', '', ''),
(1037, NULL, '', '1037.png', ' Pokemon', '', '', ''),
(1038, NULL, '', '1038.png', ' Pokemon', '', '', ''),
(1039, NULL, '', '1039.png', ' Pokemon', '', '', ''),
(1040, NULL, '', '1040.png', ' Pokemon', '', '', ''),
(1041, NULL, '', '1041.png', ' Pokemon', '', '', ''),
(1042, NULL, '', '1042.png', ' Pokemon', '', '', ''),
(1043, NULL, '', '1043.png', ' Pokemon', '', '', ''),
(1044, NULL, '', '1044.png', ' Pokemon', '', '', ''),
(1045, NULL, '', '1045.png', ' Pokemon', '', '', ''),
(1046, NULL, '', '1046.png', ' Pokemon', '', '', ''),
(1047, NULL, '', '1047.png', ' Pokemon', '', '', ''),
(1048, NULL, '', '1048.png', ' Pokemon', '', '', ''),
(1049, NULL, '', '1049.png', ' Pokemon', '', '', ''),
(1050, NULL, '', '1050.png', ' Pokemon', '', '', ''),
(1051, NULL, '', '1051.png', ' Pokemon', '', '', ''),
(1052, NULL, '', '1052.png', ' Pokemon', '', '', ''),
(1053, NULL, '', '1053.png', ' Pokemon', '', '', ''),
(1054, NULL, '', '1054.png', ' Pokemon', '', '', ''),
(1055, NULL, '', '1055.png', ' Pokemon', '', '', ''),
(1056, NULL, '', '1056.png', ' Pokemon', '', '', ''),
(1057, NULL, '', '1057.png', ' Pokemon', '', '', ''),
(1058, NULL, '', '1058.png', ' Pokemon', '', '', ''),
(1059, NULL, '', '1059.png', ' Pokemon', '', '', ''),
(1060, NULL, '', '1060.png', ' Pokemon', '', '', ''),
(1061, NULL, '', '1061.png', ' Pokemon', '', '', ''),
(1062, NULL, '', '1062.png', ' Pokemon', '', '', ''),
(1063, NULL, '', '1063.png', ' Pokemon', '', '', ''),
(1064, NULL, '', '1064.png', ' Pokemon', '', '', ''),
(1065, NULL, '', '1065.png', ' Pokemon', '', '', ''),
(1066, NULL, '', '1066.png', ' Pokemon', '', '', ''),
(1067, NULL, '', '1067.png', ' Pokemon', '', '', ''),
(1068, NULL, '', '1068.png', ' Pokemon', '', '', ''),
(1069, NULL, '', '1069.png', ' Pokemon', '', '', ''),
(1070, NULL, '', '1070.png', ' Pokemon', '', '', ''),
(1071, NULL, '', '1071.png', ' Pokemon', '', '', ''),
(1072, NULL, '', '1072.png', ' Pokemon', '', '', ''),
(1073, NULL, '', '1073.png', ' Pokemon', '', '', ''),
(1074, NULL, '', '1074.png', ' Pokemon', '', '', ''),
(1075, NULL, '', '1075.png', ' Pokemon', '', '', ''),
(1076, NULL, '', '1076.png', ' Pokemon', '', '', ''),
(1077, NULL, '', '1077.png', ' Pokemon', '', '', ''),
(1078, NULL, '', '1078.png', ' Pokemon', '', '', ''),
(1079, NULL, '', '1079.png', ' Pokemon', '', '', ''),
(1080, NULL, '', '1080.png', ' Pokemon', '', '', ''),
(1081, NULL, '', '1081.png', ' Pokemon', '', '', ''),
(1082, NULL, '', '1082.png', ' Pokemon', '', '', ''),
(1083, NULL, '', '1083.png', ' Pokemon', '', '', ''),
(1084, NULL, '', '1084.png', ' Pokemon', '', '', ''),
(1085, NULL, '', '1085.png', ' Pokemon', '', '', ''),
(1086, NULL, '', '1086.png', ' Pokemon', '', '', ''),
COMMIT TRANSACTION;