erDiagram
  Pokemon {
    INTEGER pokedex_number PK
    INTEGER region_id PK
    TEXT name
    TEXT image
    TEXT species
    INTEGER primary_type_id
    INTEGER secondary_type_id
    INTEGER primary_ability_id
    INTEGER secondary_ability_id
    INTEGER hidden_ability_id
    TEXT description
  }
  Pokemon_Ability {
    INTEGER ability_id PK
    TEXT name
    TEXT description
  }
  Pokemon_Evolution {
    INTEGER base_pokedex_number PK
    INTEGER evolved_pokedex_number PK
    INTEGER base_region_id PK
    INTEGER evolved_region_id PK
    TEXT evolution_condition
    INTEGER chain_id PK
  }
  Pokemon_Game {
    INTEGER game_id PK
    TEXT game_name
  }
  Pokemon_Level_Up_Moveset {
    INTEGER level_up_moveset_id PK
    INTEGER pokedex_number
    INTEGER region_id
    INTEGER move_id
    INTEGER mainline_game_id
    INTEGER level_learned
  }
  Pokemon_Location {
    INTEGER pokedex_number PK
    INTEGER region_id PK
    INTEGER game_id PK
    TEXT location_name
  }
  Pokemon_Mainline_Game {
    INTEGER mainline_game_id PK
    TEXT game_name
  }
  Pokemon_Move {
    INTEGER move_id PK
    TEXT move_name
    TEXT description
    INTEGER type_id
    INTEGER category_id
    INTEGER power
    FLOAT(5, 2) accuracy
    INTEGER pp
  }
  Pokemon_Move_Category {
    INTEGER category_id PK
    TEXT category_name
  }
  Pokemon_Region {
    INTEGER region_id PK
    TEXT name
    TEXT image
    INTEGER start
    INTEGER end
  }
  Pokemon_Regional_Form {
    INTEGER region_id PK
    TEXT region_name
  }
  Pokemon_Technical_Move {
    INTEGER technical_move_id PK
    INTEGER move_id
    INTEGER mainline_game_id
    INTEGER technical_number
    INTEGER is_tr
  }
  Pokemon_Technical_Moveset {
    INTEGER technical_moveset_id PK
    INTEGER pokedex_number
    INTEGER region_id
    INTEGER mainline_game_id
    INTEGER technical_move_id
  }
  Pokemon_Type {
    INTEGER type_id PK
    TEXT type_name
  }
  Pokemon_Type_Effectiveness {
    INTEGER type_effectiveness_id PK
    INTEGER attacking_type_id
    INTEGER defending_type_id
    REAL damage_multiplier
  }
  Pokemon_Regional_Form ||--o{ Pokemon : "region_id→region_id"
  Pokemon_Ability ||--o{ Pokemon : "hidden_ability_id→ability_id"
  Pokemon_Ability ||--o{ Pokemon : "secondary_ability_id→ability_id"
  Pokemon_Ability ||--o{ Pokemon : "primary_ability_id→ability_id"
  Pokemon_Type ||--o{ Pokemon : "secondary_type_id→type_id"
  Pokemon_Type ||--o{ Pokemon : "primary_type_id→type_id"
  Pokemon ||--o{ Pokemon_Evolution : "evolved_pokedex_number→pokedex_number"
  Pokemon ||--o{ Pokemon_Evolution : "evolved_region_id→region_id"
  Pokemon ||--o{ Pokemon_Evolution : "base_pokedex_number→pokedex_number"
  Pokemon ||--o{ Pokemon_Evolution : "base_region_id→region_id"
  Pokemon_Mainline_Game ||--o{ Pokemon_Level_Up_Moveset : "mainline_game_id→mainline_game_id"
  Pokemon_Move ||--o{ Pokemon_Level_Up_Moveset : "move_id→move_id"
  Pokemon ||--o{ Pokemon_Level_Up_Moveset : "pokedex_number→pokedex_number"
  Pokemon ||--o{ Pokemon_Level_Up_Moveset : "region_id→region_id"
  Pokemon_Game ||--o{ Pokemon_Location : "game_id→game_id"
  Pokemon ||--o{ Pokemon_Location : "pokedex_number→pokedex_number"
  Pokemon ||--o{ Pokemon_Location : "region_id→region_id"
  Pokemon_Move_Category ||--o{ Pokemon_Move : "category_id→category_id"
  Pokemon_Type ||--o{ Pokemon_Move : "type_id→type_id"
  Pokemon_Mainline_Game ||--o{ Pokemon_Technical_Move : "mainline_game_id→mainline_game_id"
  Pokemon_Move ||--o{ Pokemon_Technical_Move : "move_id→move_id"
  Pokemon_Mainline_Game ||--o{ Pokemon_Technical_Moveset : "mainline_game_id→mainline_game_id"
  Pokemon ||--o{ Pokemon_Technical_Moveset : "pokedex_number→pokedex_number"
  Pokemon ||--o{ Pokemon_Technical_Moveset : "region_id→region_id"
  Pokemon_Type ||--o{ Pokemon_Type_Effectiveness : "defending_type_id→type_id"
  Pokemon_Type ||--o{ Pokemon_Type_Effectiveness : "attacking_type_id→type_id"
