BEGIN TRANSACTION;

INSERT INTO Pokemon_Location (pokedex_number, region_id, game_id, location_name)
VALUES

-- Chikorita
(152, NULL, 1, NULL),
(152, NULL, 2, NULL),
(152, NULL, 3, NULL),
(152, NULL, 4, 'Coastal Biome, Torchlit Labyrinth'),
(152, NULL, 5, 'Coastal Biome, Torchlit Labyrinth'),
-- Bayleef
(153, NULL, 1, NULL),
(153, NULL, 2, NULL),
(153, NULL, 3, NULL),
(153, NULL, 4, 'Evolve Chikorita'),
(153, NULL, 5, 'Evolve Chikorita'),
-- Meganium
(154, NULL, 1, NULL),
(154, NULL, 2, NULL),
(154, NULL, 3, NULL),
(154, NULL, 4, 'Evolve Bayleef'),
(154, NULL, 5, 'Evolve Bayleef'),
-- Cyndaquil
(155, NULL, 1, NULL),
(155, NULL, 2, NULL),
(155, NULL, 3, 'Gift from Laventon, Space-time Distortion in Crimson Mirelands or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(155, NULL, 4, 'Polar Biome'),
(155, NULL, 5, 'Polar Biome'),
-- Quilava
(156, NULL, 1, NULL),
(156, NULL, 2, NULL),
(156, NULL, 3, 'Space-time Distortion in Crimson Mirelands or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(156, NULL, 4, 'Evolve Cyndaquil'),
(156, NULL, 5, 'Evolve Cyndaquil'),
-- Typhlosion
(157, NULL, 1, NULL),
(157, NULL, 2, NULL),
(157, NULL, 3, NULL),
(157, NULL, 4, 'Evolve Quilava'),
(157, NULL, 5, 'Evolve Quilava'),
-- Hisuian Typhlosion
(157, 3, 1, NULL),
(157, 3, 2, NULL),
(157, 3, 3, 'Space-time Distortion in Crimson Mirelands or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(157, 3, 4, 'Transfer from Pokémon HOME'),
(157, 3, 5, 'Transfer from Pokémon HOME'),
-- Totodile
(158, NULL, 1, NULL),
(158, NULL, 2, NULL),
(158, NULL, 3, NULL),
(158, NULL, 4, 'Savanna Biome'),
(158, NULL, 5, 'Savanna Biome'),
-- Croconaw
(159, NULL, 1, NULL),
(159, NULL, 2, NULL),
(159, NULL, 3, NULL),
(159, NULL, 4, 'Evolve Totodile'),
(159, NULL, 5, 'Evolve Totodile'),
-- Feraligatr
(160, NULL, 1, NULL),
(160, NULL, 2, NULL),
(160, NULL, 3, NULL),
(160, NULL, 4, 'Evolve Croconaw'),
(160, NULL, 5, 'Evolve Croconaw'),
-- Sentret
(161, NULL, 1, NULL),
(161, NULL, 2, NULL),
(161, NULL, 3, NULL),
(161, NULL, 4, 'Apple Hills, Kitakami Hall, Kitakami Road, Loyalty Plaza, Mossfell Confluence, Reveler''s Road<br>Fixed: Applie Hills<br>Tera Raid Battles: 1 Star Raid Battles'),
(161, NULL, 5, 'Apple Hills, Kitakami Hall, Kitakami Road, Loyalty Plaza, Mossfell Confluence, Reveler''s Road<br>Fixed: Applie Hills<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Furret
(162, NULL, 1, NULL),
(162, NULL, 2, NULL),
(162, NULL, 3, NULL),
(162, NULL, 4, 'Apple Hills, Kitakami Hall, Kitakami Road, Mossfell Confluence, Reveler''s Road<br>Fixed: Applie Hills<br>Tera Raid Battles: 3 Star Raid Battles, 4 Star Raid Battles'),
(162, NULL, 5, 'Apple Hills, Kitakami Hall, Kitakami Road, Mossfell Confluence, Reveler''s Road<br>Fixed: Applie Hills<br>Tera Raid Battles: 3 Star Raid Battles, 4 Star Raid Battles'),
-- Hoothoot
(163, NULL, 1, 'Route 1, Route 2, Dappled Grove, Giant''s Cap, Slumbering Weald<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Rolling Fields, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea'),
(163, NULL, 2, 'Route 1, Route 2, Dappled Grove, Giant''s Cap, Slumbering Weald<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Rolling Fields, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea'),
(163, NULL, 3, NULL),
(163, NULL, 4, 'Fellhorn Gorge, Kitakami Hall, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Paradise Barrens, Reveler''s Road, Timeless Woods, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
(163, NULL, 5, 'Fellhorn Gorge, Kitakami Hall, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Paradise Barrens, Reveler''s Road, Timeless Woods, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Noctowl
(164, NULL, 1, 'Bridge Field, Giant''s Cap, Motostoke Outskirts, Motostoke Riverbank<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Rolling Fields, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea<br>Dynamax Adventures'),
(164, NULL, 2, 'Bridge Field, Giant''s Cap, Motostoke Outskirts, Motostoke Riverbank<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Rolling Fields, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea<br>Dynamax Adventures'),
(164, NULL, 3, NULL),
(164, NULL, 4, 'Fellhorn Gorge, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: Oni Mountain<br>Tera Raid Battles: 3 Star Raid Battles, 4 Star Raid Battles'),
(164, NULL, 5, 'Fellhorn Gorge, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: Oni Mountain<br>Tera Raid Battles: 3 Star Raid Battles, 4 Star Raid Battles'),
-- Ledyba
(165, NULL, 1, NULL),
(165, NULL, 2, NULL),
(165, NULL, 3, NULL),
(165, NULL, 4, NULL),
(165, NULL, 5, NULL),
-- Ledian
(166, NULL, 1, NULL),
(166, NULL, 2, NULL),
(166, NULL, 3, NULL),
(166, NULL, 4, NULL),
(166, NULL, 5, NULL),
-- Spinarak
(167, NULL, 1, NULL),
(167, NULL, 2, NULL),
(167, NULL, 3, NULL),
(167, NULL, 4, 'Apple Hills, Fellhorn Gorge, Kitakami Hall, Kitakami Road, Kitakami Wilds, Loyalty Plaza, Mossfell Confluence, Reveler''s Road, Timeless Woods<br>Tera Raid Battles: 1 Star Raid Battles'),
(167, NULL, 5, 'Apple Hills, Fellhorn Gorge, Kitakami Hall, Kitakami Road, Kitakami Wilds, Loyalty Plaza, Mossfell Confluence, Reveler''s Road, Timeless Woods<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Ariados
(168, NULL, 1, NULL),
(168, NULL, 2, NULL),
(168, NULL, 3, NULL),
(168, NULL, 4, 'Fellhorn Gorge, Kitakami Wilds, Mossfell Confluence, Timeless Woods<br>Fixed: Mossfell Confluence, Timeless Woods<br>Tera Raid Battles: 3 Star Raid Battles, 4 Star Raid Battles'),
(168, NULL, 5, 'Fellhorn Gorge, Kitakami Wilds, Mossfell Confluence, Timeless Woods<br>Fixed: Mossfell Confluence, Timeless Woods<br>Tera Raid Battles: 3 Star Raid Battles, 4 Star Raid Battles'),
-- Crobat
(169, NULL, 1, 'Max Raid Battles: Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(169, NULL, 2, 'Max Raid Battles: Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(169, NULL, 3, 'Coronet Highlands: Wayward Cave or nearby<br>Alabaster Icelands: Icebound Falls or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(169, NULL, 4, NULL),
(169, NULL, 5, NULL),
-- Chinchou
(170, NULL, 1, 'East Lake Axewell, Giant''s Mirror, Hulbury, West Lake Axewell, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Giant''s Mirror, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, South Lake Miloch, West Lake Axewell, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea'),
(170, NULL, 2, 'East Lake Axewell, Giant''s Mirror, Hulbury, West Lake Axewell, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Giant''s Mirror, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, South Lake Miloch, West Lake Axewell, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea'),
(170, NULL, 3, NULL),
(170, NULL, 4, 'Canyon Biome<br>Tera Raid Battles: 1 Star Raid Battles, 3 Star Raid Battles'),
(170, NULL, 5, 'Canyon Biome<br>Tera Raid Battles: 1 Star Raid Battles, 3 Star Raid Battles'),
-- Lanturn
(171, NULL, 1, 'Bridge Field, Dusty Bowl, East Lake Axewell, Lake of Outrage, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Giant''s Mirror, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, South Lake Miloch, West Lake Axewell, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea<br>Dynamax Adventures'),
(171, NULL, 2, 'Bridge Field, Dusty Bowl, East Lake Axewell, Lake of Outrage, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Giant''s Mirror, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, South Lake Miloch, West Lake Axewell, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea<br>Dynamax Adventures'),
(171, NULL, 3, NULL),
(171, NULL, 4, 'Canyon Biome<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(171, NULL, 5, 'Canyon Biome<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Pichu
(172, NULL, 1, 'Forest of Focus<br>Max Raid Battles: Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea'),
(172, NULL, 2, 'Forest of Focus<br>Max Raid Battles: Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea'),
(172, NULL, 3, 'Obsidian Fieldlands: Floaro Gardens, Nature''s Pantry or nearby<br>Crimson Mirelands: Golden Lowlands or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(172, NULL, 4, 'South Province Area One, South Province Area Two, Apple Hills, Crystal Pool, Infernal Pass, Kitakami Road, Loyalty Plaza, Oni Mountain, Oni''s Maw, Reveler''s Road, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
(172, NULL, 5, 'South Province Area One, South Province Area Two, Apple Hills, Crystal Pool, Infernal Pass, Kitakami Road, Loyalty Plaza, Oni Mountain, Oni''s Maw, Reveler''s Road, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Cleffa
(173, NULL, 1, 'Max Raid Battles: Hammerlocke Hills, Rolling Fields, Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(173, NULL, 2, 'Max Raid Battles: Hammerlocke Hills, Rolling Fields, Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(173, NULL, 3, 'Coronet Highlands: Fabled Spring or nearby<br>Cobalt Coastlands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(173, NULL, 4, 'Crystal Pool, Infernal Pass, Kitakami Hall, Oni Mountain, Reveler''s Road<br>Tera Raid Battles: 1 Star Raid Battles'),
(173, NULL, 5, 'Crystal Pool, Infernal Pass, Kitakami Hall, Oni Mountain, Reveler''s Road<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Igglybuff
(174, NULL, 1, 'Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Stepping-Stone Sea, Insular Sea'),
(174, NULL, 2, 'Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Stepping-Stone Sea, Insular Sea'),
(174, NULL, 3, NULL),
(174, NULL, 4, 'Pokemon League, South Province Area One, South Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
(174, NULL, 5, 'Pokemon League, South Province Area One, South Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Togepi
(175, NULL, 1, 'Bridge Field<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Rolling Fields'),
(175, NULL, 2, 'Bridge Field<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Rolling Fields'),
(175, NULL, 3, 'Crimson Mirelands: Cottonsedge Prairie or nearby<br>Cobalt Coastlands: Bathers'' Lagoon, Tranquility Cove or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(175, NULL, 4, NULL),
(175, NULL, 5, NULL),
-- Togetic
(176, NULL, 1, 'Stony Wilderness<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Rolling Fields<br>Dynamax Adventures'),
(176, NULL, 2, 'Stony Wilderness<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Rolling Fields<br>Dynamax Adventures'),
(176, NULL, 3, 'Crimson Mirelands: Bolderoll Slope, Cottonsedge Prairie or nearby<br>Cobalt Coastlands: Tranquility Cove or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(176, NULL, 4, NULL),
(176, NULL, 5, NULL),
-- Natu
(177, NULL, 1, 'Giant''s Mirror, Giant''s Seat, North Lake Miloch, Rolling Fields, South Lake Miloch, West Lake Axewell<br>Max Raid Battles: Bridge Field, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Rolling Fields, Stony Wilderness'),
(177, NULL, 2, 'Giant''s Mirror, Giant''s Seat, North Lake Miloch, Rolling Fields, South Lake Miloch, West Lake Axewell<br>Max Raid Battles: Bridge Field, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Rolling Fields, Stony Wilderness'),
(177, NULL, 3, NULL),
(177, NULL, 4, NULL),
(177, NULL, 5, NULL),
-- Xatu
(178, NULL, 1, 'East Lake Axewell, Giant''s Mirror, Giant''s Seat, North Lake Miloch<br>Max Raid Battles: Bridge Field, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Rolling Fields, Stony Wilderness<br>Dynamax Adventures'),
(178, NULL, 2, 'East Lake Axewell, Giant''s Mirror, Giant''s Seat, North Lake Miloch<br>Max Raid Battles: Bridge Field, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Rolling Fields, Stony Wilderness<br>Dynamax Adventures'),
(178, NULL, 3, NULL),
(178, NULL, 4, NULL),
(178, NULL, 5, NULL),
-- Mareep
(179, NULL, 1, NULL),
(179, NULL, 2, NULL),
(179, NULL, 3, NULL),
(179, NULL, 4, 'South Province Area Two<br>Tera Raid Battles: 2 Star Raid Battles'),
(179, NULL, 5, 'South Province Area Two<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Flaaffy
(180, NULL, 1, NULL),
(180, NULL, 2, NULL),
(180, NULL, 3, NULL),
(180, NULL, 4, 'West Province Area Two<br>Fixed: South Province Area Four<br>Tera Raid Battles: 3 Star Raid Battles'),
(180, NULL, 5, 'West Province Area Two<br>Fixed: South Province Area Four<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Ampharos
(181, NULL, 1, NULL),
(181, NULL, 2, NULL),
(181, NULL, 3, NULL),
(181, NULL, 4, 'Alfornada Cavern, North Province Area One<br>Tera Raid Battles: 4 Star Raid Battles'),
(181, NULL, 5, 'Alfornada Cavern, North Province Area One<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Bellossom
(182, NULL, 1, 'Giant''s Mirror<br>Max Raid Battles: Dappled Grove<br>Dynamax Adventures'),
(182, NULL, 2, 'Giant''s Mirror<br>Max Raid Battles: Dappled Grove<br>Dynamax Adventures'),
(182, NULL, 3, NULL),
(182, NULL, 4, 'Coastal Biome, Torchlit Labyrinth<br>Tera Raid Battles: 4 Star Raid Battles'),
(182, NULL, 5, 'Coastal Biome, Torchlit Labyrinth<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Marill
(183, NULL, 1, 'Fields of Honor, Soothing Wetlands, Challenge Beach<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea'),
(183, NULL, 2, 'Fields of Honor, Soothing Wetlands, Challenge Beach<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea'),
(183, NULL, 3, NULL),
(183, NULL, 4, 'East Province Area Two, South Province Area One, South Province Area Two, South Province Area Four, South Province Area Five, West Province Area One<br>Tera Raid Battles: 3 Star Raid Battles'),
(183, NULL, 5, 'East Province Area Two, South Province Area One, South Province Area Two, South Province Area Four, South Province Area Five, West Province Area One<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Azumarill
(184, NULL, 1, 'Soothing Wetlands, Forest of Focus, Challenge Beach, Training Lowlands<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea'),
(184, NULL, 2, 'Soothing Wetlands, Forest of Focus, Challenge Beach, Training Lowlands<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea'),
(184, NULL, 3, NULL),
(184, NULL, 4, 'Casseroya Lake, West Province Area Two<br>Fixed: Casseroya Lake<br>Tera Raid Battles: 4 Star Raid Battles'),
(184, NULL, 5, 'Casseroya Lake, West Province Area Two<br>Fixed: Casseroya Lake<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Sudowoodo
(185, NULL, 1, 'Bridge Field, Dusty Bowl, Giant''s Mirror, Hammerlocke Hills, Motostoke Outskirts, Motostoke Riverbank<br>Max Raid Battles: Giant''s Seat, Rolling Fields, Stony Wilderness, Rolling Fields, Stony Wilderness, Fields of Honor, Training Lowlands, Potbottom Desert<br>Dynamax Adventures'),
(185, NULL, 2, 'Bridge Field, Dusty Bowl, Giant''s Mirror, Hammerlocke Hills, Motostoke Outskirts, Motostoke Riverbank<br>Max Raid Battles: Giant''s Seat, Rolling Fields, Stony Wilderness, Rolling Fields, Stony Wilderness, Fields of Honor, Training Lowlands, Potbottom Desert<br>Dynamax Adventures'),
(185, NULL, 3, 'Crimson Mirelands: Cloudpool Ridge or nearby<br>Coronet Highlands: Celestica Ruins or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(185, NULL, 4, 'Socarrat Trail, West Province Area Three, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
(185, NULL, 5, 'Socarrat Trail, West Province Area Three, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Politoed
(186, NULL, 1, 'Soothing Wetlands<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Courageous Cavern<br>Dynamax Adventures'),
(186, NULL, 2, 'Soothing Wetlands<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Courageous Cavern<br>Dynamax Adventures'),
(186, NULL, 3, NULL),
(186, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(186, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Hoppip
(187, NULL, 1, NULL),
(187, NULL, 2, NULL),
(187, NULL, 3, NULL),
(187, NULL, 4, 'South Province Area One, South Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
(187, NULL, 5, 'South Province Area One, South Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Skiploom
(188, NULL, 1, NULL),
(188, NULL, 2, NULL),
(188, NULL, 3, NULL),
(188, NULL, 4, 'East Province Area One, East Province Area Two, South Province Area Three, South Province Area Five<br>Fixed: West Province Area Two<br>Tera Raid Battles: 3 Star Raid Battles'),
(188, NULL, 5, 'East Province Area One, East Province Area Two, South Province Area Three, South Province Area Five<br>Fixed: West Province Area Two<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Jumpluff
(189, NULL, 1, NULL),
(189, NULL, 2, NULL),
(189, NULL, 3, NULL),
(189, NULL, 4, 'North Province Area One, North Province Area Two, North Province Area Three, West Province Area Three'),
(189, NULL, 5, 'North Province Area One, North Province Area Two, North Province Area Three, West Province Area Three'),
-- Aipom
(190, NULL, 1, NULL),
(190, NULL, 2, NULL),
(190, NULL, 3, 'Obsidian Fieldlands: Ramanas Island or nearby<br>Cobalt Coastlands: Aipom Hill, Hideaway Bay or nearby<br>Alabaster Icelands: Whiteout Valley, Glacier Terrace, Snowfall Hot Spring, Heart''s Crag or nearby<br>Cobalt Coastlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(190, NULL, 4, 'Trade from Pokémon Violet'),
(190, NULL, 5, 'Fellhorn Gorge, Kitakami Hall, Kitakami Wilds, Mossfell Confluence, Paradise Barrens, Reveler''s Road, Timeless Woods, Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Sunkern
(191, NULL, 1, NULL),
(191, NULL, 2, NULL),
(191, NULL, 3, NULL),
(191, NULL, 4, 'South Province Area One, South Province Area Two<br>Fixed: South Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
(191, NULL, 5, 'South Province Area One, South Province Area Two<br>Fixed: South Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Sunflora
(192, NULL, 1, NULL),
(192, NULL, 2, NULL),
(192, NULL, 3, NULL),
(192, NULL, 4, 'East Paldean Sea, North Province Area Three, South Province Area Six, Tagtree Thicket<br>Fixed: North Province Area Two<br>Tera Raid Battles: 3 Star Raid Battles'),
(192, NULL, 5, 'East Paldean Sea, North Province Area Three, South Province Area Six, Tagtree Thicket<br>Fixed: North Province Area Two<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Yanma
(193, NULL, 1, NULL),
(193, NULL, 2, NULL),
(193, NULL, 3, 'Crimson Mirelands: Gapejaw Bog, Ursa''s Ring, Droning Meadow or nearby<br>Coronet Highlands: Heavenward Lookout or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(193, NULL, 4, 'Crystal Pool, Infernal Pass, Kitakami Road, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: Kitakami Road, Kitakami Wilds, Mossfell Confluence, Wistful Fields<br>Tera Raid Battles: 2 Star Raid Battles'),
(193, NULL, 5, 'Crystal Pool, Infernal Pass, Kitakami Road, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: Kitakami Road, Kitakami Wilds, Mossfell Confluence, Wistful Fields<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Wooper
(194, NULL, 1, 'Giant''s Cap, Giant''s Seat, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Challenge Beach<br>Bridge Field, Dusty Bowl, Rolling Fields, West Lake Axewell, Fields of Honor, Soothing Wetlands, Courageous Cavern'),
(194, NULL, 2, 'Giant''s Cap, Giant''s Seat, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Challenge Beach<br>Bridge Field, Dusty Bowl, Rolling Fields, West Lake Axewell, Fields of Honor, Soothing Wetlands, Courageous Cavern'),
(194, NULL, 3, NULL),
(194, NULL, 4, 'Trade in Cascarrafa<br>Chilling Waterhead, Fellhorn Gorge, Kitakami Road, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Reveler''s Road, Timeless Woods<br>Fixed: Kitakami Road, Oni''s Maw<br>Tera Raid Battles: 1 Star Raid Battles'),
(194, NULL, 5, 'Trade in Cascarrafa<br>Chilling Waterhead, Fellhorn Gorge, Kitakami Road, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Reveler''s Road, Timeless Woods<br>Fixed: Kitakami Road, Oni''s Maw<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Paldean Wooper
(194, 4, 1, NULL),
(194, 4, 2, NULL),
(194, 4, 3, NULL),
(194, 4, 4, 'Alfornada Cavern, East Province Area Three, Glaseado Mountain, North Province Area One, South Province Area One, South Province Area Four, South Province Area Five, South Province Area Six, Tagtree Thicket, West Province Area Three<br>Fixed: South Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
(194, 4, 5, 'Alfornada Cavern, East Province Area Three, Glaseado Mountain, North Province Area One, South Province Area One, South Province Area Four, South Province Area Five, South Province Area Six, Tagtree Thicket, West Province Area Three<br>Fixed: South Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Quagsire
(195, NULL, 1, 'Giant''s Cap, Giant''s Seat, Lake of Outrage, West Lake Axewell, Soothing Wetlands<br>Max Raid Battles: Bridge Field, Dusty Bowl, Rolling Fields, West Lake Axewell, Fields of Honor, Soothing Wetlands, Courageous Cavern<br>Dynamax Adventures'),
(195, NULL, 2, 'Giant''s Cap, Giant''s Seat, Lake of Outrage, West Lake Axewell, Soothing Wetlands<br>Max Raid Battles: Bridge Field, Dusty Bowl, Rolling Fields, West Lake Axewell, Fields of Honor, Soothing Wetlands, Courageous Cavern<br>Dynamax Adventures'),
(195, NULL, 3, NULL),
(195, NULL, 4, 'Chilling Waterhead, Fellhorn Gorge, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Timeless Woods<br>Fixed: Chilling Waterhead, Fellhorn Gorge, Kitakami Wilds, Timeless Woods<br>Tera Raid Battles: 4 Star Raid Battles, 6 Star Raid Battles'),
(195, NULL, 5, 'Chilling Waterhead, Fellhorn Gorge, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Timeless Woods<br>Fixed: Chilling Waterhead, Fellhorn Gorge, Kitakami Wilds, Timeless Woods<br>Tera Raid Battles: 4 Star Raid Battles, 6 Star Raid Battles'),
-- Espeon
(196, NULL, 1, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Hammerlocke Hills, Ballimere Lake'),
(196, NULL, 2, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Hammerlocke Hills, Ballimere Lake'),
(196, NULL, 3, 'Alabaster Icelands: Space-time Distortion in Alabaster Icelands or nearby'),
(196, NULL, 4, 'North Province Area Three, West Province Area Three<br>Fixed: East Province Area Three<br>Tera Raid Battles: 6 Star Raid Battles'),
(196, NULL, 5, 'North Province Area Three, West Province Area Three<br>Fixed: East Province Area Three<br>Tera Raid Battles: 6 Star Raid Battles'),
-- Umbreon
(197, NULL, 1, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Giant''s Mirror, Ballimere Lake'),
(197, NULL, 2, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Giant''s Mirror, Ballimere Lake'),
(197, NULL, 3, 'Crimson Mirelands: Space-time Distortion in Crimson Mirelands or nearby'),
(197, NULL, 4, 'Alfornada Cavern, Dalizapa Passage, North Province Area One, North Province Area Two, North Province Area Three<br>Fixed: South Province Area Six<br>Tera Raid Battles: 6 Star Raid Battles'),
(197, NULL, 5, 'Alfornada Cavern, Dalizapa Passage, North Province Area One, North Province Area Two, North Province Area Three<br>Fixed: South Province Area Six<br>Tera Raid Battles: 6 Star Raid Battles'),
-- Murkrow
(198, NULL, 1, NULL),
(198, NULL, 2, NULL),
(198, NULL, 3, 'Crimson Mirelands: Cloudpool Ridge or nearby<br>Cobalt Coastlands: Crossing Slope, Veilstone Cape, Hideaway Bay, Islespy Shore or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(198, NULL, 4, 'East Province Area One, East Province Area Two, East Province Area Three, South Province Area One, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five, Tagtree Thicket, West Province Area Two, West Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
(198, NULL, 5, 'East Province Area One, East Province Area Two, East Province Area Three, South Province Area One, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five, Tagtree Thicket, West Province Area Two, West Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Slowking
(199, NULL, 1, NULL),
(199, NULL, 2, NULL),
(199, NULL, 3, NULL),
(199, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(199, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Galarian Slowking
(199, 2, 1, 'Dynamax Adventures'),
(199, 2, 2, 'Dynamax Adventures'),
(199, 2, 3, NULL),
(199, 2, 4, 'Tera Raid Battles: 6 Star Raid Battles'),
(199, 2, 5, 'Tera Raid Battles: 6 Star Raid Battles'),
-- Misdreavus
(200, NULL, 1, NULL),
(200, NULL, 2, NULL),
(200, NULL, 3, 'Coronet Highlands: Stonetooth Rows, Sacred Plaza, Celestica Ruins or nearby<br>Coronet Highlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(200, NULL, 4, 'Trade from Pokémon Violet'),
(200, NULL, 5, 'Dalizapa Passage, East Province Area Two, Glaseado Mountain, South Province Area One, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five, South Province Area Six, Tagtree Thicket, West Province Area One<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Unown
(201, NULL, 1, NULL),
(201, NULL, 2, NULL),
(201, NULL, 3, 'Crimson Mirelands: Solaceon Ruins or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(201, NULL, 4, NULL),
(201, NULL, 5, NULL),
-- Wobbuffet
(202, NULL, 1, 'Route 5, Bridge Field, Dusty Bowl, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank<br>Max Raid Battles: Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness'),
(202, NULL, 2, 'Route 5, Bridge Field, Dusty Bowl, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank<br>Max Raid Battles: Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness'),
(202, NULL, 3, NULL),
(202, NULL, 4, NULL),
(202, NULL, 5, NULL),
-- Girafarig
(203, NULL, 1, NULL),
(203, NULL, 2, NULL),
(203, NULL, 3, NULL),
(203, NULL, 4, 'Area Zero, West Province Area Three, Savanna Biome<br>Fixed: West Province Area Two, Canyon Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(203, NULL, 5, 'Area Zero, West Province Area Three, Savanna Biome<br>Fixed: West Province Area Two, Canyon Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Pineco
(204, NULL, 1, NULL),
(204, NULL, 2, NULL),
(204, NULL, 3, NULL),
(204, NULL, 4, 'East Province Area One, East Province Area Two, South Province Area Four, Tagtree Thicket, West Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
(204, NULL, 5, 'East Province Area One, East Province Area Two, South Province Area Four, Tagtree Thicket, West Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Forretress
(205, NULL, 1, NULL),
(205, NULL, 2, NULL),
(205, NULL, 3, NULL),
(205, NULL, 4, 'Socarrat Trail<br>Fixed: Casseroya Lake<br>Tera Raid Battles: 4 Star Raid Battles'),
(205, NULL, 5, 'Socarrat Trail<br>Fixed: Casseroya Lake<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Dunsparce
(206, NULL, 1, 'Soothing Wetlands, Challenge Beach<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea<br>Dynamax Adventures'),
(206, NULL, 2, 'Soothing Wetlands, Challenge Beach<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea<br>Dynamax Adventures'),
(206, NULL, 3, NULL),
(206, NULL, 4, 'Alfornada Cavern, Area Zero, Asado Desert, Dalizapa Passage, East Province Area One, East Province Area Two, East Province Area Three, South Province Area One, South Province Area Three, South Province Area Four, South Province Area Five, South Province Area Six, Tagtree Thicket, West Province Area Two, West Province Area Three, Chilling Waterhead, Crystal Pool, Oni Mountain, Timeless Woods<br>Fixed: South Province Area Three, South Province Area Five, South Province Area Six, West Province Area Two, Oni Mountain<br>Tera Raid Battles: 1 Star Raid Battles , 3 Star Raid Battles'),
(206, NULL, 5, 'Alfornada Cavern, Area Zero, Asado Desert, Dalizapa Passage, East Province Area One, East Province Area Two, East Province Area Three, South Province Area One, South Province Area Three, South Province Area Four, South Province Area Five, South Province Area Six, Tagtree Thicket, West Province Area Two, West Province Area Three, Chilling Waterhead, Crystal Pool, Oni Mountain, Timeless Woods<br>Fixed: South Province Area Three, South Province Area Five, South Province Area Six, West Province Area Two, Oni Mountain<br>Tera Raid Battles: 1 Star Raid Battles , 3 Star Raid Battles'),
-- Gligar
(207, NULL, 1, NULL),
(207, NULL, 2, NULL),
(207, NULL, 3, 'Coronet Highlands: Clamberclaw Cliffs, Celestica Ruins, Cloudcap Pass, Primeval Grotto or nearby<br>Alabaster Icelands: Glacier Terrace, Arena''s Approach or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(207, NULL, 4, 'Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
(207, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Steelix
(208, NULL, 1, 'Giant''s Mirror, Giant''s Seat<br>Max Raid Battles: Bridge Field, Giant''s Seat, Hammerlocke Hills, Rolling Fields, Stony Wilderness'),
(208, NULL, 2, 'Giant''s Mirror, Giant''s Seat<br>Max Raid Battles: Bridge Field, Giant''s Seat, Hammerlocke Hills, Rolling Fields, Stony Wilderness'),
(208, NULL, 3, 'Coronet Highlands: Celestica Trail or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Cobalt Coastlands: Massive Mass Outbreak'),
(208, NULL, 4, NULL),
(208, NULL, 5, NULL),
-- Snubbull
(209, NULL, 1, NULL),
(209, NULL, 2, NULL),
(209, NULL, 3, NULL),
(209, NULL, 4, 'Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
(209, NULL, 5, 'Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Granbull
(210, NULL, 1, NULL),
(210, NULL, 2, NULL),
(210, NULL, 3, NULL),
(210, NULL, 4, 'Polar Biome<br>Fixed: Polar Biome, Torchlit Labyrinth<br>Tera Raid Battles: 4 Star Raid Battles'),
(210, NULL, 5, 'Polar Biome<br>Fixed: Polar Biome, Torchlit Labyrinth<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Qwilfish
(211, NULL, 1, 'Route 9, Bridge Field, Dusty Bowl, Lake of Outrage<br>Max Raid Battles: Bridge Field, Dusty Bowl, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Training Lowlands, Stepping-Stone Sea<br>Dynamax Adventures'),
(211, NULL, 2, 'Route 9, Bridge Field, Dusty Bowl, Lake of Outrage<br>Max Raid Battles: Bridge Field, Dusty Bowl, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Training Lowlands, Stepping-Stone Sea<br>Dynamax Adventures'),
(211, NULL, 3, NULL),
(211, NULL, 4, 'East Paldean Sea, North Paldean Sea, South Paldean Sea, West Paldean Sea<br>Tera Raid Battles: 3 Star Raid Battles'),
(211, NULL, 5, 'East Paldean Sea, North Paldean Sea, South Paldean Sea, West Paldean Sea<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Hisuian Qwilfish
(211, 3, 1, NULL),
(211, 3, 2, NULL),
(211, 3, 3, 'Obsidian Fieldlands: Ramanas Island or nearby<br>Cobalt Coastlands: Tranquility Cove, Lunker''s Lair, Islespy Shore or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(211, 3, 4, 'Polar Biome'),
(211, 3, 5, 'Polar Biome'),
-- Scizor
(212, NULL, 1, 'Challenge Road, Training Lowlands<br>Max Raid Battles: Fields of Honor, Forest of Focus, Training Lowlands, Workout Sea'),
(212, NULL, 2, 'Challenge Road, Training Lowlands<br>Max Raid Battles: Fields of Honor, Forest of Focus, Training Lowlands, Workout Sea'),
(212, NULL, 3, 'Alabaster Icelands: Space-time Distortion in Alabaster Icelands or nearby'),
(212, NULL, 4, 'Canyon Biome, Savanna Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(212, NULL, 5, 'Canyon Biome, Savanna Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Shuckle
(213, NULL, 1, 'Dusty Bowl, Galar Mine No. 2, Giant''s Cap, Stony Wilderness, Watchtower Ruins, Ballimere Lake<br>Max Raid Battles: Rolling Fields, Stony Wilderness, Fields of Honor, Forest of Focus, Training Lowlands, Potbottom Desert, Workout Sea, Slippery Slope, Giant''s Bed, Snowslide Slope, Ballimere Lake'),
(213, NULL, 2, 'Dusty Bowl, Galar Mine No. 2, Giant''s Cap, Stony Wilderness, Watchtower Ruins, Ballimere Lake<br>Max Raid Battles: Rolling Fields, Stony Wilderness, Fields of Honor, Forest of Focus, Training Lowlands, Potbottom Desert, Workout Sea, Slippery Slope, Giant''s Bed, Snowslide Slope, Ballimere Lake'),
(213, NULL, 3, NULL),
(213, NULL, 4, NULL),
(213, NULL, 5, NULL),
-- Heracross
(214, NULL, 1, 'Trade from Pokémon Shield'),
(214, NULL, 2, 'Forest of Focus, Challenge Road, Training Lowlands<br>Max Raid Battles: Fields of Honor, Forest of Focus, Training Lowlands, Workout Sea'),
(214, NULL, 3, 'Obsidian Fieldlands: Grueling Grove or nearby<br>Coronet Highlands: Wayward Wood or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(214, NULL, 4, 'North Province Area Two, Socarrat Trail, Fellhorn Gorge, Kitakami Hall, Mossfell Confluence, Oni Mountain, Reveler''s Road<br>Fixed: North Province Area Two, Kitakami Wilds, Reveler''s Road<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
(214, NULL, 5, 'North Province Area Two, Socarrat Trail, Fellhorn Gorge, Kitakami Hall, Mossfell Confluence, Oni Mountain, Reveler''s Road<br>Fixed: North Province Area Two, Kitakami Wilds, Reveler''s Road<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
-- Sneasel
(215, NULL, 1, 'Route 8, Route 10, Bridge Field, Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Slippery Slope, Frostpoint Field, Snowslide Slope, Frigid Sea<br>Max Raid Battles: Bridge Field, Giant''s Cap, Hammerlocke Hills, Stony Wilderness, West Lake Axewell, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea<br>Dynamax Adventures'),
(215, NULL, 2, 'Route 8, Route 10, Bridge Field, Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Slippery Slope, Frostpoint Field, Snowslide Slope, Frigid Sea<br>Max Raid Battles: Bridge Field, Giant''s Cap, Hammerlocke Hills, Stony Wilderness, West Lake Axewell, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea<br>Dynamax Adventures'),
(215, NULL, 3, 'Obsidian Fieldlands: Space-time Distortion in Obsidian Fieldlands or nearby'),
(215, NULL, 4, 'Dalizapa Passage, Glaseado Mountain, Chilling Waterhead, Oni Mountain, Timeless Woods<br>Fixed: Dalizapa Passage, Glaseado Mountain, Chilling Waterhead<br>Tera Raid Battles: 3 Star Raid Battles'),
(215, NULL, 5, 'Dalizapa Passage, Glaseado Mountain, Chilling Waterhead, Oni Mountain, Timeless Woods<br>Fixed: Dalizapa Passage, Glaseado Mountain, Chilling Waterhead<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Hisuian Sneasel
(215, 3, 1, NULL),
(215, 3, 2, NULL),
(215, 3, 3, 'Coronet Highlands: Celestica Trail, Primeval Grotto or nearby<br>Alabaster Icelands: Avalugg''s Legacy, Glacier Terrace or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(215, 3, 4, 'Transfer from Pokémon HOME'),
(215, 3, 5, 'Transfer from Pokémon HOME'),
-- Teddiursa
(216, NULL, 1, NULL),
(216, NULL, 2, NULL),
(216, NULL, 3, 'Crimson Mirelands: Ursa''s Ring or nearby<br>Coronet Highlands: Sonorous Path or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(216, NULL, 4, 'East Province Area One, North Province Area Two<br>Tera Raid Battles: 2 Star Raid Battles'),
(216, NULL, 5, 'East Province Area One, North Province Area Two<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Ursaring
(217, NULL, 1, NULL),
(217, NULL, 2, NULL),
(217, NULL, 3, 'Crimson Mirelands: Ursa''s Ring or nearby<br>Coronet Highlands: Sonorous Path or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(217, NULL, 4, 'Dalizapa Passage, North Province Area One, North Province Area Two<br>Fixed: Dalizapa Passage, West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
(217, NULL, 5, 'Dalizapa Passage, North Province Area One, North Province Area Two<br>Fixed: Dalizapa Passage, West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Slugma
(218, NULL, 1, NULL),
(218, NULL, 2, NULL),
(218, NULL, 3, NULL),
(218, NULL, 4, 'Crystal Pool, Infernal Pass, Oni Mountain<br>Fixed: Infernal Pass<br>Tera Raid Battles: 2 Star Raid Battles'),
(218, NULL, 5, 'Crystal Pool, Infernal Pass, Oni Mountain<br>Fixed: Infernal Pass<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Magcargo
(219, NULL, 1, NULL),
(219, NULL, 2, NULL),
(219, NULL, 3, NULL),
(219, NULL, 4, 'Tera Raid Battles: 4 Star Raid Battles'),
(219, NULL, 5, 'Tera Raid Battles: 4 Star Raid Battles'),
-- Swinub
(220, NULL, 1, 'Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Rolling Fields, Slippery Slope<br>Max Raid Battles: Dusty Bowl, Stony Wilderness'),
(220, NULL, 2, 'Dusty Bowl, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Rolling Fields,  Slippery Slope<br>Max Raid Battles: Dusty Bowl, Stony Wilderness, Slippery Slope, Snowslide Slope, Frigid Sea'),
(220, NULL, 3, 'Alabaster Icelands: Bonechill Wastes, Avalugg''s Legacy, Avalanche Slopes or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(220, NULL, 4, 'Chilling Waterhead, Kitakami Hall, Mossfell Confluence, Oni Mountain, Oni''s Maw, Reveler''s Road<br>Tera Raid Battles: 2 Star Raid Battles'),
(220, NULL, 5, 'Chilling Waterhead, Kitakami Hall, Mossfell Confluence, Oni Mountain, Oni''s Maw, Reveler''s Road<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Piloswine
(221, NULL, 1, 'Dusty Bowl, East Lake Axewell, Lake of Outrage, Rolling Fields, Slippery Slope, Roaring-Sea Caves<br>Max Raid Battles: Dusty Bowl, Stony Wilderness, Slippery Slope, Snowslide Slope, Frigid Sea<br>Dynamax Adventures'),
(221, NULL, 2, 'Dusty Bowl, East Lake Axewell, Lake of Outrage, Rolling Fields, Slippery Slope, Roaring-Sea Caves<br>Max Raid Battles: Dusty Bowl, Stony Wilderness, Slippery Slope, Snowslide Slope, Frigid Sea<br>Dynamax Adventures'),
(221, NULL, 3, 'Alabaster Icelands: Bonechill Wastes, Avalugg''s Legacy, Avalanche Slopes or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(221, NULL, 4, 'Chilling Waterhead<br>Tera Raid Battles: 4 Star Raid Battles'),
(221, NULL, 5, 'Chilling Waterhead<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Corsola
(222, NULL, 1, 'Trade from Pokémon Shield'),
(222, NULL, 2, 'Trade from Regina in Isle of Armor Area'),
(222, NULL, 3, NULL),
(222, NULL, 4, NULL),
(222, NULL, 5, NULL),
-- Galarian Corsola
(222, 2, 1, 'Trade from Pokémon Shield'),
(222, 2, 2, 'Giant''s Mirror<br>Max Raid Battles: Giant''s Mirror, South Lake Miloch, Stony Wilderness, Watchtower Ruins, Slippery Slope, Old Cemetery, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(222, 2, 3, NULL),
(222, 2, 4, NULL),
(222, 2, 5, NULL),
-- Remoraid
(223, NULL, 1, 'Route 9, South Lake Miloch, West Lake Axewell, Fields of Honor, Workout Sea<br>Max Raid Battles: East Lake Axewell, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Insular Sea'),
(223, NULL, 2, 'Route 9, South Lake Miloch, West Lake Axewell, Fields of Honor, Workout Sea<br>Max Raid Battles: East Lake Axewell, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Insular Sea'),
(223, NULL, 3, 'Cobalt Coastlands: Castaway Shore, Sand''s Reach, Tranquility Cove or nearby'),
(223, NULL, 4, NULL),
(223, NULL, 5, NULL),
-- Octillery
(224, NULL, 1, 'Route 9, Axew''s Eye, South Lake Miloch, Fields of Honor, Challenge Beach, Loop Lagoon, Workout Sea<br>Max Raid Battles: East Lake Axewell, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Insular Sea<br>Dynamax Adventures'),
(224, NULL, 2, 'Route 9, Axew''s Eye, South Lake Miloch, Fields of Honor, Challenge Beach, Loop Lagoon, Workout Sea<br>Max Raid Battles: East Lake Axewell, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Insular Sea<br>Dynamax Adventures'),
(224, NULL, 3, 'Cobalt Coastlands: Castaway Shore, Islespy Shore or nearby'),
(224, NULL, 4, NULL),
(224, NULL, 5, NULL),
-- Delibird
(225, NULL, 1, 'Route 8, Axew''s Eye, Dappled Grove, Dusty Bowl, Giant''s Cap, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, North Lake Miloch, Rolling Fields, South Lake Miloch, Watchtower Ruins, West Lake Axewell, Snowslide Slope<br>Max Raid Battles: Dusty Bowl, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Stony Wilderness, Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Path to the Peak, Crown Shrine, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake, Dyna Tree Hill'),
(225, NULL, 2, 'Route 8, Axew''s Eye, Dappled Grove, Dusty Bowl, Giant''s Cap, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, North Lake Miloch, Rolling Fields, South Lake Miloch, Watchtower Ruins, West Lake Axewell, Snowslide Slope<br>Max Raid Battles: Dusty Bowl, East Lake Axewell, Giant''s Cap, Giant''s Seat, Hammerlocke Hills, Stony Wilderness, Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Path to the Peak, Crown Shrine, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake, Dyna Tree Hill'),
(225, NULL, 3, NULL),
(225, NULL, 4, 'Glaseado Mountain<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 5 Star Raid Battles'),
(225, NULL, 5, 'Glaseado Mountain<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Mantine
(226, NULL, 1, 'Route 9, Lake of Outrage<br>Max Raid Battles: East Lake Axewell, Giant''s Mirror, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Insular Sea<br>Dynamax Adventures'),
(226, NULL, 2, 'Route 9, Lake of Outrage<br>Max Raid Battles: East Lake Axewell, Giant''s Mirror, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Insular Sea<br>Dynamax Adventures'),
(226, NULL, 3, 'Cobalt Coastlands: Tranquility Cove or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(226, NULL, 4, NULL),
(226, NULL, 5, NULL),
-- Skarmory
(227, NULL, 1, 'Challenge Road, Training Lowlands<br>Max Raid Battles: Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea<br>Dynamax Adventures'),
(227, NULL, 2, 'Challenge Road, Training Lowlands<br>Max Raid Battles: Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea<br>Dynamax Adventures'),
(227, NULL, 3, NULL),
(227, NULL, 4, 'Canyon Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(227, NULL, 5, 'Canyon Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Houndour
(228, NULL, 1, NULL),
(228, NULL, 2, NULL),
(228, NULL, 3, NULL),
(228, NULL, 4, 'Inlet Grotto, South Province Area Four, Chilling Waterhead, Crystal Pool, Fellhorn Gorge, Infernal Pass, Kitakami Wilds, Oni Mountain, Paradise Barrens, Wistful Fields<br>Fixed: Infernal Pass<br>Tera Raid Battles: 2 Star Raid Battles'),
(228, NULL, 5, 'Inlet Grotto, South Province Area Four, Chilling Waterhead, Crystal Pool, Fellhorn Gorge, Infernal Pass, Kitakami Wilds, Oni Mountain, Paradise Barrens, Wistful Fields<br>Fixed: Infernal Pass<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Houndoom
(229, NULL, 1, NULL),
(229, NULL, 2, NULL),
(229, NULL, 3, NULL),
(229, NULL, 4, 'North Province Area Two, Chilling Waterhead, Crystal Pool, Fellhorn Gorge, Infernal Pass, Kitakami Wilds, Oni Mountain<br>Fixed: South Province Area Four, South Province Area Six, Infernal Pass, Paradise Barrens<br>era Raid Battles: 5 Star Raid Battles'),
(229, NULL, 5, 'North Province Area Two, Chilling Waterhead, Crystal Pool, Fellhorn Gorge, Infernal Pass, Kitakami Wilds, Oni Mountain<br>Fixed: South Province Area Four, South Province Area Six, Infernal Pass, Paradise Barrens<br>era Raid Battles: 5 Star Raid Battles'),
-- Kingdra
(230, NULL, 1, 'Honeycalm Sea<br>Max Raid Battles: Loop Lagoon, Workout Sea, Honeycalm Sea'),
(230, NULL, 2, 'Honeycalm Sea<br>Max Raid Battles: Loop Lagoon, Workout Sea, Honeycalm Sea'),
(230, NULL, 3, NULL),
(230, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(230, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Phanpy
(231, NULL, 1, NULL),
(231, NULL, 2, NULL),
(231, NULL, 3, NULL),
(231, NULL, 4, 'Asado Desert, South Province Area Two, South Province Area Four, West Province Area One<br>Fixed: Asado Desert<br>Tera Raid Battles: 2 Star Raid Battles'),
(231, NULL, 5, 'Asado Desert, South Province Area Two, South Province Area Four, West Province Area One<br>Fixed: Asado Desert<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Donphan
(232, NULL, 1, NULL),
(232, NULL, 2, NULL),
(232, NULL, 3, NULL),
(232, NULL, 4, 'Asado Desert, South Province Area Six, West Province Area Two<br>Fixed: Asado Desert<br>Tera Raid Battles: 4 Star Raid Battles'),
(232, NULL, 5, 'Asado Desert, South Province Area Six, West Province Area Two<br>Fixed: Asado Desert<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Porygon2
(233, NULL, 1, 'Evolve Porygon'),
(233, NULL, 2, 'Evolve Porygon'),
(233, NULL, 3, 'Crimson Mirelands: Space-time Distortion in Crimson Mirelands or nearby'),
(233, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(233, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Stantler
(234, NULL, 1, NULL),
(234, NULL, 2, NULL),
(234, NULL, 3, 'Obsidian Fieldlands: Deertrack Heights or nearby<br>Coronet Highlands: Wayward Wood or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(234, NULL, 4, 'South Province Area One, South Province Area Three, South Province Area Five, Kitakami Hall, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Reveler''s Road, Timeless Woods<br>Fixed: South Province Area Five<br>Tera Raid Battles: 3 Star Raid Battles'),
(234, NULL, 5, 'South Province Area One, South Province Area Three, South Province Area Five, Kitakami Hall, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Reveler''s Road, Timeless Woods<br>Fixed: South Province Area Five<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Smeargle
(235, NULL, 1, NULL),
(235, NULL, 2, NULL),
(235, NULL, 3, NULL),
(235, NULL, 4, 'Canyon Biome, Coastal Biome, Polar Biome, Savanna Biome, Torchlit Labyrinth<br>Fixed: Savanna Biome'),
(235, NULL, 5, 'Canyon Biome, Coastal Biome, Polar Biome, Savanna Biome, Torchlit Labyrinth<br>Fixed: Savanna Biome'),
-- Tyrogue
(236, NULL, 1, 'Route 3, Dappled Grove, Giant''s Seat, Rolling Fields, South Lake Miloch, Stony Wilderness, West Lake Axewell<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(236, NULL, 2, 'Route 3, Dappled Grove, Giant''s Seat, Rolling Fields, South Lake Miloch, Stony Wilderness, West Lake Axewell<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(236, NULL, 3, NULL),
(236, NULL, 4, 'Canyon Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
(236, NULL, 5, 'Canyon Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Hitmontop
(237, NULL, 1, 'Lake of Outrage<br>Max Raid Battles: Rolling Fields, South Lake Miloch, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(237, NULL, 2, 'Lake of Outrage<br>Max Raid Battles: Rolling Fields, South Lake Miloch, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(237, NULL, 3, NULL),
(237, NULL, 4, 'Canyon Biome<br>Fixed: Costal Biome<br>Tera Raid Battles: 5 Star Raid Battles'),
(237, NULL, 5, 'Canyon Biome<br>Fixed: Costal Biome<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Smoochum
(238, NULL, 1, 'Slippery Slope, Frostpoint Field<br>Max Raid Battles: Slippery Slope, Snowslide Slope, Frigid Sea'),
(238, NULL, 2, 'Slippery Slope, Frostpoint Field<br>Max Raid Battles: Slippery Slope, Snowslide Slope, Frigid Sea'),
(238, NULL, 3, NULL),
(238, NULL, 4, NULL),
(238, NULL, 5, NULL),
-- Elekid
(239, NULL, 1, 'Giant''s Bed, Old Cemetery, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(239, NULL, 2, 'Giant''s Bed, Old Cemetery, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(239, NULL, 3, 'Coronet Highlands: Cloudcap Pass or nearby<br>Alabaster Icelands: Arena''s Approach, Icebound Falls or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(239, NULL, 4, 'Canyon Biome, Chargestone Cavern, Polar Biome, Savanna Biome<br>Fixed: Canyon Biome, Chargestone Cavern<br>Tera Raid Battles: 2 Star Raid Battles'),
(239, NULL, 5, 'Canyon Biome, Chargestone Cavern, Polar Biome, Savanna Biome<br>Fixed: Canyon Biome, Chargestone Cavern<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Magby
(240, NULL, 1, 'Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Giant''s Foot, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Ballimere Lake'),
(240, NULL, 2, 'Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Giant''s Foot, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Ballimere Lake'),
(240, NULL, 3, 'Cobalt Coastlands: Firespit Island or nearby<br>Cobalt Coastlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(240, NULL, 4, 'Coastal Biome, Savanna Biome, Torchlit Labyrinth<br>Tera Raid Battles: 2 Star Raid Battles'),
(240, NULL, 5, 'Coastal Biome, Savanna Biome, Torchlit Labyrinth<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Miltank
(241, NULL, 1, 'Training Lowlands<br>Max Raid Battles: Soothing Wetlands, Courageous Cavern, Training Lowlands<br>Dynamax Adventures'),
(241, NULL, 2, 'Training Lowlands<br>Max Raid Battles: Soothing Wetlands, Courageous Cavern, Training Lowlands<br>Dynamax Adventures'),
(241, NULL, 3, NULL),
(241, NULL, 4, NULL),
(241, NULL, 5, NULL),
-- Blissey
(242, NULL, 1, 'Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Brawlers'' Cave, Challenge Road, Courageous Cavern, Loop Lagoon, Training Lowlands, Warm-Up Tunnel, Potbottom Desert, Workout Sea, Stepping-Stone Sea, Honeycalm Island<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Brawlers'' Cave, Challenge Road, Courageous Cavern, Loop Lagoon, Training Lowlands, Potbottom Desert, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island'),
(242, NULL, 2, 'Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Brawlers'' Cave, Challenge Road, Courageous Cavern, Loop Lagoon, Training Lowlands, Warm-Up Tunnel, Potbottom Desert, Workout Sea, Stepping-Stone Sea, Honeycalm Island<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Brawlers'' Cave, Challenge Road, Courageous Cavern, Loop Lagoon, Training Lowlands, Potbottom Desert, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island'),
(242, NULL, 3, 'Obsidian Fieldlands: Obsidian Falls or nearby<br>Alabaster Icelands: Avalanche Slopes or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(242, NULL, 4, 'North Province Area One, North Province Area Two, North Province Area Three, Coastal Biome, Savanna Biome, Torchlit Labyrinth<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(242, NULL, 5, 'North Province Area One, North Province Area Two, North Province Area Three, Coastal Biome, Savanna Biome, Torchlit Labyrinth<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Raikou
(243, NULL, 1, 'Dynamax Adventures'),
(243, NULL, 2, 'Dynamax Adventures'),
(243, NULL, 3, NULL),
(243, NULL, 4, 'West Province Area One - Requires Snack from Snacksworth'),
(243, NULL, 5, 'West Province Area One - Requires Snack from Snacksworth'),
-- Entei
(244, NULL, 1, 'Dynamax Adventures'),
(244, NULL, 2, 'Dynamax Adventures'),
(244, NULL, 3, NULL),
(244, NULL, 4, 'East Province Area Three - Requires Snack from Snacksworth'),
(244, NULL, 5, 'East Province Area Three - Requires Snack from Snacksworth'),
-- Suicune
(245, NULL, 1, 'Dynamax Adventures'),
(245, NULL, 2, 'Dynamax Adventures'),
(245, NULL, 3, NULL),
(245, NULL, 4, 'Casseroya Lake - Requires Snack from Snacksworth'),
(245, NULL, 5, 'Casseroya Lake - Requires Snack from Snacksworth'),
-- Larvitar
(246, NULL, 1, 'Trade from Pokémon Shield'),
(246, NULL, 2, 'Lake of Outrage, Roaring-Sea Caves<br>Max Raid Battles: Giant''s Seat, Rolling Fields, Stony Wilderness'),
(246, NULL, 3, NULL),
(246, NULL, 4, 'Alfornada Cavern, Asado Desert, Dalizapa Passage, East Province Area Three, South Province Area Five, West Province Area One<br>Tera Raid Battles: 3 Star Raid Battles'),
(246, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Pupitar
(247, NULL, 1, 'Trade from Pokémon Shield'),
(247, NULL, 2, 'Lake of Outrage<br>Max Raid Battles: Giant''s Seat, Rolling Fields, Stony Wilderness'),
(247, NULL, 3, NULL),
(247, NULL, 4, 'Alfornada Cavern<br>Fixed: North Province Area Two<br>Tera Raid Battles: 4 Star Raid Battles'),
(247, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Tyranitar
(248, NULL, 1, 'Trade from Pokémon Shield'),
(248, NULL, 2, 'Dusty Bowl, Roaring-Sea Caves<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Giant''s Seat, Rolling Fields, Stony Wilderness, West Lake Axewell'),
(248, NULL, 3, NULL),
(248, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(248, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Lugia
(249, NULL, 1, 'Trade from Pokémon Shield'),
(249, NULL, 2, 'Dynamax Adventures'),
(249, NULL, 3, NULL),
(249, NULL, 4, 'North Province Area One - Requires Snack from Snacksworth'),
(249, NULL, 5, 'North Province Area One - Requires Snack from Snacksworth'),
-- Ho-Oh
(250, NULL, 1, 'Dynamax Adventures'),
(250, NULL, 2, 'Trade from Pokémon Sword'),
(250, NULL, 3, NULL),
(250, NULL, 4, 'South Province Area Four - Requires Snack from Snacksworth'),
(250, NULL, 5, 'South Province Area Four - Requires Snack from Snacksworth'),
-- Celebi
(251, NULL, 1, 'Transfer through Pokémon HOME or through events'),
(251, NULL, 2, 'Transfer through Pokémon HOME or through events'),
(251, NULL, 3, NULL),
(251, NULL, 4, NULL),
(251, NULL, 5, NULL);

COMMIT TRANSACTION;
