BEGIN TRANSACTION;

INSERT INTO Pokemon_Location (pokedex_number, region_id, game_id, location_name)
VALUES 

-- Turtwig
(387, NULL, 1, NULL),
(387, NULL, 2, NULL),
(387, NULL, 3, 'Crimson Mirelands: Droning Meadow or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(387, NULL, 4, 'Reveler''s Road (Egg Gift)<br>Canyon Biome'),
(387, NULL, 5, 'Reveler''s Road (Egg Gift)<br>Canyon Biome'),
-- Grotle
(388, NULL, 1, NULL),
(388, NULL, 2, NULL),
(388, NULL, 3, 'Crimson Mirelands: Droning Meadow or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(388, NULL, 4, 'Evolve Turtwig'),
(388, NULL, 5, 'Evolve Turtwig'),
-- Torterra
(389, NULL, 1, NULL),
(389, NULL, 2, NULL),
(389, NULL, 3, 'Crimson Mirelands: Holm of Trials or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(389, NULL, 4, 'Evolve Grotle'),
(389, NULL, 5, 'Evolve Grotle'),
-- Chimchar
(390, NULL, 1, NULL),
(390, NULL, 2, NULL),
(390, NULL, 3, 'Obsidian Fieldlands: Deertrack Heights, Ramanas Island or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(390, NULL, 4, 'Reveler''s Road (Egg Gift)<br>Polar Biome'),
(390, NULL, 5, 'Reveler''s Road (Egg Gift)<br>Polar Biome'),
-- Monferno
(391, NULL, 1, NULL),
(391, NULL, 2, NULL),
(391, NULL, 3, 'Obsidian Fieldlands: Ramanas Island or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(391, NULL, 4, 'Evolve Chimchar'),
(391, NULL, 5, 'Evolve Chimchar'),
-- Infernape
(392, NULL, 1, NULL),
(392, NULL, 2, NULL),
(392, NULL, 3, 'Obsidian Fieldlands: Ramanas Island or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(392, NULL, 4, 'Evolve Monferno'),
(392, NULL, 5, 'Evolve Monferno'),
-- Piplup
(393, NULL, 1, NULL),
(393, NULL, 2, NULL),
(393, NULL, 3, 'Cobalt Coastlands: Spring Path or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(393, NULL, 4, 'Reveler''s Road (Egg Gift)<br>Polar Biome'),
(393, NULL, 5, 'Reveler''s Road (Egg Gift)<br>Polar Biome'),
-- Prinplup
(394, NULL, 1, NULL),
(394, NULL, 2, NULL),
(394, NULL, 3, 'Cobalt Coastlands: Spring Path or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(394, NULL, 4, 'Evolve Piplup'),
(394, NULL, 5, 'Evolve Piplup'),
-- Empoleon
(395, NULL, 1, NULL),
(395, NULL, 2, NULL),
(395, NULL, 3, 'Cobalt Coastlands: Islespy Shore or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(395, NULL, 4, 'Evolve Prinplup'),
(395, NULL, 5, 'Evolve Prinplup'),
-- Starly
(396, NULL, 1, NULL),
(396, NULL, 2, NULL),
(396, NULL, 3, 'Obsidian Fieldlands: Aspiration Hill, Horseshoe Plains, Windswept Run, Tidewater Dam or nearby<br>Cobalt Coastlands: Ginkgo Landing, Deadwood Haunt or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Cobalt Coastlands: Massive Mass Outbreak'),
(396, NULL, 4, 'South Province Area One, South Province Area Two, South Province Area Four, Apple Hills, Fellhorn Gorge, Kitakami Hall, Kitakami Road, Kitakami Wilds, Loyalty Plaza, Mossfell Confluence, Oni Mountain, Reveler''s Road<br>Fixed: South Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
(396, NULL, 5, 'South Province Area One, South Province Area Two, South Province Area Four, Apple Hills, Fellhorn Gorge, Kitakami Hall, Kitakami Road, Kitakami Wilds, Loyalty Plaza, Mossfell Confluence, Oni Mountain, Reveler''s Road<br>Fixed: South Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Staravia
(397, NULL, 1, NULL),
(397, NULL, 2, NULL),
(397, NULL, 3, 'Obsidian Fieldlands: Nature''s Pantry, Tidewater Dam, Ramanas Island, Sandgem Flats or nearby<br>Cobalt Coastlands: Ginkgo Landing, Deadwood Haunt or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Cobalt Coastlands: Massive Mass Outbreak'),
(397, NULL, 4, 'South Province Area Four, West Province Area Two, West Province Area Three, Fellhorn Gorge, Kitakami Wilds, Mossfell Confluence, Oni Mountain<br>Fixed: South Province Area Two, West Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles'),
(397, NULL, 5, 'South Province Area Four, West Province Area Two, West Province Area Three, Fellhorn Gorge, Kitakami Wilds, Mossfell Confluence, Oni Mountain<br>Fixed: South Province Area Two, West Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Staraptor
(398, NULL, 1, NULL),
(398, NULL, 2, NULL),
(398, NULL, 3, 'Obsidian Fieldlands: Nature''s Pantry or nearby<br>Cobalt Coastlands: Deadwood Haunt or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Cobalt Coastlands: Massive Mass Outbreak'),
(398, NULL, 4, 'Casseroya Lake. Fellhorn Gorge, Kitakami Wilds<br>Fixed: Casseroya Lake, South Province Area Three, Fellhorn Gorge, Oni Mountain<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(398, NULL, 5, 'Casseroya Lake. Fellhorn Gorge, Kitakami Wilds<br>Fixed: Casseroya Lake, South Province Area Three, Fellhorn Gorge, Oni Mountain<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Bidoof
(399, NULL, 1, NULL),
(399, NULL, 2, NULL),
(399, NULL, 3, 'Obsidian Fieldlands: Aspiration Hill, Horseshoe Plains, Tidewater Dam or nearby<br>Crimson Mirelands: Gapejaw Bog, Ursa''s Ring, Droning Meadow or nearby<br>Alabaster Icelands: Avalugg''s Legacy or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(399, NULL, 4, NULL),
(399, NULL, 5, NULL),
-- Bibarel
(400, NULL, 1, NULL),
(400, NULL, 2, NULL),
(400, NULL, 3, 'Obsidian Fieldlands: Tidewater Dam or nearby<br>Crimson Mirelands: Gapejaw Bog, Ursa''s Ring, Droning Meadow or nearby<br>Cobalt Coastlands: Spring Path or nearby<br>Alabaster Icelands: Avalugg''s Legacy or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(400, NULL, 4, NULL),
(400, NULL, 5, NULL),
-- Kricketot
(401, NULL, 1, NULL),
(401, NULL, 2, NULL),
(401, NULL, 3, 'Obsidian Fieldlands: Deertrack Path, Nature''s Pantry, Windswept Run or nearby<br>Crimson Mirelands: Golden Lowlands, Cloudpool Ridge or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Crimson Mirelands: Massive Mass Outbreak'),
(401, NULL, 4, 'South Province Area Two, Kitakami Hall, Mossfell Confluence, Oni Mountain, Reveler''s Road<br>Tera Raid Battles: 1 Star Raid Battles'),
(401, NULL, 5, 'South Province Area Two, Kitakami Hall, Mossfell Confluence, Oni Mountain, Reveler''s Road<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Kricketune
(402, NULL, 1, NULL),
(402, NULL, 2, NULL),
(402, NULL, 3, 'Obsidian Fieldlands: Nature''s Pantry or nearby<br>Crimson Mirelands: Golden Lowlands, Cloudpool Ridge or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Crimson Mirelands: Massive Mass Outbreak'),
(402, NULL, 4, 'North Province Area Two, Kitakami Hall, Mossfell Confluence, Oni Mountain, Reveler''s Road<br>Tera Raid Battles: 3 Star Raid Battles'),
(402, NULL, 5, 'North Province Area Two, Kitakami Hall, Mossfell Confluence, Oni Mountain, Reveler''s Road<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Shinx
(403, NULL, 1, 'Challenge Beach, Challenge Road, Training Lowlands, Potbottom Desert<br>Max Raid Battles: Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea'),
(403, NULL, 2, 'Challenge Beach, Challenge Road, Training Lowlands, Potbottom Desert<br>Max Raid Battles: Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea'),
(403, NULL, 3, 'Obsidian Fieldlands: Aspiration Hill, Floaro Gardens, Oreburrow Tunnel or nearby<br>Coronet Highlands: Sonorous Path or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(403, NULL, 4, 'South Province Area Three, Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: South Province Area Five<br>Tera Raid Battles: 2 Star Raid Battles'),
(403, NULL, 5, 'South Province Area Three, Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: South Province Area Five<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Luxio
(404, NULL, 1, 'Fields of Honor, Soothing Wetlands, Loop Lagoon, Training Lowlands<br>Max Raid Battles: Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea'),
(404, NULL, 2, 'Fields of Honor, Soothing Wetlands, Loop Lagoon, Training Lowlands<br>Max Raid Battles: Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea'),
(404, NULL, 3, 'Obsidian Fieldlands: Floaro Gardens, Oreburrow Tunnel, Sandgem Flats or nearby<br>Coronet Highlands: Heavenward Lookout, Sonorous Path, Sacred Plaza, Cloudcap Pass or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(404, NULL, 4, 'South Province Area Three, South Province Area Five, Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: South Province Area Five, Oni Mountain<br>Tera Raid Battles: 3 Star Raid Battles'),
(404, NULL, 5, 'South Province Area Three, South Province Area Five, Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: South Province Area Five, Oni Mountain<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Luxray
(405, NULL, 1, 'Soothing Wetlands, Forest of Focus, Challenge Beach, Loop Lagoon, Training Lowlands<br>Max Raid Battles: Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea<br>Dynamax Adventures'),
(405, NULL, 2, 'Soothing Wetlands, Forest of Focus, Challenge Beach, Loop Lagoon, Training Lowlands<br>Max Raid Battles: Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea<br>Dynamax Adventures'),
(405, NULL, 3, 'Obsidian Fieldlands: Sandgem Flats or nearby<br>Coronet Highlands: Heavenward Lookout, Sonorous Path, Sacred Plaza, Cloudcap Pass or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(405, NULL, 4, 'North Province Area Two, Fellhorn Gorge, Kitakami Wilds, Timeless Woods<br>Fixed: South Province Area Five, Kitakami Wilds<br>Tera Raid Battles: 5 Star Raid Battles'),
(405, NULL, 5, 'North Province Area Two, Fellhorn Gorge, Kitakami Wilds, Timeless Woods<br>Fixed: South Province Area Five, Kitakami Wilds<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Budew
(406, NULL, 1, 'Route 4, Dappled Grove, East Lake Axewell, Giant''s Mirror, Rolling Fields, West Lake Axewell<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness'),
(406, NULL, 2, 'Route 4, Dappled Grove, East Lake Axewell, Giant''s Mirror, Rolling Fields, West Lake Axewell<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness'),
(406, NULL, 3, 'Crimson Mirelands: Golden Lowlands, Gapejaw Bog or nearby<br>Coronet Highlands: Fabled Spring or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(406, NULL, 4, NULL),
(406, NULL, 5, NULL),
-- Roserade
(407, NULL, 1, 'Hammerlocke Hills<br>Max Raid Battles: Dappled Grove, Forest of Focus, Training Lowlands'),
(407, NULL, 2, 'Hammerlocke Hills<br>Max Raid Battles: Dappled Grove, Forest of Focus, Training Lowlands'),
(407, NULL, 3, 'Crimson Mirelands: Cloudpool Ridge or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(407, NULL, 4, NULL),
(407, NULL, 5, NULL),
-- Cranidos
(408, NULL, 1, NULL),
(408, NULL, 2, NULL),
(408, NULL, 3, 'Coronet Highlands: Space-time Distortion in Coronet Highlands or nearby'),
(408, NULL, 4, 'Canyon Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(408, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Rampardos
(409, NULL, 1, NULL),
(409, NULL, 2, NULL),
(409, NULL, 3, 'Coronet Highlands: Space-time Distortion in Coronet Highlands or nearby'),
(409, NULL, 4, 'Tera Raid Battles: 4 Star Raid Battles'),
(409, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Shieldon
(410, NULL, 1, NULL),
(410, NULL, 2, NULL),
(410, NULL, 3, 'Coronet Highlands: Space-time Distortion in Coronet Highlands or nearby'),
(410, NULL, 4, 'Trade from Pokémon Violet'),
(410, NULL, 5, 'Canyon Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Bastiodon
(411, NULL, 1, NULL),
(411, NULL, 2, NULL),
(411, NULL, 3, 'Coronet Highlands: Space-time Distortion in Coronet Highlands or nearby'),
(411, NULL, 4, 'Trade from Pokémon Violet'),
(411, NULL, 5, 'Tera Raid Battles: 4 Star Raid Battles'),
-- Burmy
(412, NULL, 1, NULL),
(412, NULL, 2, NULL),
(412, NULL, 3, 'Obsidian Fieldlands: Deertrack Path, Deertrack Heights, Nature''s Pantry, Grueling Grove or nearby<br>Crimson Mirelands: Golden Lowlands, Gapejaw Bog, Cloudpool Ridge, Shrouded Ruins or nearby<br>Cobalt Coastlands: Ginkgo Landing, Crossing Slope, Veilstone Cape, Bathers'' Lagoon or nearby<br>Coronet Highlands: Heavenward Lookout, Celestica Trail, Celestica Ruins, Stonetooth Rows or nearby<br>Alabaster Icelands: Bonechill Wastes, Glacier Terrace, Lake Acuity, Avalanche Slopes or nearby'),
(412, NULL, 4, NULL),
(412, NULL, 5, NULL),
-- Wormadam
(413, NULL, 1, NULL),
(413, NULL, 2, NULL),
(413, NULL, 3, 'Obsidian Fieldlands: Grueling Grove, Sandgem Flats or nearby<br>Crimson Mirelands: Golden Lowlands, Gapejaw Bog or nearby<br>Cobalt Coastlands: Ginkgo Landing, Crossing Slope, Veilstone Cape, Bathers'' Lagoon or nearby<br>Coronet Highlands: Heavenward Lookout, Celestica Trail, Celestica Ruins, Stonetooth Rows or nearby<br>Alabaster Icelands: Bonechill Wastes, Glacier Terrace, Lake Acuity, Avalanche Slopes or nearby'),
(413, NULL, 4, NULL),
(413, NULL, 5, NULL),
-- Mothim
(414, NULL, 1, NULL),
(414, NULL, 2, NULL),
(414, NULL, 3, 'Obsidian Fieldlands: Grueling Grove or nearby<br>Cobalt Coastlands: Ginkgo Landing, Veilstone Cape, Aipom Hill, Spring Path or nearby<br>Coronet Highlands: Wayward Cave or nearby'),
(414, NULL, 4, NULL),
(414, NULL, 5, NULL),
-- Combee
(415, NULL, 1, 'Rolling Fields, Honeycalm Island<br>Max Raid Battles: Bridge Field, South Lake Miloch, Honeycalm Island'),
(415, NULL, 2, 'Rolling Fields, Honeycalm Island<br>Max Raid Battles: Bridge Field, South Lake Miloch, Honeycalm Island'),
(415, NULL, 3, 'Obsidian Fieldlands: Heartwood, Grueling Cove, Ramanas Island or nearby<br>Crimson Mirelands: Cloudpool Ridge, Lake Valor, Cottonsedge Prairie, Droning Meadow or nearby<br>Cobalt Coastlands: Aipom Hill or nearby'),
(415, NULL, 4, 'East Paldean Sea, South Province Area One, South Province Area Two, South Province Area Four, West Province Area One<br>Fixed: South Province Area Two, West Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
(415, NULL, 5, 'East Paldean Sea, South Province Area One, South Province Area Two, South Province Area Four, West Province Area One<br>Fixed: South Province Area Two, West Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Vespiquen
(416, NULL, 1, 'Rolling Fields<br>Max Raid Battles: Bridge Field, South Lake Miloch, Honeycalm Island<br>Dynamax Adventures'),
(416, NULL, 2, 'Rolling Fields<br>Max Raid Battles: Bridge Field, South Lake Miloch, Honeycalm Island<br>Dynamax Adventures'),
(416, NULL, 3, 'Crimson Mirelands: Lake Valor, Cottonsedge Prairie, Droning Meadow or nearby'),
(416, NULL, 4, 'East Paldean Sea, North Province Area One, North Province Area Two, North Province Area Three, South Province Area Six<br>Fixed: South Province Area Two, West Province Area One<br>Tera Raid Battles: 4 Star Raid Battles'),
(416, NULL, 5, 'East Paldean Sea, North Province Area One, North Province Area Two, North Province Area Three, South Province Area Six<br>Fixed: South Province Area Two, West Province Area One<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Pachirisu
(417, NULL, 1, NULL),
(417, NULL, 2, NULL),
(417, NULL, 3, 'Crimson Mirelands: Droning Meadow or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(417, NULL, 4, 'South Province Area One, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five, West Province Area Three, Kitakami Hall, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Reveler''s Road, Timeless Woods<br>Fixed: East Province Area Two<br>Tera Raid Battles: 3 Star Raid Battles'),
(417, NULL, 5, 'South Province Area One, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five, West Province Area Three, Kitakami Hall, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Reveler''s Road, Timeless Woods<br>Fixed: East Province Area Two<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Buizel
(418, NULL, 1, NULL),
(418, NULL, 2, NULL),
(418, NULL, 3, 'Obsidian Fieldlands: Horseshoe Plains, Windswept Run, Worn Bridge or nearby<br>Cobalt Coastlands: Aipom Hill, Bathers'' Lagoon or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(418, NULL, 4, 'East Paldean Sea, East Province Area Two, East Province Area Three, South Paldean Sea, South Province Area One, South Province Area Two, South Province Area Four, South Province Area Five, Tagtree Thicket, West Paldean Sea, West Province Area One, West Province Area Two<br>Fixed: West Province Area One<br>Tera Raid Battles: 2 Star Raid Battles'),
(418, NULL, 5, 'East Paldean Sea, East Province Area Two, East Province Area Three, South Paldean Sea, South Province Area One, South Province Area Two, South Province Area Four, South Province Area Five, Tagtree Thicket, West Paldean Sea, West Province Area One, West Province Area Two<br>Fixed: West Province Area One<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Floatzel
(419, NULL, 1, NULL),
(419, NULL, 2, NULL),
(419, NULL, 3, 'Obsidian Fieldlands: Worn Bridge or nearby<br>Cobalt Coastlands: Aipom Hill, Bathers'' Lagoon or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(419, NULL, 4, 'East Paldean Sea, Glaseado Mountain, North Paldean Sea, South Paldean Sea, West Paldean Sea, West Province Area Two, West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
(419, NULL, 5, 'East Paldean Sea, Glaseado Mountain, North Paldean Sea, South Paldean Sea, West Paldean Sea, West Province Area Two, West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Cherubi
(420, NULL, 1, 'Route 3, Axew''s Eye, Bridge Field, Giant''s Cap, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, Rolling Fields, Watchtower Ruins<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness, Loop Lagoon'),
(420, NULL, 2, 'Route 3, Axew''s Eye, Bridge Field, Giant''s Cap, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, Rolling Fields, Watchtower Ruins<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness, Loop Lagoon'),
(420, NULL, 3, 'Obsidian Fieldlands: Heartwood or nearby<br>Crimson Mirelands: Gapejaw Bog or nearby<br>Coronet Highlands: Lonely Spring, Fabled Spring, Primeval Grotto or nearby'),
(420, NULL, 4, NULL),
(420, NULL, 5, NULL),
-- Cherrim
(421, NULL, 1, 'Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness<br>Dynamax Adventures'),
(421, NULL, 2, 'Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness<br>Dynamax Adventures'),
(421, NULL, 3, 'Obsidian Fieldlands: Heartwood or nearby<br>Crimson Mirelands: Gapejaw Bog or nearby<br>Coronet Highlands: Lonely Spring, Fabled Spring, Primeval Grotto or nearby'),
(421, NULL, 4, NULL),
(421, NULL, 5, NULL),
-- Shellos
(422, NULL, 1, 'Bridge Field, Galar Mine No. 2, Giant''s Cap, Giant''s Mirror, Motostoke Riverbank, Stony Wilderness<br>Max Raid Battles: Bridge Field, Giant''s Mirror, Lake of Outrage, South Lake Miloch, West Lake Axewell'),
(422, NULL, 2, 'Bridge Field, Galar Mine No. 2, Giant''s Cap, Giant''s Mirror, Motostoke Riverbank, Stony Wilderness<br>Max Raid Battles: Bridge Field, Giant''s Mirror, Lake of Outrage, South Lake Miloch, West Lake Axewell'),
(422, NULL, 3, 'Obsidian Fieldlands: Sandgem Flats, Ramanas Island or nearby<br>Cobalt Coastlands: Tranquility Cove, Seagrass Haven or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Cobalt Coastlands: Massive Mass Outbreak'),
(422, NULL, 4, 'West Province Area Two, East Province Area One, South Province Area Five<br>Tera Raid Battles: 2 Star Raid Battles'),
(422, NULL, 5, 'West Province Area Two, East Province Area One, South Province Area Five<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Gastrodon
(423, NULL, 1, 'Route 9, Dusty Bowl, Galar Mine No. 2, Giant''s Mirror<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Cap, Giant''s Mirror, Lake of Outrage, Rolling Fields, South Lake Miloch, West Lake Axewell<br>Dynamax Adventures'),
(423, NULL, 2, 'Route 9, Dusty Bowl, Galar Mine No. 2, Giant''s Mirror<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Cap, Giant''s Mirror, Lake of Outrage, Rolling Fields, South Lake Miloch, West Lake Axewell<br>Dynamax Adventures'),
(423, NULL, 3, 'Obsidian Fieldlands: Sandgem Flats, Ramanas Island or nearby<br>Cobalt Coastlands: Seagrass Haven or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Cobalt Coastlands: Massive Mass Outbreak'),
(423, NULL, 4, 'Casseroya Lake, North Province Area One<br>Fixed: North Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
(423, NULL, 5, 'Casseroya Lake, North Province Area One<br>Fixed: North Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Ambipom
(424, NULL, 1, NULL),
(424, NULL, 2, NULL),
(424, NULL, 3, 'Cobalt Coastlands: Aipom Hill, Hideaway Bay or nearby<br>Alabaster Icelands: Avalanche Slopes, Arena''s Approach, Heart''s Crag or nearby<br>Cobalt Coastlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(424, NULL, 4, 'Trade from Pokémon Violet'),
(424, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Drifloon
(425, NULL, 1, 'Route 5, North Lake Miloch, South Lake Miloch, Watchtower Ruins, Fields of Honor, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: Giant''s Cap, Hammerlocke Hills, Stony Wilderness, Watchtower Ruins, Challenge Beach, Courageous Cavern, Stepping-Stone Sea'),
(425, NULL, 2, 'Route 5, North Lake Miloch, South Lake Miloch, Watchtower Ruins, Fields of Honor, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: Giant''s Cap, Hammerlocke Hills, Stony Wilderness, Watchtower Ruins, Challenge Beach, Courageous Cavern, Stepping-Stone Sea'),
(425, NULL, 3, 'Obsidian Fieldlands: Aspiration Hill, Horseshoe Plains, Floaro Gardens, Ramanas Island or nearby<br>Cobalt Coastlands: Ginkgo Landing, Bathers'' Lagoon, Deadwood Haunt, Tranquility Cove or nearby<br>Alabaster Icelands: Avalugg''s Legacy, Glacier Terrace, Heart''s Crag or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(425, NULL, 4, 'Dalizapa Passage, East Province Area Two, Glaseado Mountain, South Province Area One, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five, South Province Area Six, Tagtree Thicket, West Province Area One<br>Tera Raid Battles: 2 Star Raid Battles'),
(425, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Drifblim
(426, NULL, 1, 'Axew''s Eye, South Lake Miloch, Watchtower Ruins, Challenge Beach, Challenge Road, Training Lowlands<br>Max Raid Battles: Giant''s Cap, Hammerlocke Hills, Stony Wilderness, Watchtower Ruins, Challenge Beach, Courageous Cavern, Stepping-Stone Sea<br>Dynamax Adventures'),
(426, NULL, 2, 'Axew''s Eye, South Lake Miloch, Watchtower Ruins, Challenge Beach, Challenge Road, Training Lowlands<br>Max Raid Battles: Giant''s Cap, Hammerlocke Hills, Stony Wilderness, Watchtower Ruins, Challenge Beach, Courageous Cavern, Stepping-Stone Sea<br>Dynamax Adventures'),
(426, NULL, 3, 'Obsidian Fieldlands: Sandgem Flats, Ramanas Island or nearby<br>Cobalt Coastlands: Ginkgo Landing, Bathers'' Lagoon, Deadwood Haunt, Tranquility Cove or nearby<br>Alabaster Icelands: Avalugg''s Legacy, Glacier Terrace, Heart''s Crag or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(426, NULL, 4, 'Alfornada Cavern, Cortondo, Dalizapa Passage, Glaseado Mountain, North Province Area One<br>Tera Raid Battles: 4 Star Raid Battles , 5 Star Raid Battles'),
(426, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Buneary
(427, NULL, 1, 'Fields of Honor<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea'),
(427, NULL, 2, 'Fields of Honor<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea'),
(427, NULL, 3, 'Obsidian Fieldlands: Heartwood or nearby<br>Alabaster Icelands: Bonechill Wastes, Snowfall Hot Spring or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(427, NULL, 4, NULL),
(427, NULL, 5, NULL),
-- Lopunny
(428, NULL, 1, 'Fields of Honor, Soothing Wetlands, Challenge Beach<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea<br>Dynamax Adventures'),
(428, NULL, 2, 'Fields of Honor, Soothing Wetlands, Challenge Beach<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea<br>Dynamax Adventures'),
(428, NULL, 3, 'Obsidian Fieldlands: Heartwood or nearby<br>Alabaster Icelands: Bonechill Wastes, Snowfall Hot Spring or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(428, NULL, 4, NULL),
(428, NULL, 5, NULL),
-- Mismagius
(429, NULL, 1, NULL),
(429, NULL, 2, NULL),
(429, NULL, 3, 'Coronet Highlands: Stonetooth Rows or nearby<br>Coronet Highlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(429, NULL, 4, 'Trade from Pokémon Violet'),
(429, NULL, 5, 'Alfornada Cavern, Casseroya Lake, Glaseado Mountain, North Province Area One, North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Honchkrow
(430, NULL, 1, NULL),
(430, NULL, 2, NULL),
(430, NULL, 3, 'Crimson Mirelands: Cloudpool Ridge or nearby<br>Cobalt Coastlands: Bathers'' Lagoon or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(430, NULL, 4, 'Casseroya Lake, Dalizapa Passage, North Province Area One, North Province Area Two, North Province Area Three, Socarrat Trail, South Province Area Six<br>Fixed: North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles'),
(430, NULL, 5, 'Casseroya Lake, Dalizapa Passage, North Province Area One, North Province Area Two, North Province Area Three, Socarrat Trail, South Province Area Six<br>Fixed: North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Glameow
(431, NULL, 1, NULL),
(431, NULL, 2, NULL),
(431, NULL, 3, 'Cobalt Coastlands: Crossing Slope, Veilstone Cape or nearby<br>Alabaster Icelands: Glacier Terrace or nearby<br>Cobalt Coastlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(431, NULL, 4, NULL),
(431, NULL, 5, NULL),
-- Purugly
(432, NULL, 1, NULL),
(432, NULL, 2, NULL),
(432, NULL, 3, 'Cobalt Coastlands: Crossing Slope, Veilstone Cape or nearby<br>Alabaster Icelands: Glacier Terrace or nearby<br>Cobalt Coastlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(432, NULL, 4, NULL),
(432, NULL, 5, NULL),
-- Chingling
(433, NULL, 1, NULL),
(433, NULL, 2, NULL),
(433, NULL, 3, 'Coronet Highlands: Sacred Plaza or nearby<br>Alabaster Icelands: Lake Acuity or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(433, NULL, 4, 'Chilling Waterhead, Crystal Pool, Infernal Pass, Oni Mountain<br>Fixed: Infernal Pass<br>Tera Raid Battles: 1 Star Raid Battles, 3 Star Raid Battles'),
(433, NULL, 5, 'Chilling Waterhead, Crystal Pool, Infernal Pass, Oni Mountain<br>Fixed: Infernal Pass<br>Tera Raid Battles: 1 Star Raid Battles, 3 Star Raid Battles'),
-- Stunky
(434, NULL, 1, 'Route 3, Dappled Grove, Giant''s Cap, North Lake Miloch, South Lake Miloch<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Motostoke Riverbank, North Lake Miloch, Stony Wilderness, West Lake Axewell'),
(434, NULL, 2, 'Route 3, Dappled Grove, Giant''s Cap, North Lake Miloch, South Lake Miloch<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Motostoke Riverbank, North Lake Miloch, Stony Wilderness, West Lake Axewell'),
(434, NULL, 3, 'Crimson Mirelands: Scarlet Bog or nearby<br>Coronet Highlands: Ancient Quarry or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(434, NULL, 4, 'South Province Area Three, South Province Area Five, West Province Area Two<br>Tera Raid Battles: 2 Star Raid Battles'),
(434, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Skuntank
(435, NULL, 1, 'Dusty Bowl, Lake of Outrage, North Lake Miloch, South Lake Miloch<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Motostoke Riverbank, North Lake Miloch, Stony Wilderness, West Lake Axewell<br>Dynamax Adventures'),
(435, NULL, 2, 'Dusty Bowl, Lake of Outrage, North Lake Miloch, South Lake Miloch<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Motostoke Riverbank, North Lake Miloch, Stony Wilderness, West Lake Axewell<br>Dynamax Adventures'),
(435, NULL, 3, 'Crimson Mirelands: Scarlet Bog or nearby<br>Coronet Highlands: Ancient Quarry or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(435, NULL, 4, 'Casseroya Lake<br>Tera Raid Battles: 4 Star Raid Battles'),
(435, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Bronzor
(436, NULL, 1, 'Bridge Field, Giant''s Seat, South Lake Miloch, Giant''s Foot, Three-Point Pass<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake'),
(436, NULL, 2, 'Bridge Field, Giant''s Seat, South Lake Miloch, Giant''s Foot, Three-Point Pass<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake'),
(436, NULL, 3, 'Coronet Highlands: Ancient Quarry, Clamberclaw Cliffs, Stonetooth Rows, Celestica Ruins or nearby<br>Alabaster Icelands: Lake Acuity, Snowpoint Temple or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(436, NULL, 4, 'East Province Area Two, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five, West Province Area One, West Province Area Two, Chilling Waterhead, Crystal Pool, Fellhorn Gorge, Infernal Pass, Kitakami Wilds, Oni Mountain, Paradise Barrens, Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
(436, NULL, 5, 'East Province Area Two, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five, West Province Area One, West Province Area Two, Chilling Waterhead, Crystal Pool, Fellhorn Gorge, Infernal Pass, Kitakami Wilds, Oni Mountain, Paradise Barrens, Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Bronzong
(437, NULL, 1, 'Route 8, Axew''s Eye, Bridge Field, Dusty Bowl, Giant''s Seat, Lake of Outrage, Stony Wilderness, Giant''s Bed, Giant''s Foot, Three-Point Pass<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Hammerlocke Hills, Stony Wilderness, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake<br>Dynamax Adventures'),
(437, NULL, 2, 'Route 8, Axew''s Eye, Bridge Field, Dusty Bowl, Giant''s Seat, Lake of Outrage, Stony Wilderness, Giant''s Bed, Giant''s Foot, Three-Point Pass<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Hammerlocke Hills, Stony Wilderness, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake<br>Dynamax Adventures'),
(437, NULL, 3, 'Coronet Highlands: Ancient Quarry, Clamberclaw Cliffs, Stonetooth Rows, Celestica Ruins or nearby<br>Alabaster Icelands: Lake Acuity, Snowpoint Temple or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(437, NULL, 4, 'Casseroya Lake, Dalizapa Passage, Glaseado Mountain, North Province Area Two, South Province Area Six, Oni Mountain<br>Fixed: South Province Area Six<br>Tera Raid Battles: 5 Star Raid Battles'),
(437, NULL, 5, 'Casseroya Lake, Dalizapa Passage, Glaseado Mountain, North Province Area Two, South Province Area Six, Oni Mountain<br>Fixed: South Province Area Six<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Bonsly
(438, NULL, 1, 'Bridge Field, Stony Wilderness<br>Max Raid Battles: Giant''s Seat, Rolling Fields, Stony Wilderness, Fields of Honor, Training Lowlands, Potbottom Desert'),
(438, NULL, 2, 'Bridge Field, Stony Wilderness<br>Max Raid Battles: Giant''s Seat, Rolling Fields, Stony Wilderness, Fields of Honor, Training Lowlands, Potbottom Desert'),
(438, NULL, 3, 'Crimson Mirelands: Cloudpool Ridge or nearby<br>Coronet Highlands: Celestica Ruins or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(438, NULL, 4, 'South Province Area One, South Province Area Two, Apple Hills, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
(438, NULL, 5, 'South Province Area One, South Province Area Two, Apple Hills, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Mime Jr.
(439, NULL, 1, 'Rolling Fields, Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, Stony Wilderness, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake'),
(439, NULL, 2, 'Rolling Fields, Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, Stony Wilderness, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake'),
(439, NULL, 3, 'Obsidian Fieldlands: Horseshoe Plains, Sandgem Flats or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(439, NULL, 4, NULL),
(439, NULL, 5, NULL),
-- Happiny
(440, NULL, 1, 'Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Road, Loop Lagoon, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Island'),
(440, NULL, 2, 'Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Road, Loop Lagoon, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Island'),
(440, NULL, 3, 'Obsidian Fieldlands: Oreburrow Tunnel, Obsidian Falls or nearby<br>Cobalt Coastlands: Hideaway Bay or nearby<br>Alabaster Icelands: Avalanche Slopes or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(440, NULL, 4, 'Pokemon League, South Province Area One, South Province Area Two, South Province Area Three, South Province Area Five, West Province Area One, Coastal Biome, Savanna Biome, Torchlit Labyrinth<br>Fixed: South Province Area One'),
(440, NULL, 5, 'Pokemon League, South Province Area One, South Province Area Two, South Province Area Three, South Province Area Five, West Province Area One, Coastal Biome, Savanna Biome, Torchlit Labyrinth<br>Fixed: South Province Area One'),
-- Chatot
(441, NULL, 1, NULL),
(441, NULL, 2, NULL),
(441, NULL, 3, 'Cobalt Coastlands: Deadwood Haunt or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Cobalt Coastlands: Massive Mass Outbreak'),
(441, NULL, 4, NULL),
(441, NULL, 5, NULL),
-- Spiritomb
(442, NULL, 1, 'Ballimere Lake'),
(442, NULL, 2, 'Ballimere Lake'),
(442, NULL, 3, 'Crimson Mirelands: Shrouded Ruins or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(442, NULL, 4, 'Glaseado Mountain<br>Fixed: Casseroya Lake, Glaseado Mountain'),
(442, NULL, 5, 'Glaseado Mountain<br>Fixed: Casseroya Lake, Glaseado Mountain'),
-- Gible
(443, NULL, 1, 'Trade from Pokémon Shield'),
(443, NULL, 2, 'Tunnel to the Top<br>Max Raid Battles: Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(443, NULL, 3, 'Coronet Highlands: Wayward Cave, Clamberclaw Cliffs or nearby<br>Alabaster Icelands: Avalanche Slopes or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(443, NULL, 4, 'Alfornada Cavern, West Province Area One, West Province Area Two, Crystal Pool, Oni Mountain, Paradise Barrens, Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
(443, NULL, 5, 'Alfornada Cavern, West Province Area One, West Province Area Two, Crystal Pool, Oni Mountain, Paradise Barrens, Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Gabite
(444, NULL, 1, 'Trade from Pokémon Shield'),
(444, NULL, 2, 'Max Raid Battles: Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(444, NULL, 3, 'Coronet Highlands: Clamberclaw Cliffs or nearby<br>Alabaster Icelands: Avalanche Slopes or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(444, NULL, 4, 'Alfornada Cavern, Dalizapa Passage, Glaseado Mountain, North Province Area Two, Crystal Pool, Oni Mountain<br>Fixed: South Province Area Six, West Province Area Two<br>Tera Raid Battles: 4 Star Raid Battles'),
(444, NULL, 5, 'Alfornada Cavern, Dalizapa Passage, Glaseado Mountain, North Province Area Two, Crystal Pool, Oni Mountain<br>Fixed: South Province Area Six, West Province Area Two<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Garchomp
(445, NULL, 1, 'Trade from Pokémon Shield'),
(445, NULL, 2, 'Tunnel to the Top, Path to the Peak<br>Max Raid Battles: Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(445, NULL, 3, 'Alabaster Icelands: Avalanche Slopes or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(445, NULL, 4, 'Great Crater of Paldea<br>Fixed: Great Crater of Paldea, West Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(445, NULL, 5, 'Great Crater of Paldea<br>Fixed: Great Crater of Paldea, West Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Munchlax
(446, NULL, 1, 'Motostoke Riverbank, Ballimere Lake<br>Max Raid Battles: Bridge Field, Motostoke Riverbank, Stony Wilderness, Slippery Slope, Giant''s Bed, Giant''s Foot, Ballimere Lake<br>Dynamax Adventures'),
(446, NULL, 2, 'Motostoke Riverbank, Ballimere Lake<br>Max Raid Battles: Bridge Field, Motostoke Riverbank, Stony Wilderness, Slippery Slope, Giant''s Bed, Giant''s Foot, Ballimere Lake<br>Dynamax Adventures'),
(446, NULL, 3, 'Obsidian Fieldlands: Deertrack Heights or nearby<br>Alabaster Icelands: Snowfall Hot Spring or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(446, NULL, 4, 'Apple Hills, Kitakami Road, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: Kitakami Road, Wistful Fields<br>Tera Raid Battles: 2 Star Raid Battles, 3 Star Raid Battles'),
(446, NULL, 5, 'Apple Hills, Kitakami Road, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: Kitakami Road, Wistful Fields<br>Tera Raid Battles: 2 Star Raid Battles, 3 Star Raid Battles'),
-- Riolu
(447, NULL, 1, 'Giant''s Cap, Roaring-Sea Caves<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Hammerlocke Hills, North Lake Miloch, Rolling Fields, Stony Wilderness'),
(447, NULL, 2, 'Giant''s Cap, Roaring-Sea Caves<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Hammerlocke Hills, North Lake Miloch, Rolling Fields'),
(447, NULL, 3, 'Alabaster Icelands: Icebound Falls, Snowfall Hot Spring or nearby<br>Cobalt Coastlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(447, NULL, 4, 'South Province Area Two, South Province Area Fourm, Fellhorn Gorge, Kitakami Road, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Timeless Woods, Wistful Fields<br>Fixed: North Province Area One, South Province Area Four, Fellhorn Gorge<br>Tera Raid Battles: 3 Star Raid Battles'),
(447, NULL, 5, 'South Province Area Two, South Province Area Fourm, Fellhorn Gorge, Kitakami Road, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Timeless Woods, Wistful Fields<br>Fixed: North Province Area One, South Province Area Four, Fellhorn Gorge<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Lucario
(448, NULL, 1, 'North Lake Miloch, Roaring-Sea Caves<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Hammerlocke Hills, North Lake Miloch, Rolling Fields, Stony Wilderness, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea'),
(448, NULL, 2, 'North Lake Miloch, Roaring-Sea Caves<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Hammerlocke Hills, North Lake Miloch, Rolling Fields, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea'),
(448, NULL, 3, 'Alabaster Icelands: Icebound Falls, Snowfall Hot Spring or nearby<br>Cobalt Coastlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(448, NULL, 4, 'North Province Area One, North Province Area Two, Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Timeless Woods<br>Fixed: Dalizapa Passage'),
(448, NULL, 5, 'North Province Area One, North Province Area Two, Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Timeless Woods<br>Fixed: Dalizapa Passage'),
-- Hippopotas
(449, NULL, 1, 'Route 6, Dusty Bowl<br>Max Raid Battles: Dusty Bowl'),
(449, NULL, 2, 'Route 6, Dusty Bowl<br>Max Raid Battles: Dusty Bowl'),
(449, NULL, 3, 'Crimson Mirelands: Sludge Mound, Scarlet Bog or nearby<br>Coronet Highlands: Celestica Trail or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(449, NULL, 4, 'Asado Desert<br>Fixed: Asado Desert<br>Tera Raid Battles: 3 Star Raid Battles'),
(449, NULL, 5, 'Asado Desert<br>Fixed: Asado Desert<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Hippowdon
(450, NULL, 1, 'Route 8, Giant''s Mirror, Lake of Outrage<br>Max Raid Battles: Dusty Bowl'),
(450, NULL, 2, 'Route 8, Giant''s Mirror, Lake of Outrage<br>Max Raid Battles: Dusty Bowl'),
(450, NULL, 3, 'Crimson Mirelands: Sludge Mound, Scarlet Bog or nearby<br>Coronet Highlands: Celestica Trail or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(450, NULL, 4, 'Fixed: Asado Desert<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(450, NULL, 5, 'Fixed: Asado Desert<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Skorupi
(451, NULL, 1, 'Route 6, Giant''s Mirror, Motostoke Riverbank, Soothing Wetlands, Challenge Beach<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, North Lake Miloch, Soothing Wetlands, Forest of Focus, Training Lowlands, Stepping-Stone Sea'),
(451, NULL, 2, 'Route 6, Giant''s Mirror, Motostoke Riverbank, Soothing Wetlands, Challenge Beach<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, North Lake Miloch, Soothing Wetlands, Forest of Focus, Training Lowlands, Stepping-Stone Sea'),
(451, NULL, 3, 'Cobalt Coastlands: Ginkgo Landing, Castaway Shore or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Cobalt Coastlands: Massive Mass Outbreak'),
(451, NULL, 4, NULL),
(451, NULL, 5, NULL),
-- Drapion
(452, NULL, 1, 'Route 8, Bridge Field, Lake of Outrage, Motostoke Riverbank, Soothing Wetlands, Challenge Beach, Training Lowlands<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Motostoke Riverbank, North Lake Miloch, Soothing Wetlands, Forest of Focus, Challenge Road, Training Lowlands, Workout Sea, Stepping-Stone Sea, Honeycalm Sea<br>Dynamax Adventures'),
(452, NULL, 2, 'Route 8, Bridge Field, Lake of Outrage, Motostoke Riverbank, Soothing Wetlands, Challenge Beach, Training Lowlands<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Motostoke Riverbank, North Lake Miloch, Soothing Wetlands, Forest of Focus, Challenge Road, Training Lowlands, Workout Sea, Stepping-Stone Sea, Honeycalm Sea<br>Dynamax Adventures'),
(452, NULL, 3, 'Cobalt Coastlands: Ginkgo Landing, Castaway Shore or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Cobalt Coastlands: Massive Mass Outbreak'),
(452, NULL, 4, NULL),
(452, NULL, 5, NULL),
-- Croagunk
(453, NULL, 1, 'Trade Pokémon from Shield'),
(453, NULL, 2, 'Bridge Field, Dusty Bowl, Galar Mine No. 2, Giant''s Cap, Motostoke Outskirts, Stony Wilderness, Soothing Wetlands, Forest of Focus<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness, Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea'),
(453, NULL, 3, 'Crimson Mirelands: Gapejaw Bog, Scarlet Bog, Holm of Trials or nearby<br>Coronet Highlands: Ancient Quarry or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(453, NULL, 4, 'South Province Area Five, West Province Area Two<br>Tera Raid Battles: 2 Star Raid Battles'),
(453, NULL, 5, 'South Province Area Five, West Province Area Two<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Toxicroak
(454, NULL, 1, 'Trade Pokémon from Shield'),
(454, NULL, 2, 'Stony Wilderness, Challenge Road, Training Lowlands<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness, Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea'),
(454, NULL, 3, 'Crimson Mirelands: Holm of Trials or nearby<br>Cobalt Coastlands: Spring Path or nearby<br>Coronet Highlands: Ancient Quarry or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(454, NULL, 4, 'Casseroya Lake<br>Tera Raid Battles: 4 Star Raid Battles'),
(454, NULL, 5, 'Casseroya Lake<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Carnivine
(455, NULL, 1, NULL),
(455, NULL, 2, NULL),
(455, NULL, 3, 'Crimson Mirelands: Golden Lowlands, Gapejaw Bog, Cloudpool Ridge, Holm of Trials or nearby<br>Coronet Highlands: Lonely Spring or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(455, NULL, 4, NULL),
(455, NULL, 5, NULL),
-- Finneon
(456, NULL, 1, NULL),
(456, NULL, 2, NULL),
(456, NULL, 3, 'Cobalt Coastlands: Seagrass Haven or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(456, NULL, 4, 'West Paldean Sea, Coastal Biome, Polar Biome<br>Fixed: Coastal Biome<br>Tera Raid Battles: 1 Star Raid Battles, 2 Star Raid Battles'),
(456, NULL, 5, 'West Paldean Sea, Coastal Biome, Polar Biome<br>Fixed: Coastal Biome<br>Tera Raid Battles: 1 Star Raid Battles, 2 Star Raid Battles'),
-- Lumineon
(457, NULL, 1, NULL),
(457, NULL, 2, NULL),
(457, NULL, 3, 'Cobalt Coastlands: Seagrass Haven or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(457, NULL, 4, 'North Paldean Sea, West Paldean Sea, Coastal Biome, Polar Biome<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(457, NULL, 5, 'North Paldean Sea, West Paldean Sea, Coastal Biome, Polar Biome<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Mantyke
(458, NULL, 1, 'Route 9, Lake of Outrage, Motostoke Riverbank, Fields of Honor, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: East Lake Axewell, Giant''s Mirror, North Lake Miloch, South Lake Miloch, West Lake Axewell'),
(458, NULL, 2, 'Route 9, Lake of Outrage, Motostoke Riverbank, Fields of Honor, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: East Lake Axewell, Giant''s Mirror, North Lake Miloch, South Lake Miloch, West Lake Axewell'),
(458, NULL, 3, 'Cobalt Coastlands: Ginkgo Landing, Tranquility Cove or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(458, NULL, 4, NULL),
(458, NULL, 5, NULL),
-- Snover
(459, NULL, 1, 'Route 8, Route 10, Axew''s Eye, Dappled Grove, Dusty Bowl, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Giant''s Seat, North Lake Miloch, South Lake Miloch, Watchtower Ruins, Frostpoint Field<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills'),
(459, NULL, 2, 'Route 8, Route 10, Axew''s Eye, Dappled Grove, Dusty Bowl, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Giant''s Seat, North Lake Miloch, South Lake Miloch, Watchtower Ruins, Frostpoint Field<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills'),
(459, NULL, 3, 'Alabaster Icelands: Avalugg''s Legacy, Glacier Terrace or nearby<br>Coronet Highlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(459, NULL, 4, 'Glaseado Mountain, Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(459, NULL, 5, 'Glaseado Mountain, Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Abomasnow
(460, NULL, 1, 'Route 10, Axew''s Eye, Dusty Bowl, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Lake of Outrage, Slippery Slope, Frostpoint Field<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Fields of Honor, Soothing Wetlands, Training Lowlands, Insular Sea, Slippery Slope, Snowslide Slope, Frigid Sea<br>Dynamax Adventures'),
(460, NULL, 2, 'Route 10, Axew''s Eye, Dusty Bowl, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Lake of Outrage, Slippery Slope, Frostpoint Field<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Fields of Honor, Soothing Wetlands, Training Lowlands, Insular Sea, Slippery Slope, Snowslide Slope, Frigid Sea<br>Dynamax Adventures'),
(460, NULL, 3, 'Alabaster Icelands: Avalugg''s Legacy, Glacier Terrace or nearby<br>Coronet Highlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(460, NULL, 4, 'Glaseado Mountain, Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 5 Star Raid Battles'),
(460, NULL, 5, 'Glaseado Mountain, Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Weavile
(461, NULL, 1, 'Bridge Field, Slippery Slope, Frostpoint Field, Snowslide Slope<br>Max Raid Battles: Bridge Field, Stony Wilderness, West Lake Axewell, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea'),
(461, NULL, 2, 'Bridge Field, Slippery Slope, Frostpoint Field, Snowslide Slope<br>Max Raid Battles: Bridge Field, Stony Wilderness, West Lake Axewell, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea'),
(461, NULL, 3, 'Obsidian Fieldlands: Space-time Distortion in Obsidian Fieldlands or nearby'),
(461, NULL, 4, 'Glaseado Mountain<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 5 Star Raid Battles'),
(461, NULL, 5, 'Glaseado Mountain<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Magnezone
(462, NULL, 1, 'Challenge Beach, Loop Lagoon, Insular Sea<br>Max Raid Battles: Fields of Honor, Forest of Focus, Challenge Beach, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea, Honeycalm Sea'),
(462, NULL, 2, 'Challenge Beach, Loop Lagoon, Insular Sea<br>Max Raid Battles: Fields of Honor, Forest of Focus, Challenge Beach, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea, Honeycalm Sea'),
(462, NULL, 3, 'Coronet Highlands: Celestica Trail, Fabled Spring , Clamberclaw Cliffs or nearby'),
(462, NULL, 4, 'East Province Area Two<br>Fixed: Great Crater of Paldea, Canyon Biome<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(462, NULL, 5, 'East Province Area Two<br>Fixed: Great Crater of Paldea, Canyon Biome<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Lickilicky
(463, NULL, 1, 'Soothing Wetlands<br>Max Raid Battles: Soothing Wetlands, Courageous Cavern, Training Lowlands'),
(463, NULL, 2, 'Soothing Wetlands<br>Max Raid Battles: Soothing Wetlands, Courageous Cavern, Training Lowlands'),
(463, NULL, 3, 'Crimson Mirelands: Shrouded Ruins or nearby<br>Alabaster Icelands: Avalanche Slopes or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(463, NULL, 4, NULL),
(463, NULL, 5, NULL),
-- Rhyperior
(464, NULL, 1, 'Potbottom Desert<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Seat, Rolling Fields, Fields of Honor, Training Lowlands, Potbottom Desert'),
(464, NULL, 2, 'Potbottom Desert<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Seat, Rolling Fields, Fields of Honor, Training Lowlands, Potbottom Desert'),
(464, NULL, 3, 'Coronet Highlands: Sacred Plaza or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(464, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(464, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Tangrowth
(465, NULL, 1, 'Forest of Focus<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Training Lowlands, Insular Sea'),
(465, NULL, 2, 'Forest of Focus<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Training Lowlands, Insular Sea'),
(465, NULL, 3, 'Crimson Mirelands: Gapejaw Bog or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(465, NULL, 4, NULL),
(465, NULL, 5, NULL),
-- Electivire
(466, NULL, 1, 'Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(466, NULL, 2, 'Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(466, NULL, 3, 'Coronet Highlands: Cloudcap Pass or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(466, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(466, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Magmortar
(467, NULL, 1, 'Slippery Slope, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Ballimere Lake'),
(467, NULL, 2, 'Slippery Slope, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Ballimere Lake'),
(467, NULL, 3, 'Coronet Highlands: Space-time Distortion in Coronet Highlands or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(467, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(467, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Togekiss
(468, NULL, 1, 'Dusty Bowl<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Rolling Fields'),
(468, NULL, 2, 'Dusty Bowl<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Rolling Fields'),
(468, NULL, 3, 'Obsidian Fieldlands: Lake Verity or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(468, NULL, 4, NULL),
(468, NULL, 5, NULL),
-- Yanmega
(469, NULL, 1, NULL),
(469, NULL, 2, NULL),
(469, NULL, 3, 'Crimson Mirelands: Droning Meadow or nearby<br>Coronet Highlands: Heavenward Lookout or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(469, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(469, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Leafeon
(470, NULL, 1, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Giant''s Mirror, Ballimere Lake'),
(470, NULL, 2, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Giant''s Mirror, Ballimere Lake'),
(470, NULL, 3, 'Obsidian Fieldlands: Space-time Distortion in Obsidian Fieldlands or nearby'),
(470, NULL, 4, 'Socarrat Trail, West Province Area Three<br>Fixed: South Province Area Four<br>Tera Raid Battles: 6 Star Raid Battles'),
(470, NULL, 5, 'Socarrat Trail, West Province Area Three<br>Fixed: South Province Area Four<br>Tera Raid Battles: 6 Star Raid Battles'),
-- Glaceon
(471, NULL, 1, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Hammerlocke Hills, Ballimere Lake'),
(471, NULL, 2, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Hammerlocke Hills, Ballimere Lake'),
(471, NULL, 3, 'Alabaster Icelands: Space-time Distortion in Alabaster Icelands or nearby'),
(471, NULL, 4, 'Glaseado Mountain<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 6 Star Raid Battles'),
(471, NULL, 5, 'Glaseado Mountain<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 6 Star Raid Battles'),
-- Gliscor
(472, NULL, 1, NULL),
(472, NULL, 2, NULL),
(472, NULL, 3, 'Coronet Highlands: Primeval Grotto or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(472, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(472, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Mamoswine
(473, NULL, 1, 'Slippery Slope<br>Max Raid Battles: Stony Wilderness, Slippery Slope, Snowslide Slope, Frigid Sea'),
(473, NULL, 2, 'Slippery Slope<br>Max Raid Battles: Stony Wilderness, Slippery Slope, Snowslide Slope, Frigid Sea'),
(473, NULL, 3, 'Alabaster Icelands: Avalugg''s Legacy or nearby<br>Alabaster Icelands: Massive Mass Outbreak'),
(473, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(473, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Porygon-Z
(474, NULL, 1, 'Evolve Porygon2'),
(474, NULL, 2, 'Evolve Porygon2'),
(474, NULL, 3, 'Crimson Mirelands: Space-time Distortion in Crimson Mirelands or nearby'),
(474, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(474, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Gallade
(475, NULL, 1, 'Bridge Field, Challenge Road<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Rolling Fields, Stony Wilderness'),
(475, NULL, 2, 'Bridge Field, Challenge Road<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Rolling Fields'),
(475, NULL, 3, 'Alabaster Icelands: Snowpoint Temple or nearby<br>Alabaster Icelands: Massive Mass Outbreak'),
(475, NULL, 4, 'Alfornada Cavern, Dalizapa Passage, Glaseado Mountain, North Province Area One, Fellhorn Gorge, Kitakami Wilds, Timeless Woods<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(475, NULL, 5, 'Alfornada Cavern, Dalizapa Passage, Glaseado Mountain, North Province Area One, Fellhorn Gorge, Kitakami Wilds, Timeless Woods<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Probopass
(476, NULL, 1, NULL),
(476, NULL, 2, NULL),
(476, NULL, 3, 'Coronet Highlands: Primeval Grotto or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(476, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles'),
(476, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles'),
-- Dusknoir
(477, NULL, 1, 'Stony Wilderness<br>Max Raid Battles: Giant''s Mirror, South Lake Miloch, Stony Wilderness'),
(477, NULL, 2, 'Stony Wilderness<br>Max Raid Battles: Giant''s Mirror, South Lake Miloch, Stony Wilderness'),
(477, NULL, 3, 'Cobalt Coastlands: Deadwood Haunt or nearby<br>Coronet Highlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(477, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(477, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Froslass
(478, NULL, 1, 'Slippery Slope, Giant''s Bed, Old Cemetery, Snowslide Slope, Tunnel to the Top<br>Max Raid Battles: Slippery Slope, Old Cemetery, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(478, NULL, 2, 'Slippery Slope, Giant''s Bed, Old Cemetery, Snowslide Slope, Tunnel to the Top<br>Max Raid Battles: Slippery Slope, Old Cemetery, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(478, NULL, 3, 'Alabaster Icelands: Bonechill Wastes, Avalugg''s Legacy, Avalanche Slopes or nearby<br>Alabaster Icelands: Massive Mass Outbreak'),
(478, NULL, 4, 'Glaseado Mountain<br>Fixed: Dalizapa Passage, Glaseado Mountain<br>Tera Raid Battles: 5 Star Raid Battles'),
(478, NULL, 5, 'Glaseado Mountain<br>Fixed: Dalizapa Passage, Glaseado Mountain<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Rotom
(479, NULL, 1, 'Lake of Outrage, Workout Sea<br>Max Raid Battles: Hammerlocke Hills<br>Dynamax Adventures'),
(479, NULL, 2, 'Lake of Outrage, Workout Sea<br>Max Raid Battles: Hammerlocke Hills<br>Dynamax Adventures'),
(479, NULL, 3, 'Coronet Highlands: Stonetooth Rows, Sacred Plaza or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(479, NULL, 4, 'East Province Area Two, West Province Area Two, Canyon Biome, Chargestone Cavern, Coastal Biome, Polar Biome, Savanna Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles , 5 Star Raid Battles'),
(479, NULL, 5, 'East Province Area Two, West Province Area Two, Canyon Biome, Chargestone Cavern, Coastal Biome, Polar Biome, Savanna Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles , 5 Star Raid Battles'),
-- Uxie
(480, NULL, 1, 'Dynamax Adventures'),
(480, NULL, 2, 'Dynamax Adventures'),
(480, NULL, 3, 'Alabaster Icelands: Lake Acuity'),
(480, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(480, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Mesprit
(481, NULL, 1, 'Dynamax Adventures'),
(481, NULL, 2, 'Dynamax Adventures'),
(481, NULL, 3, 'Obsidian Fieldlands: Lake Verity'),
(481, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(481, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Azelf
(482, NULL, 1, 'Dynamax Adventures'),
(482, NULL, 2, 'Dynamax Adventures'),
(482, NULL, 3, 'Crimson Mirelands: Lake Valor'),
(482, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(482, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Dialga
(483, NULL, 1, 'Dynamax Adventures'),
(483, NULL, 2, 'Trade from Pokémon Sword'),
(483, NULL, 3, 'Coronet Highlands: Temple of Sinnoh'),
(483, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(483, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Palkia
(484, NULL, 1, 'Trade from Pokémon Shield'),
(484, NULL, 2, 'Dynamax Adventures'),
(484, NULL, 3, 'Coronet Highlands: Temple of Sinnoh'),
(484, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(484, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Heatran
(485, NULL, 1, 'Dynamax Adventures'),
(485, NULL, 2, 'Dynamax Adventures'),
(485, NULL, 3, 'Cobalt Coastlands: Lava Dome Sanctum'),
(485, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(485, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Regigigas
(486, NULL, 1, 'Giant''s Bed'),
(486, NULL, 2, 'Giant''s Bed'),
(486, NULL, 3, 'Alabaster Icelands: Snowpoint Temple'),
(486, NULL, 4, NULL),
(486, NULL, 5, NULL),
-- Giratina
(487, NULL, 1, 'Dynamax Adventures'),
(487, NULL, 2, 'Dynamax Adventures'),
(487, NULL, 3, 'Cobalt Coastlands: Turnback Cave'),
(487, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(487, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Cresselia
(488, NULL, 1, 'Dynamax Adventures'),
(488, NULL, 2, 'Dynamax Adventures'),
(488, NULL, 3, 'Coronet Highlands: Moonview Arena'),
(488, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(488, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Phione
(489, NULL, 1, NULL),
(489, NULL, 2, NULL),
(489, NULL, 3, 'Cobalt Coastlands: Seaside Hollow'),
(489, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(489, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Manaphy
(490, NULL, 1, NULL),
(490, NULL, 2, NULL),
(490, NULL, 3, 'Cobalt Coastlands: Seaside Hollow'),
(490, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(490, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Darkrai
(491, NULL, 1, NULL),
(491, NULL, 2, NULL),
(491, NULL, 3, 'Coronet Highlands: Clamberclaw Cliffs'),
(491, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(491, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Shaymin
(492, NULL, 1, NULL),
(492, NULL, 2, NULL),
(492, NULL, 3, 'Obsidian Fieldlands: Floaro Gardens'),
(492, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(492, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Arceus
(493, NULL, 1, NULL),
(493, NULL, 2, NULL),
(493, NULL, 3, 'Coronet Highlands: Temple of Sinnoh'),
(493, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(493, NULL, 5, 'Transfer from Pokémon HOME or obtain from event');

COMMIT TRANSACTION;