BEGIN TRANSACTION;

INSERT INTO Pokemon_Location (pokedex_number, region_id, game_id, location_name)
VALUES

-- Bulbasaur
(1, NULL, 1, 'Gift in Master Dojo'),
(1, NULL, 2, 'Gift in Master Dojo'),
(1, NULL, 3, NULL),
(1, NULL, 4, 'Coastal Biome, Torchlit Labyrinth'),
(1, NULL, 5, 'Coastal Biome, Torchlit Labyrinth'),
-- Ivysaur
(2, NULL, 1, 'Dynamax Adventures'),
(2, NULL, 2, 'Dynamax Adventures'),
(2, NULL, 3, NULL),
(2, NULL, 4, 'Evolve Bulbasaur'),
(2, NULL, 5, 'Evolve Bulbasaur'),
-- Venusaur
(3, NULL, 1, 'Max Raid Battles: Forest of Focus, Training Lowlands<br>Gigantamax Raid Battles: Forest of Focus, Training Lowlands'),
(3, NULL, 2, 'Max Raid Battles: Forest of Focus, Training Lowlands<br>Gigantamax Raid Battles: Forest of Focus, Training Lowlands'),
(3, NULL, 3, NULL),
(3, NULL, 4, 'Evolve Ivysaur'),
(3, NULL, 5, 'Evolve Ivysaur'),
-- Charmander
(4, NULL, 1, 'Gift from Leon in Postwick<br>Max Raid Battles: Hammerlocke Hills, Lake of Outrage'),
(4, NULL, 2, 'Gift from Leon in Postwick<br>Max Raid Battles: Hammerlocke Hills, Lake of Outrage'),
(4, NULL, 3, NULL),
(4, NULL, 4, 'Savanna Biome'),
(4, NULL, 5, 'Savanna Biome'),
-- Charmeleon
(5, NULL, 1, 'Max Raid Battles: Hammerlocke Hills, Lake of Outrage<br>Dynamax Adventures'),
(5, NULL, 2, 'Max Raid Battles: Hammerlocke Hills, Lake of Outrage<br>Dynamax Adventures'),
(5, NULL, 3, NULL),
(5, NULL, 4, 'Evolve Charmander'),
(5, NULL, 5, 'Evolve Charmander'),
-- Charizard
(6, NULL, 1, 'Max Raid Battles: Hammerlocke Hills, Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert<br>Gigantamax Raid Battles: Lake of Outrage'),
(6, NULL, 2, 'Max Raid Battles: Hammerlocke Hills, Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert<br>Gigantamax Raid Battles: Lake of Outrage'),
(6, NULL, 3, NULL),
(6, NULL, 4, 'Evolve Charmeleon'),
(6, NULL, 5, 'Evolve Charmeleon'),
-- Squirtle
(7, NULL, 1, 'Gift in Master Dojo'),
(7, NULL, 2, 'Gift in Master Dojo'),
(7, NULL, 3, NULL),
(7, NULL, 4, 'Canyon Biome'),
(7, NULL, 5, 'Canyon Biome'),
-- Wartortle
(8, NULL, 1, 'Dynamax Adventures'),
(8, NULL, 2, 'Dynamax Adventures'),
(8, NULL, 3, NULL),
(8, NULL, 4, 'Evolve Squirtle'),
(8, NULL, 5, 'Evolve Squirtle'),
-- Blastoise
(9, NULL, 1, 'Max Raid Battles: Workout Sea, Stepping-Stone Sea<br>Gigantamax Raid Battles: Workout Sea, Stepping-Stone Sea'),
(9, NULL, 2, 'Max Raid Battles: Workout Sea, Stepping-Stone Sea<br>Gigantamax Raid Battles: Workout Sea, Stepping-Stone Sea'),
(9, NULL, 3, NULL),
(9, NULL, 4, 'Evolve Wartortle'),
(9, NULL, 5, 'Evolve Wartortle'),
-- Caterpie
(10, NULL, 1, 'Route 1<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch'),
(10, NULL, 2, 'Route 1<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch'),
(10, NULL, 3, NULL),
(10, NULL, 4, NULL),
(10, NULL, 5, NULL),
-- Metapod
(11, NULL, 1, 'Rolling Fields<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch'),
(11, NULL, 2, 'Rolling Fields<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch'),
(11, NULL, 3, NULL),
(11, NULL, 4, NULL),
(11, NULL, 5, NULL),
-- Butterfree
(12, NULL, 1, 'East Lake Axewell, Giant''s Mirror, Rolling Fields, Slumbering Weald<br>Dynamax Adventures<br>Max Raid Battles: Bridge Field, Dappled Grove, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Rolling Fields, South Lake Miloch, Slippery Slope, Giant''s Bed, Crown Shrine, Giant''s Foot, Ballimere Lake<br>Gigantamax Raid Battles: Rolling Fields, Slippery Slope, Giant''s Bed, Crown Shrine, Giant''s Foot, Ballimere Lake'),
(12, NULL, 2, 'East Lake Axewell, Giant''s Mirror, Rolling Fields, Slumbering Weald<br>Dynamax Adventures<br>Max Raid Battles: Bridge Field, Dappled Grove, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Rolling Fields, South Lake Miloch, Slippery Slope, Giant''s Bed, Crown Shrine, Giant''s Foot, Ballimere Lake<br>Gigantamax Raid Battles: Rolling Fields, Slippery Slope, Giant''s Bed, Crown Shrine, Giant''s Foot, Ballimere Lake'),
(12, NULL, 3, NULL),
(12, NULL, 4, NULL),
(12, NULL, 5, NULL),
-- Weedle
(13, NULL, 1, NULL),
(13, NULL, 2, NULL),
(13, NULL, 3, NULL),
(13, NULL, 4, NULL),
(13, NULL, 5, NULL),
-- Kakuna
(14, NULL, 1, NULL),
(14, NULL, 2, NULL),
(14, NULL, 3, NULL),
(14, NULL, 4, NULL),
(14, NULL, 5, NULL),
-- Beedrill
(15, NULL, 1, NULL),
(15, NULL, 2, NULL),
(15, NULL, 3, NULL),
(15, NULL, 4, NULL),
(15, NULL, 5, NULL),
-- Pidgey
(16, NULL, 1, NULL),
(16, NULL, 2, NULL),
(16, NULL, 3, NULL),
(16, NULL, 4, NULL),
(16, NULL, 5, NULL),
-- Pidgeotto
(17, NULL, 1, NULL),
(17, NULL, 2, NULL),
(17, NULL, 3, NULL),
(17, NULL, 4, NULL),
(17, NULL, 5, NULL),
-- Pidgeot
(18, NULL, 1, NULL),
(18, NULL, 2, NULL),
(18, NULL, 3, NULL),
(18, NULL, 4, NULL),
(18, NULL, 5, NULL),
-- Rattata
(19, NULL, 1, NULL),
(19, NULL, 2, NULL),
(19, NULL, 3, NULL),
(19, NULL, 4, NULL),
(19, NULL, 5, NULL),
-- Alolan Rattata
(19, 1, 1, NULL),
(19, 1, 2, NULL),
(19, 1, 3, NULL),
(19, 1, 4, NULL),
(19, 1, 5, NULL),
-- Raticate
(20, NULL, 1, NULL),
(20, NULL, 2, NULL),
(20, NULL, 3, NULL),
(20, NULL, 4, NULL),
(20, NULL, 5, NULL),
-- Alolan Raticate
(20, 1, 1, NULL),
(20, 1, 2, NULL),
(20, 1, 3, NULL),
(20, 1, 4, NULL),
(20, 1, 5, NULL),
-- Spearow
(21, NULL, 1, NULL),
(21, NULL, 2, NULL),
(21, NULL, 3, NULL),
(21, NULL, 4, NULL),
(21, NULL, 5, NULL),
-- Fearow
(22, NULL, 1, NULL),
(22, NULL, 2, NULL),
(22, NULL, 3, NULL),
(22, NULL, 4, NULL),
(22, NULL, 5, NULL),
-- Ekans
(23, NULL, 1, NULL),
(23, NULL, 2, NULL),
(23, NULL, 3, NULL),
(23, NULL, 4, 'Apple Hills, Crystal Pool, Fellhorn Gorge, Kitakami Road, Loyalty Plaza, Mossfell Confluence, Oni Mountain, Reveler''s Road, Wistful Fields<br>Fixed: Mossfell Confluence, Reveler''s Road<br>Tera Raid Battles: 1 Star Raid Battles, 3 Star Raid Battles'),
(23, NULL, 5, 'Apple Hills, Crystal Pool, Fellhorn Gorge, Kitakami Road, Loyalty Plaza, Mossfell Confluence, Oni Mountain, Reveler''s Road, Wistful Fields<br>Fixed: Mossfell Confluence, Reveler''s Road<br>Tera Raid Battles: 1 Star Raid Battles, 3 Star Raid Battles'),
-- Arbok
(24, NULL, 1, NULL),
(24, NULL, 2, NULL),
(24, NULL, 3, NULL),
(24, NULL, 4, 'Fellhorn Gorge, Mossfell Confluence<br>Fixed: Mossfell Confluence'),
(24, NULL, 5, 'Fellhorn Gorge, Mossfell Confluence<br>Fixed: Mossfell Confluence'),
-- Pikachu
(25, NULL, 1, 'Route 4, Rolling Fields, Stony Wilderness, Fields of Honor, Soothing Wetlands, Forest of Focus<br>Max Raid Battles: Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea'),
(25, NULL, 2, 'Route 4, Rolling Fields, Stony Wilderness, Fields of Honor, Soothing Wetlands, Forest of Focus<br>Max Raid Battles: Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea'),
(25, NULL, 3, 'Obsidian Fieldlands: Nature''s Pantry or nearby<br>Crimson Mirelands: Golden Lowlands or nearby<br>Cobalt Coastlands: Windbreak Stand or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(25, NULL, 4, 'East Province Area One, South Province Area Two, South Province Area Four, West Province Area Three, Apple Hills, Kitakami Road, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: South Province Area Two, Apple Hills<br>Tera Raid Battles: 2 Star Raid Battles , 3 Star Raid Battles'),
(25, NULL, 5, 'East Province Area One, South Province Area Two, South Province Area Four, West Province Area Three, Apple Hills, Kitakami Road, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: South Province Area Two, Apple Hills<br>Tera Raid Battles: 2 Star Raid Battles , 3 Star Raid Battles'),
-- Raichu
(26, NULL, 1, 'Soothing Wetlands, Forest of Focus, Challenge Beach<br>Dynamax Adventures<br>Max Raid Battles: Giant''s Cap, Motostoke Riverbank, Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea'),
(26, NULL, 2, 'Soothing Wetlands, Forest of Focus, Challenge Beach<br>Dynamax Adventures<br>Max Raid Battles: Giant''s Cap, Motostoke Riverbank, Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea'),
(26, NULL, 3, 'Crimson Mirelands: Golden Lowlands or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(26, NULL, 4, 'Area Zero, Socarrat Trail<br>Fixed: West Province Area Two<br>Tera Raid Battles: 4 Star Raid Battles , 5 Star Raid Battles'),
(26, NULL, 5, 'Area Zero, Socarrat Trail<br>Fixed: West Province Area Two<br>Tera Raid Battles: 4 Star Raid Battles , 5 Star Raid Battles'),
-- Alolan Raichu
(26, 1, 1, 'Gift from Diglett Master<br>Dynamax Adventures'),
(26, 1, 2, 'Gift from Diglett Master<br>Dynamax Adventures'),
(26, 1, 3, NULL),
(26, 1, 4, 'Transfer from Pokémon HOME'),
(26, 1, 5, 'Transfer from Pokémon HOME'),
-- Sandshrew
(27, NULL, 1, 'Warm-Up Tunnel<br>Max Raid Battles: Challenge Beach, Courageous Cavern, Potbottom Desert, Stepping-Stone Sea'),
(27, NULL, 2, 'Warm-Up Tunnel<br>Max Raid Battles: Challenge Beach, Courageous Cavern, Potbottom Desert, Stepping-Stone Sea'),
(27, NULL, 3, NULL),
(27, NULL, 4, 'Kitakami Wilds, Oni Mountain, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Fixed: Reveler''s Road<br>Tera Raid Battles: 1 Star Raid Battles, 3 Star Raid Battles'),
(27, NULL, 5, 'Kitakami Wilds, Oni Mountain, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Fixed: Reveler''s Road<br>Tera Raid Battles: 1 Star Raid Battles, 3 Star Raid Battles'),
-- Alolan Sandshrew
(27, 1, 1, 'Gift from Diglett Master'),
(27, 1, 2, 'Gift from Diglett Master'),
(27, 1, 3, NULL),
(27, 1, 4, 'Trade from Pokémon Violet'),
(27, 1, 5, 'Polar Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Sandslash
(28, NULL, 1, 'Forest of Focus, Potbottom Desert<br>Max Raid Battles: Challenge Beach, Courageous Cavern, Potbottom Desert, Stepping-Stone Sea<br>Dynamax Adventures'),
(28, NULL, 2, 'Forest of Focus, Potbottom Desert<br>Max Raid Battles: Challenge Beach, Courageous Cavern, Potbottom Desert, Stepping-Stone Sea<br>Dynamax Adventures'),
(28, NULL, 3, NULL),
(28, NULL, 4, 'Kitakami Wilds, Oni Mountain, Paradise Barrens<br>Fixed: Paradise Barrens, Reveler''s Road<br>Tera Raid Battles: 6 Star Raid Battles'),
(28, NULL, 5, 'Kitakami Wilds, Oni Mountain, Paradise Barrens<br>Fixed: Paradise Barrens, Reveler''s Road<br>Tera Raid Battles: 6 Star Raid Battles'),
-- Alolan Sandslash
(28, 1, 1, 'Dynamax Adventures'),
(28, 1, 2, 'Dynamax Adventures'),
(28, 1, 3, NULL),
(28, 1, 4, 'Trade from Pokémon Violet'),
(28, 1, 5, 'Tera Raid Battles: 6 Star Raid Battles'),
-- Nidoran♀
(29, NULL, 1, 'Frostpoint Field, Giant''s Bed, Old Cemetery<br>Max Raid Battles: Giant''s Bed, Frigid Sea, Ballimere Lake'),
(29, NULL, 2, 'Frostpoint Field, Giant''s Bed, Old Cemetery<br>Max Raid Battles: Giant''s Bed, Frigid Sea, Ballimere Lake'),
(29, NULL, 3, NULL),
(29, NULL, 4, NULL),
(29, NULL, 5, NULL),
-- Nidorina
(30, NULL, 1, 'Giant''s Bed<br>Max Raid Battles: Giant''s Bed, Frigid Sea, Ballimere Lake'),
(30, NULL, 2, 'Giant''s Bed<br>Max Raid Battles: Giant''s Bed, Frigid Sea, Ballimere Lake'),
(30, NULL, 3, NULL),
(30, NULL, 4, NULL),
(30, NULL, 5, NULL),
-- Nidoqueen
(31, NULL, 1, 'Giant''s Bed<br>Dynamax Adventures<br>Max Raid Battles: Giant''s Bed, Frigid Sea, Ballimere Lake'),
(31, NULL, 2, 'Giant''s Bed<br>Dynamax Adventures<br>Max Raid Battles: Giant''s Bed, Frigid Sea, Ballimere Lake'),
(31, NULL, 3, NULL),
(31, NULL, 4, NULL),
(31, NULL, 5, NULL),
-- Nidoran♂
(32, NULL, 1, 'Frostpoint Field, Giant''s Bed, Old Cemetery<br>Max Raid Battles: Giant''s Bed, Frigid Sea, Ballimere Lake'),
(32, NULL, 2, 'Frostpoint Field, Giant''s Bed, Old Cemetery<br>Max Raid Battles: Giant''s Bed, Frigid Sea, Ballimere Lake'),
(32, NULL, 3, NULL),
(32, NULL, 4, NULL),
(32, NULL, 5, NULL),
-- Nidorino
(33, NULL, 1, 'Giant''s Bed<br>Max Raid Battles: Giant''s Bed, Frigid Sea, Ballimere Lake'),
(33, NULL, 2, 'Giant''s Bed<br>Max Raid Battles: Giant''s Bed, Frigid Sea, Ballimere Lake'),
(33, NULL, 3, NULL),
(33, NULL, 4, NULL),
(33, NULL, 5, NULL),
-- Nidoking
(34, NULL, 1, 'Giant''s Bed<br>Dynamax Adventures<br>Max Raid Battles: Giant''s Bed, Frigid Sea, Ballimere Lake'),
(34, NULL, 2, 'Giant''s Bed<br>Dynamax Adventures<br>Max Raid Battles: Giant''s Bed, Frigid Sea, Ballimere Lake'),
(34, NULL, 3, NULL),
(34, NULL, 4, NULL),
(34, NULL, 5, NULL),
-- Clefairy
(35, NULL, 1, 'Giant''s Cap, Motostoke Riverbank, Giant''s Bed, Snowslide Slope, Tunnel to the Top<br>Dynamax Adventures<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Rolling Fields, Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(35, NULL, 2, 'Giant''s Cap, Motostoke Riverbank, Giant''s Bed, Snowslide Slope, Tunnel to the Top<br>Dynamax Adventures<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Rolling Fields, Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(35, NULL, 3, 'Coronet Highlands: Fabled Spring or nearby<br>Cobalt Coastlands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(35, NULL, 4, 'Crystal Pool, Infernal Pass, Kitakami Hall, Oni Mountain, Reveler''s Road<br>Fixed: Oni Mountain<br>Tera Raid Battles: 3 Star Raid Battles'),
(35, NULL, 5, 'Crystal Pool, Infernal Pass, Kitakami Hall, Oni Mountain, Reveler''s Road<br>Fixed: Oni Mountain<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Clefable
(36, NULL, 1, 'Motostoke Riverbank, Giant''s Bed, Snowslide Slope, Tunnel to the Top<br>Dynamax Adventures<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Rolling Fields, Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(36, NULL, 2, 'Motostoke Riverbank, Giant''s Bed, Snowslide Slope, Tunnel to the Top<br>Dynamax Adventures<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Rolling Fields, Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(36, NULL, 3, 'Coronet Highlands: Fabled Spring or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(36, NULL, 4, 'Tera Raid Battles: 4 Star Raid Battles, 6 Star Raid Battles'),
(36, NULL, 5, 'Tera Raid Battles: 4 Star Raid Battles, 6 Star Raid Battles'),
-- Vulpix
(37, NULL, 1, 'Route 3, Axew''s Eye, Dappled Grove, East Lake Axewell, Giant''s Seat, Motostoke, North Lake Miloch, Rolling Fields, South Lake Miloch, Watchtower Ruins, West Lake Axewell<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness'),
(37, NULL, 2, 'Dusty Bowl, Hammerlocke Hills, Motostoke'),
(37, NULL, 3, 'Cobalt Coastlands: Veilstone Cape or nearby<br>Cobalt Coastlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(37, NULL, 4, 'Chilling Waterhead, Crystal Pool, Fellhorn Gorge, Infernal Pass, Kitakami Hall, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Timeless Woods, Wistful Fields<br>Fixed: Reveler''s Road<br>Tera Raid Battles: 2 Star Raid Battles'),
(37, NULL, 5, 'Chilling Waterhead, Crystal Pool, Fellhorn Gorge, Infernal Pass, Kitakami Hall, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Timeless Woods, Wistful Fields<br>Fixed: Reveler''s Road<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Alolan Vulpix
(37, 1, 1, 'Isle of Armor'),
(37, 1, 2, 'Isle of Armor'),
(37, 1, 3, 'Complete Snow White Vulpix in the Snow request'),
(37, 1, 4, 'Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(37, 1, 5, 'Trade from Pokémon Scarlet'),
-- Ninetales
(38, NULL, 1, 'Lake of Outrage<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert, Giant''s Bed, Snowslide Slope, Ballimere Lake'),
(38, NULL, 2, 'Max Raid Battles: Giant''s Cap'),
(38, NULL, 3, 'Cobalt Coastlands: Firespit Island or nearby<br>Cobalt Coastlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(38, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(38, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Alolan Ninetales
(38, 1, 1, 'Evolve Alolan Vulpix'),
(38, 1, 2, 'Evolve Alolan Vulpix'),
(38, 1, 3, 'Evolve Alolan Vulpix'),
(38, 1, 4, 'Tera Raid Battles: 6 Star Raid Battles'),
(38, 1, 5, 'Trade from Pokémon Scarlet'),
-- Jigglypuff
(39, NULL, 1, 'Fields of Honor<br>Dynamax Adventures<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Stepping-Stone Sea, Insular Sea'),
(39, NULL, 2, 'Fields of Honor, Forest of Focus<br>Dynamax Adventures<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Stepping-Stone Sea, Insular Sea'),
(39, NULL, 3, NULL),
(39, NULL, 4, 'South Province Area Two, West Province Area Three<br>Fixed: South Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
(39, NULL, 5, 'South Province Area Two, West Province Area Three<br>Fixed: South Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Wigglytuff
(40, NULL, 1, 'Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Loop Lagoon, Training Lowlands<br>Dynamax Adventures<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Stepping-Stone Sea, Insular Sea'),
(40, NULL, 2, 'Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Loop Lagoon, Training Lowlands<br>Dynamax Adventures<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Stepping-Stone Sea, Insular Sea'),
(40, NULL, 3, NULL),
(40, NULL, 4, 'North Province Area One<br>Tera Raid Battles: 4 Star Raid Battles'),
(40, NULL, 5, 'North Province Area One<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Zubat
(41, NULL, 1, 'Tunnel to the Top, Roaring-Sea Caves, Lakeside Cave<br>Max Raid Battles: Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(41, NULL, 2, 'Tunnel to the Top, Roaring-Sea Caves, Lakeside Cave<br>Max Raid Battles: Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(41, NULL, 3, 'Obsidian Fieldlands: Deertrack Path, Nature''s Pantry, Heartwood, Oreburrow Tunnel or nearby<br>Obsidian Fieldlands: Deertrack Path, Nature''s Pantry, Heartwood, Oreburrow Tunnel or nearby<br>Coronet Highlands: Heavenward Lookout, Wayward Cave or nearby<br>Alabaster Icelands: Snowpoint Temple or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(41, NULL, 4, NULL),
(41, NULL, 5, NULL),
-- Golbat
(42, NULL, 1, 'Tunnel to the Top, Roaring-Sea Caves<br>Max Raid Battles: Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(42, NULL, 2, 'Tunnel to the Top, Roaring-Sea Caves<br>Max Raid Battles: Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(42, NULL, 3, 'Obsidian Fieldlands: Oreburrow Tunnel or nearby<br>Crimson Mirelands: Bolderoll Slope, Diamond Heath, Cloudpool Ridge or nearby<br>Coronet Highlands: Heavenward Lookout, Wayward Cave or nearby<br>Alabaster Icelands: Snowpoint Temple or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(42, NULL, 4, NULL),
(42, NULL, 5, NULL),
-- Oddish
(43, NULL, 1, 'Dappled Grove, East Lake Axewell, Rolling Fields, Watchtower Ruins<br>Max Raid Battles: Dappled Grove, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, North Lake Miloch'),
(43, NULL, 2, 'Dappled Grove, East Lake Axewell, Rolling Fields, Watchtower Ruins<br>Max Raid Battles: Dappled Grove, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, North Lake Miloch'),
(43, NULL, 3, NULL),
(43, NULL, 4, 'Coastal Biome<br>Fixed: Costal Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
(43, NULL, 5, 'Coastal Biome<br>Fixed: Costal Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Gloom
(44, NULL, 1, 'Axew''s Eye, Giant''s Cap, Giant''s Mirror, North Lake Miloch<br>Max Raid Battles: Dappled Grove, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Dynamax Adventures'),
(44, NULL, 2, 'Axew''s Eye, Giant''s Cap, Giant''s Mirror, North Lake Miloch<br>Max Raid Battles: Dappled Grove, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Dynamax Adventures'),
(44, NULL, 3, NULL),
(44, NULL, 4, 'Coastal Biome<br>Fixed: Costal Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(44, NULL, 5, 'Coastal Biome<br>Fixed: Costal Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Vileplume
(45, NULL, 1, 'Dappled Grove, Giant''s Mirror, Hammerlocke Hills<br>Max Raid Battles: Dappled Grove, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, North Lake Miloch<br>Dynamax Adventures'),
(45, NULL, 2, 'Dappled Grove, Giant''s Mirror, Hammerlocke Hills<br>Max Raid Battles: Dappled Grove, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, North Lake Miloch<br>Dynamax Adventures'),
(45, NULL, 3, NULL),
(45, NULL, 4, 'Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(45, NULL, 5, 'Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Paras
(46, NULL, 1, NULL),
(46, NULL, 2, NULL),
(46, NULL, 3, 'Obsidian Fieldlands: Nature''s Pantry or nearby<br>Crimson Mirelands: Golden Lowlands, Diamond Heath, Cloudpool Ridge, Cottonsedge Prairie or nearby<br>Cobalt Coastlands: Windbreak Stand or nearby<br>Coronet Highlands: Heavenward Lookout, Wayward Wood or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Crimson Mirelands: Massive Mass Outbreak'),
(46, NULL, 4, NULL),
(46, NULL, 5, NULL),
-- Parasect
(47, NULL, 1, NULL),
(47, NULL, 2, NULL),
(47, NULL, 3, 'Obsidian Fieldlands: Nature''s Pantry or nearby<br>Crimson Mirelands: Golden Lowlands, Diamond Heath, Cloudpool Ridge, Cottonsedge Prairie or nearby<br>Cobalt Coastlands: Windbreak Stand or nearby<br>Coronet Highlands: Heavenward Lookout, Wayward Wood or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Crimson Mirelands: Massive Mass Outbreak'),
(47, NULL, 4, NULL),
(47, NULL, 5, NULL),
-- Venonat
(48, NULL, 1, NULL),
(48, NULL, 2, NULL),
(48, NULL, 3, NULL),
(48, NULL, 4, 'East Province Area One, Tagtree Thicket, Savanna Biome<br>Fixed: Costal Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
(48, NULL, 5, 'East Province Area One, Tagtree Thicket, Savanna Biome<br>Fixed: Costal Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Venomoth
(49, NULL, 1, NULL),
(49, NULL, 2, NULL),
(49, NULL, 3, NULL),
(49, NULL, 4, 'Area Zero, North Province Area Two, Tagtree Thicket, Savanna Biome<br>Fixed: Casseroya Lake, Savanna Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(49, NULL, 5, 'Area Zero, North Province Area Two, Tagtree Thicket, Savanna Biome<br>Fixed: Casseroya Lake, Savanna Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Diglett
(50, NULL, 1, 'Route 4, Galar Mine, Giant''s Mirror, Rolling Fields<br>Max Raid Battles: Bridge Field, Rolling Fields'),
(50, NULL, 2, 'Route 4, Galar Mine, Giant''s Mirror, Rolling Fields<br>Max Raid Battles: Bridge Field, Rolling Fields'),
(50, NULL, 3, NULL),
(50, NULL, 4, 'Alfornada Cavern, Asado Desert, East Province Area Three, Inlet Grotto, South Province Area Two<br>Fixed: East Province Area Three, South Province Area Two, South Province Area Six<br>Tera Raid Battles: 2 Star Raid Battles'),
(50, NULL, 5, 'Alfornada Cavern, Asado Desert, East Province Area Three, Inlet Grotto, South Province Area Two<br>Fixed: East Province Area Three, South Province Area Two, South Province Area Six<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Alolan Diglett
(50, 1, 1, 'Isle of Armor'),
(50, 1, 2, 'Isle of Armor'),
(50, 1, 3, NULL),
(50, 1, 4, 'Coastal Biome, Torchlit Labyrinth<br>Tera Raid Battles: 3 Star Raid Battles'),
(50, 1, 5, 'Coastal Biome, Torchlit Labyrinth<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Dugtrio
(51, NULL, 1, 'Route 6, Dusty Bowl, Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage<br>Max Raid Battles: Bridge Field, Rolling Fields<br>Dynamax Adventures'),
(51, NULL, 2, 'Route 6, Dusty Bowl, Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage<br>Max Raid Battles: Bridge Field, Rolling Fields<br>Dynamax Adventures'),
(51, NULL, 3, NULL),
(51, NULL, 4, 'Alfornada Cavern, Asado Desert, Dalizapa Passage, East Province Area Three, North Province Area Two, North Province Area Three, South Province Area Two<br>Fixed: South Province Area Six<br>Tera Raid Battles: 4 Star Raid Battles'),
(51, NULL, 5, 'Alfornada Cavern, Asado Desert, Dalizapa Passage, East Province Area Three, North Province Area Two, North Province Area Three, South Province Area Two<br>Fixed: South Province Area Six<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Alolan Dugtrio
(51, 1, 1, 'Evovle Alolan Diglett'),
(51, 1, 2, 'Evovle Alolan Diglett'),
(51, 1, 3, NULL),
(51, 1, 4, 'Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 6 Star Raid Battles'),
(51, 1, 5, 'Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 6 Star Raid Battles'),
-- Meowth
(52, NULL, 1, 'Trade in Turffield'),
(52, NULL, 2, 'Trade in Turffield'),
(52, NULL, 3, NULL),
(52, NULL, 4, 'East Province Area Three, West Province Area Three<br>Fixed: South Province Area Two<br>Tera Raid Battles: 2 Star Raid Battles'),
(52, NULL, 5, 'East Province Area Three, West Province Area Three<br>Fixed: South Province Area Two<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Alolan Meowth
(52, 1, 1, 'Gift from Diglett Master'),
(52, 1, 2, 'Gift from Diglett Master'),
(52, 1, 3, NULL),
(52, 1, 4, 'League Club Trade with Salvatore'),
(52, 1, 5, 'League Club Trade with Salvatore'),
-- Galarian Meowth
(52, 2, 1, 'Route 4<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Stony Wilderness, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea'),
(52, 2, 2, 'Route 4<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Stony Wilderness, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea'),
(52, 2, 3, NULL),
(52, 2, 4, 'Gift from Salvadore in Naranja Academ'),
(52, 2, 5, 'Gift from Salvadore in Naranja Academ'),
-- Persian
(53, NULL, 1, 'Evolve Kantonian Meowth'),
(53, NULL, 2, 'Evolve Kantonian Meowth'),
(53, NULL, 3, NULL),
(53, NULL, 4, 'West Province Area Three<br>Fixed: South Province Area Four<br>Tera Raid Battles: 4 Star Raid Battles'),
(53, NULL, 5, 'West Province Area Three<br>Fixed: South Province Area Four<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Alolan Persian
(53, 1, 1, 'Evolve Alolan Meowth'),
(53, 1, 2, 'Evolve Alolan Meowth'),
(53, 1, 3, NULL),
(53, 1, 4, 'Evolve Alolan Meowth'),
(53, 1, 5, 'Evolve Alolan Meowth'),
-- Psyduck
(54, NULL, 1, 'Challenge Beach, Brawlers'' Cave<br>Max Raid Battles: Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern'),
(54, NULL, 2, 'Challenge Beach, Brawlers'' Cave<br>Max Raid Battles: Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern'),
(54, NULL, 3, 'Obsidian Fieldlands: Heartwood or nearby<br>Crimson Mirelands: Golden Lowlands, Gapejaw Bog, Holm of Trials or nearby<br>Cobalt Coastlands: Bathers'' Lagoon or nearby<br>Coronet Highlands: Wayward Wood, Lonely Spring or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Cobalt Coastlands: Massive Mass Outbreak'),
(54, NULL, 4, 'Casseroya Lake, East Province Area Two, East Province Area Three, Glaseado Mountain, South Province Area One, South Province Area Four, South Province Area Five, South Province Area Six, Tagtree Thicket, West Province Area One, West Province Area Two<br>Tera Raid Battles: 2 Star Raid Battles'),
(54, NULL, 5, 'Casseroya Lake, East Province Area Two, East Province Area Three, Glaseado Mountain, South Province Area One, South Province Area Four, South Province Area Five, South Province Area Six, Tagtree Thicket, West Province Area One, West Province Area Two<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Golduck
(55, NULL, 1, 'Forest of Focus, Challenge Beach, Brawlers'' Cave, Training Lowlands<br>Max Raid Battles: Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern<br>Dynamax Adventures'),
(55, NULL, 2, 'Forest of Focus, Challenge Beach, Brawlers'' Cave, Training Lowlands<br>Max Raid Battles: Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern<br>Dynamax Adventures'),
(55, NULL, 3, 'Crimson Mirelands: Holm of Trials or nearby<br>Cobalt Coastlands: Bathers'' Lagoon, Spring Path or nearby<br>Coronet Highlands: Wayward Wood, Lonely Spring or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Cobalt Coastlands: Massive Mass Outbreak'),
(55, NULL, 4, 'Area Zero, Casseroya Lake, Glaseado Mountain, North Province Area One, North Province Area Three<br>Fixed: South Province Area Four, South Province Area Six<br>Tera Raid Battles: 4 Star Raid Battles'),
(55, NULL, 5, 'Area Zero, Casseroya Lake, Glaseado Mountain, North Province Area One, North Province Area Three<br>Fixed: South Province Area Four, South Province Area Six<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Mankey
(56, NULL, 1, NULL),
(56, NULL, 2, NULL),
(56, NULL, 3, NULL),
(56, NULL, 4, 'South Province Area One, South Province Area Five, West Province Area One, Apple Hills, Kitakami Road, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: West Province Area One<br>Tera Raid Battles: 2 Star Raid Battles'),
(56, NULL, 5, 'South Province Area One, South Province Area Five, West Province Area One, Apple Hills, Kitakami Road, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: West Province Area One<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Primeape
(57, NULL, 1, NULL),
(57, NULL, 2, NULL),
(57, NULL, 3, NULL),
(57, NULL, 4, 'North Province Area One, West Province Area Three, Kitakami Wilds, Timeless Woods<br>Fixed: Glaseado Mountain, South Province Area Four, West Province Area One, Kitakami Wilds<br>Tera Raid Battles: 4 Star Raid Battles'),
(57, NULL, 5, 'North Province Area One, West Province Area Three, Kitakami Wilds, Timeless Woods<br>Fixed: Glaseado Mountain, South Province Area Four, West Province Area One, Kitakami Wilds<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Growlithe
(58, NULL, 1, 'Dusty Bowl, Giant''s Mirror, Hammerlocke Hills'),
(58, NULL, 2, 'Route 3, Axew''s Eye, Dappled Grove, East Lake Axewell, Giant''s Seat, North Lake Miloch, Rolling Fields, South Lake Miloch, Watchtower Ruins, West Lake Axewell<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness'),
(58, NULL, 3, NULL),
(58, NULL, 4, 'East Province Area Three, South Province Area Three, Apple Hills, Crystal Pool, Infernal Pass, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Timeless Woods<br>Fixed: East Province Area Two, North Province Area Two, South Province Area Three, Mossfell Confluence<br>Tera Raid Battles: 2 Star Raid Battles'),
(58, NULL, 5, 'East Province Area Three, South Province Area Three, Apple Hills, Crystal Pool, Infernal Pass, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Timeless Woods<br>Fixed: East Province Area Two, North Province Area Two, South Province Area Three, Mossfell Confluence<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Hisuian Growlithe
(58, 3, 1, NULL),
(58, 3, 2, NULL),
(58, 3, 3, 'Cobalt Coastlands: Windbreak Stand, Veilstone Cape or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(58, 3, 4, 'Gift from Perrin'),
(58, 3, 5, 'Gift from Perrin'),
-- Arcanine
(59, NULL, 1, 'Max Raid Battles: Giant''s Cap'),
(59, NULL, 2, 'Lake of Outrage<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert, Giant''s Bed, Snowslide Slope, Ballimere Lake'),
(59, NULL, 3, NULL),
(59, NULL, 4, 'North Province Area Two<br>Fixed: North Province Area Two, South Province Area Four<br>Tera Raid Battles: 5 Star Raid Battles'),
(59, NULL, 5, 'North Province Area Two<br>Fixed: North Province Area Two, South Province Area Four<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Hisuian Arcanine
(59, 3, 1, NULL),
(59, 3, 2, NULL),
(59, 3, 3, 'Cobalt Coastlands: Massive Mass Outbreak'),
(59, 3, 4, 'Evolve Hisuian Growlithe'),
(59, 3, 5, 'Evolve Hisuian Growlithe'),
-- Poliwag
(60, NULL, 1, 'Brawlers'' Cave<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Courageous Cavern'),
(60, NULL, 2, 'Brawlers'' Cave<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Courageous Cavern'),
(60, NULL, 3, NULL),
(60, NULL, 4, 'Fellhorn Gorge, Kitakami Road, Mossfell Confluence, Reveler''s Road<br>Fixed: Reveler''s Road<br>Tera Raid Battles: 1 Star Raid Battles'),
(60, NULL, 5, 'Fellhorn Gorge, Kitakami Road, Mossfell Confluence, Reveler''s Road<br>Fixed: Reveler''s Road<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Poliwhirl
(61, NULL, 1, 'Soothing Wetlands<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Courageous Cavern'),
(61, NULL, 2, 'Soothing Wetlands<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Courageous Cavern'),
(61, NULL, 3, NULL),
(61, NULL, 4, 'Fellhorn Gorge, Mossfell Confluence<br>Fixed: Mossfell Confluence<br>Tera Raid Battles: 3 Star Raid Battles'),
(61, NULL, 5, 'Fellhorn Gorge, Mossfell Confluence<br>Fixed: Mossfell Confluence<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Poliwrath
(62, NULL, 1, 'Brawlers'' Cave<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Courageous Cavern<br>Dynamax Adventures'),
(62, NULL, 2, 'Brawlers'' Cave<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Courageous Cavern<br>Dynamax Adventures'),
(62, NULL, 3, NULL),
(62, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(62, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Abra
(63, NULL, 1, 'Fields of Honor<br>Max Raid Battles: Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea'),
(63, NULL, 2, 'Fields of Honor<br>Max Raid Battles: Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea'),
(63, NULL, 3, 'Obsidian Fieldlands: Windswept Run, Sandgem Flats or nearby<br>Alabaster Icelands: Lake Acuity or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(63, NULL, 4, NULL),
(63, NULL, 5, NULL),
-- Kadabra
(64, NULL, 1, 'Fields of Honor, Soothing Wetlands<br>Max Raid Battles: Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea<br>Dynamax Adventures'),
(64, NULL, 2, 'Fields of Honor, Soothing Wetlands<br>Max Raid Battles: Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea<br>Dynamax Adventures'),
(64, NULL, 3, 'Obsidian Fieldlands: Sandgem Flats or nearby<br>Alabaster Icelands: Lake Acuity or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(64, NULL, 4, NULL),
(64, NULL, 5, NULL),
-- Alakazam
(65, NULL, 1, 'Loop Lagoon, Insular Sea<br>Max Raid Battles: Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea'),
(65, NULL, 2, 'Loop Lagoon, Insular Sea<br>Max Raid Battles: Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea'),
(65, NULL, 3, 'Obsidian Fieldlands: Sandgem Flats or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(65, NULL, 4, NULL),
(65, NULL, 5, NULL),
-- Machop
(66, NULL, 1, 'Route 3, Giant''s Mirror, Giant''s Seat, North Lake Miloch, South Lake Miloch, Stony Wilderness, Watchtower Ruins<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness'),
(66, NULL, 2, 'Route 3, Giant''s Mirror, Giant''s Seat, North Lake Miloch, South Lake Miloch, Stony Wilderness, Watchtower Ruins<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness'),
(66, NULL, 3, 'Obsidian Fieldlands: Oreburrow Tunnel, Obsidian Falls or nearby<br>Cobalt Coastlands: Castaway Shore or nearby<br>Coronet Highlands: Bolderoll Ravine, Cloudcap Pass or nearby<br>Alabaster Icelands: Icebound Falls, Arena''s Approach, Snowfall Hot Spring or nearby<br>Cobalt Coastlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(66, NULL, 4, NULL),
(66, NULL, 5, NULL),
-- Machoke
(67, NULL, 1, 'Axew''s Eye, Giant''s Seat, Hammerlocke Hills, South Lake Miloch, Stony Wilderness<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness<br>Dynamax Adventures'),
(67, NULL, 2, 'Axew''s Eye, Giant''s Seat, Hammerlocke Hills, South Lake Miloch, Stony Wilderness<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness<br>Dynamax Adventures'),
(67, NULL, 3, 'Obsidian Fieldlands: Obsidian Falls or nearby<br>Cobalt Coastlands: Castaway Shore or nearby<br>Coronet Highlands: Bolderoll Ravine, Cloudcap Pass or nearby<br>Alabaster Icelands: Icebound Falls, Arena''s Approach, Snowfall Hot Spring or nearby<br>Cobalt Coastlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(67, NULL, 4, NULL),
(67, NULL, 5, NULL),
-- Machamp
(68, NULL, 1, 'Giant''s Mirror<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness<br>Gigantamax Raid Battles: Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(68, NULL, 2, 'Giant''s Mirror<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(68, NULL, 3, 'Alabaster Icelands: Arena''s Approach or nearby<br>Cobalt Coastlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(68, NULL, 4, NULL),
(68, NULL, 5, NULL),
-- Bellsprout
(69, NULL, 1, NULL),
(69, NULL, 2, NULL),
(69, NULL, 3, NULL),
(69, NULL, 4, 'Apple Hills, Kitakami Road, Loyalty Plaza, Mossfell Confluence<br>Tera Raid Battles: 2 Star Raid Battles'),
(69, NULL, 5, 'Apple Hills, Kitakami Road, Loyalty Plaza, Mossfell Confluence<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Weepinbell
(70, NULL, 1, NULL),
(70, NULL, 2, NULL),
(70, NULL, 3, NULL),
(70, NULL, 4, 'Mossfell Confluence<br>Tera Raid Battles: 3 Star Raid Battles'),
(70, NULL, 5, 'Mossfell Confluence<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Victreebel
(71, NULL, 1, NULL),
(71, NULL, 2, NULL),
(71, NULL, 3, NULL),
(71, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles'),
(71, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles'),
-- Tentacool
(72, NULL, 1, 'Fields of Honor, Challenge Beach, Courageous Cavern, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Loop Lagoon, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea'),
(72, NULL, 2, 'Fields of Honor, Challenge Beach, Courageous Cavern, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Loop Lagoon, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea'),
(72, NULL, 3, 'Cobalt Coastlands: Lunker''s Lair, Seagrass Haven, Islespy Shore or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(72, NULL, 4, 'Coastal Biome<br>Fixed: Coastal Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
(72, NULL, 5, 'Coastal Biome<br>Fixed: Coastal Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Tentacruel
(73, NULL, 1, 'Fields of Honor, Challenge Beach, Courageous Cavern, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Loop Lagoon, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea<br>Dynamax Adventures'),
(73, NULL, 2, 'Fields of Honor, Challenge Beach, Courageous Cavern, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Loop Lagoon, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea<br>Dynamax Adventures'),
(73, NULL, 3, 'Cobalt Coastlands: Lunker''s Lair, Seagrass Haven, Islespy Shore or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(73, NULL, 4, 'Coastal Biome<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(73, NULL, 5, 'Coastal Biome<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Geodude
(74, NULL, 1, NULL),
(74, NULL, 2, NULL),
(74, NULL, 3, 'Obsidian Fieldlands: Deertrack Heights, Worn Bridge, Oreburrow Tunnel or nearby<br>Crimson Mirelands: Gapejaw Bog, Scarlet Bog, Ursa''s Ring, Bolderoll Slope or nearby<br>Cobalt Coastlands: Ginkgo Landing, Veilstone Cape, Aipom Hill, Bathers'' Lagoon or nearby<br>Coronet Highlands: Bolderoll Ravine, Clamberclaw Cliffs, Celestica Ruins or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Cobalt Coastlands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(74, NULL, 4, 'Apple Hills, Chilling Waterhead, Infernal Pass, Kitakami Road, Kitakami Wilds, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Fixed: Oni Mountain<br>Tera Raid Battles: 1 Star Raid Battles'),
(74, NULL, 5, 'Apple Hills, Chilling Waterhead, Infernal Pass, Kitakami Road, Kitakami Wilds, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Fixed: Oni Mountain<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Alolan Geodude
(74, 1, 1, NULL),
(74, 1, 2, NULL),
(74, 1, 3, NULL),
(74, 1, 4, 'Canyon Biome, Chargestone Cavern<br>Fixed: Canyon Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(74, 1, 5, 'Canyon Biome, Chargestone Cavern<br>Fixed: Canyon Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Graveler
(75, NULL, 1, NULL),
(75, NULL, 2, NULL),
(75, NULL, 3, 'Obsidian Fieldlands: Oreburrow Tunnel, Sandgem Flats or nearby<br>Crimson Mirelands: Gapejaw Bog, Scarlet Bog, Ursa''s Ring, Bolderoll Slope or nearby<br>Cobalt Coastlands: Windbreak Stand, Firespit Island, Islespy Shore, Spring Path or nearby<br>Coronet Highlands: Heavenward Lookout, Bolderoll Ravine, Clamberclaw Cliffs, Celestica Ruins or nearby<br>Alabaster Icelands: Snowpoint Temple or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Cobalt Coastlands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(75, NULL, 4, 'Chilling Waterhead, Crystal Pool, Fellhorn Gorge, Infernal Pass, Kitakami Wilds, Oni Mountain, Timeless Woods<br>Fixed: Chilling Waterhead, Infernal Pass, Paradise Barrens, Wistful Fields<br>Tera Raid Battles: 4 Star Raid Battles'),
(75, NULL, 5, 'Chilling Waterhead, Crystal Pool, Fellhorn Gorge, Infernal Pass, Kitakami Wilds, Oni Mountain, Timeless Woods<br>Fixed: Chilling Waterhead, Infernal Pass, Paradise Barrens, Wistful Fields<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Alolan Graveler
(75, 1, 1, NULL),
(75, 1, 2, NULL),
(75, 1, 3, NULL),
(75, 1, 4, 'Canyon Biome, Chargestone Cavern<br>Fixed: Canyon Biome'),
(75, 1, 5, 'Canyon Biome, Chargestone Cavern<br>Fixed: Canyon Biome'),
-- Golem
(76, NULL, 1, NULL),
(76, NULL, 2, NULL),
(76, NULL, 3, 'Coronet Highlands: Bolderoll Ravine or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Cobalt Coastlands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(76, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(76, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Alolan Golem
(76, 1, 1, NULL),
(76, 1, 2, NULL),
(76, 1, 3, NULL),
(76, 1, 4, 'Tera Raid Battles: 6 Star Raid Battles'),
(76, 1, 5, 'Tera Raid Battles: 6 Star Raid Battles'),
-- Ponyta
(77, NULL, 1, 'Trade from Pokémon Shield'),
(77, NULL, 2, 'Trade from Regina in Isle of Armor Area'),
(77, NULL, 3, 'Obsidian Fieldlands: Horseshoe Plains or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(77, NULL, 4, NULL),
(77, NULL, 5, NULL),
-- Galarian Ponyta
(77, 2, 1, 'Trade from Pokémon Shield'),
(77, 2, 2, 'Glimwood Tangle, Old Cemetery<br>Max Raid Battles: Bridge Field, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake'),
(77, 2, 3, NULL),
(77, 2, 4, NULL),
(77, 2, 5, NULL),
-- Rapidash
(78, NULL, 1, 'Trade from Pokémon Shield'),
(78, NULL, 2, 'Evolve Kantonian Ponyta'),
(78, NULL, 3, 'Obsidian Fieldlands: Horseshoe Plains or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(78, NULL, 4, NULL),
(78, NULL, 5, NULL),
-- Galarian Rapidash
(78, 2, 1, 'Trade from Pokémon Shield'),
(78, 2, 2, 'Evolve Galarian Ponyta'),
(78, 2, 3, NULL),
(78, 2, 4, NULL),
(78, 2, 5, NULL),
-- Slowpoke
(79, NULL, 1, 'Gift from Diglett Master'),
(79, NULL, 2, 'Gift from Diglett Master'),
(79, NULL, 3, NULL),
(79, NULL, 4, 'Casseroya Lake, East Province Area Two, South Province Area One, South Province Area Five, West Province Area Two<br>Fixed: Casseroya Lake<br>Tera Raid Battles: 2 Star Raid Battles'),
(79, NULL, 5, 'Casseroya Lake, East Province Area Two, South Province Area One, South Province Area Five, West Province Area Two<br>Fixed: Casseroya Lake<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Galarian Slowpoke
(79, 2, 1, 'Wedgehurst, Fields of Honor<br>Max Raid Battles: Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Ballimere Lake'),
(79, 2, 2, 'Wedgehurst, Fields of Honor<br>Max Raid Battles: Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Ballimere Lake'),
(79, 2, 3, NULL),
(79, 2, 4, 'Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(79, 2, 5, 'Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Slowbro
(80, NULL, 1, 'Evolve Kantonian Slowpoke'),
(80, NULL, 2, 'Evolve Kantonian Slowpoke'),
(80, NULL, 3, NULL),
(80, NULL, 4, 'Casseroya Lake, West Province Area Two<br>Fixed: Casseroya Lake<br>Tera Raid Battles: 5 Star Raid Battles'),
(80, NULL, 5, 'Casseroya Lake, West Province Area Two<br>Fixed: Casseroya Lake<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Galarian Slowbro
(80, 2, 1, 'Dynamax Adventures'),
(80, 2, 2, 'Dynamax Adventures'),
(80, 2, 3, NULL),
(80, 2, 4, 'Tera Raid Battles: 6 Star Raid Battles'),
(80, 2, 5, 'Tera Raid Battles: 6 Star Raid Battles'),
-- Magnemite
(81, NULL, 1, 'Max Raid Battles: Fields of Honor, Forest of Focus, Challenge Beach, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea, Honeycalm Sea'),
(81, NULL, 2, 'Max Raid Battles: Fields of Honor, Forest of Focus, Challenge Beach, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea, Honeycalm Sea'),
(81, NULL, 3, 'Cobalt Coastlands: Space-time Distortion in Cobalt Coastlands or nearby'),
(81, NULL, 4, 'East Province Area Two, East Province Area Three, Canyon Biome, Chargestone Cavern, Polar Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
(81, NULL, 5, 'East Province Area Two, East Province Area Three, Canyon Biome, Chargestone Cavern, Polar Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Magneton
(82, NULL, 1, 'Max Raid Battles: Fields of Honor, Forest of Focus, Challenge Beach, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea, Honeycalm Sea<br>Dynamax Adventures'),
(82, NULL, 2, 'Max Raid Battles: Fields of Honor, Forest of Focus, Challenge Beach, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea, Honeycalm Sea<br>Dynamax Adventures'),
(82, NULL, 3, 'Cobalt Coastlands: Space-time Distortion in Cobalt Coastlands or nearby'),
(82, NULL, 4, 'Dalizapa Passage, Glaseado Mountain, Canyon Biome, Chargestone Cavern, Polar Biome<br>Fixed: Glaseado Mountain, Coastal Biome, Chargestone Cavern<br>Tera Raid Battles: 4 Star Raid Battles'),
(82, NULL, 5, 'Dalizapa Passage, Glaseado Mountain, Canyon Biome, Chargestone Cavern, Polar Biome<br>Fixed: Glaseado Mountain, Coastal Biome, Chargestone Cavern<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Farfetch'd
(83, NULL, 1, 'Trade from Regina in Isle of Armor Area'),
(83, NULL, 2, 'Trade from Pokémon Sword'),
(83, NULL, 3, NULL),
(83, NULL, 4, NULL),
(83, NULL, 5, NULL),
-- Galarian Farfetch'd
(83, 2, 1, 'Route 5, Giant''s Mirror<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(83, 2, 2, 'Trade from Pokémon Sword'),
(83, 2, 3, NULL),
(83, 2, 4, NULL),
(83, 2, 5, NULL),
-- Doduo
(84, NULL, 1, NULL),
(84, NULL, 2, NULL),
(84, NULL, 3, NULL),
(84, NULL, 4, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
(84, NULL, 5, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Dodrio
(85, NULL, 1, NULL),
(85, NULL, 2, NULL),
(85, NULL, 3, NULL),
(85, NULL, 4, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(85, NULL, 5, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Seel
(86, NULL, 1, NULL),
(86, NULL, 2, NULL),
(86, NULL, 3, NULL),
(86, NULL, 4, 'Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
(86, NULL, 5, 'Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Dewgong
(87, NULL, 1, NULL),
(87, NULL, 2, NULL),
(87, NULL, 3, NULL),
(87, NULL, 4, 'Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(87, NULL, 5, 'Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Grimer
(88, NULL, 1, NULL),
(88, NULL, 2, NULL),
(88, NULL, 3, NULL),
(88, NULL, 4, 'West Province Area Two, East Province Area Two, Coastal Biome, Torchlit Labyrinth<br>Tera Raid Battles: 2 Star Raid Battles'),
(88, NULL, 5, 'West Province Area Two, East Province Area Two, Coastal Biome, Torchlit Labyrinth<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Alolan Grimer
(88, 1, 1, NULL),
(88, 1, 2, NULL),
(88, 1, 3, NULL),
(88, 1, 4, 'Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(88, 1, 5, 'Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Muk
(89, NULL, 1, NULL),
(89, NULL, 2, NULL),
(89, NULL, 3, NULL),
(89, NULL, 4, 'Tera Raid Battles: 4 Star Raid Battles'),
(89, NULL, 5, 'Tera Raid Battles: 4 Star Raid Battles'),
-- Alolan Muk
(89, 1, 1, NULL),
(89, 1, 2, NULL),
(89, 1, 3, NULL),
(89, 1, 4, 'Coastal Biome, Torchlit Labyrinth<br>Fixed: Canyon Biome, Coastal Biome<br>Tera Raid Battles: 6 Star Raid Battles'),
(89, 1, 5, 'Coastal Biome, Torchlit Labyrinth<br>Fixed: Canyon Biome, Coastal Biome<br>Tera Raid Battles: 6 Star Raid Battles'),
-- Shellder
(90, NULL, 1, 'East Lake Axewell, Giant''s Seat, West Lake Axewell, Courageous Cavern, Loop Lagoon<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea'),
(90, NULL, 2, 'East Lake Axewell, Giant''s Seat, West Lake Axewell, Courageous Cavern, Loop Lagoon<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea'),
(90, NULL, 3, NULL),
(90, NULL, 4, 'East Paldean Sea, North Paldean Sea, South Paldean Sea, West Paldean Sea<br>Tera Raid Battles: 1 Star Raid Battles , 2 Star Raid Battles'),
(90, NULL, 5, 'East Paldean Sea, North Paldean Sea, South Paldean Sea, West Paldean Sea<br>Tera Raid Battles: 1 Star Raid Battles , 2 Star Raid Battles'),
-- Cloyster
(91, NULL, 1, 'Giant''s Seat, West Lake Axewell, Challenge Beach, Courageous Cavern, Loop Lagoon<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, South Lake Miloch, Stony Wilderness, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea'),
(91, NULL, 2, 'Giant''s Seat, West Lake Axewell, Challenge Beach, Courageous Cavern, Loop Lagoon<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, South Lake Miloch, Stony Wilderness, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea'),
(91, NULL, 3, NULL),
(91, NULL, 4, 'East Paldean Sea, North Paldean Sea, South Paldean Sea, West Paldean Sea<br>Tera Raid Battles: 4 Star Raid Battles , 5 Star Raid Battles'),
(91, NULL, 5, 'East Paldean Sea, North Paldean Sea, South Paldean Sea, West Paldean Sea<br>Tera Raid Battles: 4 Star Raid Battles , 5 Star Raid Battles'),
-- Gastly
(92, NULL, 1, 'Giant''s Seat, Hammerlocke Hills, North Lake Miloch, Watchtower Ruins<br>Max Raid Battles: Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Motostoke Riverbank, South Lake Miloch, Stony Wilderness, Watchtower Ruins'),
(92, NULL, 2, 'Giant''s Seat, Hammerlocke Hills, North Lake Miloch, Watchtower Ruins<br>Max Raid Battles: Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Motostoke Riverbank, South Lake Miloch, Stony Wilderness, Watchtower Ruins'),
(92, NULL, 3, 'Crimson Mirelands: Golden Lowlands, Gapejaw Bog, Scarlet Bog, Shrouded Ruins or nearby<br>Coronet Highlands: Bolderoll Ravine, Sacred Plaza, Celestica Ruins or nearby<br>Alabaster Icelands: Bonechill Wastes or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(92, NULL, 4, 'East Province Area Two, East Province Area Three, South Province Area One, South Province Area Three, West Province Area One, Apple Hills, Mossfell Confluence, Oni Mountain, Paradise Barrens, Wistful Fields<br>Tera Raid Battles: 2 Star Raid Battles'),
(92, NULL, 5, 'East Province Area Two, East Province Area Three, South Province Area One, South Province Area Three, West Province Area One, Apple Hills, Mossfell Confluence, Oni Mountain, Paradise Barrens, Wistful Fields<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Haunter
(93, NULL, 1, 'Route 8, Giant''s Seat, Rolling Fields, Watchtower Ruins<br>Max Raid Battles: Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Motostoke Riverbank, South Lake Miloch, Stony Wilderness, Watchtower Ruins, Slippery Slope, Old Cemetery, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(93, NULL, 2, 'Route 8, Giant''s Seat, Rolling Fields, Watchtower Ruins<br>Max Raid Battles: Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Motostoke Riverbank, South Lake Miloch, Stony Wilderness, Watchtower Ruins<br>Dynamax Adventures'),
(93, NULL, 3, 'Crimson Mirelands: Gapejaw Bog, Scarlet Bog, Shrouded Ruins, Cottonsedge Prairie or nearby<br>Coronet Highlands: Bolderoll Ravine, Sacred Plaza, Celestica Ruins or nearby<br>Alabaster Icelands: Bonechill Wastes or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(93, NULL, 4, 'Dalizapa Passage, Glaseado Mountain, North Province Area One, Mossfell Confluence, Oni Mountain<br>Fixed: West Province Area One<br>Tera Raid Battles: 3 Star Raid Battles'),
(93, NULL, 5, 'Dalizapa Passage, Glaseado Mountain, North Province Area One, Mossfell Confluence, Oni Mountain<br>Fixed: West Province Area One<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Gengar
(94, NULL, 1, 'Giant''s Cap<br>Max Raid Battles: Giant''s Mirror, South Lake Miloch, Stony Wilderness, Slippery Slope, Old Cemetery, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(94, NULL, 2, 'Giant''s Cap<br>Max Raid Battles: Giant''s Mirror, South Lake Miloch, Stony Wilderness<br>Gigantamax Raid Battles: Stony Wilderness, Slippery Slope, Old Cemetery, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(94, NULL, 3, 'Obsidian Fieldlands: Space-time Distortion in Obsidian Fieldlands or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(94, NULL, 4, 'Mossfell Confluence<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(94, NULL, 5, 'Mossfell Confluence<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Onix
(95, NULL, 1, 'East Lake Axewell, Giant''s Seat, Motostoke Riverbank, Rolling Fields<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Seat, Hammerlocke Hills, Rolling Fields, Stony Wilderness'),
(95, NULL, 2, 'East Lake Axewell, Giant''s Seat, Motostoke Riverbank, Rolling Fields<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Seat, Hammerlocke Hills, Rolling Fields, Stony Wilderness'),
(95, NULL, 3, 'Crimson Mirelands: Scarlet Bog, Bolderoll Slope, Lake Valor or nearby<br>Coronet Highlands: Celestica Trail or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Cobalt Coastlands: Massive Mass Outbreak'),
(95, NULL, 4, NULL),
(95, NULL, 5, NULL),
-- Drowzee
(96, NULL, 1, NULL),
(96, NULL, 2, NULL),
(96, NULL, 3, NULL),
(96, NULL, 4, 'South Province Area Two, South Province Area Three, South Province Area Five<br>Tera Raid Battles: 1 Star Raid Battles'),
(96, NULL, 5, 'South Province Area Two, South Province Area Three, South Province Area Five<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Hypno
(97, NULL, 1, NULL),
(97, NULL, 2, NULL),
(97, NULL, 3, NULL),
(97, NULL, 4, 'Area Zero, Dalizapa Passage, North Province Area Three, South Province Area Six, West Province Area One<br>Tera Raid Battles: 4 Star Raid Battles'),
(97, NULL, 5, 'Area Zero, Dalizapa Passage, North Province Area Three, South Province Area Six, West Province Area One<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Krabby
(98, NULL, 1, 'Giant''s Cap, South Lake Miloch, West Lake Axewell, Fields of Honor, Loop Lagoon<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Giant''s Mirror, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Insular Sea'),
(98, NULL, 2, 'Giant''s Cap, South Lake Miloch, West Lake Axewell, Fields of Honor, Loop Lagoon<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Giant''s Mirror, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Insular Sea'),
(98, NULL, 3, NULL),
(98, NULL, 4, NULL),
(98, NULL, 5, NULL),
-- Kingler
(99, NULL, 1, 'Route 9, Axew''s Eye, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Training Lowlands, Max Raid Battles: Dusty Bowl, Giant''s Cap, Giant''s Mirror, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Insular Sea<br>South Lake Miloch, West Lake Axewell, Insular Sea, Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(99, NULL, 2, 'Route 9, Axew''s Eye, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Training Lowlands, Max Raid Battles: Dusty Bowl, Giant''s Cap, Giant''s Mirror, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Insular Sea<br>South Lake Miloch, West Lake Axewell, Insular Sea, Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(99, NULL, 3, NULL),
(99, NULL, 4, NULL),
(99, NULL, 5, NULL),
-- Voltorb
(100, NULL, 1, NULL),
(100, NULL, 2, NULL),
(100, NULL, 3, NULL),
(100, NULL, 4, 'East Province Area Three, West Province Area Three<br>Fixed: West Province Area One<br>Tera Raid Battles: 2 Star Raid Battles'),
(100, NULL, 5, 'East Province Area Three, West Province Area Three<br>Fixed: West Province Area One<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Hisuian Voltorb
(100, 3, 1, NULL),
(100, 3, 2, NULL),
(100, 3, 3, 'Coronet Highlands: Sacred Plaza or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(100, 3, 4, 'Transfer from Pokémon HOME'),
(100, 3, 5, 'Transfer from Pokémon HOME'),
-- Electrode
(101, NULL, 1, NULL),
(101, NULL, 2, NULL),
(101, NULL, 3, NULL),
(101, NULL, 4, 'West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
(101, NULL, 5, 'West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Hisuian Electrode
(101, 3, 1, NULL),
(101, 3, 2, NULL),
(101, 3, 3, 'Coronet Highlands: Massive Mass Outbreak'),
(101, 3, 4, 'Evolve Hisuian Voltorb'),
(101, 3, 5, 'Evolve Hisuian Voltorb'),
-- Exeggcute
(102, NULL, 1, 'Workout Sea, Stepping-Stone Sea, Insular Sea<br>Max Raid Battles: Soothing Wetlands, Forest of Focus, Challenge Beach, Training Lowlands, Stepping-Stone Sea'),
(102, NULL, 2, 'Workout Sea, Stepping-Stone Sea, Insular Sea<br>Max Raid Battles: Soothing Wetlands, Forest of Focus, Challenge Beach, Training Lowlands, Stepping-Stone Sea'),
(102, NULL, 3, NULL),
(102, NULL, 4, 'Coastal Biome, Savanna Biome, Torchlit Labyrinth<br>Fixed: Savanna Biome, Coastal Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
(102, NULL, 5, 'Coastal Biome, Savanna Biome, Torchlit Labyrinth<br>Fixed: Savanna Biome, Coastal Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Exeggutor
(103, NULL, 1, 'Workout Sea, Insular Sea<br>Max Raid Battles: Soothing Wetlands, Forest of Focus, Challenge Beach, Training Lowlands, Stepping-Stone Sea<br>Dynamax Adventures'),
(103, NULL, 2, 'Workout Sea, Insular Sea<br>Max Raid Battles: Soothing Wetlands, Forest of Focus, Challenge Beach, Training Lowlands, Stepping-Stone Sea<br>Dynamax Adventures'),
(103, NULL, 3, NULL),
(103, NULL, 4, 'Savanna Biome'),
(103, NULL, 5, 'Savanna Biome'),
-- Alolan Exeggutor
(103, 1, 1, 'Gift from Diglett Maste'),
(103, 1, 2, 'Gift from Diglett Maste'),
(103, 1, 3, NULL),
(103, 1, 4, 'Coastal Biome<br>Fixed: Coastal Biome, Savanna Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(103, 1, 5, 'Coastal Biome<br>Fixed: Coastal Biome, Savanna Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Cubone
(104, NULL, 1, 'Forest of Focus, Warm-Up Tunnel<br>Max Raid Battles: Challenge Beach, Courageous Cavern, Potbottom Desert, Stepping-Stone Sea'),
(104, NULL, 2, 'Forest of Focus, Warm-Up Tunnel<br>Max Raid Battles: Challenge Beach, Courageous Cavern, Potbottom Desert, Stepping-Stone Sea'),
(104, NULL, 3, NULL),
(104, NULL, 4, NULL),
(104, NULL, 5, NULL),
-- Marowak
(105, NULL, 1, 'Potbottom Desert<br>Max Raid Battles: Challenge Beach, Courageous Cavern, Potbottom Desert, Stepping-Stone Sea<br>Dynamax Adventures'),
(105, NULL, 2, 'Potbottom Desert<br>Max Raid Battles: Challenge Beach, Courageous Cavern, Potbottom Desert, Stepping-Stone Sea<br>Dynamax Adventures'),
(105, NULL, 3, NULL),
(105, NULL, 4, NULL),
(105, NULL, 5, NULL),
-- Alolan Marowak
(105, 1, 1, 'Gift from Diglett Master'),
(105, 1, 2, 'Gift from Diglett Master'),
(105, 1, 3, NULL),
(105, 1, 4, NULL),
(105, 1, 5, NULL),
-- Hitmonlee
(106, NULL, 1, 'Dusty Bowl<br>Max Raid Battles: Rolling Fields, South Lake Miloch, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(106, NULL, 2, 'Max Raid Battles: Rolling Fields, South Lake Miloch, Stony Wilderness<br>Dynamax Adventures'),
(106, NULL, 3, NULL),
(106, NULL, 4, 'Canyon Biome<br>Tera Raid Battles: 5 Star Raid Battles'),
(106, NULL, 5, 'Canyon Biome<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Hitmonchan
(107, NULL, 1, 'Max Raid Battles: Rolling Fields, South Lake Miloch, Stony Wilderness<br>Dynamax Adventures'),
(107, NULL, 2, 'Dusty Bowl<br>Max Raid Battles: Rolling Fields, South Lake Miloch, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(107, NULL, 3, NULL),
(107, NULL, 4, 'Canyon Biome<br>Tera Raid Battles: 5 Star Raid Battles'),
(107, NULL, 5, 'Canyon Biome<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Lickitung
(108, NULL, 1, 'Soothing Wetlands, Challenge Beach, Brawlers'' Cave, Max Raid Battles: Soothing Wetlands, Courageous Cavern, Training Lowlands<br>Dynamax Adventures'),
(108, NULL, 2, 'Soothing Wetlands, Challenge Beach, Brawlers'' Cave, Max Raid Battles: Soothing Wetlands, Courageous Cavern, Training Lowlands<br>Dynamax Adventures'),
(108, NULL, 3, 'Crimson Mirelands: Shrouded Ruins or nearby<br>Alabaster Icelands: Snowfall Hot Spring, Avalanche Slopes or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(108, NULL, 4, NULL),
(108, NULL, 5, NULL),
-- Koffing
(109, NULL, 1, 'Dusty Bowl, Giant''s Mirror, Motostoke Outskirts, Motostoke Riverbank<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, North Lake Miloch'),
(109, NULL, 2, 'Dusty Bowl, Giant''s Mirror, Motostoke Outskirts, Motostoke Riverbank<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, North Lake Miloch'),
(109, NULL, 3, NULL),
(109, NULL, 4, 'Crystal Pool, Infernal Pass, Oni Mountain<br>Fixed: Infernal Pass'),
(109, NULL, 5, 'Crystal Pool, Infernal Pass, Oni Mountain<br>Fixed: Infernal Pass'),
-- Weezing
(110, NULL, 1, NULL),
(110, NULL, 2, NULL),
(110, NULL, 3, NULL),
(110, NULL, 4, 'Evolve Koffing'),
(110, NULL, 5, 'Evolve Koffing'),
-- Galarian Weezing
(110, 2, 1, 'East Lake Axewell, Lake of Outrage, Slumbering Weald<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, North Lake Miloch, Soothing Wetlands, Forest of Focus, Training Lowlands, Stepping-Stone Sea, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(110, 2, 2, 'East Lake Axewell, Lake of Outrage, Slumbering Weald<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, North Lake Miloch, Soothing Wetlands, Forest of Focus, Training Lowlands, Stepping-Stone Sea, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(110, 2, 3, NULL),
(110, 2, 4, 'Transfer from Pokémon HOME'),
(110, 2, 5, 'Transfer from Pokémon HOME'),
-- Rhyhorn
(111, NULL, 1, 'Route 8, Bridge Field, Giant''s Cap, Giant''s Mirror, Motostoke Riverbank, Stony Wilderness, Potbottom Desert<br>Max Raid Battles: Rolling Fields, Stony Wilderness, Fields of Honor, Training Lowlands, Potbottom Desert'),
(111, NULL, 2, 'Route 8, Bridge Field, Giant''s Cap, Giant''s Mirror, Motostoke Riverbank, Stony Wilderness, Potbottom Desert<br>Max Raid Battles: Rolling Fields, Stony Wilderness, Fields of Honor, Training Lowlands, Potbottom Desert'),
(111, NULL, 3, 'Crimson Mirelands: Bolderoll Slope, Diamond Heath, Shrouded Ruins or nearby<br>Coronet Highlands: Celestica Trail, Sacred Plaza or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(111, NULL, 4, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(111, NULL, 5, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Rhydon
(112, NULL, 1, 'Route 10, Bridge Field, Dusty Bowl, Giant''s Seat, Lake of Outrage, Motostoke Riverbank, Stony Wilderness, Potbottom Desert<br>Max Raid Battles: Rolling Fields, Stony Wilderness, Fields of Honor, Training Lowlands, Potbottom Desert<br>Dynamax Adventures'),
(112, NULL, 2, 'Route 10, Bridge Field, Dusty Bowl, Giant''s Seat, Lake of Outrage, Motostoke Riverbank, Stony Wilderness, Potbottom Desert<br>Max Raid Battles: Rolling Fields, Stony Wilderness, Fields of Honor, Training Lowlands, Potbottom Desert<br>Dynamax Adventures'),
(112, NULL, 3, 'Coronet Highlands: Celestica Trail, Sacred Plaza or nearby<br>Crimson Mirelands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(112, NULL, 4, 'Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(112, NULL, 5, 'Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Chansey
(113, NULL, 1, 'Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Brawlers'' Cave, Challenge Road, Courageous Cavern, Loop Lagoon, Training Lowlands, Warm-Up Tunnel, Potbottom Desert, Workout Sea, Stepping-Stone Sea, Honeycalm Island<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Brawlers'' Cave, Challenge Road, Courageous Cavern, Loop Lagoon, Training Lowlands, Potbottom Desert, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Dynamax Adventures'),
(113, NULL, 2, 'Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Brawlers'' Cave, Challenge Road, Courageous Cavern, Loop Lagoon, Training Lowlands, Warm-Up Tunnel, Potbottom Desert, Workout Sea, Stepping-Stone Sea, Honeycalm Island<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Brawlers'' Cave, Challenge Road, Courageous Cavern, Loop Lagoon, Training Lowlands, Potbottom Desert, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Dynamax Adventures'),
(113, NULL, 3, 'Obsidian Fieldlands: Obsidian Falls or nearby<br>Cobalt Coastlands: Hideaway Bay, Tombolo Walk or nearby<br>Alabaster Icelands: Avalanche Slopes or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(113, NULL, 4, 'Casseroya Lake, East Province Area Two, North Province Area One, North Province Area Two, North Province Area Three, South Province Area Six, West Province Area Two, West Province Area Three, Savanna Biome<br>Fixed: South Province Area Four, Savanna Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(113, NULL, 5, 'Casseroya Lake, East Province Area Two, North Province Area One, North Province Area Two, North Province Area Three, South Province Area Six, West Province Area Two, West Province Area Three, Savanna Biome<br>Fixed: South Province Area Four, Savanna Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Tangela
(114, NULL, 1, 'Forest of Focus<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Training Lowlands, Insular Sea<br>Dynamax Adventures'),
(114, NULL, 2, 'Forest of Focus<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Training Lowlands, Insular Sea<br>Dynamax Adventures'),
(114, NULL, 3, 'Crimson Mirelands: Gapejaw Bog or nearby<br>Cobalt Coastlands: Crossing Slope or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(114, NULL, 4, NULL),
(114, NULL, 5, NULL),
-- Kangaskhan
(115, NULL, 1, 'Training Lowlands, Warm-Up Tunnel<br>Max Raid Battles: Challenge Beach, Courageous Cavern, Potbottom Desert, Stepping-Stone Sea<br>Dynamax Adventures'),
(115, NULL, 2, 'Training Lowlands, Warm-Up Tunnel<br>Max Raid Battles: Challenge Beach, Courageous Cavern, Potbottom Desert, Stepping-Stone Sea<br>Dynamax Adventures'),
(115, NULL, 3, NULL),
(115, NULL, 4, NULL),
(115, NULL, 5, NULL),
-- Horsea
(116, NULL, 1, 'Insular Sea<br>Max Raid Battles: Loop Lagoon, Workout Sea, Honeycalm Sea'),
(116, NULL, 2, 'Insular Sea<br>Max Raid Battles: Loop Lagoon, Workout Sea, Honeycalm Sea'),
(116, NULL, 3, NULL),
(116, NULL, 4, 'Canyon Biome, Coastal Biome, Polar Biome, Torchlit Labyrinth<br>Fixed: Polar Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
(116, NULL, 5, 'Canyon Biome, Coastal Biome, Polar Biome, Torchlit Labyrinth<br>Fixed: Polar Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Seadra
(117, NULL, 1, 'Honeycalm Sea<br>Max Raid Battles: Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea<br>Dynamax Adventures'),
(117, NULL, 2, 'Honeycalm Sea<br>Max Raid Battles: Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea<br>Dynamax Adventures'),
(117, NULL, 3, NULL),
(117, NULL, 4, 'Canyon Biome, Coastal Biome, Polar Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome, Canyon Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(117, NULL, 5, 'Canyon Biome, Coastal Biome, Polar Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome, Canyon Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Goldeen
(118, NULL, 1, 'Route 4, Route 5, Route 6, Bridge Field, East Lake Axewell, Giant''s Cap, North Lake Miloch, South Lake Miloch, West Lake Axewell, Forest of Focus<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Courageous Cavern'),
(118, NULL, 2, 'Route 4, Route 5, Route 6, Bridge Field, East Lake Axewell, Giant''s Cap, North Lake Miloch, South Lake Miloch, West Lake Axewell, Forest of Focus<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Courageous Cavern'),
(118, NULL, 3, NULL),
(118, NULL, 4, NULL),
(118, NULL, 5, NULL),
-- Seaking
(119, NULL, 1, 'Bridge Field, Lake of Outrage, North Lake Miloch, West Lake Axewell<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Courageous Cavern<br>Dynamax Adventures'),
(119, NULL, 2, 'Bridge Field, Lake of Outrage, North Lake Miloch, West Lake Axewell<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Courageous Cavern<br>Dynamax Adventures'),
(119, NULL, 3, NULL),
(119, NULL, 4, NULL),
(119, NULL, 5, NULL),
-- Staryu
(120, NULL, 1, 'Challenge Beach, Training Lowlands<br>Max Raid Battles: Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea'),
(120, NULL, 2, 'Challenge Beach, Training Lowlands<br>Max Raid Battles: Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea'),
(120, NULL, 3, NULL),
(120, NULL, 4, NULL),
(120, NULL, 5, NULL),
-- Starmie
(121, NULL, 1, 'Fields of Honor, Challenge Beach<br>Max Raid Battles: Soothing Wetlands, Challenge Beach, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea<br>Dynamax Adventures'),
(121, NULL, 2, 'Fields of Honor, Challenge Beach<br>Max Raid Battles: Soothing Wetlands, Challenge Beach, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea<br>Dynamax Adventures'),
(121, NULL, 3, NULL),
(121, NULL, 4, NULL),
(121, NULL, 5, NULL),
-- Mr. Mime
(122, NULL, 1, 'Trade Obstagoon to Team Yell Grunt in Spikemuth'),
(122, NULL, 2, 'Trade Obstagoon to Team Yell Grunt in Spikemuth'),
(122, NULL, 3, 'Obsidian Fieldlands: Sandgem Flats or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Coronet Highlands: Massive Mass Outbreak'),
(122, NULL, 4, NULL),
(122, NULL, 5, NULL),
-- Galarian Mr. Mime
(122, 2, 1, 'Route 10, Lake of Outrage<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Watchtower Ruins, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake<br>Dynamax Adventures'),
(122, 2, 2, 'Route 10, Lake of Outrage<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Giant''s Seat, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Watchtower Ruins, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake'),
(122, 2, 3, NULL),
(122, 2, 4, NULL),
(122, 2, 5, NULL),
-- Scyther
(123, NULL, 1, 'Training Lowlands<br>Max Raid Battles: Fields of Honor, Forest of Focus, Training Lowlands, Workout Sea<br>Dynamax Adventures'),
(123, NULL, 2, 'Training Lowlands<br>Max Raid Battles: Fields of Honor, Forest of Focus, Training Lowlands, Workout Sea<br>Dynamax Adventures'),
(123, NULL, 3, 'Obsidian Fieldlands: Grandtree Arena or nearby<br>Coronet Highlands: Primeval Grotto or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(123, NULL, 4, 'Casseroya Lake, North Province Area Two, South Province Area Four, South Province Area Six, Canyon Biome, Savanna Biome<br>Fixed: South Province Area Four, Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles, 5 Star Raid Battles'),
(123, NULL, 5, 'Casseroya Lake, North Province Area Two, South Province Area Four, South Province Area Six, Canyon Biome, Savanna Biome<br>Fixed: South Province Area Four, Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles, 5 Star Raid Battles'),
-- Jynx
(124, NULL, 1, 'Slippery Slope, Frostpoint Field<br>Max Raid Battles: Slippery Slope, Snowslide Slope, Frigid Sea<br>Dynamax Adventures'),
(124, NULL, 2, 'Slippery Slope, Frostpoint Field<br>Max Raid Battles: Slippery Slope, Snowslide Slope, Frigid Sea<br>Dynamax Adventures'),
(124, NULL, 3, NULL),
(124, NULL, 4, NULL),
(124, NULL, 5, NULL),
-- Electabuzz
(125, NULL, 1, 'Giant''s Bed, Old Cemetery, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Dynamax Adventures'),
(125, NULL, 2, 'Giant''s Bed, Old Cemetery, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Dynamax Adventures'),
(125, NULL, 3, 'Coronet Highlands: Cloudcap Pass or nearby<br>Alabaster Icelands: Arena''s Approach, Icebound Falls or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(125, NULL, 4, 'Canyon Biome, Chargestone Cavern, Polar Biome, Savanna Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(125, NULL, 5, 'Canyon Biome, Chargestone Cavern, Polar Biome, Savanna Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Magmar
(126, NULL, 1, 'Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Giant''s Foot, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Ballimere Lake<br>Dynamax Adventures'),
(126, NULL, 2, 'Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Giant''s Foot, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Ballimere Lake<br>Dynamax Adventures'),
(126, NULL, 3, 'Cobalt Coastlands: Firespit Island or nearby<br>Cobalt Coastlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(126, NULL, 4, 'Coastal Biome, Savanna Biome, Torchlit Labyrinth<br>Fixed: Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(126, NULL, 5, 'Coastal Biome, Savanna Biome, Torchlit Labyrinth<br>Fixed: Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Pinsir
(127, NULL, 1, 'Forest of Focus, Challenge Road, Training Lowlands<br>Max Raid Battles: Fields of Honor, Forest of Focus, Training Lowlands, Workout Sea'),
(127, NULL, 2, 'Trade from Pokémon Sword'),
(127, NULL, 3, NULL),
(127, NULL, 4, NULL),
(127, NULL, 5, NULL),
-- Tauros
(128, NULL, 1, 'Training Lowlands<br>Max Raid Battles: Soothing Wetlands, Courageous Cavern, Training Lowlands<br>Dynamax Adventures'),
(128, NULL, 2, 'Training Lowlands<br>Max Raid Battles: Soothing Wetlands, Courageous Cavern, Training Lowlands<br>Dynamax Adventures'),
(128, NULL, 3, NULL),
(128, NULL, 4, 'Savanna Biome<br>Fixed: Savanna Biome'),
(128, NULL, 5, 'Savanna Biome<br>Fixed: Savanna Biome'),
-- Paldean Tauros
(128, 4, 1, NULL),
(128, 4, 2, NULL),
(128, 4, 3, NULL),
(128, 4, 4, 'Asado Desert, East Province Area One, East Province Area Two, East Province Area Three, West Province Area Two<br>Fixed: East Province Area One, East Province Area Two<br>Tera Raid Battles: 4 Star Raid Battles , 5 Star Raid Battles , 6 Star Raid Battles'),
(128, 4, 5, 'Asado Desert, East Province Area One, East Province Area Two, East Province Area Three, West Province Area Two<br>Fixed: East Province Area One, East Province Area Two<br>Tera Raid Battles: 4 Star Raid Battles , 5 Star Raid Battles , 6 Star Raid Battles'),
-- Magikarp
(129, NULL, 1, 'Route 2, Route 4, Route 5, Route 6, Axew''s Eye, Bridge Field, East Lake Axewell, Motostoke, North Lake Miloch, Slumbering Weald, South Lake Miloch, West Lake Axewell, Fields of Honor, Soothing Wetlands, Forest of Focus, Courageous Cavern, Loop Lagoon, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island, Giant''s Bed, Snowslide Slope, Giant''s Foot, Roaring-Sea Caves, Frigid Sea, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dusty Bowl, East Lake Axewell, Giant''s Cap, Lake of Outrage, West Lake Axewell, Workout Sea, Stepping-Stone Sea'),
(129, NULL, 2, 'Route 2, Route 4, Route 5, Route 6, Axew''s Eye, Bridge Field, East Lake Axewell, Motostoke, North Lake Miloch, Slumbering Weald, South Lake Miloch, West Lake Axewell, Fields of Honor, Soothing Wetlands, Forest of Focus, Courageous Cavern, Loop Lagoon, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island, Giant''s Bed, Snowslide Slope, Giant''s Foot, Roaring-Sea Caves, Frigid Sea, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dusty Bowl, East Lake Axewell, Giant''s Cap, Lake of Outrage, West Lake Axewell, Workout Sea, Stepping-Stone Sea'),
(129, NULL, 3, 'Obsidian Fieldlands: Obsidian Falls, Lake Verity or nearby<br>Coronet Highlands: Fabled Spring or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(129, NULL, 4, 'Dalizapa Passage, East Paldean Sea, East Province Area Two, East Province Area Three, North Paldean Sea, North Province Area One, South Paldean Sea, South Province Area One, South Province Area Three, South Province Area Four, South Province Area Five, South Province Area Six, Tagtree Thicket, West Paldean Sea, West Province Area Two, West Province Area Three, Chilling Waterhead, Fellhorn Gorge, Infernal Pass, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Oni''s Maw, Reveler''s Road<br>Tera Raid Battles: 2 Star Raid Battles, 3 Star Raid Battles'),
(129, NULL, 5, 'Dalizapa Passage, East Paldean Sea, East Province Area Two, East Province Area Three, North Paldean Sea, North Province Area One, South Paldean Sea, South Province Area One, South Province Area Three, South Province Area Four, South Province Area Five, South Province Area Six, Tagtree Thicket, West Paldean Sea, West Province Area Two, West Province Area Three, Chilling Waterhead, Fellhorn Gorge, Infernal Pass, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Oni''s Maw, Reveler''s Road<br>Tera Raid Battles: 2 Star Raid Battles, 3 Star Raid Battles'),
-- Gyarados
(130, NULL, 1, 'Route 2, Axew''s Eye, Bridge Field, Dusty Bowl, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Giant''s Seat, Lake of Outrage, West Lake Axewell, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dusty Bowl, East Lake Axewell, Giant''s Cap, Lake of Outrage, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Honeycalm Sea, Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(130, NULL, 2, 'Route 2, Axew''s Eye, Bridge Field, Dusty Bowl, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Giant''s Seat, Lake of Outrage, West Lake Axewell, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dusty Bowl, East Lake Axewell, Giant''s Cap, Lake of Outrage, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Honeycalm Sea, Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(130, NULL, 3, 'Obsidian Fieldlands: Obsidian Falls, Lake Verity or nearby<br>Cobalt Coastlands: Sand''s Reach or nearby<br>Coronet Highlands: Primeval Grotto or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(130, NULL, 4, 'East Paldean Sea, North Paldean Sea, South Paldean Sea, West Paldean Sea, Chilling Waterhead, Fellhorn Gorge, Kitakami Wilds, Oni Mountain<br>Fixed: Casseroya Lake<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(130, NULL, 5, 'East Paldean Sea, North Paldean Sea, South Paldean Sea, West Paldean Sea, Chilling Waterhead, Fellhorn Gorge, Kitakami Wilds, Oni Mountain<br>Fixed: Casseroya Lake<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Lapras
(131, NULL, 1, 'Route 2, Route 9, Lake of Outrage, North Lake Miloch, Frigid Sea<br>Max Raid Battles: Bridge Field, Dusty Bowl, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Lake of Outrage, South Lake Miloch, Stony Wilderness, West Lake Axewell, Giant''s Bed, Frigid Sea'),
(131, NULL, 2, 'Route 2, Route 9, Lake of Outrage, North Lake Miloch, Frigid Sea<br>Max Raid Battles: Bridge Field, Dusty Bowl, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Lake of Outrage, South Lake Miloch, Stony Wilderness, West Lake Axewell, Giant''s Bed, Frigid Sea<br>Gigantamax Raid Battles: Giant''s Seat'),
(131, NULL, 3, NULL),
(131, NULL, 4, 'Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(131, NULL, 5, 'Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Ditto
(132, NULL, 1, 'Lake of Outrage, Workout Sea<br>Max Raid Battles: Stony Wilderness, Workout Sea<br>Dynamax Adventures'),
(132, NULL, 2, 'Lake of Outrage, Workout Sea<br>Max Raid Battles: Stony Wilderness, Workout Sea<br>Dynamax Adventures'),
(132, NULL, 3, NULL),
(132, NULL, 4, 'West Province Area Two, West Province Area Three (May disguise as other Pokémon)<br>Tera Raid Battles: 3 Star Raid Battles , 4 Star Raid Battles , 5 Star Raid Battles , 6 Star Raid Battles'),
(132, NULL, 5, 'West Province Area Two, West Province Area Three (May disguise as other Pokémon)<br>Tera Raid Battles: 3 Star Raid Battles , 4 Star Raid Battles , 5 Star Raid Battles , 6 Star Raid Battles'),
-- Eevee
(133, NULL, 1, 'Route 4, Frostpoint Field, Giant''s Bed, Ballimere Lake<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Ballimere Lake'),
(133, NULL, 2, 'Route 4, Frostpoint Field, Giant''s Bed, Ballimere Lake<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Ballimere Lake'),
(133, NULL, 3, 'Obsidian Fieldlands: Horseshoe Plains, Space-time Distortion in Obsidian Fieldlands or nearby<br>Crimson Mirelands: Space-time Distortion in Crimson Mirelands or nearby<br>Cobalt Coastlands: Crossing Slope, Space-time Distortion in Cobalt Coastlands or nearby<br>Coronet Highlands: Space-time Distortion in Coronet Highlands or nearby<br>Alabaster Icelands: Avalugg''s Legacy, Avalanche Slopes, Space-time Distortion in Alabaster Icelands or nearby'),
(133, NULL, 4, 'South Province Area Two, West Province Area Three<br>Fixed: South Province Area Five<br>Tera Raid Battles: 3 Star Raid Battles , 5 Star Raid Battles'),
(133, NULL, 5, 'South Province Area Two, West Province Area Three<br>Fixed: South Province Area Five<br>Tera Raid Battles: 3 Star Raid Battles , 5 Star Raid Battles'),
-- Vaporeon
(134, NULL, 1, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Giant''s Mirror, Ballimere Lake<br>Dynamax Adventures'),
(134, NULL, 2, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Giant''s Mirror, Ballimere Lake<br>Dynamax Adventures'),
(134, NULL, 3, 'Cobalt Coastlands: Space-time Distortion in Cobalt Coastlands or nearby'),
(134, NULL, 4, 'Casseroya Lake, Glaseado Mountain, North Province Area Two, North Province Area Three, South Province Area Six, Tagtree Thicket<br>Fixed: Casseroya Lake<br>Tera Raid Battles: 6 Star Raid Battles'),
(134, NULL, 5, 'Casseroya Lake, Glaseado Mountain, North Province Area Two, North Province Area Three, South Province Area Six, Tagtree Thicket<br>Fixed: Casseroya Lake<br>Tera Raid Battles: 6 Star Raid Battles'),
-- Jolteon
(135, NULL, 1, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Giant''s Mirror, Ballimere Lake<br>Dynamax Adventures'),
(135, NULL, 2, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Giant''s Mirror, Ballimere Lake<br>Dynamax Adventures'),
(135, NULL, 3, 'Coronet Highlands: Space-time Distortion in Coronet Highlands or nearby'),
(135, NULL, 4, 'Socarrat Trail, West Province Area Three<br>Fixed: West Province Area One<br>Tera Raid Battles: 6 Star Raid Battles'),
(135, NULL, 5, 'Socarrat Trail, West Province Area Three<br>Fixed: West Province Area One<br>Tera Raid Battles: 6 Star Raid Battles'),
-- Flareon
(136, NULL, 1, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Giant''s Bed, Ballimere Lake<br>Dynamax Adventures'),
(136, NULL, 2, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Giant''s Bed, Ballimere Lake<br>Dynamax Adventures'),
(136, NULL, 3, 'Crimson Mirelands: Space-time Distortion in Crimson Mirelands<br>Cobalt Coastlands: Space-time Distortion in Cobalt Coastlands or nearby'),
(136, NULL, 4, 'Dalizapa Passage, North Province Area One, South Province Area Six<br>Fixed: South Province Area Five<br>Tera Raid Battles: 6 Star Raid Battles'),
(136, NULL, 5, 'Dalizapa Passage, North Province Area One, South Province Area Six<br>Fixed: South Province Area Five<br>Tera Raid Battles: 6 Star Raid Battles'),
-- Porygon
(137, NULL, 1, 'Gift from Hyde in Master Dojo<br>Dynamax Adventures'),
(137, NULL, 2, 'Gift from Hyde in Master Dojo<br>Dynamax Adventures'),
(137, NULL, 3, 'Crimson Mirelands: Space-time Distortion in Crimson Mirelands or nearby'),
(137, NULL, 4, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Fixed: Chargestone Cavern<br>Tera Raid Battles: 3 Star Raid Battles'),
(137, NULL, 5, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Fixed: Chargestone Cavern<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Omanyte
(138, NULL, 1, 'Giant''s Foot, Roaring-Sea Caves<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(138, NULL, 2, 'Trade from Pokémon Sword'),
(138, NULL, 3, NULL),
(138, NULL, 4, NULL),
(138, NULL, 5, NULL),
-- Omastar
(139, NULL, 1, 'Roaring-Sea Caves<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(139, NULL, 2, 'Trade from Pokémon Sword'),
(139, NULL, 3, NULL),
(139, NULL, 4, NULL),
(139, NULL, 5, NULL),
-- Kabuto
(140, NULL, 1, 'Trade from Pokémon Shield'),
(140, NULL, 2, 'Giant''s Foot, Roaring-Sea Caves<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(140, NULL, 3, NULL),
(140, NULL, 4, NULL),
(140, NULL, 5, NULL),
-- Kabutops
(141, NULL, 1, 'Trade from Pokémon Shield'),
(141, NULL, 2, 'Roaring-Sea Caves<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(141, NULL, 3, NULL),
(141, NULL, 4, NULL),
(141, NULL, 5, NULL),
-- Aerodactyl
(142, NULL, 1, 'Giant''s Bed<br>Max Raid Battles: Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(142, NULL, 2, 'Giant''s Bed<br>Max Raid Battles: Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(142, NULL, 3, NULL),
(142, NULL, 4, NULL),
(142, NULL, 5, NULL),
-- Snorlax
(143, NULL, 1, 'Motostoke Riverbank, Slippery Slope, Frostpoint Field<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Slippery Slope, Giant''s Bed, Giant''s Foot, Ballimere Lake<br>Gigantamax Raid Battles: Slippery Slope, Giant''s Bed, Giant''s Foot, Ballimere Lake'),
(143, NULL, 2, 'Motostoke Riverbank, Slippery Slope, Frostpoint Field, Giant''s Bed<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Slippery Slope, Giant''s Bed, Giant''s Foot, Ballimere Lake<br>Gigantamax Raid Battles: Slippery Slope, Giant''s Bed, Giant''s Foot, Ballimere Lake'),
(143, NULL, 3, 'Obsidian Fieldlands: Sandgem Flats or nearby<br>Alabaster Icelands: Snowfall Hot Spring or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(143, NULL, 4, 'Fixed: Timeless Woods<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(143, NULL, 5, 'Fixed: Timeless Woods<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Articuno
(144, NULL, 1, 'Dynamax Adventures'),
(144, NULL, 2, 'Dynamax Adventures'),
(144, NULL, 3, NULL),
(144, NULL, 4, 'Glaseado Mountain - Requires Snack from Snacksworth'),
(144, NULL, 5, 'Glaseado Mountain - Requires Snack from Snacksworth'),
-- Galarian Articuno
(144, 2, 1, 'The Crown Tunda'),
(144, 2, 2, 'The Crown Tunda'),
(144, 2, 3, NULL),
(144, 2, 4, 'Transfer from Pokémon HOME'),
(144, 2, 5, 'Transfer from Pokémon HOME'),
-- Zapdos
(145, NULL, 1, 'Dynamax Adventures'),
(145, NULL, 2, 'Dynamax Adventures'),
(145, NULL, 3, NULL),
(145, NULL, 4, 'Poco Path - Requires Snack from Snacksworth'),
(145, NULL, 5, 'Poco Path - Requires Snack from Snacksworth'),
-- Galarian Zapdos
(145, 2, 1, 'Wild Area'),
(145, 2, 2, 'Wild Area'),
(145, 2, 3, NULL),
(145, 2, 4, 'Transfer from Pokémon HOME'),
(145, 2, 5, 'Transfer from Pokémon HOME'),
-- Moltres
(146, NULL, 1, 'Dynamax Adventures'),
(146, NULL, 2, 'Dynamax Adventures'),
(146, NULL, 3, NULL),
(146, NULL, 4, 'Asado Desert - Requires Snack from Snacksworth'),
(146, NULL, 5, 'Asado Desert - Requires Snack from Snacksworth'),
-- Galarian Moltres
(146, 2, 1, 'The Isle of Armor'),
(146, 2, 2, 'The Isle of Armor'),
(146, 2, 3, NULL),
(146, 2, 4, 'Transfer from Pokémon HOME'),
(146, 2, 5, 'Transfer from Pokémon HOME'),
-- Dratini
(147, NULL, 1, 'Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(147, NULL, 2, 'Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(147, NULL, 3, NULL),
(147, NULL, 4, 'Casseroya Lake, North Province Area Two, South Province Area Six<br>Tera Raid Battles: 3 Star Raid Battles'),
(147, NULL, 5, 'Casseroya Lake, North Province Area Two, South Province Area Six<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Dragonair
(148, NULL, 1, 'Ballimere Lake<br>Dynamax Adventures'),
(148, NULL, 2, 'Ballimere Lake<br>Dynamax Adventures'),
(148, NULL, 3, NULL),
(148, NULL, 4, 'Casseroya Lake<br>Fixed: Casseroya Lake, South Province Area Six<br>Tera Raid Battles: 4 Star Raid Battles'),
(148, NULL, 5, 'Casseroya Lake<br>Fixed: Casseroya Lake, South Province Area Six<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Dragonite
(149, NULL, 1, 'Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(149, NULL, 2, 'Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(149, NULL, 3, NULL),
(149, NULL, 4, 'North Province Area Two<br>Fixed: Casseroya Lake, North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(149, NULL, 5, 'North Province Area Two<br>Fixed: Casseroya Lake, North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Mewtwo
(150, NULL, 1, 'Dynamax Adventures'),
(150, NULL, 2, 'Dynamax Adventures'),
(150, NULL, 3, NULL),
(150, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(150, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Mew
(151, NULL, 1, 'Transfer from Pokémon HOME or obtain from event'),
(151, NULL, 2, 'Transfer from Pokémon HOME or obtain from event'),
(151, NULL, 3, NULL),
(151, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(151, NULL, 5, 'Transfer from Pokémon HOME or obtain from event');

COMMIT TRANSACTION;