BEGIN TRANSACTION;

INSERT INTO Pokemon_Location (pokedex_number, region_id, game_id, location_name)
VALUES 

-- Grookey
(810, NULL, 1, 'Gift from Leon in Postwick'),
(810, NULL, 2, 'Gift from Leon in Postwick'),
(810, NULL, 3, NULL),
(810, NULL, 4, 'Coastal Biome'),
(810, NULL, 5, 'Coastal Biome'),
-- Thwackey
(811, NULL, 1, 'Evolve Grookey'),
(811, NULL, 2, 'Evolve Grookey'),
(811, NULL, 3, NULL),
(811, NULL, 4, 'Evolve Grookey'),
(811, NULL, 5, 'Evolve Grookey'),
-- Rillaboom
(812, NULL, 1, 'Evolve Thwackey'),
(812, NULL, 2, 'Evolve Thwackey'),
(812, NULL, 3, NULL),
(812, NULL, 4, 'Evolve Thwackey'),
(812, NULL, 5, 'Evolve Thwackey'),
-- Scorbunny
(813, NULL, 1, 'Gift from Leon in Postwick'),
(813, NULL, 2, 'Gift from Leon in Postwick'),
(813, NULL, 3, NULL),
(813, NULL, 4, 'Polar Biome'),
(813, NULL, 5, 'Polar Biome'),
-- Raboot
(814, NULL, 1, 'Evolve Scorbunny'),
(814, NULL, 2, 'Evolve Scorbunny'),
(814, NULL, 3, NULL),
(814, NULL, 4, 'Evolve Scorbunny'),
(814, NULL, 5, 'Evolve Scorbunny'),
-- Cinderace
(815, NULL, 1, 'Evolve Raboot'),
(815, NULL, 2, 'Evolve Raboot'),
(815, NULL, 3, NULL),
(815, NULL, 4, 'Evolve Raboot'),
(815, NULL, 5, 'Evolve Raboot'),
-- Sobble
(816, NULL, 1, 'Gift from Leon in Postwick'),
(816, NULL, 2, 'Gift from Leon in Postwick'),
(816, NULL, 3, NULL),
(816, NULL, 4, 'Savanna Biome'),
(816, NULL, 5, 'Savanna Biome'),
-- Drizzile
(817, NULL, 1, 'Evolve Sobble'),
(817, NULL, 2, 'Evolve Sobble'),
(817, NULL, 3, NULL),
(817, NULL, 4, 'Evolve Sobble'),
(817, NULL, 5, 'Evolve Sobble'),
-- Inteleon
(818, NULL, 1, 'Evolve Drizzile'),
(818, NULL, 2, 'Evolve Drizzile'),
(818, NULL, 3, NULL),
(818, NULL, 4, 'Evolve Drizzile'),
(818, NULL, 5, 'Evolve Drizzile'),
-- Skwovet
(819, NULL, 1, 'Route 1, Route 2, Route 3, Route 4, Route 5, Dappled Grove, Motostoke Riverbank, North Lake Miloch, Rolling Fields, Slumbering Weald, Watchtower Ruins, Fields of Honor, Soothing Wetlands, Forest of Focus, Loop Lagoon, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea, Slippery Slope, Frostpoint Field, Giant''s Bed, Giant''s Foot, Ballimere Lake<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Slippery Slope, Giant''s Bed, Giant''s Foot, Ballimere Lake'),
(819, NULL, 2, 'Route 1, Route 2, Route 3, Route 4, Route 5, Dappled Grove, Motostoke Riverbank, North Lake Miloch, Rolling Fields, Slumbering Weald, Watchtower Ruins, Fields of Honor, Soothing Wetlands, Forest of Focus, Loop Lagoon, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea, Slippery Slope, Frostpoint Field, Giant''s Bed, Giant''s Foot, Ballimere Lake<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Slippery Slope, Giant''s Bed, Giant''s Foot, Ballimere Lake'),
(819, NULL, 3, NULL),
(819, NULL, 4, 'South Province Area One, South Province Area Two, Kitakami Hall, Mossfell Confluence, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
(819, NULL, 5, 'South Province Area One, South Province Area Two, Kitakami Hall, Mossfell Confluence, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Greedent
(820, NULL, 1, 'Route 6, Route 7, Route 9, Axew''s Eye, Bridge Field, Giant''s Cap, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, Slippery Slope, Frostpoint Field, Giant''s Bed, Giant''s Foot, Ballimere Lake, Dyna Tree Hill<br>Max Raid Battles: Bridge Field, Motostoke Riverbank, Stony Wilderness, Loop Lagoon, Slippery Slope, Giant''s Bed, Giant''s Foot, Ballimere Lake<br>Dynamax Adventures'),
(820, NULL, 2, 'Route 6, Route 7, Route 9, Axew''s Eye, Bridge Field, Giant''s Cap, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, Slippery Slope, Frostpoint Field, Giant''s Bed, Giant''s Foot, Ballimere Lake, Dyna Tree Hill<br>Max Raid Battles: Bridge Field, Motostoke Riverbank, Stony Wilderness, Loop Lagoon, Slippery Slope, Giant''s Bed, Giant''s Foot, Ballimere Lake<br>Dynamax Adventures'),
(820, NULL, 3, NULL),
(820, NULL, 4, 'Dalizapa Passage, North Province Area One, South Province Area Six, Tagtree Thicket, West Province Area Three, Fellhorn Gorge, Kitakami Wilds, Timeless Woods<br>Fixed: Tagtree Thicket, Oni Mountain<br>Tera Raid Battles: 3 Star Raid Battles , 5 Star Raid Battles'),
(820, NULL, 5, 'Dalizapa Passage, North Province Area One, South Province Area Six, Tagtree Thicket, West Province Area Three, Fellhorn Gorge, Kitakami Wilds, Timeless Woods<br>Fixed: Tagtree Thicket, Oni Mountain<br>Tera Raid Battles: 3 Star Raid Battles , 5 Star Raid Battles'),
-- Rookidee
(821, NULL, 1, 'Route 1, Route 2, Route 3, Motostoke Riverbank, Slumbering Weald<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills'),
(821, NULL, 2, 'Route 1, Route 2, Route 3, Motostoke Riverbank, Slumbering Weald<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills'),
(821, NULL, 3, NULL),
(821, NULL, 4, 'East Province Area One, East Province Area Two, East Province Area Three, South Province Area One, South Province Area Three, South Province Area Five<br>Tera Raid Battles: 1 Star Raid Battles'),
(821, NULL, 5, 'East Province Area One, East Province Area Two, East Province Area Three, South Province Area One, South Province Area Three, South Province Area Five<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Corvisquire
(822, NULL, 1, 'Route 3, Giant''s Mirror, Hammerlocke Hills, Motostoke Riverbank, Ballimere Lake<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(822, NULL, 2, 'Route 3, Giant''s Mirror, Hammerlocke Hills, Motostoke Riverbank, Ballimere Lake<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(822, NULL, 3, NULL),
(822, NULL, 4, 'East Province Area One, East Province Area Two, East Province Area Three, South Province Area One, South Province Area Three, South Province Area Five<br>Fixed: East Province Area One, East Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles'),
(822, NULL, 5, 'East Province Area One, East Province Area Two, East Province Area Three, South Province Area One, South Province Area Three, South Province Area Five<br>Fixed: East Province Area One, East Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Corviknight
(823, NULL, 1, 'Route 7, Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, Slumbering Weald, Watchtower Ruins, Ballimere Lake<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Frostpoint Field, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Ballimere Lake, Dyna Tree Hill<br>Gigantamax Raid Battles: Giant''s Cap, Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(823, NULL, 2, 'Route 7, Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, Slumbering Weald, Watchtower Ruins, Ballimere Lake<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Frostpoint Field, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Ballimere Lake, Dyna Tree Hill<br>Gigantamax Raid Battles: Giant''s Cap, Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(823, NULL, 3, NULL),
(823, NULL, 4, 'Area Zero<br>Fixed: North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(823, NULL, 5, 'Area Zero<br>Fixed: North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Blipbug
(824, NULL, 1, 'Route 1, Route 2, Giant''s Cap, Slumbering Weald, Fields of Honor, Challenge Road, Loop Lagoon, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Island<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch, Training Lowlands'),
(824, NULL, 2, 'Route 1, Route 2, Giant''s Cap, Slumbering Weald, Fields of Honor, Challenge Road, Loop Lagoon, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Island<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch, Training Lowlands'),
(824, NULL, 3, NULL),
(824, NULL, 4, NULL),
(824, NULL, 5, NULL),
-- Dottler
(825, NULL, 1, 'Route 5, Giant''s Cap, Giant''s Mirror, Stony Wilderness<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch, Fields of Honor, Forest of Focus, Training Lowlands, Workout Sea'),
(825, NULL, 2, 'Route 5, Giant''s Cap, Giant''s Mirror, Stony Wilderness<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch, Fields of Honor, Forest of Focus, Training Lowlands, Workout Sea'),
(825, NULL, 3, NULL),
(825, NULL, 4, NULL),
(825, NULL, 5, NULL),
-- Orbeetle
(826, NULL, 1, 'Giant''s Cap, Lake of Outrage, Slumbering Weald<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch, Fields of Honor, Forest of Focus, Training Lowlands, Workout Sea<br>Gigantamax Raid Battles: Bridge Field, Dappled Grove, Training Lowlands<br>Dynamax Adventures'),
(826, NULL, 2, 'Giant''s Cap, Lake of Outrage, Slumbering Weald<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch, Fields of Honor, Forest of Focus, Training Lowlands, Workout Sea<br>Gigantamax Raid Battles: Bridge Field, Dappled Grove, Training Lowlands<br>Dynamax Adventures'),
(826, NULL, 3, NULL),
(826, NULL, 4, NULL),
(826, NULL, 5, NULL),
-- Nickit
(827, NULL, 1, 'Route 1, Route 2, Dusty Bowl, Giant''s Mirror, Stony Wilderness<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Stony Wilderness, West Lake Axewell'),
(827, NULL, 2, 'Route 1, Route 2, Dusty Bowl, Giant''s Mirror, Stony Wilderness<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Stony Wilderness, West Lake Axewell'),
(827, NULL, 3, NULL),
(827, NULL, 4, NULL),
(827, NULL, 5, NULL),
-- Thievul
(828, NULL, 1, 'Route 7, Route 9, Bridge Field, Hammerlocke Hills, South Lake Miloch, Stony Wilderness<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Stony Wilderness, West Lake Axewell, Soothing Wetlands, Challenge Road, Workout Sea, Honeycalm Sea, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea<br>Dynamax Adventures'),
(828, NULL, 2, 'Route 7, Route 9, Bridge Field, Hammerlocke Hills, South Lake Miloch, Stony Wilderness<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Stony Wilderness, West Lake Axewell, Soothing Wetlands, Challenge Road, Workout Sea, Honeycalm Sea, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea<br>Dynamax Adventures'),
(828, NULL, 3, NULL),
(828, NULL, 4, NULL),
(828, NULL, 5, NULL),
-- Gossifleur
(829, NULL, 1, 'Route 2, Route 3, Motostoke Riverbank, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness, Slippery Slope, Giant''s Bed, Crown Shrine, Giant''s Foot, Ballimere Lake'),
(829, NULL, 2, 'Route 2, Route 3, Motostoke Riverbank, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness, Slippery Slope, Giant''s Bed, Crown Shrine, Giant''s Foot, Ballimere Lake'),
(829, NULL, 3, NULL),
(829, NULL, 4, NULL),
(829, NULL, 5, NULL),
-- Eldegoss
(830, NULL, 1, 'Route 5, Dusty Bowl, Giant''s Cap, Motostoke Riverbank, Stony Wilderness, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness, Slippery Slope, Giant''s Bed, Crown Shrine, Giant''s Foot, Ballimere Lake<br>Dynamax Adventures'),
(830, NULL, 2, 'Route 5, Dusty Bowl, Giant''s Cap, Motostoke Riverbank, Stony Wilderness, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness, Slippery Slope, Giant''s Bed, Crown Shrine, Giant''s Foot, Ballimere Lake<br>Dynamax Adventures'),
(830, NULL, 3, NULL),
(830, NULL, 4, NULL),
(830, NULL, 5, NULL),
-- Wooloo
(831, NULL, 1, 'Route 1, Route 4, Motostoke Riverbank, Slippery Slope, Frostpoint Field, Giant''s Bed, Snowslide Slope, Three-Point Pass<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Slippery Slope, Giant''s Bed, Giant''s Foot, Ballimere Lake'),
(831, NULL, 2, 'Route 1, Route 4, Motostoke Riverbank, Slippery Slope, Frostpoint Field, Giant''s Bed, Snowslide Slope, Three-Point Pass<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Slippery Slope, Giant''s Bed, Giant''s Foot, Ballimere Lake'),
(831, NULL, 3, NULL),
(831, NULL, 4, NULL),
(831, NULL, 5, NULL),
-- Dubwool
(832, NULL, 1, 'Dusty Bowl, Hammerlocke Hills, Motostoke Riverbank, Slippery Slope, Frostpoint Field, Giant''s Bed, Snowslide Slope, Three-Point Pass<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea, Slippery Slope, Giant''s Bed, Giant''s Foot, Ballimere Lake<br>Dynamax Adventures'),
(832, NULL, 2, 'Dusty Bowl, Hammerlocke Hills, Motostoke Riverbank, Slippery Slope, Frostpoint Field, Giant''s Bed, Snowslide Slope, Three-Point Pass<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea, Slippery Slope, Giant''s Bed, Giant''s Foot, Ballimere Lake<br>Dynamax Adventures'),
(832, NULL, 3, NULL),
(832, NULL, 4, NULL),
(832, NULL, 5, NULL),
-- Chewtle
(833, NULL, 1, 'Route 2, Route 4, Route 5, Galar Mine No. 2, Giant''s Cap, Giant''s Mirror, Hulbury, Motostoke, Motostoke Outskirts, Motostoke Riverbank, Courageous Cavern<br>Max Raid Battles: Bridge Field, Dusty Bowl, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Lake of Outrage, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern'),
(833, NULL, 2, 'Route 2, Route 4, Route 5, Galar Mine No. 2, Giant''s Cap, Giant''s Mirror, Hulbury, Motostoke, Motostoke Outskirts, Motostoke Riverbank, Courageous Cavern<br>Max Raid Battles: Bridge Field, Dusty Bowl, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Lake of Outrage, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern'),
(833, NULL, 3, NULL),
(833, NULL, 4, 'East Province Area Two, East Province Area Three, South Province Area One, South Province Area Two, South Province Area Four, South Province Area Five, West Province Area One, West Province Area Two, Fellhorn Gorge, Kitakami Wilds, Mossfell Confluence, Timeless Woods<br>Fixed: Fellhorn Gorge<br>Tera Raid Battles: 1 Star Raid Battles'),
(833, NULL, 5, 'East Province Area Two, East Province Area Three, South Province Area One, South Province Area Two, South Province Area Four, South Province Area Five, West Province Area One, West Province Area Two, Fellhorn Gorge, Kitakami Wilds, Mossfell Confluence, Timeless Woods<br>Fixed: Fellhorn Gorge<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Drednaw
(834, NULL, 1, 'Route 2, Route 6, Bridge Field, Dusty Bowl, Galar Mine No. 2, Giant''s Cap, Giant''s Mirror, Lake of Outrage, West Lake Axewell, Fields of Honor, Soothing Wetlands, Challenge Beach, Courageous Cavern, Loop Lagoon<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Lake of Outrage, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern<br>Gigantamax Raid Battles: Giant''s Cap, Courageous Cavern<br>Dynamax Adventures'),
(834, NULL, 2, 'Route 2, Route 6, Bridge Field, Dusty Bowl, Galar Mine No. 2, Giant''s Cap, Giant''s Mirror, Lake of Outrage, West Lake Axewell, Fields of Honor, Soothing Wetlands, Challenge Beach, Courageous Cavern, Loop Lagoon<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Lake of Outrage, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern<br>Gigantamax Raid Battles: Giant''s Cap, Courageous Cavern<br>Dynamax Adventures'),
(834, NULL, 3, NULL),
(834, NULL, 4, 'Casseroya Lake, East Province Area Two, East Province Area Three, Glaseado Mountain, South Province Area Five, South Province Area Six, West Province Area Two, Fellhorn Gorge, Kitakami Wilds, Timeless Woods<br>Fixed: Casseroya Lake, Fellhorn Gorge<br>Tera Raid Battles: 4 Star Raid Battles'),
(834, NULL, 5, 'Casseroya Lake, East Province Area Two, East Province Area Three, Glaseado Mountain, South Province Area Five, South Province Area Six, West Province Area Two, Fellhorn Gorge, Kitakami Wilds, Timeless Woods<br>Fixed: Casseroya Lake, Fellhorn Gorge<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Yamper
(835, NULL, 1, 'Route 2, Route 4, Giant''s Mirror, Motostoke Riverbank, Stony Wilderness, Ballimere Lake<br>Max Raid Battles: Giant''s Mirror, Lake of Outrage, Motostoke Riverbank'),
(835, NULL, 2, 'Route 2, Route 4, Giant''s Mirror, Motostoke Riverbank, Stony Wilderness, Ballimere Lake<br>Max Raid Battles: Giant''s Mirror, Lake of Outrage, Motostoke Riverbank'),
(835, NULL, 3, NULL),
(835, NULL, 4, NULL),
(835, NULL, 5, NULL),
-- Boltund
(836, NULL, 1, 'Dusty Bowl, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, Ballimere Lake<br>Max Raid Battles: Giant''s Mirror, Lake of Outrage, Motostoke Riverbank, Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea, Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Dynamax Adventures'),
(836, NULL, 2, 'Dusty Bowl, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, Ballimere Lake<br>Max Raid Battles: Giant''s Mirror, Lake of Outrage, Motostoke Riverbank, Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea, Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Dynamax Adventures'),
(836, NULL, 3, NULL),
(836, NULL, 4, NULL),
(836, NULL, 5, NULL),
-- Rolycoly
(837, NULL, 1, 'Route 3, Galar Mine, Giant''s Cap, Motostoke Riverbank<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Rolling Fields, Stony Wilderness'),
(837, NULL, 2, 'Route 3, Galar Mine, Giant''s Cap, Motostoke Riverbank<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Rolling Fields, Stony Wilderness, Slippery Slope, Giant''s Bed, Snowslide Slope, Ballimere Lake'),
(837, NULL, 3, NULL),
(837, NULL, 4, 'East Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
(837, NULL, 5, 'East Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Carkol
(838, NULL, 1, 'Bridge Field, Galar Mine, Giant''s Cap, Stony Wilderness, Ballimere Lake, Lakeside Cave<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Giant''s Seat, Rolling Fields, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(838, NULL, 2, 'Bridge Field, Galar Mine, Giant''s Cap, Stony Wilderness, Ballimere Lake, Lakeside Cave<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Giant''s Seat, Rolling Fields, Stony Wilderness, Slippery Slope, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(838, NULL, 3, NULL),
(838, NULL, 4, 'East Province Area Three<br>Fixed: East Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles'),
(838, NULL, 5, 'East Province Area Three<br>Fixed: East Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Coalossal
(839, NULL, 1, 'Dusty Bowl, Giant''s Cap, Lake of Outrage, Ballimere Lake, Lakeside Cave<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Rolling Fields, Stony Wilderness, Slippery Slope, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Gigantamax Raid Battles: Giant''s Seat, Slippery Slope, Giant''s Bed, Snowslide Slope, Ballimere Lake<br>Dynamax Adventures'),
(839, NULL, 2, 'Dusty Bowl, Giant''s Cap, Lake of Outrage, Ballimere Lake, Lakeside Cave<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Rolling Fields, Stony Wilderness, Slippery Slope, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Gigantamax Raid Battles: Giant''s Seat, Slippery Slope, Giant''s Bed, Snowslide Slope, Ballimere Lake<br>Dynamax Adventures'),
(839, NULL, 3, NULL),
(839, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles'),
(839, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles'),
-- Applin
(840, NULL, 1, 'Route 5, Dusty Bowl, Giant''s Mirror, Stony Wilderness, Fields of Honor, Soothing Wetlands, Forest of Focus, Loop Lagoon, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea<br>Max Raid Battles: Axew''s Eye, Bridge Field, Dappled Grove, Giant''s Mirror, Rolling Fields, Stony Wilderness, Loop Lagoon, Workout Sea, Honeycalm Sea'),
(840, NULL, 2, 'Route 5, Dusty Bowl, Giant''s Mirror, Stony Wilderness, Fields of Honor, Soothing Wetlands, Forest of Focus, Loop Lagoon, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea<br>Max Raid Battles: Axew''s Eye, Bridge Field, Dappled Grove, Giant''s Mirror, Rolling Fields, Stony Wilderness, Loop Lagoon, Workout Sea, Honeycalm Sea'),
(840, NULL, 3, NULL),
(840, NULL, 4, 'East Province Area One, East Province Area Two, South Province Area One, South Province Area Two, Tagtree Thicket, West Province Area Three, Apple Hills, Kitakami Road, Mossfell Confluence<br>Fixed: East Province Area One, Mossfell Confluence, Apple Hills<br>Tera Raid Battles: 1 Star Raid Battles, 2 Star Raid Battles, 3 Star Raid Battles'),
(840, NULL, 5, 'East Province Area One, East Province Area Two, South Province Area One, South Province Area Two, Tagtree Thicket, West Province Area Three, Apple Hills, Kitakami Road, Mossfell Confluence<br>Fixed: East Province Area One, Mossfell Confluence, Apple Hills<br>Tera Raid Battles: 1 Star Raid Battles, 2 Star Raid Battles, 3 Star Raid Battles'),
-- Flapple
(841, NULL, 1, 'Stepping-Stone Sea<br>Max Raid Battles: Axew''s Eye, Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness, Loop Lagoon, Workout Sea, Honeycalm Sea<br>Gigantamax Raid Battles: Dappled Grove, Loop Lagoon'),
(841, NULL, 2, 'Trade from Pokémon Sword'),
(841, NULL, 3, NULL),
(841, NULL, 4, 'Mossfell Confluence<br>Tera Raid Battles: 5 Star Raid Battles'),
(841, NULL, 5, 'Mossfell Confluence<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Appletun
(842, NULL, 1, 'Trade from Pokémon Shield'),
(842, NULL, 2, 'Stepping-Stone Sea<br>Max Raid Battles: Axew''s Eye, Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness, Loop Lagoon, Workout Sea, Honeycalm Sea<br>Gigantamax Raid Battles: Dappled Grove, Loop Lagoon'),
(842, NULL, 3, NULL),
(842, NULL, 4, 'Mossfell Confluence<br>Tera Raid Battles: 5 Star Raid Battles'),
(842, NULL, 5, 'Mossfell Confluence<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Silicobra
(843, NULL, 1, 'Route 6, Forest of Focus, Challenge Road, Training Lowlands, Potbottom Desert<br>Max Raid Battles: Dusty Bowl, Potbottom Desert'),
(843, NULL, 2, 'Route 6, Forest of Focus, Challenge Road, Training Lowlands, Potbottom Desert<br>Max Raid Battles: Dusty Bowl, Potbottom Desert'),
(843, NULL, 3, NULL),
(843, NULL, 4, 'Asado Desert, East Province Area Three<br>Tera Raid Battles: 1 Star Raid Battles'),
(843, NULL, 5, 'Asado Desert, East Province Area Three<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Sandaconda
(844, NULL, 1, 'Route 8, Lake of Outrage, Potbottom Desert<br>Max Raid Battles: Dusty Bowl, Challenge Beach, Courageous Cavern, Potbottom Desert, Stepping-Stone Sea<br>Gigantamax Raid Battles: Dusty Bowl, Potbottom Desert<br>Dynamax Adventures'),
(844, NULL, 2, 'Route 8, Lake of Outrage, Potbottom Desert<br>Max Raid Battles: Dusty Bowl, Challenge Beach, Courageous Cavern, Potbottom Desert, Stepping-Stone Sea<br>Gigantamax Raid Battles: Dusty Bowl, Potbottom Desert<br>Dynamax Adventures'),
(844, NULL, 3, NULL),
(844, NULL, 4, 'Fixed: Asado Desert<br>Tera Raid Battles: 4 Star Raid Battles'),
(844, NULL, 5, 'Fixed: Asado Desert<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Cramorant
(845, NULL, 1, 'Route 9, Axew''s Eye, Bridge Field, Lake of Outrage, Stony Wilderness, Forest of Focus, Challenge Beach, Training Lowlands<br>Max Raid Battles: Giant''s Cap, Hammerlocke Hills, Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern<br>Dynamax Adventures'),
(845, NULL, 2, 'Route 9, Axew''s Eye, Bridge Field, Lake of Outrage, Stony Wilderness, Forest of Focus, Challenge Beach, Training Lowlands<br>Max Raid Battles: Giant''s Cap, Hammerlocke Hills, Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern<br>Dynamax Adventures'),
(845, NULL, 3, NULL),
(845, NULL, 4, 'Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods<br>Tera Raid Battles: 4 Star Raid Battles'),
(845, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Arrokuda
(846, NULL, 1, 'Route 2, Hulbury, Motostoke Riverbank, Forest of Focus, Training Lowlands<br>Max Raid Battles: Bridge Field, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Lake of Outrage, North Lake Miloch, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern'),
(846, NULL, 2, 'Route 2, Hulbury, Motostoke Riverbank, Forest of Focus, Training Lowlands<br>Max Raid Battles: Bridge Field, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Lake of Outrage, North Lake Miloch, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern'),
(846, NULL, 3, NULL),
(846, NULL, 4, 'East Paldean Sea, East Province Area Two, East Province Area Three, South Paldean Sea, South Province Area One, South Province Area Five, West Paldean Sea, West Province Area One, West Province Area Two, Chilling Waterhead, Crystal Pool, Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Oni''s Maw<br>Tera Raid Battles: 2 Star Raid Battles'),
(846, NULL, 5, 'East Paldean Sea, East Province Area Two, East Province Area Three, South Paldean Sea, South Province Area One, South Province Area Five, West Paldean Sea, West Province Area One, West Province Area Two, Chilling Waterhead, Crystal Pool, Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Oni''s Maw<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Barraskewda
(847, NULL, 1, 'Route 2, Dusty Bowl, Lake of Outrage, Motostoke Riverbank, Challenge Beach, Training Lowlands<br>Max Raid Battles: Bridge Field, Lake of Outrage, North Lake Miloch, South Lake Miloch, Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern<br>Dynamax Adventures'),
(847, NULL, 2, 'Route 2, Dusty Bowl, Lake of Outrage, Motostoke Riverbank, Challenge Beach, Training Lowlands<br>Max Raid Battles: Bridge Field, Lake of Outrage, North Lake Miloch, South Lake Miloch, Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern<br>Dynamax Adventures'),
(847, NULL, 3, NULL),
(847, NULL, 4, 'East Paldean Sea, East Province Area Two, East Province Area Three, Glaseado Mountain, North Paldean Sea, North Province Area One, North Province Area Three, South Paldean Sea, West Paldean Sea, West Province Area Two, Chilling Waterhead, Fellhorn Gorge, Oni Mountain<br>Fixed: Fellhorn Gorge<br>Tera Raid Battles: 4 Star Raid Battles'),
(847, NULL, 5, 'East Paldean Sea, East Province Area Two, East Province Area Three, Glaseado Mountain, North Paldean Sea, North Province Area One, North Province Area Three, South Paldean Sea, West Paldean Sea, West Province Area Two, Chilling Waterhead, Fellhorn Gorge, Oni Mountain<br>Fixed: Fellhorn Gorge<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Toxel
(848, NULL, 1, 'Route 7, Bridge Field, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, North Lake Miloch'),
(848, NULL, 2, 'Route 7, Bridge Field, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, North Lake Miloch'),
(848, NULL, 3, NULL),
(848, NULL, 4, 'South Province Area One, South Province Area Two, South Province Area Four<br>Fixed: South Province Area Four<br>Tera Raid Battles: 1 Star Raid Battles'),
(848, NULL, 5, 'South Province Area One, South Province Area Two, South Province Area Four<br>Fixed: South Province Area Four<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Toxtricity
(849, NULL, 1, 'Max Raid Battles: East Lake Axewell, Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Gigantamax Raid Battles: Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Dynamax Adventures'),
(849, NULL, 2, 'Max Raid Battles: East Lake Axewell, Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Gigantamax Raid Battles: Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Dynamax Adventures'),
(849, NULL, 3, NULL),
(849, NULL, 4, 'Alfornada Cavern<br>Tera Raid Battles: 5 Star Raid Battles'),
(849, NULL, 5, 'Alfornada Cavern<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Sizzlipede
(850, NULL, 1, 'Route 3, Motostoke, Giant''s Foot<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Giant''s Bed, Snowslide Slope, Ballimere Lake'),
(850, NULL, 2, 'Route 3, Motostoke, Giant''s Foot<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Giant''s Bed, Snowslide Slope, Ballimere Lake'),
(850, NULL, 3, NULL),
(850, NULL, 4, NULL),
(850, NULL, 5, NULL),
-- Centiskorch
(851, NULL, 1, 'Giant''s Foot<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Giant''s Bed, Snowslide Slope, Ballimere Lake<br>Gigantamax Raid Battles: Stony Wilderness, Giant''s Bed, Snowslide Slope, Ballimere Lake<br>Dynamax Adventures'),
(851, NULL, 2, 'Giant''s Foot<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Giant''s Bed, Snowslide Slope, Ballimere Lake<br>Gigantamax Raid Battles: Stony Wilderness, Giant''s Bed, Snowslide Slope, Ballimere Lake<br>Dynamax Adventures'),
(851, NULL, 3, NULL),
(851, NULL, 4, NULL),
(851, NULL, 5, NULL),
-- Clobbopus
(852, NULL, 1, 'Route 9, Courageous Cavern, Loop Lagoon<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea'),
(852, NULL, 2, 'Route 9, Courageous Cavern, Loop Lagoon<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea'),
(852, NULL, 3, NULL),
(852, NULL, 4, NULL),
(852, NULL, 5, NULL),
-- Grapploct
(853, NULL, 1, 'Route 9, Lake of Outrage, West Lake Axewell, Loop Lagoon<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea<br>Dynamax Adventures'),
(853, NULL, 2, 'Route 9, Lake of Outrage, West Lake Axewell, Loop Lagoon<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea<br>Dynamax Adventures'),
(853, NULL, 3, NULL),
(853, NULL, 4, NULL),
(853, NULL, 5, NULL),
-- Sinistea
(854, NULL, 1, 'Glimwood Tangle, Old Cemetery<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins, Giant''s Bed, Old Cemetery, Ballimere Lake'),
(854, NULL, 2, 'Glimwood Tangle, Old Cemetery<br>Max Raid Battles: Giant''s Mirror, South Lake Miloch, Stony Wilderness, Watchtower Ruins, Giant''s Bed, Old Cemetery, Ballimere Lake'),
(854, NULL, 3, NULL),
(854, NULL, 4, 'East Province Area Three, South Province Area Six, Canyon Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
(854, NULL, 5, 'East Province Area Three, South Province Area Six, Canyon Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Polteageist
(855, NULL, 1, 'Old Cemetery<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins, Giant''s Bed, Old Cemetery, Ballimere Lake<br>Dynamax Adventures'),
(855, NULL, 2, 'Old Cemetery<br>Max Raid Battles: Giant''s Mirror, South Lake Miloch, Stony Wilderness, Watchtower Ruins, Giant''s Bed, Old Cemetery, Ballimere Lake<br>Dynamax Adventures'),
(855, NULL, 3, NULL),
(855, NULL, 4, 'Tera Raid Battles: 4 Star Raid Battles , 5 Star Raid Battles'),
(855, NULL, 5, 'Tera Raid Battles: 4 Star Raid Battles , 5 Star Raid Battles'),
-- Hatenna
(856, NULL, 1, 'Hammerlocke Hills, Motostoke Outskirts, Stony Wilderness, Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Watchtower Ruins, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(856, NULL, 2, 'Hammerlocke Hills, Motostoke Outskirts, Stony Wilderness, Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Watchtower Ruins, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(856, NULL, 3, NULL),
(856, NULL, 4, 'South Province Area One, South Province Area Two, South Province Area Four, West Province Area Three, Apple Hills, Crystal Pool, Infernal Pass, Kitakami Wilds, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Timeless Woods<br>Fixed: Reveler''s Road, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
(856, NULL, 5, 'South Province Area One, South Province Area Two, South Province Area Four, West Province Area Three, Apple Hills, Crystal Pool, Infernal Pass, Kitakami Wilds, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Timeless Woods<br>Fixed: Reveler''s Road, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Hattrem
(857, NULL, 1, 'Dusty Bowl, Glimwood Tangle, Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Watchtower Ruins, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(857, NULL, 2, 'Dusty Bowl, Glimwood Tangle, Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Watchtower Ruins, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(857, NULL, 3, NULL),
(857, NULL, 4, 'Glaseado Mountain, South Province Area Six, Tagtree Thicket, Kitakami Wilds, Timeless Woods<br>Fixed: Kitakami Wilds<br>Tera Raid Battles: 3 Star Raid Battles'),
(857, NULL, 5, 'Glaseado Mountain, South Province Area Six, Tagtree Thicket, Kitakami Wilds, Timeless Woods<br>Fixed: Kitakami Wilds<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Hatterene
(858, NULL, 1, 'Lake of Outrage, Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Watchtower Ruins, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Gigantamax Raid Battles: Bridge Field, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(858, NULL, 2, 'Lake of Outrage, Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Watchtower Ruins, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Gigantamax Raid Battles: Bridge Field, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(858, NULL, 3, NULL),
(858, NULL, 4, 'Timeless Woods<br>Fixed: Timeless Woods<br>Tera Raid Battles: 5 Star Raid Battles'),
(858, NULL, 5, 'Timeless Woods<br>Fixed: Timeless Woods<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Impidimp
(859, NULL, 1, 'Giant''s Mirror, Glimwood Tangle, Hammerlocke Hills, Motostoke Outskirts, Stony Wilderness, Slippery Slope<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage, Rolling Fields, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea'),
(859, NULL, 2, 'Giant''s Mirror, Glimwood Tangle, Hammerlocke Hills, Motostoke Outskirts, Stony Wilderness, Slippery Slope<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage, Rolling Fields, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea'),
(859, NULL, 3, NULL),
(859, NULL, 4, 'Tagtree Thicket, Kitakami Wilds, Timeless Woods<br>Tera Raid Battles: 2 Star Raid Battles'),
(859, NULL, 5, 'Tagtree Thicket, Kitakami Wilds, Timeless Woods<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Morgrem
(860, NULL, 1, 'Glimwood Tangle, Giant''s Bed, Snowslide Slope, Giant''s Foot<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage, Rolling Fields, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea'),
(860, NULL, 2, 'Glimwood Tangle, Giant''s Bed, Snowslide Slope, Giant''s Foot<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage, Rolling Fields, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea'),
(860, NULL, 3, NULL),
(860, NULL, 4, 'Tagtree Thicket, Kitakami Wilds, Timeless Woods<br>Tera Raid Battles: 3 Star Raid Battles'),
(860, NULL, 5, 'Tagtree Thicket, Kitakami Wilds, Timeless Woods<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Grimmsnarl
(861, NULL, 1, 'Lake of Outrage, Slippery Slope, Giant''s Bed, Snowslide Slope<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage, Rolling Fields, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea<br>Gigantamax Raid Battles: Dusty Bowl, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea<br>Dynamax Adventures'),
(861, NULL, 2, 'Lake of Outrage, Slippery Slope, Giant''s Bed, Snowslide Slope<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage, Rolling Fields, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea<br>Gigantamax Raid Battles: Dusty Bowl, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea<br>Dynamax Adventures'),
(861, NULL, 3, NULL),
(861, NULL, 4, 'Timeless Woods<br>Fixed: Timeless Woods<br>Tera Raid Battles: 5 Star Raid Battles'),
(861, NULL, 5, 'Timeless Woods<br>Fixed: Timeless Woods<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Obstagoon
(862, NULL, 1, 'Route 2, Lake of Outrage, Giant''s Bed, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Stony Wilderness, West Lake Axewell, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea<br>Dynamax Adventures'),
(862, NULL, 2, 'Route 2, Lake of Outrage, Giant''s Bed, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Stony Wilderness, West Lake Axewell, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea<br>Dynamax Adventures'),
(862, NULL, 3, NULL),
(862, NULL, 4, NULL),
(862, NULL, 5, NULL),
-- Perrserker
(863, NULL, 1, 'Route 7, Route 9, Giant''s Mirror, Lake of Outrage<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Stony Wilderness, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea<br>Dynamax Adventures'),
(863, NULL, 2, 'Route 7, Route 9, Giant''s Mirror, Lake of Outrage<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Stony Wilderness, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea<br>Dynamax Adventures'),
(863, NULL, 3, NULL),
(863, NULL, 4, 'Evolve Galarian Meowth'),
(863, NULL, 5, 'Evolve Galarian Meowth'),
-- Cursola
(864, NULL, 1, 'Trade from Pokémon Shield'),
(864, NULL, 2, 'Max Raid Battles: Giant''s Mirror, South Lake Miloch, Stony Wilderness, Watchtower Ruins, Challenge Beach, Courageous Cavern, Stepping-Stone Sea, Slippery Slope, Old Cemetery, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(864, NULL, 3, NULL),
(864, NULL, 4, NULL),
(864, NULL, 5, NULL),
-- Sirfetch'd
(865, NULL, 1, 'Max Raid Battles: Dusty Bowl, North Lake Miloch, Stony Wilderness, Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(865, NULL, 2, 'Trade from Pokémon Sword'),
(865, NULL, 3, NULL),
(865, NULL, 4, NULL),
(865, NULL, 5, NULL),
-- Mr. Rime
(866, NULL, 1, 'Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Watchtower Ruins, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake'),
(866, NULL, 2, 'Max Raid Battles: Dusty Bowl, Giant''s Cap, Giant''s Seat, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Watchtower Ruins, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake'),
(866, NULL, 3, NULL),
(866, NULL, 4, NULL),
(866, NULL, 5, NULL),
-- Runerigus
(867, NULL, 1, 'Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Rolling Fields, South Lake Miloch, Stony Wilderness, Watchtower Ruins'),
(867, NULL, 2, 'Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Rolling Fields, South Lake Miloch, Stony Wilderness, Watchtower Ruins'),
(867, NULL, 3, NULL),
(867, NULL, 4, NULL),
(867, NULL, 5, NULL),
-- Milcery
(868, NULL, 1, 'Route 4, Bridge Field, Giant''s Mirror<br>Max Raid Battles: Bridge Field, Lake of Outrage'),
(868, NULL, 2, 'Route 4, Bridge Field, Giant''s Mirror<br>Max Raid Battles: Bridge Field, Lake of Outrage'),
(868, NULL, 3, NULL),
(868, NULL, 4, 'Polar Biome<br>Fixed: Coastal Biome, Polar Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
(868, NULL, 5, 'Polar Biome<br>Fixed: Coastal Biome, Polar Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Alcremie
(869, NULL, 1, 'Max Raid Battles: Bridge Field, Lake of Outrage<br>Gigantamax Raid Battles: Bridge Field, Giant''s Bed, Old Cemetery, Ballimere Lake<br>Dynamax Adventures'),
(869, NULL, 2, 'Max Raid Battles: Bridge Field, Lake of Outrage<br>Gigantamax Raid Battles: Bridge Field, Giant''s Bed, Old Cemetery, Ballimere Lake<br>Dynamax Adventures'),
(869, NULL, 3, NULL),
(869, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(869, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Falinks
(870, NULL, 1, 'Route 8, Lake of Outrage<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Rolling Fields, Stony Wilderness, Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(870, NULL, 2, 'Route 8, Lake of Outrage<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Rolling Fields, Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(870, NULL, 3, NULL),
(870, NULL, 4, 'North Province Area Two, West Province Area One, West Province Area Two<br>Fixed: East Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles , 5 Star Raid Battles'),
(870, NULL, 5, 'North Province Area Two, West Province Area One, West Province Area Two<br>Fixed: East Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles , 5 Star Raid Battles'),
-- Pincurchin
(871, NULL, 1, 'Route 9, Courageous Cavern, Loop Lagoon, Frigid Sea<br>Max Raid Battles: Giant''s Mirror, Lake of Outrage, Motostoke Riverbank, Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea, Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(871, NULL, 2, 'Route 9, Courageous Cavern, Loop Lagoon, Frigid Sea<br>Max Raid Battles: Giant''s Mirror, Lake of Outrage, Motostoke Riverbank, Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea, Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(871, NULL, 3, NULL),
(871, NULL, 4, 'East Province Area Two, North Province Area One, North Province Area Three, West Province Area Two<br>Fixed: Glaseado Mountain, North Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles , 5 Star Raid Battles , 6 Star Raid Battles'),
(871, NULL, 5, 'East Province Area Two, North Province Area One, North Province Area Three, West Province Area Two<br>Fixed: Glaseado Mountain, North Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles , 5 Star Raid Battles , 6 Star Raid Battles'),
-- Snom
(872, NULL, 1, 'Route 8, Route 10, Lake of Outrage, Slippery Slope, Snowslide Slope, Path to the Peak<br>Max Raid Battles: Giant''s Cap, Hammerlocke Hills, Stony Wilderness'),
(872, NULL, 2, 'Route 8, Route 10, Lake of Outrage, Slippery Slope, Snowslide Slope, Path to the Peak<br>Max Raid Battles: Giant''s Cap, Hammerlocke Hills, Stony Wilderness'),
(872, NULL, 3, NULL),
(872, NULL, 4, 'Dalizapa Passage, Glaseado Mountain<br>Tera Raid Battles: 1 Star Raid Battles'),
(872, NULL, 5, 'Dalizapa Passage, Glaseado Mountain<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Frosmoth
(873, NULL, 1, 'Path to the Peak<br>Max Raid Battles: Giant''s Cap, Hammerlocke Hills, Stony Wilderness, Slippery Slope, Snowslide Slope, Frigid Sea<br>Dynamax Adventures'),
(873, NULL, 2, 'Path to the Peak<br>Max Raid Battles: Giant''s Cap, Hammerlocke Hills, Stony Wilderness, Slippery Slope, Snowslide Slope, Frigid Sea<br>Dynamax Adventures'),
(873, NULL, 3, NULL),
(873, NULL, 4, 'Glaseado Mountain, North Province Area One<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
(873, NULL, 5, 'Glaseado Mountain, North Province Area One<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
-- Stonjourner
(874, NULL, 1, 'Route 10, Lake of Outrage, Giant''s Bed, Giant''s Foot<br>Max Raid Battles: Giant''s Seat, Rolling Fields, Stony Wilderness, Slippery Slope, Giant''s Bed, Snowslide Slope, Ballimere Lake'),
(874, NULL, 2, 'Trade from Pokémon Sword'),
(874, NULL, 3, NULL),
(874, NULL, 4, 'Asado Desert<br>Tera Raid Battles: 4 Star Raid Battles'),
(874, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Eiscue
(875, NULL, 1, 'Trade from Pokémon Shield'),
(875, NULL, 2, 'Route 10, Lake of Outrage, Frigid Sea<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Giant''s Seat, Hammerlocke Hills, Stony Wilderness'),
(875, NULL, 3, NULL),
(875, NULL, 4, 'Trade from Pokémon Violet'),
(875, NULL, 5, 'North Paldean Sea, North Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Indeedee
(876, NULL, 1, 'Glimwood Tangle, Lake of Outrage, Ballimere Lake<br>Max Raid Battles: Bridge Field, East Lake Axewell, Hammerlocke Hills, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake<br>Dynamax Adventures'),
(876, NULL, 2, 'Glimwood Tangle, Lake of Outrage, Ballimere Lake<br>Max Raid Battles: Bridge Field, East Lake Axewell, Hammerlocke Hills, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake<br>Dynamax Adventures'),
(876, NULL, 3, NULL),
(876, NULL, 4, 'North Province Area One, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods<br>Tera Raid Battles: 3 Star Raid Battles, 5 Star Raid Battles'),
(876, NULL, 5, 'North Province Area One, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods<br>Tera Raid Battles: 3 Star Raid Battles, 5 Star Raid Battles'),
-- Morpeko
(877, NULL, 1, 'Route 7, Route 9, Lake of Outrage, Challenge Beach, Ballimere Lake<br>Max Raid Battles: Giant''s Mirror, Lake of Outrage, Motostoke Riverbank, Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea<br>Dynamax Adventures'),
(877, NULL, 2, 'Route 7, Route 9, Lake of Outrage, Challenge Beach, Ballimere Lake<br>Max Raid Battles: Giant''s Mirror, Lake of Outrage, Motostoke Riverbank, Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea<br>Dynamax Adventures'),
(877, NULL, 3, NULL),
(877, NULL, 4, 'Trade from Pokémon Violet'),
(877, NULL, 5, 'Apple Hills, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Tera Raid Battles: 4 Star Raid Battles, 6 Star Raid Battles'),
-- Cufant
(878, NULL, 1, 'Bridge Field, Giant''s Foot<br>Max Raid Battles: Dusty Bowl, Giant''s Seat'),
(878, NULL, 2, 'Bridge Field, Giant''s Foot<br>Max Raid Battles: Dusty Bowl, Giant''s Seat'),
(878, NULL, 3, NULL),
(878, NULL, 4, 'East Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
(878, NULL, 5, 'East Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Copperajah
(879, NULL, 1, 'Hammerlocke Hills, Lake of Outrage, Giant''s Foot<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea<br>Gigantamax Raid Battles: Stony Wilderness, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea'),
(879, NULL, 2, 'Hammerlocke Hills, Lake of Outrage, Giant''s Foot<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea<br>Gigantamax Raid Battles: Stony Wilderness, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea'),
(879, NULL, 3, NULL),
(879, NULL, 4, 'Casseroya Lake, Dalizapa Passage, Glaseado Mountain, North Province Area One, North Province Area Two, North Province Area Three<br>Fixed: North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles'),
(879, NULL, 5, 'Casseroya Lake, Dalizapa Passage, Glaseado Mountain, North Province Area One, North Province Area Two, North Province Area Three<br>Fixed: North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Dracozolt
(880, NULL, 1, 'Revive Fossilized Bird & Fossilized Drake in Route 6<br>Max Raid Battles: Snowslide Slope'),
(880, NULL, 2, 'Revive Fossilized Bird & Fossilized Drake in Route 6<br>Max Raid Battles: Snowslide Slope'),
(880, NULL, 3, NULL),
(880, NULL, 4, NULL),
(880, NULL, 5, NULL),
-- Arctozolt
(881, NULL, 1, 'Revive Fossilized Bird & Fossilized Dino in Route 6<br>Max Raid Battles: Snowslide Slope'),
(881, NULL, 2, 'Revive Fossilized Bird & Fossilized Dino in Route 6<br>Max Raid Battles: Snowslide Slope'),
(881, NULL, 3, NULL),
(881, NULL, 4, NULL),
(881, NULL, 5, NULL),
-- Dracovish
(882, NULL, 1, 'Revive Fossilized Fish & Fossilized Drake in Route 6<br>Max Raid Battles: Snowslide Slope'),
(882, NULL, 2, 'Revive Fossilized Fish & Fossilized Drake in Route 6<br>Max Raid Battles: Snowslide Slope'),
(882, NULL, 3, NULL),
(882, NULL, 4, NULL),
(882, NULL, 5, NULL),
-- Arctovish
(883, NULL, 1, 'Revive Fossilized Fish & Fossilized Dino in Route 6<br>Max Raid Battles: Snowslide Slope'),
(883, NULL, 2, 'Revive Fossilized Fish & Fossilized Dino in Route 6<br>Max Raid Battles: Snowslide Slope'),
(883, NULL, 3, NULL),
(883, NULL, 4, NULL),
(883, NULL, 5, NULL),
-- Duraludon
(884, NULL, 1, 'Route 10, Giant''s Seat, Lake of Outrage<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Stony Wilderness, Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Gigantamax Raid Battles: Giant''s Seat, Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(884, NULL, 2, 'Route 10, Giant''s Seat, Lake of Outrage<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Stony Wilderness, Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Gigantamax Raid Battles: Giant''s Seat, Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(884, NULL, 3, NULL),
(884, NULL, 4, 'Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(884, NULL, 5, 'Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Dreepy
(885, NULL, 1, 'Lake of Outrage<br>Max Raid Battles: Axew''s Eye, Rolling Fields, Slippery Slope, Old Cemetery, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(885, NULL, 2, 'Lake of Outrage<br>Max Raid Battles: Axew''s Eye, Rolling Fields, Slippery Slope, Old Cemetery, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(885, NULL, 3, NULL),
(885, NULL, 4, 'Trade from Pokémon Violet'),
(885, NULL, 5, 'East Province Area Two, East Province Area Three, Glaseado Mountain, South Province Area One, South Province Area Four, South Province Area Five, South Province Area Six, West Province Area Two, West Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Drakloak
(886, NULL, 1, 'Lake of Outrage, Old Cemetery<br>Max Raid Battles: Axew''s Eye, Rolling Fields, Slippery Slope, Old Cemetery, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(886, NULL, 2, 'Lake of Outrage, Old Cemetery<br>Max Raid Battles: Axew''s Eye, Rolling Fields, Slippery Slope, Old Cemetery, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(886, NULL, 3, NULL),
(886, NULL, 4, 'Trade from Pokémon Violet'),
(886, NULL, 5, 'Casseroya Lake, Glaseado Mountain, North Province Area One, North Province Area Two, North Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Dragapult
(887, NULL, 1, 'Old Cemetery, Three-Point Pass<br>Max Raid Battles: Axew''s Eye, Rolling Fields, Slippery Slope, Old Cemetery, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(887, NULL, 2, 'Old Cemetery, Three-Point Pass<br>Max Raid Battles: Axew''s Eye, Rolling Fields, Slippery Slope, Old Cemetery, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(887, NULL, 3, NULL),
(887, NULL, 4, 'Trade from Pokémon Violet'),
(887, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Zacian
(888, NULL, 1, 'Energy Plant'),
(888, NULL, 2, 'Trade from Pokémon Sword'),
(888, NULL, 3, NULL),
(888, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(888, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Zamazenta
(889, NULL, 1, 'Trade from Pokémon Shield'),
(889, NULL, 2, 'Energy Plant'),
(889, NULL, 3, NULL),
(889, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(889, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Eternatus
(890, NULL, 1, 'Energy Plant'),
(890, NULL, 2, 'Energy Plant'),
(890, NULL, 3, NULL),
(890, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(890, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Kubfu
(891, NULL, 1, 'Gift from Mustard in Master Dojo'),
(891, NULL, 2, 'Gift from Mustard in Master Dojo'),
(891, NULL, 3, NULL),
(891, NULL, 4, 'North Province Area Two - Requires Snack from Snacksworth'),
(891, NULL, 5, 'North Province Area Two - Requires Snack from Snacksworth'),
-- Urshifu
(892, NULL, 1, 'Evolve Kubfu'),
(892, NULL, 2, 'Evolve Kubfu'),
(892, NULL, 3, NULL),
(892, NULL, 4, 'Evolve Kubfu'),
(892, NULL, 5, 'Evolve Kubfu'),
-- Zarude
(893, NULL, 1, 'Event Only'),
(893, NULL, 2, 'Event Only'),
(893, NULL, 3, NULL),
(893, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(893, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Regieleki
(894, NULL, 1, 'Split-Decision Ruins'),
(894, NULL, 2, 'Split-Decision Ruins'),
(894, NULL, 3, NULL),
(894, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(894, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Regidrago
(895, NULL, 1, 'Split-Decision Ruins'),
(895, NULL, 2, 'Split-Decision Ruins'),
(895, NULL, 3, NULL),
(895, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(895, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Glastrier
(896, NULL, 1, 'Crown Shrine'),
(896, NULL, 2, 'Crown Shrine'),
(896, NULL, 3, NULL),
(896, NULL, 4, 'Glaseado Mountain - Requires Snack from Snacksworth'),
(896, NULL, 5, 'Glaseado Mountain - Requires Snack from Snacksworth'),
-- Spectrier
(897, NULL, 1, 'Crown Shrine'),
(897, NULL, 2, 'Crown Shrine'),
(897, NULL, 3, NULL),
(897, NULL, 4, 'Glaseado Mountain - Requires Snack from Snacksworth'),
(897, NULL, 5, 'Glaseado Mountain - Requires Snack from Snacksworth'),
-- Calyrex
(898, NULL, 1, 'Crown Shrine'),
(898, NULL, 2, 'Crown Shrine'),
(898, NULL, 3, NULL),
(898, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(898, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Wyrdeer
(899, NULL, 1, NULL),
(899, NULL, 2, NULL),
(899, NULL, 3, 'Obsidian Fieldlands: Massive Mass Outbreak'),
(899, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(899, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Kleavor
(900, NULL, 1, NULL),
(900, NULL, 2, NULL),
(900, NULL, 3, 'Obsidian Fieldlands: Massive Mass Outbreak'),
(900, NULL, 4, 'Canyon Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 6 Star Raid Battles'),
(900, NULL, 5, 'Canyon Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 6 Star Raid Battles'),
-- Ursaluna
(901, NULL, 1, NULL),
(901, NULL, 2, NULL),
(901, NULL, 3, 'Crimson Mirelands: Massive Mass Outbreak'),
(901, NULL, 4, 'Timeless Woods (Bloodmoon)'),
(901, NULL, 5, 'Timeless Woods (Bloodmoon)'),
-- Basculegion
(902, NULL, 1, NULL),
(902, NULL, 2, NULL),
(902, NULL, 3, 'Cobalt Coastlands: Massive Mass Outbreak'),
(902, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(902, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Sneasler
(903, NULL, 1, NULL),
(903, NULL, 2, NULL),
(903, NULL, 3, 'Coronet Highlands: Massive Mass Outbreak'),
(903, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(903, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Overqwil
(904, NULL, 1, NULL),
(904, NULL, 2, NULL),
(904, NULL, 3, 'Crimson Mirelands: Lake Valor (Story)<br>Cobalt Coastlands: Massive Mass Outbreak'),
(904, NULL, 4, 'Tera Raid Battles: 6 Star Raid Battles'),
(904, NULL, 5, 'Tera Raid Battles: 6 Star Raid Battles'),
-- Enamorus
(905, NULL, 1, NULL),
(905, NULL, 2, NULL),
(905, NULL, 3, 'Crimson Mirelands: Scarlet Bog'),
(905, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(905, NULL, 5, 'Transfer from Pokémon HOME or obtain from event');

COMMIT TRANSACTION;