BEGIN TRANSACTION;

INSERT INTO Pokemon_Location (pokedex_number, region_id, game_id, location_name)
VALUES 

-- Chespin
(650, NULL, 1, NULL),
(650, NULL, 2, NULL),
(650, NULL, 3, NULL),
(650, NULL, 4, 'Chargestone Cavern'),
(650, NULL, 5, 'Chargestone Cavern'),
-- Quilladin
(651, NULL, 1, NULL),
(651, NULL, 2, NULL),
(651, NULL, 3, NULL),
(651, NULL, 4, 'Evolve Chespin'),
(651, NULL, 5, 'Evolve Chespin'),
-- Chesnaught
(652, NULL, 1, NULL),
(652, NULL, 2, NULL),
(652, NULL, 3, NULL),
(652, NULL, 4, 'Evolve Quilladin'),
(652, NULL, 5, 'Evolve Quilladin'),
-- Fennekin
(653, NULL, 1, NULL),
(653, NULL, 2, NULL),
(653, NULL, 3, NULL),
(653, NULL, 4, 'Savanna Biome'),
(653, NULL, 5, 'Savanna Biome'),
-- Braixen
(654, NULL, 1, NULL),
(654, NULL, 2, NULL),
(654, NULL, 3, NULL),
(654, NULL, 4, 'Evolve Fennekin'),
(654, NULL, 5, 'Evolve Fennekin'),
-- Delphox
(655, NULL, 1, NULL),
(655, NULL, 2, NULL),
(655, NULL, 3, NULL),
(655, NULL, 4, 'Evolve Braixen'),
(655, NULL, 5, 'Evolve Braixen'),
-- Froakie
(656, NULL, 1, NULL),
(656, NULL, 2, NULL),
(656, NULL, 3, NULL),
(656, NULL, 4, 'Coastal Biome'),
(656, NULL, 5, 'Coastal Biome'),
-- Frogadier
(657, NULL, 1, NULL),
(657, NULL, 2, NULL),
(657, NULL, 3, NULL),
(657, NULL, 4, 'Evolve Froakie'),
(657, NULL, 5, 'Evolve Froakie'),
-- Greninja
(658, NULL, 1, NULL),
(658, NULL, 2, NULL),
(658, NULL, 3, NULL),
(658, NULL, 4, 'Evolve Frogadier'),
(658, NULL, 5, 'Evolve Frogadier'),
-- Bunnelby
(659, NULL, 1, 'Dappled Grove, East Lake Axewell, Giant''s Cap, North Lake Miloch, Rolling Fields, West Lake Axewell<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields'),
(659, NULL, 2, 'Dappled Grove, East Lake Axewell, Giant''s Cap, North Lake Miloch, Rolling Fields, West Lake Axewell<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields'),
(659, NULL, 3, NULL),
(659, NULL, 4, NULL),
(659, NULL, 5, NULL),
-- Diggersby
(660, NULL, 1, 'Axew''s Eye, Bridge Field, Giant''s Cap, Giant''s Mirror, Giant''s Seat, North Lake Miloch, Rolling Fields<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Stony Wilderness<br>Dynamax Adventures'),
(660, NULL, 2, 'Axew''s Eye, Bridge Field, Giant''s Cap, Giant''s Mirror, Giant''s Seat, North Lake Miloch, Rolling Fields<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Stony Wilderness<br>Dynamax Adventures'),
(660, NULL, 3, NULL),
(660, NULL, 4, NULL),
(660, NULL, 5, NULL),
-- Fletchling
(661, NULL, 1, 'Challenge Road, Loop Lagoon, Potbottom Desert<br>Max Raid Battles: Fields of Honor, Challenge Beach, Challenge Road, Loop Lagoon, Potbottom Desert, Workout Sea, Stepping-Stone Sea'),
(661, NULL, 2, 'Challenge Road, Loop Lagoon, Potbottom Desert<br>Max Raid Battles: Fields of Honor, Challenge Beach, Challenge Road, Loop Lagoon, Potbottom Desert, Workout Sea, Stepping-Stone Sea'),
(661, NULL, 3, NULL),
(661, NULL, 4, 'South Province Area One, South Province Area Two, South Province Area Five, Canyon Biome, Coastal Biome<br>Fixed: South Province Area One, South Province Area Two<br>Tera Raid Battles: 2 Star Raid Battles'),
(661, NULL, 5, 'South Province Area One, South Province Area Two, South Province Area Five, Canyon Biome, Coastal Biome<br>Fixed: South Province Area One, South Province Area Two<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Fletchinder
(662, NULL, 1, 'Fields of Honor, Soothing Wetlands, Challenge Beach, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: Fields of Honor, Challenge Beach, Challenge Road, Loop Lagoon, Potbottom Desert, Workout Sea, Stepping-Stone Sea'),
(662, NULL, 2, 'Fields of Honor, Soothing Wetlands, Challenge Beach, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: Fields of Honor, Challenge Beach, Challenge Road, Loop Lagoon, Potbottom Desert, Workout Sea, Stepping-Stone Sea'),
(662, NULL, 3, NULL),
(662, NULL, 4, 'South Province Area One, South Province Area Three, South Province Area Four, South Province Area Five, West Province Area Three, Canyon Biome, Coastal Biome<br>Fixed: East Province Area One, West Province Area Two, Coastal Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(662, NULL, 5, 'South Province Area One, South Province Area Three, South Province Area Four, South Province Area Five, West Province Area Three, Canyon Biome, Coastal Biome<br>Fixed: East Province Area One, West Province Area Two, Coastal Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Talonflame
(663, NULL, 1, 'Soothing Wetlands, Loop Lagoon, Training Lowlands<br>Max Raid Battles: Fields of Honor, Challenge Beach, Challenge Road, Loop Lagoon, Potbottom Desert, Workout Sea, Stepping-Stone Sea<br>Dynamax Adventures'),
(663, NULL, 2, 'Soothing Wetlands, Loop Lagoon, Training Lowlands<br>Max Raid Battles: Fields of Honor, Challenge Beach, Challenge Road, Loop Lagoon, Potbottom Desert, Workout Sea, Stepping-Stone Sea<br>Dynamax Adventures'),
(663, NULL, 3, NULL),
(663, NULL, 4, 'Area Zero, Coastal Biome, Torchlit Labyrinth<br>Fixed: South Province Area Three, Coastal Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(663, NULL, 5, 'Area Zero, Coastal Biome, Torchlit Labyrinth<br>Fixed: South Province Area Three, Coastal Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Scatterbug
(664, NULL, 1, NULL),
(664, NULL, 2, NULL),
(664, NULL, 3, NULL),
(664, NULL, 4, 'South Province Area One, South Province Area Five'),
(664, NULL, 5, 'South Province Area One, South Province Area Five'),
-- Spewpa
(665, NULL, 1, NULL),
(665, NULL, 2, NULL),
(665, NULL, 3, NULL),
(665, NULL, 4, 'South Province Area One, South Province Area Four'),
(665, NULL, 5, 'South Province Area One, South Province Area Four'),
-- Vivillon
(666, NULL, 1, NULL),
(666, NULL, 2, NULL),
(666, NULL, 3, NULL),
(666, NULL, 4, 'East Paldean Sea, North Province Area One, North Province Area Two, North Province Area Three'),
(666, NULL, 5, 'East Paldean Sea, North Province Area One, North Province Area Two, North Province Area Three'),
-- Litleo
(667, NULL, 1, NULL),
(667, NULL, 2, NULL),
(667, NULL, 3, NULL),
(667, NULL, 4, 'East Province Area One, East Province Area Two, South Province Area One, South Province Area Three, South Province Area Five, Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
(667, NULL, 5, 'East Province Area One, East Province Area Two, South Province Area One, South Province Area Three, South Province Area Five, Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Pyroar
(668, NULL, 1, NULL),
(668, NULL, 2, NULL),
(668, NULL, 3, NULL),
(668, NULL, 4, 'Dalizapa Passage, North Province Area One, Savanna Biome<br>Fixed: East Province Area Three, Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(668, NULL, 5, 'Dalizapa Passage, North Province Area One, Savanna Biome<br>Fixed: East Province Area Three, Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Flabébé
(669, NULL, 1, NULL),
(669, NULL, 2, NULL),
(669, NULL, 3, NULL),
(669, NULL, 4, 'East Paldean Sea, South Province Area Five, South Province Area Four, West Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
(669, NULL, 5, 'East Paldean Sea, South Province Area Five, South Province Area Four, West Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Floette
(670, NULL, 1, NULL),
(670, NULL, 2, NULL),
(670, NULL, 3, NULL),
(670, NULL, 4, 'East Paldean Sea, North Province Area One, North Province Area Two, North Province Area Three, South Province Area Five, South Province Area Four, South Province Area Six, West Province Area One, Area Zero<br>Fixed: East Province Area One'),
(670, NULL, 5, 'East Paldean Sea, North Province Area One, North Province Area Two, North Province Area Three, South Province Area Five, South Province Area Four, South Province Area Six, West Province Area One, Area Zero<br>Fixed: East Province Area One'),
-- Florges
(671, NULL, 1, NULL),
(671, NULL, 2, NULL),
(671, NULL, 3, NULL),
(671, NULL, 4, 'North Province Area Three<br>Tera Raid Battles: 5 Star Raid Battles'),
(671, NULL, 5, 'North Province Area Three<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Skiddo
(672, NULL, 1, NULL),
(672, NULL, 2, NULL),
(672, NULL, 3, NULL),
(672, NULL, 4, 'Asado Desert, East Province Area One, East Province Area Two, East Province Area Three, South Province Area One, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five, West Province Area One, West Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
(672, NULL, 5, 'Asado Desert, East Province Area One, East Province Area Two, East Province Area Three, South Province Area One, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five, West Province Area One, West Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Gogoat
(673, NULL, 1, NULL),
(673, NULL, 2, NULL),
(673, NULL, 3, NULL),
(673, NULL, 4, 'Casseroya Lake, Dalizapa Passage, North Province Area One, North Province Area Two, North Province Area Three, South Province Area Six, West Province Area Three<br>Fixed: North Province Area One, North Province Area Two<br>Tera Raid Battles: 4 Star Raid Battles'),
(673, NULL, 5, 'Casseroya Lake, Dalizapa Passage, North Province Area One, North Province Area Two, North Province Area Three, South Province Area Six, West Province Area Three<br>Fixed: North Province Area One, North Province Area Two<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Pancham
(674, NULL, 1, 'Route 3, East Lake Axewell, Rolling Fields, West Lake Axewell<br>Max Raid Battles: Dusty Bowl, North Lake Miloch'),
(674, NULL, 2, 'Route 3, East Lake Axewell, Rolling Fields, West Lake Axewell<br>Max Raid Battles: Dusty Bowl, North Lake Miloch'),
(674, NULL, 3, NULL),
(674, NULL, 4, NULL),
(674, NULL, 5, NULL),
-- Pangoro
(675, NULL, 1, 'Bridge Field, Dappled Grove, Lake of Outrage, Rolling Fields<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, North Lake Miloch, Stony Wilderness, West Lake Axewell<br>Dynamax Adventures'),
(675, NULL, 2, 'Bridge Field, Dappled Grove, Lake of Outrage, Rolling Fields<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, North Lake Miloch, Stony Wilderness, West Lake Axewell<br>Dynamax Adventures'),
(675, NULL, 3, NULL),
(675, NULL, 4, NULL),
(675, NULL, 5, NULL),
-- Furfrou
(676, NULL, 1, NULL),
(676, NULL, 2, NULL),
(676, NULL, 3, NULL),
(676, NULL, 4, NULL),
(676, NULL, 5, NULL),
-- Espurr
(677, NULL, 1, 'Route 5, Hammerlocke Hills, Motostoke Riverbank<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins'),
(677, NULL, 2, 'Route 5, Hammerlocke Hills, Motostoke Riverbank<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins'),
(677, NULL, 3, NULL),
(677, NULL, 4, 'Canyon Biome, Coastal Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
(677, NULL, 5, 'Canyon Biome, Coastal Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Meowstic
(678, NULL, 1, 'Route 7, Dusty Bowl<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins, Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea'),
(678, NULL, 2, 'Route 7, Dusty Bowl<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins, Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea'),
(678, NULL, 3, NULL),
(678, NULL, 4, 'Canyon Biome, Coastal Biome<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(678, NULL, 5, 'Canyon Biome, Coastal Biome<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Honedge
(679, NULL, 1, 'Hammerlocke Hills<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Stony Wilderness, Watchtower Ruins'),
(679, NULL, 2, 'Hammerlocke Hills<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Stony Wilderness, Watchtower Ruins'),
(679, NULL, 3, NULL),
(679, NULL, 4, NULL),
(679, NULL, 5, NULL),
-- Doublade
(680, NULL, 1, 'Giant''s Cap, Lake of Outrage<br>Max Raid Battles: Watchtower Ruins<br>Dynamax Adventures'),
(680, NULL, 2, 'Giant''s Cap, Lake of Outrage<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins<br>Dynamax Adventures'),
(680, NULL, 3, NULL),
(680, NULL, 4, NULL),
(680, NULL, 5, NULL),
-- Aegislash
(681, NULL, 1, 'Giant''s Cap<br>Max Raid Battles: Watchtower Ruins'),
(681, NULL, 2, 'Giant''s Cap<br>Max Raid Battles: Watchtower Ruins'),
(681, NULL, 3, NULL),
(681, NULL, 4, NULL),
(681, NULL, 5, NULL),
-- Spritzee
(682, NULL, 1, 'Trade from Pokémon Shield'),
(682, NULL, 2, 'Route 5, Giant''s Mirror, Glimwood Tangle, Stony Wilderness<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Rolling Fields'),
(682, NULL, 3, NULL),
(682, NULL, 4, NULL),
(682, NULL, 5, NULL),
-- Aromatisse
(683, NULL, 1, 'Trade from Pokémon Shield'),
(683, NULL, 2, 'Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Rolling Fields'),
(683, NULL, 3, NULL),
(683, NULL, 4, NULL),
(683, NULL, 5, NULL),
-- Swirlix
(684, NULL, 1, 'Route 5, Giant''s Mirror, Glimwood Tangle, Stony Wilderness<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Rolling Fields'),
(684, NULL, 2, 'Trade from Pokémon Sword'),
(684, NULL, 3, NULL),
(684, NULL, 4, NULL),
(684, NULL, 5, NULL),
-- Slurpuff
(685, NULL, 1, 'Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Rolling Fields'),
(685, NULL, 2, 'Trade from Pokémon Sword'),
(685, NULL, 3, NULL),
(685, NULL, 4, NULL),
(685, NULL, 5, NULL),
-- Inkay
(686, NULL, 1, 'Route 7, Route 9, Bridge Field, Giant''s Mirror, Hammerlocke Hills, Fields of Honor, Challenge Beach, Loop Lagoon, Training Lowlands<br>Max Raid Battles: Giant''s Mirror, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Watchtower Ruins, West Lake Axewell, Soothing Wetlands, Challenge Road, Workout Sea, Honeycalm Sea'),
(686, NULL, 2, 'Route 7, Route 9, Bridge Field, Giant''s Mirror, Hammerlocke Hills, Fields of Honor, Challenge Beach, Loop Lagoon, Training Lowlands<br>Max Raid Battles: Giant''s Mirror, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Watchtower Ruins, West Lake Axewell, Soothing Wetlands, Challenge Road, Workout Sea, Honeycalm Sea'),
(686, NULL, 3, NULL),
(686, NULL, 4, 'Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(686, NULL, 5, 'Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Malamar
(687, NULL, 1, 'Fields of Honor, Soothing Wetlands, Challenge Beach, Loop Lagoon, Training Lowlands<br>Max Raid Battles: Giant''s Mirror, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Watchtower Ruins, West Lake Axewell, Soothing Wetlands, Challenge Road, Workout Sea, Honeycalm Sea<br>Dynamax Adventures'),
(687, NULL, 2, 'Fields of Honor, Soothing Wetlands, Challenge Beach, Loop Lagoon, Training Lowlands<br>Max Raid Battles: Giant''s Mirror, Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Watchtower Ruins, West Lake Axewell, Soothing Wetlands, Challenge Road, Workout Sea, Honeycalm Sea<br>Dynamax Adventures'),
(687, NULL, 3, NULL),
(687, NULL, 4, 'Fixed: Canyon Biome, Coastal Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(687, NULL, 5, 'Fixed: Canyon Biome, Coastal Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Binacle
(688, NULL, 1, 'Bridge Field, Galar Mine No. 2, Motostoke Riverbank<br>Max Raid Battles: Dusty Bowl, Giant''s Mirror, Giant''s Seat, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea'),
(688, NULL, 2, 'Bridge Field, Galar Mine No. 2, Motostoke Riverbank<br>Max Raid Battles: Dusty Bowl, Giant''s Mirror, Giant''s Seat, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea'),
(688, NULL, 3, NULL),
(688, NULL, 4, NULL),
(688, NULL, 5, NULL),
-- Barbaracle
(689, NULL, 1, 'Route 9, Dusty Bowl, Lake of Outrage<br>Max Raid Battles: Dusty Bowl, Giant''s Mirror, Giant''s Seat, Rolling Fields, Stony Wilderness, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea<br>Dynamax Adventures'),
(689, NULL, 2, 'Route 9, Dusty Bowl, Lake of Outrage<br>Max Raid Battles: Dusty Bowl, Giant''s Mirror, Giant''s Seat, Rolling Fields, Stony Wilderness, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea<br>Dynamax Adventures'),
(689, NULL, 3, NULL),
(689, NULL, 4, NULL),
(689, NULL, 5, NULL),
-- Skrelp
(690, NULL, 1, 'Trade from Pokémon Shield'),
(690, NULL, 2, 'Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea'),
(690, NULL, 3, NULL),
(690, NULL, 4, 'East Paldean Sea, North Paldean Sea, South Paldean Sea, West Paldean Sea<br>Tera Raid Battles: 2 Star Raid Battles'),
(690, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Dragalge
(691, NULL, 1, 'Trade from Pokémon Shield'),
(691, NULL, 2, 'Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea'),
(691, NULL, 3, NULL),
(691, NULL, 4, 'North Paldean Sea<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(691, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Clauncher
(692, NULL, 1, 'Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea'),
(692, NULL, 2, 'Trade from Pokémon Sword'),
(692, NULL, 3, NULL),
(692, NULL, 4, 'Trade from Pokémon Violet'),
(692, NULL, 5, 'East Paldean Sea, North Paldean Sea, South Paldean Sea, West Paldean Sea<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Clawitzer
(693, NULL, 1, 'Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea'),
(693, NULL, 2, 'Trade from Pokémon Sword'),
(693, NULL, 3, NULL),
(693, NULL, 4, 'Trade from Pokémon Violet'),
(693, NULL, 5, 'North Paldean Sea, South Paldean Sea<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Helioptile
(694, NULL, 1, 'Route 6, Giant''s Mirror<br>Max Raid Battles: East Lake Axewell, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage, Rolling Fields'),
(694, NULL, 2, 'Route 6, Giant''s Mirror<br>Max Raid Battles: East Lake Axewell, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage, Rolling Fields'),
(694, NULL, 3, NULL),
(694, NULL, 4, NULL),
(694, NULL, 5, NULL),
-- Heliolisk
(695, NULL, 1, 'Max Raid Battles: East Lake Axewell, Giant''s Mirror, Lake of Outrage, Rolling Fields<br>Dynamax Adventures'),
(695, NULL, 2, 'Max Raid Battles: East Lake Axewell, Giant''s Mirror, Lake of Outrage, Rolling Fields<br>Dynamax Adventures'),
(695, NULL, 3, NULL),
(695, NULL, 4, NULL),
(695, NULL, 5, NULL),
-- Tyrunt
(696, NULL, 1, 'Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(696, NULL, 2, 'Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(696, NULL, 3, NULL),
(696, NULL, 4, NULL),
(696, NULL, 5, NULL),
-- Tyrantrum
(697, NULL, 1, 'Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Dynamax Adventures'),
(697, NULL, 2, 'Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Dynamax Adventures'),
(697, NULL, 3, NULL),
(697, NULL, 4, NULL),
(697, NULL, 5, NULL),
-- Amaura
(698, NULL, 1, 'Slippery Slope, Frostpoint Field, Snowslide Slope<br>Max Raid Battles: Slippery Slope, Snowslide Slope, Frigid Sea'),
(698, NULL, 2, 'Slippery Slope, Frostpoint Field, Snowslide Slope<br>Max Raid Battles: Slippery Slope, Snowslide Slope, Frigid Sea'),
(698, NULL, 3, NULL),
(698, NULL, 4, NULL),
(698, NULL, 5, NULL),
-- Aurorus
(699, NULL, 1, 'Snowslide Slope<br>Max Raid Battles: Slippery Slope, Snowslide Slope, Frigid Sea<br>Dynamax Adventures'),
(699, NULL, 2, 'Snowslide Slope<br>Max Raid Battles: Slippery Slope, Snowslide Slope, Frigid Sea<br>Dynamax Adventures'),
(699, NULL, 3, NULL),
(699, NULL, 4, NULL),
(699, NULL, 5, NULL),
-- Sylveon
(700, NULL, 1, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Lake of Outrage, Ballimere Lake'),
(700, NULL, 2, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Lake of Outrage, Ballimere Lake'),
(700, NULL, 3, 'Obsidian Fieldlands: Space-time Distortion in Obsidian Fieldlands or nearby'),
(700, NULL, 4, 'South Province Area Six, West Province Area Three<br>Fixed: North Province Area Three<br>Tera Raid Battles: 6 Star Raid Battles'),
(700, NULL, 5, 'South Province Area Six, West Province Area Three<br>Fixed: North Province Area Three<br>Tera Raid Battles: 6 Star Raid Battles'),
-- Hawlucha
(701, NULL, 1, 'Route 6, Hammerlocke Hills<br>Max Raid Battles: Dusty Bowl, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, North Lake Miloch, Stony Wilderness<br>Dynamax Adventures'),
(701, NULL, 2, 'Route 6, Hammerlocke Hills<br>Max Raid Battles: Dusty Bowl, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, North Lake Miloch, Rolling Fields<br>Dynamax Adventures'),
(701, NULL, 3, NULL),
(701, NULL, 4, 'Area Zero, Casseroya Lake, North Province Area One, North Province Area Two, North Province Area Three, Socarrat Trail<br>Fixed: South Province Area Four, South Province Area Six<br>Tera Raid Battles: 4 Star Raid Battles'),
(701, NULL, 5, 'Area Zero, Casseroya Lake, North Province Area One, North Province Area Two, North Province Area Three, Socarrat Trail<br>Fixed: South Province Area Four, South Province Area Six<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Dedenne
(702, NULL, 1, 'Challenge Beach<br>Max Raid Battles: Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea, Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Dynamax Adventures'),
(702, NULL, 2, 'Challenge Beach<br>Max Raid Battles: Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea, Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Dynamax Adventures'),
(702, NULL, 3, NULL),
(702, NULL, 4, 'North Province Area Three, West Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles , 4 Star Raid Battles'),
(702, NULL, 5, 'North Province Area Three, West Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles , 4 Star Raid Battles'),
-- Carbink
(703, NULL, 1, 'Tunnel to the Top, Roaring-Sea Caves, Lakeside Cave<br>Max Raid Battles: Slippery Slope, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(703, NULL, 2, 'Tunnel to the Top, Roaring-Sea Caves, Lakeside Cave<br>Max Raid Battles: Slippery Slope, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(703, NULL, 3, NULL),
(703, NULL, 4, 'Crystal Pool, Oni Mountain, Area Zero<br>Fixed: Chilling Waterhead<br>Tera Raid Battles: 4 Star Raid Battles'),
(703, NULL, 5, 'Crystal Pool, Oni Mountain, Area Zero<br>Fixed: Chilling Waterhead<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Goomy
(704, NULL, 1, 'Trade from Pokémon Shield'),
(704, NULL, 2, 'Lake of Outrage, Forest of Focus, Soothing Wetlands, Challenge Beach<br>Max Raid Battles: Axew''s Eye, Rolling Fields, Loop Lagoon, Workout Sea, Honeycalm Sea'),
(704, NULL, 3, 'Crimson Mirelands: Holm of Trials or nearby<br>Coronet Highlands: Ancient Quarry or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(704, NULL, 4, 'East Province Area Three, Glaseado Mountain, South Province Area One, South Province Area Three, South Province Area Four, South Province Area Five, West Province Area Three, Chilling Waterhead, Fellhorn Gorge, Oni Mountain, Timeless Woods<br>Fixed: Chilling Waterhead<br>Tera Raid Battles: 3 Star Raid Battles'),
(704, NULL, 5, 'East Province Area Three, Glaseado Mountain, South Province Area One, South Province Area Three, South Province Area Four, South Province Area Five, West Province Area Three, Chilling Waterhead, Fellhorn Gorge, Oni Mountain, Timeless Woods<br>Fixed: Chilling Waterhead<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Sliggoo
(705, NULL, 1, 'Trade from Pokémon Shield'),
(705, NULL, 2, 'Lake of Outrage<br>Max Raid Battles: Axew''s Eye, Rolling Fields, Loop Lagoon, Workout Sea, Honeycalm Sea'),
(705, NULL, 3, NULL),
(705, NULL, 4, 'Casseroya Lake, Timeless Woods<br>Fixed: South Province Area Four, West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
(705, NULL, 5, 'Casseroya Lake, Timeless Woods<br>Fixed: South Province Area Four, West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Hisuian Sliggoo
(705, 3, 1, NULL),
(705, 3, 2, NULL),
(705, 3, 3, 'Crimson Mirelands: Holm of Trials or nearby<br>Coronet Highlands: Ancient Quarry or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(705, 3, 4, 'Transfer from Pokémon HOME'),
(705, 3, 5, 'Transfer from Pokémon HOME'),
-- Goodra
(706, NULL, 1, 'Trade from Pokémon Shield'),
(706, NULL, 2, 'Max Raid Battles: Axew''s Eye, Rolling Fields, Loop Lagoon, Workout Sea, Honeycalm Sea'),
(706, NULL, 3, NULL),
(706, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(706, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Hisuian Goodra
(706, 3, 1, NULL),
(706, 3, 2, NULL),
(706, 3, 3, 'Obsidian Fieldlands: Lake Verity<br>Coronet Highlands: Ancient Quarry or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(706, 3, 4, 'Transfer from Pokémon HOME'),
(706, 3, 5, 'Transfer from Pokémon HOME'),
-- Klefki
(707, NULL, 1, 'Fields of Honor<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea, Insular Sea<br>Dynamax Adventures'),
(707, NULL, 2, 'Fields of Honor<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea, Insular Sea<br>Dynamax Adventures'),
(707, NULL, 3, NULL),
(707, NULL, 4, 'Glaseado Mountain, South Province Area Six'),
(707, NULL, 5, 'Glaseado Mountain, South Province Area Six'),
-- Phantump
(708, NULL, 1, 'Glimwood Tangle, Slippery Slope, Old Cemetery, Snowslide Slope, Giant''s Foot, Three-Point Pass<br>Max Raid Battles: Dappled Grove, Giant''s Mirror, Stony Wilderness, Watchtower Ruins, Slippery Slope, Old Cemetery, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(708, NULL, 2, 'Glimwood Tangle, Slippery Slope, Old Cemetery, Snowslide Slope, Giant''s Foot, Three-Point Pass<br>Max Raid Battles: Dappled Grove, Giant''s Mirror, Stony Wilderness, Watchtower Ruins, Slippery Slope, Old Cemetery, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(708, NULL, 3, NULL),
(708, NULL, 4, 'Kitakami Wilds, Reveler''s Road, Timeless Woods<br>Fixed: Timeless Woods<br>Tera Raid Battles: 3 Star Raid Battles'),
(708, NULL, 5, 'Kitakami Wilds, Reveler''s Road, Timeless Woods<br>Fixed: Timeless Woods<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Trevenant
(709, NULL, 1, 'Slippery Slope, Old Cemetery, Snowslide Slope<br>Max Raid Battles: Dappled Grove, Giant''s Mirror, Stony Wilderness, Watchtower Ruins, Slippery Slope, Old Cemetery, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(709, NULL, 2, 'Slippery Slope, Old Cemetery, Snowslide Slope<br>Max Raid Battles: Dappled Grove, Giant''s Mirror, Stony Wilderness, Watchtower Ruins, Slippery Slope, Old Cemetery, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(709, NULL, 3, NULL),
(709, NULL, 4, 'Kitakami Wilds, Timeless Woods<br>Fixed: Timeless Woods<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(709, NULL, 5, 'Kitakami Wilds, Timeless Woods<br>Fixed: Timeless Woods<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Pumpkaboo
(710, NULL, 1, 'Route 4, Giant''s Mirror, Hammerlocke Hills<br>Max Raid Battles: Dappled Grove, Giant''s Mirror, South Lake Miloch, Stony Wilderness, Watchtower Ruins'),
(710, NULL, 2, 'Route 4, Giant''s Mirror, Hammerlocke Hills<br>Max Raid Battles: Dappled Grove, Giant''s Mirror, Stony Wilderness, Watchtower Ruins'),
(710, NULL, 3, NULL),
(710, NULL, 4, NULL),
(710, NULL, 5, NULL),
-- Gourgeist
(711, NULL, 1, 'Hammerlocke Hills<br>Max Raid Battles: Dappled Grove, Giant''s Mirror, South Lake Miloch, Stony Wilderness, Watchtower Ruins, Challenge Beach, Courageous Cavern, Stepping-Stone Sea<br>Dynamax Adventures'),
(711, NULL, 2, 'Hammerlocke Hills<br>Max Raid Battles: Dappled Grove, Giant''s Mirror, Stony Wilderness, Watchtower Ruins, Challenge Beach, Courageous Cavern, Stepping-Stone Sea<br>Dynamax Adventures'),
(711, NULL, 3, NULL),
(711, NULL, 4, NULL),
(711, NULL, 5, NULL),
-- Bergmite
(712, NULL, 1, 'Route 9, Lake of Outrage, Frigid Sea, Three-Point Pass<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Stony Wilderness, Giant''s Bed, Frigid Sea'),
(712, NULL, 2, 'Route 9, Lake of Outrage, Frigid Sea, Three-Point Pass<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Giant''s Seat, Hammerlocke Hills, Stony Wilderness'),
(712, NULL, 3, 'Alabaster Icelands: Avalugg''s Legacy, Arena''s Approach or nearby<br>Alabaster Icelands: Massive Mass Outbreak'),
(712, NULL, 4, 'Casseroya Lake, Glaseado Mountain, North Paldean Sea<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 3 Star Raid Battles'),
(712, NULL, 5, 'Casseroya Lake, Glaseado Mountain, North Paldean Sea<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Avalugg
(713, NULL, 1, 'Lake of Outrage, Frigid Sea, Three-Point Pass<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Stony Wilderness, Insular Sea, Giant''s Bed, Frigid Sea'),
(713, NULL, 2, 'Lake of Outrage, Frigid Sea, Three-Point Pass<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Giant''s Seat, Hammerlocke Hills, Stony Wilderness, Insular Sea, Giant''s Bed, Frigid Sea'),
(713, NULL, 3, NULL),
(713, NULL, 4, 'Casseroya Lake, Glaseado Mountain, North Paldean Sea<br>Fixed: Casseroya Lake, Dalizapa Passage<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(713, NULL, 5, 'Casseroya Lake, Glaseado Mountain, North Paldean Sea<br>Fixed: Casseroya Lake, Dalizapa Passage<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Hisuian Avalugg
(713, 3, 1, NULL),
(713, 3, 2, NULL),
(713, 3, 3, 'Alabaster Icelands: Avalugg''s Legacy<br>Alabaster Icelands: Massive Mass Outbreak'),
(713, 3, 4, 'Transfer from Pokémon HOME'),
(713, 3, 5, 'Transfer from Pokémon HOME'),
-- Noibat
(714, NULL, 1, 'Bridge Field, Galar Mine No. 2, Watchtower Ruins<br>Max Raid Battles: Axew''s Eye, Giant''s Cap, Hammerlocke Hills, Rolling Fields, Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(714, NULL, 2, 'Bridge Field, Galar Mine No. 2, Watchtower Ruins<br>Max Raid Battles: Axew''s Eye, Giant''s Cap, Hammerlocke Hills, Rolling Fields, Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(714, NULL, 3, NULL),
(714, NULL, 4, 'North Province Area One, North Province Area Two, West Province Area Two, Apple Hills, Crystal Pool, Fellhorn Gorge, Kitakami Hall, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Oni''s Maw, Reveler''s Road<br>Fixed: Oni''s Maw<br>Tera Raid Battles: 3 Star Raid Battles'),
(714, NULL, 5, 'North Province Area One, North Province Area Two, West Province Area Two, Apple Hills, Crystal Pool, Fellhorn Gorge, Kitakami Hall, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Oni''s Maw, Reveler''s Road<br>Fixed: Oni''s Maw<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Noivern
(715, NULL, 1, 'Bridge Field, Lake of Outrage, Ballimere Lake, Lakeside Cave<br>Max Raid Battles: Axew''s Eye, Workout Sea, Honeycalm Sea, Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(715, NULL, 2, 'Bridge Field, Lake of Outrage, Ballimere Lake, Lakeside Cave<br>Max Raid Battles: Axew''s Eye, Workout Sea, Honeycalm Sea, Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(715, NULL, 3, NULL),
(715, NULL, 4, 'North Province Area One, North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles'),
(715, NULL, 5, 'North Province Area One, North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Xerneas
(716, NULL, 1, 'Dynamax Adventures'),
(716, NULL, 2, 'Trade from Pokémon Sword'),
(716, NULL, 3, NULL),
(716, NULL, 4, NULL),
(716, NULL, 5, NULL),
-- Yveltal
(717, NULL, 1, 'Trade from Pokémon Shield'),
(717, NULL, 2, 'Dynamax Adventures'),
(717, NULL, 3, NULL),
(717, NULL, 4, NULL),
(717, NULL, 5, NULL),
-- Zygarde
(718, NULL, 1, 'Dynamax Adventures'),
(718, NULL, 2, 'Dynamax Adventures'),
(718, NULL, 3, NULL),
(718, NULL, 4, NULL),
(718, NULL, 5, NULL),
-- Diancie
(719, NULL, 1, 'Transfer from Pokémon HOME or obtain from event'),
(719, NULL, 2, 'Transfer from Pokémon HOME or obtain from event'),
(719, NULL, 3, NULL),
(719, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(719, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Hoopa
(720, NULL, 1, NULL),
(720, NULL, 2, NULL),
(720, NULL, 3, NULL),
(720, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(720, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Volcanion
(721, NULL, 1, 'Transfer from Pokémon HOME or obtain from event'),
(721, NULL, 2, 'Transfer from Pokémon HOME or obtain from event'),
(721, NULL, 3, NULL),
(721, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(721, NULL, 5, 'Transfer from Pokémon HOME or obtain from event');

COMMIT TRANSACTION;