BEGIN TRANSACTION;

INSERT INTO Pokemon_Location (pokedex_number, region_id, game_id, location_name)
VALUES 

-- Sprigatito
(906, NULL, 1, NULL),
(906, NULL, 2, NULL),
(906, NULL, 3, NULL),
(906, NULL, 4, 'Starter Pokémon in Cabo Poco'),
(906, NULL, 5, 'Starter Pokémon in Cabo Poco'),
-- Floragato
(907, NULL, 1, NULL),
(907, NULL, 2, NULL),
(907, NULL, 3, NULL),
(907, NULL, 4, 'Evolve Sprigatito'),
(907, NULL, 5, 'Evolve Sprigatito'),
-- Meowscarada
(908, NULL, 1, NULL),
(908, NULL, 2, NULL),
(908, NULL, 3, NULL),
(908, NULL, 4, 'Evolve Floragato'),
(908, NULL, 5, 'Evolve Floragato'),
-- Fuecoco
(909, NULL, 1, NULL),
(909, NULL, 2, NULL),
(909, NULL, 3, NULL),
(909, NULL, 4, 'Starter Pokémon in Cabo Poco'),
(909, NULL, 5, 'Starter Pokémon in Cabo Poco'),
-- Crocalor
(910, NULL, 1, NULL),
(910, NULL, 2, NULL),
(910, NULL, 3, NULL),
(910, NULL, 4, 'Evolve Fuecoco'),
(910, NULL, 5, 'Evolve Fuecoco'),
-- Skeledirge
(911, NULL, 1, NULL),
(911, NULL, 2, NULL),
(911, NULL, 3, NULL),
(911, NULL, 4, 'Evolve Crocalor'),
(911, NULL, 5, 'Evolve Crocalor'),
-- Quaxly
(912, NULL, 1, NULL),
(912, NULL, 2, NULL),
(912, NULL, 3, NULL),
(912, NULL, 4, 'Starter Pokémon in Cabo Poco'),
(912, NULL, 5, 'Starter Pokémon in Cabo Poco'),
-- Quaxwell
(913, NULL, 1, NULL),
(913, NULL, 2, NULL),
(913, NULL, 3, NULL),
(913, NULL, 4, 'Evolve Quaxly'),
(913, NULL, 5, 'Evolve Quaxly'),
-- Quaquaval
(914, NULL, 1, NULL),
(914, NULL, 2, NULL),
(914, NULL, 3, NULL),
(914, NULL, 4, 'Evolve Quaxwell'),
(914, NULL, 5, 'Evolve Quaxwell'),
-- Lechonk
(915, NULL, 1, NULL),
(915, NULL, 2, NULL),
(915, NULL, 3, NULL),
(915, NULL, 4, 'East Province Area One, East Province Area Two, Pokemon League, South Province Area One, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five<br>Tera Raid Battles: 1 Star Raid Battles'),
(915, NULL, 5, 'East Province Area One, East Province Area Two, Pokemon League, South Province Area One, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Oinkologne
(916, NULL, 1, NULL),
(916, NULL, 2, NULL),
(916, NULL, 3, NULL),
(916, NULL, 4, 'East Province Area One, East Province Area Two, South Province Area Three, South Province Area Five, Tagtree Thicket, West Province Area Two, West Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles'),
(916, NULL, 5, 'East Province Area One, East Province Area Two, South Province Area Three, South Province Area Five, Tagtree Thicket, West Province Area Two, West Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Tarountula
(917, NULL, 1, NULL),
(917, NULL, 2, NULL),
(917, NULL, 3, NULL),
(917, NULL, 4, 'Pokemon League, South Province Area One, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five'),
(917, NULL, 5, 'Pokemon League, South Province Area One, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five'),
-- Spidops
(918, NULL, 1, NULL),
(918, NULL, 2, NULL),
(918, NULL, 3, NULL),
(918, NULL, 4, 'East Province Area One, East Province Area Two, North Province Area Two, Socarrat Trail, Tagtree Thicket, West Province Area Three'),
(918, NULL, 5, 'East Province Area One, East Province Area Two, North Province Area Two, Socarrat Trail, Tagtree Thicket, West Province Area Three'),
-- Nymble
(919, NULL, 1, NULL),
(919, NULL, 2, NULL),
(919, NULL, 3, NULL),
(919, NULL, 4, 'South Province Area Two, South Province Area Three, South Province Area Six, West Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
(919, NULL, 5, 'South Province Area Two, South Province Area Three, South Province Area Six, West Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Lokix
(920, NULL, 1, NULL),
(920, NULL, 2, NULL),
(920, NULL, 3, NULL),
(920, NULL, 4, 'Alfornada Cavern, Asado Desert, Casseroya Lake, Dalizapa Passage, East Province Area Three, Glaseado Mountain, North Province Area One, North Province Area Two, North Province Area Three, South Province Area Six, West Province Area Two<br>Fixed: North Province Area Two, West Province Area One<br>Tera Raid Battles: 3 Star Raid Battles'),
(920, NULL, 5, 'Alfornada Cavern, Asado Desert, Casseroya Lake, Dalizapa Passage, East Province Area Three, Glaseado Mountain, North Province Area One, North Province Area Two, North Province Area Three, South Province Area Six, West Province Area Two<br>Fixed: North Province Area Two, West Province Area One<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Pawmi
(921, NULL, 1, NULL),
(921, NULL, 2, NULL),
(921, NULL, 3, NULL),
(921, NULL, 4, 'South Province Area One, South Province Area Three, South Province Area Five<br>Fixed: South Province Area One, South Province Area Two, West Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
(921, NULL, 5, 'South Province Area One, South Province Area Three, South Province Area Five<br>Fixed: South Province Area One, South Province Area Two, West Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Pawmo
(922, NULL, 1, NULL),
(922, NULL, 2, NULL),
(922, NULL, 3, NULL),
(922, NULL, 4, 'East Province Area One, East Province Area Two, North Province Area One, North Province Area Three, South Province Area One, South Province Area Three, South Province Area Four, South Province Area Five, South Province Area Six, West Province Area One, West Province Area Two, West Province Area Three<br>Fixed: North Province Area One, North Province Area Three, West Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles'),
(922, NULL, 5, 'East Province Area One, East Province Area Two, North Province Area One, North Province Area Three, South Province Area One, South Province Area Three, South Province Area Four, South Province Area Five, South Province Area Six, West Province Area One, West Province Area Two, West Province Area Three<br>Fixed: North Province Area One, North Province Area Three, West Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Pawmot
(923, NULL, 1, NULL),
(923, NULL, 2, NULL),
(923, NULL, 3, NULL),
(923, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(923, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Tandemaus
(924, NULL, 1, NULL),
(924, NULL, 2, NULL),
(924, NULL, 3, NULL),
(924, NULL, 4, 'East Province Area One, East Province Area Two, East Province Area Three, Pokemon League, West Province Area Two, West Province Area Three, Apple Hills, Kitakami Road, Kitakami Wilds, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Fixed: Pokemon League, West Province Area Three, Apple Hills<br>Tera Raid Battles: 2 Star Raid Battles'),
(924, NULL, 5, 'East Province Area One, East Province Area Two, East Province Area Three, Pokemon League, West Province Area Two, West Province Area Three, Apple Hills, Kitakami Road, Kitakami Wilds, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Fixed: Pokemon League, West Province Area Three, Apple Hills<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Maushold
(925, NULL, 1, NULL),
(925, NULL, 2, NULL),
(925, NULL, 3, NULL),
(925, NULL, 4, 'Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
(925, NULL, 5, 'Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
-- Fidough
(926, NULL, 1, NULL),
(926, NULL, 2, NULL),
(926, NULL, 3, NULL),
(926, NULL, 4, 'South Province Area One, South Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
(926, NULL, 5, 'South Province Area One, South Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Dachsbun
(927, NULL, 1, NULL),
(927, NULL, 2, NULL),
(927, NULL, 3, NULL),
(927, NULL, 4, 'East Province Area Three, South Province Area Six, West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
(927, NULL, 5, 'East Province Area Three, South Province Area Six, West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
-- Smoliv
(928, NULL, 1, NULL),
(928, NULL, 2, NULL),
(928, NULL, 3, NULL),
(928, NULL, 4, 'South Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
(928, NULL, 5, 'South Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Dolliv
(929, NULL, 1, NULL),
(929, NULL, 2, NULL),
(929, NULL, 3, NULL),
(929, NULL, 4, 'East Paldean Sea, North Province Area Three, Tagtree Thicket<br>Tera Raid Battles: 3 Star Raid Battles'),
(929, NULL, 5, 'East Paldean Sea, North Province Area Three, Tagtree Thicket<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Arboliva
(930, NULL, 1, NULL),
(930, NULL, 2, NULL),
(930, NULL, 3, NULL),
(930, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles'),
(930, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles'),
-- Squawkabilly
(931, NULL, 1, NULL),
(931, NULL, 2, NULL),
(931, NULL, 3, NULL),
(931, NULL, 4, 'East Province Area One, East Province Area Two, East Province Area Three<br>Fixed: West Province Area One<br>Tera Raid Battles: 4 Star Raid Battles'),
(931, NULL, 5, 'East Province Area One, East Province Area Two, East Province Area Three<br>Fixed: West Province Area One<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Nacli
(932, NULL, 1, NULL),
(932, NULL, 2, NULL),
(932, NULL, 3, NULL),
(932, NULL, 4, 'Asado Desert, East Province Area One, East Province Area Two, East Province Area Three, South Province Area Three, South Province Area Four, South Province Area Five, West Province Area One, West Province Area Two<br>Fixed: South Province Area Three<br>Tera Raid Battles: 1 Star Raid Battles'),
(932, NULL, 5, 'Asado Desert, East Province Area One, East Province Area Two, East Province Area Three, South Province Area Three, South Province Area Four, South Province Area Five, West Province Area One, West Province Area Two<br>Fixed: South Province Area Three<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Naclstack
(933, NULL, 1, NULL),
(933, NULL, 2, NULL),
(933, NULL, 3, NULL),
(933, NULL, 4, 'Alfornada Cavern, Casseroya Lake, Dalizapa Passage, Glaseado Mountain, North Province Area One, North Province Area Two, North Province Area Three, West Province Area Three<br>Fixed: South Province Area Five, West Province Area Two<br>Tera Raid Battles: 3 Star Raid Battles'),
(933, NULL, 5, 'Alfornada Cavern, Casseroya Lake, Dalizapa Passage, Glaseado Mountain, North Province Area One, North Province Area Two, North Province Area Three, West Province Area Three<br>Fixed: South Province Area Five, West Province Area Two<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Garganacl
(934, NULL, 1, NULL),
(934, NULL, 2, NULL),
(934, NULL, 3, NULL),
(934, NULL, 4, 'Area Zero<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(934, NULL, 5, 'Area Zero<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Charcadet
(935, NULL, 1, NULL),
(935, NULL, 2, NULL),
(935, NULL, 3, NULL),
(935, NULL, 4, 'Asado Desert, East Province Area One, East Province Area Two, East Province Area Three, South Province Area Three, South Province Area Four, South Province Area Five, Tagtree Thicket, West Province Area One, West Province Area Two, West Province Area Three<br>Fixed: South Province Area Three, South Province Area Five, West Province Area One<br>Tera Raid Battles: 1 Star Raid Battles , 3 Star Raid Battles'),
(935, NULL, 5, 'Asado Desert, East Province Area One, East Province Area Two, East Province Area Three, South Province Area Three, South Province Area Four, South Province Area Five, Tagtree Thicket, West Province Area One, West Province Area Two, West Province Area Three<br>Fixed: South Province Area Three, South Province Area Five, West Province Area One<br>Tera Raid Battles: 1 Star Raid Battles , 3 Star Raid Battles'),
-- Armarouge
(936, NULL, 1, NULL),
(936, NULL, 2, NULL),
(936, NULL, 3, NULL),
(936, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(936, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Ceruledge
(937, NULL, 1, NULL),
(937, NULL, 2, NULL),
(937, NULL, 3, NULL),
(937, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(937, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Tadbulb
(938, NULL, 1, NULL),
(938, NULL, 2, NULL),
(938, NULL, 3, NULL),
(938, NULL, 4, 'East Province Area Two, East Province Area Three, Glaseado Mountain, South Province Area One, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five, West Province Area Two<br>Fixed: East Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
(938, NULL, 5, 'East Province Area Two, East Province Area Three, Glaseado Mountain, South Province Area One, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five, West Province Area Two<br>Fixed: East Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Bellibolt
(939, NULL, 1, NULL),
(939, NULL, 2, NULL),
(939, NULL, 3, NULL),
(939, NULL, 4, 'East Province Area Three, Glaseado Mountain, North Province Area Three, South Province Area Four, Tagtree Thicket, West Province Area Two, West Province Area Three<br>Fixed: Casseroya Lake, South Province Area Six, Tagtree Thicket<br>Tera Raid Battles: 4 Star Raid Battles'),
(939, NULL, 5, 'East Province Area Three, Glaseado Mountain, North Province Area Three, South Province Area Four, Tagtree Thicket, West Province Area Two, West Province Area Three<br>Fixed: Casseroya Lake, South Province Area Six, Tagtree Thicket<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Wattrel
(940, NULL, 1, NULL),
(940, NULL, 2, NULL),
(940, NULL, 3, NULL),
(940, NULL, 4, 'East Paldean Sea, East Province Area Two, South Paldean Sea, West Paldean Sea, West Province Area One<br>Fixed: East Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
(940, NULL, 5, 'East Paldean Sea, East Province Area Two, South Paldean Sea, West Paldean Sea, West Province Area One<br>Fixed: East Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Kilowattrel
(941, NULL, 1, NULL),
(941, NULL, 2, NULL),
(941, NULL, 3, NULL),
(941, NULL, 4, 'Casseroya Lake, East Paldean Sea, North Paldean Sea, North Province Area One, West Paldean Sea<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
(941, NULL, 5, 'Casseroya Lake, East Paldean Sea, North Paldean Sea, North Province Area One, West Paldean Sea<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
-- Maschiff
(942, NULL, 1, NULL),
(942, NULL, 2, NULL),
(942, NULL, 3, NULL),
(942, NULL, 4, 'South Province Area One, South Province Area Two, South Province Area Four, West Province Area Two, West Province Area Three<br>Fixed: South Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
(942, NULL, 5, 'South Province Area One, South Province Area Two, South Province Area Four, West Province Area Two, West Province Area Three<br>Fixed: South Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Mabosstiff
(943, NULL, 1, NULL),
(943, NULL, 2, NULL),
(943, NULL, 3, NULL),
(943, NULL, 4, 'West Province Area Three<br>Fixed: North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(943, NULL, 5, 'West Province Area Three<br>Fixed: North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Shroodle
(944, NULL, 1, NULL),
(944, NULL, 2, NULL),
(944, NULL, 3, NULL),
(944, NULL, 4, 'East Province Area One, East Province Area Two, South Province Area One, South Province Area Two, Tagtree Thicket, West Province Area Three<br>Fixed: South Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
(944, NULL, 5, 'East Province Area One, East Province Area Two, South Province Area One, South Province Area Two, Tagtree Thicket, West Province Area Three<br>Fixed: South Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Grafaiai
(945, NULL, 1, NULL),
(945, NULL, 2, NULL),
(945, NULL, 3, NULL),
(945, NULL, 4, 'Tagtree Thicket<br>Fixed: Casseroya Lake, North Province Area Two, Tagtree Thicket<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
(945, NULL, 5, 'Tagtree Thicket<br>Fixed: Casseroya Lake, North Province Area Two, Tagtree Thicket<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
-- Bramblin
(946, NULL, 1, NULL),
(946, NULL, 2, NULL),
(946, NULL, 3, NULL),
(946, NULL, 4, 'Asado Desert, East Province Area Three<br>Fixed: East Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
(946, NULL, 5, 'Asado Desert, East Province Area Three<br>Fixed: East Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Brambleghast
(947, NULL, 1, NULL),
(947, NULL, 2, NULL),
(947, NULL, 3, NULL),
(947, NULL, 4, 'North Province Area One, Socarrat Trail<br>Tera Raid Battles: 5 Star Raid Battles'),
(947, NULL, 5, 'North Province Area One, Socarrat Trail<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Toedscool
(948, NULL, 1, NULL),
(948, NULL, 2, NULL),
(948, NULL, 3, NULL),
(948, NULL, 4, 'East Province Area One, East Province Area Two, Socarrat Trail, South Province Area One, South Province Area Three, South Province Area Four, South Province Area Five, Tagtree Thicket, West Province Area Two, West Province Area Three, Fellhorn Gorge, Kitakami Hall, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Reveler''s Road, Timeless Woods<br>Fixed: East Province Area One, West Province Area Three<br>Tera Raid Battles: 1 Star Raid Battles'),
(948, NULL, 5, 'East Province Area One, East Province Area Two, Socarrat Trail, South Province Area One, South Province Area Three, South Province Area Four, South Province Area Five, Tagtree Thicket, West Province Area Two, West Province Area Three, Fellhorn Gorge, Kitakami Hall, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Reveler''s Road, Timeless Woods<br>Fixed: East Province Area One, West Province Area Three<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Toedscruel
(949, NULL, 1, NULL),
(949, NULL, 2, NULL),
(949, NULL, 3, NULL),
(949, NULL, 4, 'Socarrat Trail, Kitakami Wilds, Timeless Woods<br>Fixed: Kitakami Wilds, Timeless Woods<br>Tera Raid Battles: 4 Star Raid Battles, 6 Star Raid Battles'),
(949, NULL, 5, 'Socarrat Trail, Kitakami Wilds, Timeless Woods<br>Fixed: Kitakami Wilds, Timeless Woods<br>Tera Raid Battles: 4 Star Raid Battles, 6 Star Raid Battles'),
-- Klawf
(950, NULL, 1, NULL),
(950, NULL, 2, NULL),
(950, NULL, 3, NULL),
(950, NULL, 4, 'South Province Area Three<br>Titan: South Province Area Three<br>Fixed: South Province Area Three<br>Tera Raid Battles: 6 Star Raid Battles'),
(950, NULL, 5, 'South Province Area Three<br>Titan: South Province Area Three<br>Fixed: South Province Area Three<br>Tera Raid Battles: 6 Star Raid Battles'),
-- Capsakid
(951, NULL, 1, NULL),
(951, NULL, 2, NULL),
(951, NULL, 3, NULL),
(951, NULL, 4, 'Asado Desert, West Province Area One<br>Fixed: South Province Area Two, West Province Area One<br>Tera Raid Battles: 2 Star Raid Battles'),
(951, NULL, 5, 'Asado Desert, West Province Area One<br>Fixed: South Province Area Two, West Province Area One<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Scovillain
(952, NULL, 1, NULL),
(952, NULL, 2, NULL),
(952, NULL, 3, NULL),
(952, NULL, 4, 'Dalizapa Passage, North Province Area One, North Province Area Three, South Province Area Six<br>Tera Raid Battles: 4 Star Raid Battles'),
(952, NULL, 5, 'Dalizapa Passage, North Province Area One, North Province Area Three, South Province Area Six<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Rellor
(953, NULL, 1, NULL),
(953, NULL, 2, NULL),
(953, NULL, 3, NULL),
(953, NULL, 4, 'Asado Desert, Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
(953, NULL, 5, 'Asado Desert, Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Rabsca
(954, NULL, 1, NULL),
(954, NULL, 2, NULL),
(954, NULL, 3, NULL),
(954, NULL, 4, 'Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(954, NULL, 5, 'Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Flittle
(955, NULL, 1, NULL),
(955, NULL, 2, NULL),
(955, NULL, 3, NULL),
(955, NULL, 4, 'Asado Desert, Dalizapa Passage, East Province Area Two, North Province Area One, South Province Area One, South Province Area Four, South Province Area Five, South Province Area Six, West Province Area One<br>Fixed: West Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
(955, NULL, 5, 'Asado Desert, Dalizapa Passage, East Province Area Two, North Province Area One, South Province Area One, South Province Area Four, South Province Area Five, South Province Area Six, West Province Area One<br>Fixed: West Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Espathra
(956, NULL, 1, NULL),
(956, NULL, 2, NULL),
(956, NULL, 3, NULL),
(956, NULL, 4, 'Dalizapa Passage, North Province Area One, South Province Area Six<br>Fixed: Asado Desert, Dalizapa Passage<br>Tera Raid Battles: 4 Star Raid Battles'),
(956, NULL, 5, 'Dalizapa Passage, North Province Area One, South Province Area Six<br>Fixed: Asado Desert, Dalizapa Passage<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Tinkatink
(957, NULL, 1, NULL),
(957, NULL, 2, NULL),
(957, NULL, 3, NULL),
(957, NULL, 4, 'East Province Area Two, South Province Area Two, South Province Area Three, West Province Area One<br>Fixed: Asado Desert, South Province Area Two<br>Tera Raid Battles: 2 Star Raid Battles'),
(957, NULL, 5, 'East Province Area Two, South Province Area Two, South Province Area Three, West Province Area One<br>Fixed: Asado Desert, South Province Area Two<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Tinkatuff
(958, NULL, 1, NULL),
(958, NULL, 2, NULL),
(958, NULL, 3, NULL),
(958, NULL, 4, 'Dalizapa Passage, East Province Area Two, North Province Area One, North Province Area Three, South Province Area Six, West Province Area Two<br>Fixed: Casseroya Lake, West Province Area One<br>Tera Raid Battles: 3 Star Raid Battles'),
(958, NULL, 5, 'Dalizapa Passage, East Province Area Two, North Province Area One, North Province Area Three, South Province Area Six, West Province Area Two<br>Fixed: Casseroya Lake, West Province Area One<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Tinkaton
(959, NULL, 1, NULL),
(959, NULL, 2, NULL),
(959, NULL, 3, NULL),
(959, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(959, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Wiglett
(960, NULL, 1, NULL),
(960, NULL, 2, NULL),
(960, NULL, 3, NULL),
(960, NULL, 4, 'East Province Area Two, South Province Area Five, West Province Area One, West Province Area Two<br>Fixed: North Province Area One, South Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
(960, NULL, 5, 'East Province Area Two, South Province Area Five, West Province Area One, West Province Area Two<br>Fixed: North Province Area One, South Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Wugtrio
(961, NULL, 1, NULL),
(961, NULL, 2, NULL),
(961, NULL, 3, NULL),
(961, NULL, 4, 'North Province Area One, North Province Area Three, West Province Area Two<br>Fixed: North Province Area One, North Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
(961, NULL, 5, 'North Province Area One, North Province Area Three, West Province Area Two<br>Fixed: North Province Area One, North Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Bombirdier
(962, NULL, 1, NULL),
(962, NULL, 2, NULL),
(962, NULL, 3, NULL),
(962, NULL, 4, 'South Province Area Six, West Paldean Sea, West Province Area One, West Province Area Three, Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Titan: West Province Area One<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(962, NULL, 5, 'South Province Area Six, West Paldean Sea, West Province Area One, West Province Area Three, Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Titan: West Province Area One<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Finizen
(963, NULL, 1, NULL),
(963, NULL, 2, NULL),
(963, NULL, 3, NULL),
(963, NULL, 4, 'East Paldean Sea, North Paldean Sea, South Paldean Sea, West Paldean Sea<br>Fixed: West Province Area Two<br>Tera Raid Battles: 3 Star Raid Battles'),
(963, NULL, 5, 'East Paldean Sea, North Paldean Sea, South Paldean Sea, West Paldean Sea<br>Fixed: West Province Area Two<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Palafin
(964, NULL, 1, NULL),
(964, NULL, 2, NULL),
(964, NULL, 3, NULL),
(964, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles'),
(964, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles'),
-- Varoom
(965, NULL, 1, NULL),
(965, NULL, 2, NULL),
(965, NULL, 3, NULL),
(965, NULL, 4, 'East Province Area Three, West Province Area Two<br>Fixed: East Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
(965, NULL, 5, 'East Province Area Three, West Province Area Two<br>Fixed: East Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Revavroom
(966, NULL, 1, NULL),
(966, NULL, 2, NULL),
(966, NULL, 3, NULL),
(966, NULL, 4, 'Dalizapa Passage, North Province Area One<br>Fixed: Glaseado Mountain, North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(966, NULL, 5, 'Dalizapa Passage, North Province Area One<br>Fixed: Glaseado Mountain, North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Cyclizar
(967, NULL, 1, NULL),
(967, NULL, 2, NULL),
(967, NULL, 3, NULL),
(967, NULL, 4, 'East Province Area Two, West Province Area Two<br>Fixed: Asado Desert, East Province Area One, West Province Area One, West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
(967, NULL, 5, 'East Province Area Two, West Province Area Two<br>Fixed: Asado Desert, East Province Area One, West Province Area One, West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
-- Orthworm
(968, NULL, 1, NULL),
(968, NULL, 2, NULL),
(968, NULL, 3, NULL),
(968, NULL, 4, 'Asado Desert, East Province Area Three, Apple Hills, Kitakami Wilds, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Titan: East Province Area Three<br>Fixed: Paradise Barrens<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(968, NULL, 5, 'Asado Desert, East Province Area Three, Apple Hills, Kitakami Wilds, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Titan: East Province Area Three<br>Fixed: Paradise Barrens<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Glimmet
(969, NULL, 1, NULL),
(969, NULL, 2, NULL),
(969, NULL, 3, NULL),
(969, NULL, 4, 'Alfornada Cavern, Area Zero, East Province Area Three, Glaseado Mountain, North Province Area One, North Province Area Two, West Province Area Two, Crystal Pool, Infernal Pass, Oni Mountain, Aera Zero<br>Tera Raid Battles: 3 Star Raid Battles'),
(969, NULL, 5, 'Alfornada Cavern, Area Zero, East Province Area Three, Glaseado Mountain, North Province Area One, North Province Area Two, West Province Area Two, Crystal Pool, Infernal Pass, Oni Mountain, Aera Zero<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Glimmora
(970, NULL, 1, NULL),
(970, NULL, 2, NULL),
(970, NULL, 3, NULL),
(970, NULL, 4, 'Aera Zero<br>Fixed: Crystal Pool, Oni Mountain<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(970, NULL, 5, 'Aera Zero<br>Fixed: Crystal Pool, Oni Mountain<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Greavard
(971, NULL, 1, NULL),
(971, NULL, 2, NULL),
(971, NULL, 3, NULL),
(971, NULL, 4, 'Dalizapa Passage, Glaseado Mountain, West Province Area Three<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 1 Star Raid Battles'),
(971, NULL, 5, 'Dalizapa Passage, Glaseado Mountain, West Province Area Three<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Houndstone
(972, NULL, 1, NULL),
(972, NULL, 2, NULL),
(972, NULL, 3, NULL),
(972, NULL, 4, 'Casseroya Lake, Dalizapa Passage, Glaseado Mountain, North Province Area One<br>Fixed: Glaseado Mountain, South Province Area Five<br>Tera Raid Battles: 4 Star Raid Battles'),
(972, NULL, 5, 'Casseroya Lake, Dalizapa Passage, Glaseado Mountain, North Province Area One<br>Fixed: Glaseado Mountain, South Province Area Five<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Flamigo
(973, NULL, 1, NULL),
(973, NULL, 2, NULL),
(973, NULL, 3, NULL),
(973, NULL, 4, 'Casseroya Lake, East Province Area Two, East Province Area Three, Glaseado Mountain, North Province Area One, South Province Area Four, South Province Area Five, West Province Area Two, West Province Area Three<br>Fixed: South Province Area One, South Province Area Five<br>Tera Raid Battles: 4 Star Raid Battles'),
(973, NULL, 5, 'Casseroya Lake, East Province Area Two, East Province Area Three, Glaseado Mountain, North Province Area One, South Province Area Four, South Province Area Five, West Province Area Two, West Province Area Three<br>Fixed: South Province Area One, South Province Area Five<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Cetoddle
(974, NULL, 1, NULL),
(974, NULL, 2, NULL),
(974, NULL, 3, NULL),
(974, NULL, 4, 'Dalizapa Passage, Glaseado Mountain<br>Fixed: Dalizapa Passage, West Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles'),
(974, NULL, 5, 'Dalizapa Passage, Glaseado Mountain<br>Fixed: Dalizapa Passage, West Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Cetitan
(975, NULL, 1, NULL),
(975, NULL, 2, NULL),
(975, NULL, 3, NULL),
(975, NULL, 4, 'Glaseado Mountain<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(975, NULL, 5, 'Glaseado Mountain<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Veluza
(976, NULL, 1, NULL),
(976, NULL, 2, NULL),
(976, NULL, 3, NULL),
(976, NULL, 4, 'Casseroya Lake, North Paldean Sea, West Paldean Sea<br>Fixed: Casseroya Lake, East Province Area One, Glaseado Mountain<br>Tera Raid Battles: 4 Star Raid Battles'),
(976, NULL, 5, 'Casseroya Lake, North Paldean Sea, West Paldean Sea<br>Fixed: Casseroya Lake, East Province Area One, Glaseado Mountain<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Dondozo
(977, NULL, 1, NULL),
(977, NULL, 2, NULL),
(977, NULL, 3, NULL),
(977, NULL, 4, 'Casseroya Lake<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(977, NULL, 5, 'Casseroya Lake<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Tatsugiri
(978, NULL, 1, NULL),
(978, NULL, 2, NULL),
(978, NULL, 3, NULL),
(978, NULL, 4, 'Casseroya Lake<br>Titan: Casseroya Lake<br>Fixed: Casseroya Lake<br>Tera Raid Battles: 5 Star Raid Battles'),
(978, NULL, 5, 'Casseroya Lake<br>Titan: Casseroya Lake<br>Fixed: Casseroya Lake<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Annihilape
(979, NULL, 1, NULL),
(979, NULL, 2, NULL),
(979, NULL, 3, NULL),
(979, NULL, 4, 'Kitakami Wilds, Timeless Woods<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(979, NULL, 5, 'Kitakami Wilds, Timeless Woods<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Clodsire
(980, NULL, 1, NULL),
(980, NULL, 2, NULL),
(980, NULL, 3, NULL),
(980, NULL, 4, 'East Province Area Three, Glaseado Mountain, North Province Area One, South Province Area Five, South Province Area Six, West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
(980, NULL, 5, 'East Province Area Three, Glaseado Mountain, North Province Area One, South Province Area Five, South Province Area Six, West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
-- Farigiraf
(981, NULL, 1, NULL),
(981, NULL, 2, NULL),
(981, NULL, 3, NULL),
(981, NULL, 4, 'Area Zero, Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
(981, NULL, 5, 'Area Zero, Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
-- Dudunsparce
(982, NULL, 1, NULL),
(982, NULL, 2, NULL),
(982, NULL, 3, NULL),
(982, NULL, 4, 'Area Zero, Chilling Waterhead, Oni Mountain, Timeless Woods<br>Tera Raid Battles: 4 Star Raid Battles'),
(982, NULL, 5, 'Area Zero, Chilling Waterhead, Oni Mountain, Timeless Woods<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Kingambit
(983, NULL, 1, NULL),
(983, NULL, 2, NULL),
(983, NULL, 3, NULL),
(983, NULL, 4, 'Timeless Woods<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(983, NULL, 5, 'Timeless Woods<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Great Tusk
(984, NULL, 1, NULL),
(984, NULL, 2, NULL),
(984, NULL, 3, NULL),
(984, NULL, 4, 'Area Zero<br>Titan: Asado Desert'),
(984, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Scream Tail
(985, NULL, 1, NULL),
(985, NULL, 2, NULL),
(985, NULL, 3, NULL),
(985, NULL, 4, 'Area Zero'),
(985, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Brute Bonnet
(986, NULL, 1, NULL),
(986, NULL, 2, NULL),
(986, NULL, 3, NULL),
(986, NULL, 4, 'Area Zero'),
(986, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Flutter Mane
(987, NULL, 1, NULL),
(987, NULL, 2, NULL),
(987, NULL, 3, NULL),
(987, NULL, 4, 'Area Zero'),
(987, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Slither Wing
(988, NULL, 1, NULL),
(988, NULL, 2, NULL),
(988, NULL, 3, NULL),
(988, NULL, 4, 'Area Zero'),
(988, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Sandy Shocks
(989, NULL, 1, NULL),
(989, NULL, 2, NULL),
(989, NULL, 3, NULL),
(989, NULL, 4, 'Area Zero (in rocky area to left of Research Station 2)'),
(989, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Iron Treads
(990, NULL, 1, NULL),
(990, NULL, 2, NULL),
(990, NULL, 3, NULL),
(990, NULL, 4, 'Trade from Pokémon Violet'),
(990, NULL, 5, 'Area Zero<br>Titan: Asado Desert'),
-- Iron Bundle
(991, NULL, 1, NULL),
(991, NULL, 2, NULL),
(991, NULL, 3, NULL),
(991, NULL, 4, 'Trade from Pokémon Violet'),
(991, NULL, 5, 'Area Zero'),
-- Iron Hands
(992, NULL, 1, NULL),
(992, NULL, 2, NULL),
(992, NULL, 3, NULL),
(992, NULL, 4, 'Trade from Pokémon Violet'),
(992, NULL, 5, 'Area Zero'),
-- Iron Jugulis
(993, NULL, 1, NULL),
(993, NULL, 2, NULL),
(993, NULL, 3, NULL),
(993, NULL, 4, 'Trade from Pokémon Violet'),
(993, NULL, 5, 'Area Zero'),
-- Iron Moth
(994, NULL, 1, NULL),
(994, NULL, 2, NULL),
(994, NULL, 3, NULL),
(994, NULL, 4, 'Trade from Pokémon Violet'),
(994, NULL, 5, 'Area Zero'),
-- Iron Thorns
(995, NULL, 1, NULL),
(995, NULL, 2, NULL),
(995, NULL, 3, NULL),
(995, NULL, 4, 'Trade from Pokémon Violet'),
(995, NULL, 5, 'Area Zero (in rocky area to left of Research Station 2)'),
-- Frigibax
(996, NULL, 1, NULL),
(996, NULL, 2, NULL),
(996, NULL, 3, NULL),
(996, NULL, 4, 'Dalizapa Passage, Glaseado Mountain<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 3 Star Raid Battles'),
(996, NULL, 5, 'Dalizapa Passage, Glaseado Mountain<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Arctibax
(997, NULL, 1, NULL),
(997, NULL, 2, NULL),
(997, NULL, 3, NULL),
(997, NULL, 4, 'Glaseado Mountain<br>Fixed: Glaseado Mountain'),
(997, NULL, 5, 'Glaseado Mountain<br>Fixed: Glaseado Mountain'),
-- Baxcalibur
(998, NULL, 1, NULL),
(998, NULL, 2, NULL),
(998, NULL, 3, NULL),
(998, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(998, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Gimmighoul
(999, NULL, 1, NULL),
(999, NULL, 2, NULL),
(999, NULL, 3, NULL),
(999, NULL, 4, 'All over Paldea'),
(999, NULL, 5, 'All over Paldea'),
-- Gholdengo
(1000, NULL, 1, NULL),
(1000, NULL, 2, NULL),
(1000, NULL, 3, NULL),
(1000, NULL, 4, 'Evolve Gimmighoul'),
(1000, NULL, 5, 'Evolve Gimmighoul'),
-- Wo-Chien
(1001, NULL, 1, NULL),
(1001, NULL, 2, NULL),
(1001, NULL, 3, NULL),
(1001, NULL, 4, 'South Province Area One'),
(1001, NULL, 5, 'South Province Area One'),
-- Chien-Pao
(1002, NULL, 1, NULL),
(1002, NULL, 2, NULL),
(1002, NULL, 3, NULL),
(1002, NULL, 4, 'West Province Area One'),
(1002, NULL, 5, 'West Province Area One'),
-- Ting-Lu
(1003, NULL, 1, NULL),
(1003, NULL, 2, NULL),
(1003, NULL, 3, NULL),
(1003, NULL, 4, 'Socarrat Trail'),
(1003, NULL, 5, 'Socarrat Trail'),
-- Chi-Yu
(1004, NULL, 1, NULL),
(1004, NULL, 2, NULL),
(1004, NULL, 3, NULL),
(1004, NULL, 4, 'North Province Area Two'),
(1004, NULL, 5, 'North Province Area Two'),
-- Roaring Moon
(1005, NULL, 1, NULL),
(1005, NULL, 2, NULL),
(1005, NULL, 3, NULL),
(1005, NULL, 4, 'Area Zero (in cave in rocks to left of Research Station 3)'),
(1005, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Iron Valiant
(1006, NULL, 1, NULL),
(1006, NULL, 2, NULL),
(1006, NULL, 3, NULL),
(1006, NULL, 4, 'Trade from Pokémon Violet'),
(1006, NULL, 5, 'Area Zero (in cave in rocks to left of Research Station 3)'),
-- Koraidon
(1007, NULL, 1, NULL),
(1007, NULL, 2, NULL),
(1007, NULL, 3, NULL),
(1007, NULL, 4, 'Area Zero'),
(1007, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Miraidon
(1008, NULL, 1, NULL),
(1008, NULL, 2, NULL),
(1008, NULL, 3, NULL),
(1008, NULL, 4, 'Trade from Pokémon Violet'),
(1008, NULL, 5, 'Area Zero'),
-- Walking Wake
(1009, NULL, 1, NULL),
(1009, NULL, 2, NULL),
(1009, NULL, 3, NULL),
(1009, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(1009, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Iron Leaves
(1010, NULL, 1, NULL),
(1010, NULL, 2, NULL),
(1010, NULL, 3, NULL),
(1010, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(1010, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Dipplin
(1011, NULL, 1, NULL),
(1011, NULL, 2, NULL),
(1011, NULL, 3, NULL),
(1011, NULL, 4, 'Tera Raid Battles: 4 Star Raid Battles'),
(1011, NULL, 5, 'Tera Raid Battles: 4 Star Raid Battles'),
-- Poltchageist
(1012, NULL, 1, NULL),
(1012, NULL, 2, NULL),
(1012, NULL, 3, NULL),
(1012, NULL, 4, 'Mossfell Confluence, Reveler''s Road<br>Fixed: Mossfell Confluence, Apple Hills<br>Tera Raid Battles: 3 Star Raid Battles'),
(1012, NULL, 5, 'Mossfell Confluence, Reveler''s Road<br>Fixed: Mossfell Confluence, Apple Hills<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Sinistcha
(1013, NULL, 1, NULL),
(1013, NULL, 2, NULL),
(1013, NULL, 3, NULL),
(1013, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(1013, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Okidogi
(1014, NULL, 1, NULL),
(1014, NULL, 2, NULL),
(1014, NULL, 3, NULL),
(1014, NULL, 4, 'Paradise Barrens'),
(1014, NULL, 5, 'Paradise Barrens'),
-- Munkidori
(1015, NULL, 1, NULL),
(1015, NULL, 2, NULL),
(1015, NULL, 3, NULL),
(1015, NULL, 4, 'Wistful Fields'),
(1015, NULL, 5, 'Wistful Fields'),
-- Fezandipiti
(1016, NULL, 1, NULL),
(1016, NULL, 2, NULL),
(1016, NULL, 3, NULL),
(1016, NULL, 4, 'Oni Mountain'),
(1016, NULL, 5, 'Oni Mountain'),
-- Ogerpon
(1017, NULL, 1, NULL),
(1017, NULL, 2, NULL),
(1017, NULL, 3, NULL),
(1017, NULL, 4, 'Dreaded Den'),
(1017, NULL, 5, 'Dreaded Den'),
-- Archaludon
(1018, NULL, 1, NULL),
(1018, NULL, 2, NULL),
(1018, NULL, 3, NULL),
(1018, NULL, 4, 'Evolve Duraludon'),
(1018, NULL, 5, 'Evolve Duraludon'),
-- Hydrapple
(1019, NULL, 1, NULL),
(1019, NULL, 2, NULL),
(1019, NULL, 3, NULL),
(1019, NULL, 4, 'Evolve Dipplin'),
(1019, NULL, 5, 'Evolve Dipplin'),
-- Gouging Fire
(1020, NULL, 1, NULL),
(1020, NULL, 2, NULL),
(1020, NULL, 3, NULL),
(1020, NULL, 4, 'Area Zero'),
(1020, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Raging Bolt
(1021, NULL, 1, NULL),
(1021, NULL, 2, NULL),
(1021, NULL, 3, NULL),
(1021, NULL, 4, 'Area Zero'),
(1021, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Iron Boulder
(1022, NULL, 1, NULL),
(1022, NULL, 2, NULL),
(1022, NULL, 3, NULL),
(1022, NULL, 4, 'Trade from Pokémon Violet'),
(1022, NULL, 5, 'Area Zero'),
-- Iron Crown
(1023, NULL, 1, NULL),
(1023, NULL, 2, NULL),
(1023, NULL, 3, NULL),
(1023, NULL, 4, 'Trade from Pokémon Violet'),
(1023, NULL, 5, 'Area Zero'),
-- Terapagos
(1024, NULL, 1, NULL),
(1024, NULL, 2, NULL),
(1024, NULL, 3, NULL),
(1024, NULL, 4, 'Area Zero'),
(1024, NULL, 5, 'Area Zero'),
-- Pecharunt
(1025, NULL, 1, NULL),
(1025, NULL, 2, NULL),
(1025, NULL, 3, NULL),
(1025, NULL, 4, 'Loyalty Plaza'),
(1025, NULL, 5, 'Loyalty Plaza');

COMMIT TRANSACTION;