BEGIN TRANSACTION;

INSERT INTO Pokemon_Evolution (base_pokedex_number, evolved_pokedex_number, base_region_id, evolved_region_id, evolution_condition)
VALUES 
(1, 2, NULL, NULL, "Level 16"),
(2, 3, NULL, NULL, "Level 32"),
(4, 5, NULL, NULL, "Level 16"),
(5, 6, NULL, NULL, "Level 36"),
(7, 8, NULL, NULL, "Level 16"),
(8, 9, NULL, NULL, "Level 36"),
(10, 11, NULL, NULL, "Level 7"),
(11, 12, NULL, NULL, "Level 10"),
(13, 14, NULL, NULL, "Level 7"),
(14, 15, NULL, NULL, "Level 10"),
(16, 17, NULL, NULL, "Level 18"),
(17, 18, NULL, NULL, "Level 36"),
(19, 20, NULL, NULL, "Level 20"),
(19, 20, 1, 1, "Level 20 during Nighttime"),
(21, 22, NULL, NULL, "Level 20"),
(23, 24, NULL, NULL, "Level 22"),
(25, 26, NULL, NULL, "Use Thunder Stone Outside Alola"),
(25, 26, NULL, 1, "Use Thunder Stone in Alola"),
(27, 28, NULL, NULL, "Level 22"),
(27, 28, 1, 1, "Use Ice Stone"),
(29, 30, NULL, NULL, "Level 16"),
(30, 31, NULL, NULL, "Use Moon Stone"),
(32, 33, NULL, NULL, "Level 16"),
(33, 34, NULL, NULL, "Use Moon Stone"),
(35, 36, NULL, NULL, "Use Moon Stone"),
(37, 38, NULL, NULL, "Use Fire Stone"),
(37, 38, 1, 1, "Use Ice Stone"),
(39, 40, NULL, NULL, "Use Moon Stone"),
(41, 42, NULL, NULL, "Level 22"),
(43, 44, NULL, NULL, "Level 21"),
(44, 45, NULL, NULL, "Use Leaf Stone"),
(46, 47, NULL, NULL, "Level 24"),
(48, 49, NULL, NULL, "Level 31"),
(50, 51, NULL, NULL, "Level 26"),
(50, 51, 1, 1, "Level 26"),
(52, 53, NULL, NULL, "Level 28"),
(52, 53, 1, 1, "Level Up with Happiness Value at 220"),
(52, 863, 2, NULL, "Level 28"),
(54, 55, NULL, NULL, "Level 33"),
(56, 57, NULL, NULL, "Level 28"),
(57, 979, NULL, NULL, "Use Rage Fist 20 Times then Level Up"),
(58, 59, NULL, NULL, "Use Fire Stone"),
(58, 59, 3, 3, "Use Fire Stone"),
(60, 61, NULL, NULL, "Level 25"),
(61, 62, NULL, NULL, "Use Water Stone"),
(61, 186, NULL, NULL, "Trade while Holding Kings Rock"),
(63, 64, NULL, NULL, "Level 16"),
(64, 65, NULL, NULL, "Trade"),
(66, 67, NULL, NULL, "Level 28"),
(67, 68, NULL, NULL, "Trade"),
(69, 70, NULL, NULL, "Level 21"),
(70, 71, NULL, NULL, "Use Leaf Stone"),
(72, 73, NULL, NULL, "Level 30"),
(74, 75, NULL, NULL, "Level 25"),
(74, 75, 1, 1, "Level 25"),
(75, 76, NULL, NULL, "Trade"),
(75, 76, 1, 1, "Trade"),
(77, 78, NULL, NULL, "Level 40"),
(77, 78, 2, 2, "Level 40"),
(79, 80, NULL, NULL, "Level 37"),
(79, 80, 2, 2, "Use Galarcia Cuff"),
(79, 199, NULL, NULL, "Trade while Holding Kings Rock"),
(79, 199, 2, 2, "Use Galarcia Wreath"),
(81, 82, NULL, NULL, "Level 30"),
(82, 462, NULL, NULL, "Use Thunder Stone in Gen 8+ or Level Up in a Magnetic Field Area"),
(83, 865, 3, NULL, "Achieve 3 Critical Hits in One Battle then Level Up"),
(84, 85, NULL, NULL, "Level 31"),
(86, 87, NULL, NULL, "Level 34"),
(88, 89, NULL, NULL, "Level 38"),
(88, 89, 1, 1, "Level 38"),
(90, 91, NULL, NULL, "Use Water Stone"),
(92, 93, NULL, NULL, "Level 25"),
(93, 94, NULL, NULL, "Trade"),
(95, 208, NULL, NULL, "Trade while Holding Metal Coat"),
(96, 97, NULL, NULL, "Level 26"),
(98, 99, NULL, NULL, "Level 28"),
(100, 101, NULL, NULL, "Level 30"),
(100, 101, 3, 3, "Use Leaf Stone"),
(102, 103, NULL, NULL, "Use Leaf Stone Outside Alola"),
(102, 103, NULL, 2, "Use Leaf Stone in Alola"),
(104, 105, NULL, NULL, "Level 28 Outside Alola"),
(104, 105, NULL, 1, "Level 28 at Nighttime in Alola"),
(108, 463, NULL, NULL, "Level Up after Learning Rollout"),
(109, 110, NULL, NULL, "Level 35 Outside Galar"),
(109, 110, NULL, 2, "Level 35 in Galar"),
(111, 112, NULL, NULL, "Level 42"),
(112, 464, NULL, NULL, "Trade while Holding Protector"),
(113, 242, NULL, NULL, "Level Up with Happiness Value at 220"),
(114, 465, NULL, NULL, "Level Up after Learning Ancient Power"),
(116, 117, NULL, NULL, "Level 32"),
(117, 230, NULL, NULL, "Trade while Holding Dragon Scale"),
(118, 119, NULL, NULL, "Level 33"),
(120, 121, NULL, NULL, "Use Water Stone"),
(122, 866, 2, NULL, "Level 42"),
(123, 212, NULL, NULL, "Trade while Holding Metal Coat"),
(123, 900, NULL, NULL, "Use Black Augurite"),
(125, 466, NULL, NULL, "Trade while Holding Electrizer"),
(126, 467, NULL, NULL, "Trade while Holding Magmarizer"),
(129, 130, NULL, NULL, "Level 20"),
(133, 134, NULL, NULL, "Use Water Stone"),
(133, 135, NULL, NULL, "Use Thunder Stone"),
(133, 136, NULL, NULL, "Use Fire Stone"),
(133, 196, NULL, NULL, "Level Up with Happiness Value at 220 During Daytime"),
(133, 197, NULL, NULL, "Level Up with Happiness Value at 220 During Nighttime"),
(133, 470, NULL, NULL, "Use Leaf Stone or Level Up Near a Mossy Rock"),
(133, 471, NULL, NULL, "Use Ice Stone or Level Up Near a Icy Rock"),
(133, 700, NULL, NULL, "Level Up after Learning a Fairy-Type Move with Either 2 Affection Hearts in Gen 6-7 or Happiness Value at 220 in Gen 8+"),
(137, 233, NULL, NULL, "Trade Wwile Holding Upgrade"),
(138, 139, NULL, NULL, "Level 40"),
(140, 141, NULL, NULL, "Level 40"),
(147, 148, NULL, NULL, "Level 30"),
(148, 149, NULL, NULL, "Level 55"),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),
(, , NULL, NULL, ""),

COMMIT TRANSACTION;