BEGIN TRANSACTION;

INSERT INTO Pokemon_Location (pokedex_number, region_id, game_id, location_name)
VALUES 

-- Treecko
(252, NULL, 1, 'Breed Grovyle/Sceptile'),
(252, NULL, 2, 'Breed Grovyle/Sceptile'),
(252, NULL, 3, NULL),
(252, NULL, 4, 'Canyon Biome'),
(252, NULL, 5, 'Canyon Biome'),
-- Grovyle
(253, NULL, 1, 'Dynamax Adventures'),
(253, NULL, 2, 'Dynamax Adventures'),
(253, NULL, 3, NULL),
(253, NULL, 4, 'Evolve Treecko'),
(253, NULL, 5, 'Evolve Treecko'),
-- Sceptile
(254, NULL, 1, 'Dynamax Adventures'),
(254, NULL, 2, 'Dynamax Adventures'),
(254, NULL, 3, NULL),
(254, NULL, 4, 'Evolve Grovyle'),
(254, NULL, 5, 'Evolve Grovyle'),
-- Torchic
(255, NULL, 1, 'Breed Combusken/Blaziken'),
(255, NULL, 2, 'Breed Combusken/Blaziken'),
(255, NULL, 3, NULL),
(255, NULL, 4, 'Polar Biome'),
(255, NULL, 5, 'Polar Biome'),
-- Combusken
(256, NULL, 1, 'Dynamax Adventures'),
(256, NULL, 2, 'Dynamax Adventures'),
(256, NULL, 3, NULL),
(256, NULL, 4, 'Evolve Torchic'),
(256, NULL, 5, 'Evolve Torchic'),
-- Blaziken
(257, NULL, 1, 'Dynamax Adventures'),
(257, NULL, 2, 'Dynamax Adventures'),
(257, NULL, 3, NULL),
(257, NULL, 4, 'Evolve Combusken'),
(257, NULL, 5, 'Evolve Combusken'),
-- Mudkip
(258, NULL, 1, 'Breed Marshtomp/Swampert'),
(258, NULL, 2, 'Breed Marshtomp/Swampert'),
(258, NULL, 3, NULL),
(258, NULL, 4, 'Coastal Biome, Torchlit Labyrinth'),
(258, NULL, 5, 'Coastal Biome, Torchlit Labyrinth'),
-- Marshtomp
(259, NULL, 1, 'Dynamax Adventures'),
(259, NULL, 2, 'Dynamax Adventures'),
(259, NULL, 3, NULL),
(259, NULL, 4, 'Evolve Mudkip'),
(259, NULL, 5, 'Evolve Mudkip'),
-- Swampert
(260, NULL, 1, 'Dynamax Adventures'),
(260, NULL, 2, 'Dynamax Adventures'),
(260, NULL, 3, NULL),
(260, NULL, 4, 'Evolve Marshtomp'),
(260, NULL, 5, 'Evolve Marshtomp'),
-- Poochyena
(261, NULL, 1, NULL),
(261, NULL, 2, NULL),
(261, NULL, 3, NULL),
(261, NULL, 4, 'Apple Hills, Kitakami Road, Kitakami Wilds, Loyalty Plaza, Oni Mountain, Paradise Barrens, Timeless Woods<br>Fixed: Kitakami Road, Apple Hills<br>Tera Raid Battles: 1 Star Raid Battles'),
(261, NULL, 5, 'Apple Hills, Kitakami Road, Kitakami Wilds, Loyalty Plaza, Oni Mountain, Paradise Barrens, Timeless Woods<br>Fixed: Kitakami Road, Apple Hills<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Mightyena
(262, NULL, 1, NULL),
(262, NULL, 2, NULL),
(262, NULL, 3, NULL),
(262, NULL, 4, 'Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: Kitakami Road, Kitakami Wilds<br>Tera Raid Battles: 4 Star Raid Battles'),
(262, NULL, 5, 'Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: Kitakami Road, Kitakami Wilds<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Zigzagoon
(263, NULL, 1, 'Trade from Regina in Isle of Armor Area'),
(263, NULL, 2, 'Trade from Regina in Isle of Armor Area'),
(263, NULL, 3, NULL),
(263, NULL, 4, NULL),
(263, NULL, 5, NULL),
-- Galarian Zigzagoon
(263, 2, 1, 'Route 2, Route 3, Bridge Field, Giant''s Cap, Stony Wilderness<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Motostoke Riverbank, Stony Wilderness, West Lake Axewell'),
(263, 2, 2, 'Route 2, Route 3, Bridge Field, Giant''s Cap, Stony Wilderness<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Motostoke Riverbank, Stony Wilderness, West Lake Axewell'),
(263, 2, 3, NULL),
(263, 2, 4, NULL),
(263, 2, 5, NULL),
-- Linoone
(264, NULL, 1, 'Evolve Zigzagoo'),
(264, NULL, 2, 'Evolve Zigzagoo'),
(264, NULL, 3, NULL),
(264, NULL, 4, NULL),
(264, NULL, 5, NULL),
-- Galarian Linoone
(264, 2, 1, 'Bridge Field, Giant''s Cap<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Motostoke Riverbank, Stony Wilderness, West Lake Axewell'),
(264, 2, 2, 'Bridge Field, Giant''s Cap<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Motostoke Riverbank, Stony Wilderness, West Lake Axewell'),
(264, 2, 3, NULL),
(264, 2, 4, NULL),
(264, 2, 5, NULL),
-- Wurmple
(265, NULL, 1, NULL),
(265, NULL, 2, NULL),
(265, NULL, 3, 'Obsidian Fieldlands: Horseshoe Plains, Floaro Gardens, Heartwood or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(265, NULL, 4, NULL),
(265, NULL, 5, NULL),
-- Silcoon
(266, NULL, 1, NULL),
(266, NULL, 2, NULL),
(266, NULL, 3, 'Obsidian Fieldlands: Floaro Gardens, Heartwood or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(266, NULL, 4, NULL),
(266, NULL, 5, NULL),
-- Beautifly
(267, NULL, 1, NULL),
(267, NULL, 2, NULL),
(267, NULL, 3, 'Obsidian Fieldlands: Floaro Gardens, Heartwood, Grueling Grove or nearby<br>Cobalt Coastlands: Veilstone Cape or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(267, NULL, 4, NULL),
(267, NULL, 5, NULL),
-- Cascoon
(268, NULL, 1, NULL),
(268, NULL, 2, NULL),
(268, NULL, 3, 'Obsidian Fieldlands: Floaro Gardens, Heartwood or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(268, NULL, 4, NULL),
(268, NULL, 5, NULL),
-- Dustox
(269, NULL, 1, NULL),
(269, NULL, 2, NULL),
(269, NULL, 3, 'Obsidian Fieldlands: Floaro Gardens, Heartwood, Grueling Grove or nearby<br>Cobalt Coastlands: Veilstone Cape or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak'),
(269, NULL, 4, NULL),
(269, NULL, 5, NULL),
-- Lotad
(270, NULL, 1, 'Trade from Pokémon Shield'),
(270, NULL, 2, 'Route 2, Dappled Grove, Rolling Fields, West Lake Axewell<br>Max Raid Battles: Bridge Field, Dappled Grove, Stony Wilderness'),
(270, NULL, 3, NULL),
(270, NULL, 4, 'Apple Hills, Infernal Pass, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: Reveler''s Road<br>Tera Raid Battles: 2 Star Raid Battles'),
(270, NULL, 5, 'Apple Hills, Infernal Pass, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: Reveler''s Road<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Lombre
(271, NULL, 1, 'Trade from Pokémon Shield'),
(271, NULL, 2, 'Route 5, Dappled Grove, Giant''s Cap, Giant''s Seat, South Lake Miloch<br>Max Raid Battles: Bridge Field, Dappled Grove, Stony Wilderness'),
(271, NULL, 3, NULL),
(271, NULL, 4, 'Apple Hills, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: Mossfell Confluence<br>Tera Raid Battles: 3 Star Raid Battles'),
(271, NULL, 5, 'Apple Hills, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: Mossfell Confluence<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Ludicolo
(272, NULL, 1, 'Trade from Pokémon Shield'),
(272, NULL, 2, 'Dappled Grove<br>Max Raid Battles: Bridge Field, Dappled Grove, Stony Wilderness'),
(272, NULL, 3, NULL),
(272, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(272, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Seedot
(273, NULL, 1, 'Route 2, Dappled Grove, West Lake Axewell<br>Max Raid Battles: Bridge Field, Dappled Grove, Stony Wilderness'),
(273, NULL, 2, 'Trade from Pokémon Sword'),
(273, NULL, 3, NULL),
(273, NULL, 4, 'Fellhorn Gorge, Kitakami Hall, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Paradise Barrens, Reveler''s Road, Timeless Woods<br>Fixed: Reveler''s Road<br>Tera Raid Battles: 2 Star Raid Battles'),
(273, NULL, 5, 'Fellhorn Gorge, Kitakami Hall, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Paradise Barrens, Reveler''s Road, Timeless Woods<br>Fixed: Reveler''s Road<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Nuzleaf
(274, NULL, 1, 'Route 5, Dappled Grove, Giant''s Cap, Giant''s Seat, Rolling Fields, South Lake Miloch<br>Max Raid Battles: Bridge Field, Dappled Grove, Stony Wilderness'),
(274, NULL, 2, 'Trade from Pokémon Sword'),
(274, NULL, 3, NULL),
(274, NULL, 4, 'Fellhorn Gorge, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Paradise Barrens, Reveler''s Road, Timeless Woods<br>Fixed: Reveler''s Road, Timeless Woods<br>Tera Raid Battles: 3 Star Raid Battles'),
(274, NULL, 5, 'Fellhorn Gorge, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Paradise Barrens, Reveler''s Road, Timeless Woods<br>Fixed: Reveler''s Road, Timeless Woods<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Shiftry
(275, NULL, 1, 'Dappled Grove<br>Max Raid Battles: Bridge Field, Dappled Grove, Stony Wilderness, West Lake Axewell'),
(275, NULL, 2, 'Trade from Pokémon Sword'),
(275, NULL, 3, NULL),
(275, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(275, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Taillow
(276, NULL, 1, NULL),
(276, NULL, 2, NULL),
(276, NULL, 3, NULL),
(276, NULL, 4, NULL),
(276, NULL, 5, NULL),
-- Swellow
(277, NULL, 1, NULL),
(277, NULL, 2, NULL),
(277, NULL, 3, NULL),
(277, NULL, 4, NULL),
(277, NULL, 5, NULL),
-- Wingull
(278, NULL, 1, 'East Lake Axewell, North Lake Miloch, Rolling Fields, South Lake Miloch, Watchtower Ruins, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills'),
(278, NULL, 2, 'East Lake Axewell, North Lake Miloch, Rolling Fields, South Lake Miloch, Watchtower Ruins, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills'),
(278, NULL, 3, NULL),
(278, NULL, 4, 'South Paldean Sea, West Paldean Sea<br>Tera Raid Battles: 1 Star Raid Battles'),
(278, NULL, 5, 'South Paldean Sea, West Paldean Sea<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Pelipper
(279, NULL, 1, 'Route 9, Axew''s Eye, Bridge Field, Dusty Bowl, Hammerlocke Hills, Lake of Outrage, North Lake Miloch, Rolling Fields, Fields of Honor, Challenge Beach, Loop Lagoon, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea<br>Dynamax Adventures'),
(279, NULL, 2, 'Route 9, Axew''s Eye, Bridge Field, Dusty Bowl, Hammerlocke Hills, Lake of Outrage, North Lake Miloch, Rolling Fields, Fields of Honor, Challenge Beach, Loop Lagoon, Training Lowlands, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea<br>Dynamax Adventures'),
(279, NULL, 3, NULL),
(279, NULL, 4, 'North Paldean Sea, West Paldean Sea<br>Tera Raid Battles: 3 Star Raid Battles , 6 Star Raid Battles'),
(279, NULL, 5, 'North Paldean Sea, West Paldean Sea<br>Tera Raid Battles: 3 Star Raid Battles , 6 Star Raid Battles'),
-- Ralts
(280, NULL, 1, 'Dappled Grove, North Lake Miloch, Rolling Fields, South Lake Miloch, Watchtower Ruins, West Lake Axewell, Fields of Honor<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Watchtower Ruins, Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea'),
(280, NULL, 2, 'Dappled Grove, North Lake Miloch, Rolling Fields, South Lake Miloch, Watchtower Ruins, West Lake Axewell, Fields of Honor<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Watchtower Ruins, Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea'),
(280, NULL, 3, 'Crimson Mirelands: Gapejaw Bog, Shrouded Ruins or nearby<br>Alabaster Icelands: Heart''s Crag, Snowpoint Temple or nearby<br>Alabaster Icelands: Massive Mass Outbreak'),
(280, NULL, 4, 'South Province Area One<br>Fixed: South Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
(280, NULL, 5, 'South Province Area One<br>Fixed: South Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Kirlia
(281, NULL, 1, 'Rolling Fields<br>Max Raid Battles: Bridge Field, Lake of Outrage, Motostoke Riverbank, Stony Wilderness, Watchtower Ruins, Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Training Lowlands, Stepping-Stone Sea, Insular Sea'),
(281, NULL, 2, 'Rolling Fields<br>Max Raid Battles: Bridge Field, Lake of Outrage, Motostoke Riverbank, Stony Wilderness, Watchtower Ruins, Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Training Lowlands, Stepping-Stone Sea, Insular Sea'),
(281, NULL, 3, 'Crimson Mirelands: Shrouded Ruins or nearby<br>Alabaster Icelands: Heart''s Crag, Snowpoint Temple or nearby<br>Alabaster Icelands: Massive Mass Outbreak'),
(281, NULL, 4, 'Cortondo, Dalizapa Passage, East Province Area Two, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: East Province Area Three, Kitakami Wilds, Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
(281, NULL, 5, 'Cortondo, Dalizapa Passage, East Province Area Two, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Fixed: East Province Area Three, Kitakami Wilds, Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Gardevoir
(282, NULL, 1, 'Dusty Bowl, Lake of Outrage, Rolling Fields, Forest of Focus, Training Lowlands<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Watchtower Ruins, Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Training Lowlands, Stepping-Stone Sea, Insular Sea'),
(282, NULL, 2, 'Dusty Bowl, Lake of Outrage, Rolling Fields, Forest of Focus, Training Lowlands<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Watchtower Ruins, Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Training Lowlands, Stepping-Stone Sea, Insular Sea'),
(282, NULL, 3, 'Alabaster Icelands: Heart''s Crag or nearby<br>Alabaster Icelands: Massive Mass Outbreak'),
(282, NULL, 4, 'Glaseado Mountain<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(282, NULL, 5, 'Glaseado Mountain<br>Fixed: Glaseado Mountain<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Surskit
(283, NULL, 1, NULL),
(283, NULL, 2, NULL),
(283, NULL, 3, NULL),
(283, NULL, 4, 'South Province Area One, South Province Area Two, South Province Area Five, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Paradise Barrens, Timeless Woods<br>Tera Raid Battles: 1 Star Raid Battles'),
(283, NULL, 5, 'South Province Area One, South Province Area Two, South Province Area Five, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Paradise Barrens, Timeless Woods<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Masquerain
(284, NULL, 1, NULL),
(284, NULL, 2, NULL),
(284, NULL, 3, NULL),
(284, NULL, 4, 'South Province Area One, South Province Area Five, Kitakami Wilds, Mossfell Confluence<br>Fixed: Oni Mountain<br>Tera Raid Battles: 4 Star Raid Battles'),
(284, NULL, 5, 'South Province Area One, South Province Area Five, Kitakami Wilds, Mossfell Confluence<br>Fixed: Oni Mountain<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Shroomish
(285, NULL, 1, NULL),
(285, NULL, 2, NULL),
(285, NULL, 3, NULL),
(285, NULL, 4, 'South Province Area Three, South Province Area Five, West Province Area Three<br>Tera Raid Battles: 1 Star Raid Battles'),
(285, NULL, 5, 'South Province Area Three, South Province Area Five, West Province Area Three<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Breloom
(286, NULL, 1, NULL),
(286, NULL, 2, NULL),
(286, NULL, 3, NULL),
(286, NULL, 4, 'West Province Area Three<br>Fixed: West Province Area Three<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(286, NULL, 5, 'West Province Area Three<br>Fixed: West Province Area Three<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Slakoth
(287, NULL, 1, NULL),
(287, NULL, 2, NULL),
(287, NULL, 3, NULL),
(287, NULL, 4, 'South Province Area One, South Province Area Three, South Province Area Five, Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
(287, NULL, 5, 'South Province Area One, South Province Area Three, South Province Area Five, Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Vigoroth
(288, NULL, 1, NULL),
(288, NULL, 2, NULL),
(288, NULL, 3, NULL),
(288, NULL, 4, 'Dalizapa Passage, North Province Area One, South Province Area Three, South Province Area Five, West Province Area Three, Coastal Biome<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(288, NULL, 5, 'Dalizapa Passage, North Province Area One, South Province Area Three, South Province Area Five, West Province Area Three, Coastal Biome<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Slaking
(289, NULL, 1, NULL),
(289, NULL, 2, NULL),
(289, NULL, 3, NULL),
(289, NULL, 4, 'North Province Area Two, Socarrat Trail, Costal Biome<br>Fixed: North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles'),
(289, NULL, 5, 'North Province Area Two, Socarrat Trail, Costal Biome<br>Fixed: North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Nincada
(290, NULL, 1, 'Route 5, South Lake Miloch, West Lake Axewell<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields'),
(290, NULL, 2, 'Route 5, South Lake Miloch, West Lake Axewell<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields'),
(290, NULL, 3, NULL),
(290, NULL, 4, NULL),
(290, NULL, 5, NULL),
-- Ninjask
(291, NULL, 1, 'Rolling Fields, Stony Wilderness<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, Training Lowlands<br>Dynamax Adventures'),
(291, NULL, 2, 'Rolling Fields, Stony Wilderness<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, Training Lowlands<br>Dynamax Adventures'),
(291, NULL, 3, NULL),
(291, NULL, 4, NULL),
(291, NULL, 5, NULL),
-- Shedinja
(292, NULL, 1, 'Max Raid Battles: Bridge Field, Rolling Fields, South Lake Miloch'),
(292, NULL, 2, 'Max Raid Battles: Bridge Field, Rolling Fields, South Lake Miloch'),
(292, NULL, 3, NULL),
(292, NULL, 4, NULL),
(292, NULL, 5, NULL),
-- Whismur
(293, NULL, 1, 'Brawlers'' Cave<br>Max Raid Battles: Soothing Wetlands, Courageous Cavern, Training Lowlands'),
(293, NULL, 2, 'Brawlers'' Cave<br>Max Raid Battles: Soothing Wetlands, Courageous Cavern, Training Lowlands'),
(293, NULL, 3, NULL),
(293, NULL, 4, NULL),
(293, NULL, 5, NULL),
-- Loudred
(294, NULL, 1, 'Brawlers'' Cave<br>Max Raid Battles: Soothing Wetlands, Courageous Cavern, Training Lowlands'),
(294, NULL, 2, 'Brawlers'' Cave<br>Max Raid Battles: Soothing Wetlands, Courageous Cavern, Training Lowlands'),
(294, NULL, 3, NULL),
(294, NULL, 4, NULL),
(294, NULL, 5, NULL),
-- Exploud
(295, NULL, 1, 'Max Raid Battles: Soothing Wetlands, Courageous Cavern, Training Lowlands<br>Dynamax Adventures'),
(295, NULL, 2, 'Max Raid Battles: Soothing Wetlands, Courageous Cavern, Training Lowlands<br>Dynamax Adventures'),
(295, NULL, 3, NULL),
(295, NULL, 4, NULL),
(295, NULL, 5, NULL),
-- Makuhita
(296, NULL, 1, NULL),
(296, NULL, 2, NULL),
(296, NULL, 3, NULL),
(296, NULL, 4, 'Asado Desert, East Province Area One, East Province Area Two, East Province Area Three, South Province Area One, South Province Area Three, South Province Area Five, West Province Area One<br>Tera Raid Battles: 1 Star Raid Battles , 3 Star Raid Battles'),
(296, NULL, 5, 'Asado Desert, East Province Area One, East Province Area Two, East Province Area Three, South Province Area One, South Province Area Three, South Province Area Five, West Province Area One<br>Tera Raid Battles: 1 Star Raid Battles , 3 Star Raid Battles'),
-- Hariyama
(297, NULL, 1, NULL),
(297, NULL, 2, NULL),
(297, NULL, 3, NULL),
(297, NULL, 4, 'Alfornada Cavern, Dalizapa Passage, East Province Area Three, Glaseado Mountain, West Province Area Two, West Province Area Three<br>Fixed: East Province Area Three, South Province Area Three, South Province Area Six, West Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles'),
(297, NULL, 5, 'Alfornada Cavern, Dalizapa Passage, East Province Area Three, Glaseado Mountain, West Province Area Two, West Province Area Three<br>Fixed: East Province Area Three, South Province Area Three, South Province Area Six, West Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Azurill
(298, NULL, 1, 'Brawlers'' Cave<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea'),
(298, NULL, 2, 'Brawlers'' Cave<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea'),
(298, NULL, 3, NULL),
(298, NULL, 4, 'East Province Area One, South Province Area One, South Province Area Two, South Province Area Five<br>South Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
(298, NULL, 5, 'East Province Area One, South Province Area One, South Province Area Two, South Province Area Five<br>South Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Nosepass
(299, NULL, 1, NULL),
(299, NULL, 2, NULL),
(299, NULL, 3, 'Coronet Highlands: Celestica Ruins, Primeval Grotto or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(299, NULL, 4, 'Kitakami Wilds, Oni Mountain, Paradise Barrens, Wistful Fields<br>Fixed: Paradise Barrens, Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
(299, NULL, 5, 'Kitakami Wilds, Oni Mountain, Paradise Barrens, Wistful Fields<br>Fixed: Paradise Barrens, Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Skitty
(300, NULL, 1, NULL),
(300, NULL, 2, NULL),
(300, NULL, 3, NULL),
(300, NULL, 4, NULL),
(300, NULL, 5, NULL),
-- Delcatty
(301, NULL, 1, NULL),
(301, NULL, 2, NULL),
(301, NULL, 3, NULL),
(301, NULL, 4, NULL),
(301, NULL, 5, NULL),
-- Sableye
(302, NULL, 1, 'Trade from Pokémon Shield'),
(302, NULL, 2, 'Dusty Bowl, Lakeside Cave<br>Max Raid Battles: Giant''s Mirror, South Lake Miloch, Stony Wilderness, Watchtower Ruins, West Lake Axewell, Slippery Slope, Giant''s Bed, Old Cemetery, Snowslide Slope, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(302, NULL, 3, NULL),
(302, NULL, 4, 'Alfornada Cavern, Dalizapa Passage, East Province Area Three, North Province Area One, West Province Area One, West Province Area Two<br>Fixed: South Province Area Six<br>Tera Raid Battles: 3 Star Raid Battles , 5 Star Raid Battles'),
(302, NULL, 5, 'Alfornada Cavern, Dalizapa Passage, East Province Area Three, North Province Area One, West Province Area One, West Province Area Two<br>Fixed: South Province Area Six<br>Tera Raid Battles: 3 Star Raid Battles , 5 Star Raid Battles'),
-- Mawile
(303, NULL, 1, 'Bridge Field, Dusty Bowl, Giant''s Mirror, Lakeside Cave<br>Max Raid Battles: Bridge Field, Giant''s Seat, Hammerlocke Hills, Lake of Outrage, Rolling Fields, Stony Wilderness, Slippery Slope, Giant''s Bed, Old Cemetery, Snowslide Slope, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(303, NULL, 2, 'Trade from Pokémon Sword'),
(303, NULL, 3, NULL),
(303, NULL, 4, NULL),
(303, NULL, 5, NULL),
-- Aron
(304, NULL, 1, 'Ballimere Lake, Lakeside Cave<br>Max Raid Battles: Slippery Slope, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Ballimere Lake'),
(304, NULL, 2, 'Ballimere Lake, Lakeside Cave<br>Max Raid Battles: Slippery Slope, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Ballimere Lake'),
(304, NULL, 3, NULL),
(304, NULL, 4, NULL),
(304, NULL, 5, NULL),
-- Lairon
(305, NULL, 1, 'Lakeside Cave<br>Max Raid Battles: Slippery Slope, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(305, NULL, 2, 'Lakeside Cave<br>Max Raid Battles: Slippery Slope, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(305, NULL, 3, NULL),
(305, NULL, 4, NULL),
(305, NULL, 5, NULL),
-- Aggron
(306, NULL, 1, 'Lakeside Cave<br>Max Raid Battles: Slippery Slope, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Ballimere Lake'),
(306, NULL, 2, 'Lakeside Cave<br>Max Raid Battles: Slippery Slope, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Ballimere Lake'),
(306, NULL, 3, NULL),
(306, NULL, 4, NULL),
(306, NULL, 5, NULL),
-- Meditite
(307, NULL, 1, NULL),
(307, NULL, 2, NULL),
(307, NULL, 3, NULL),
(307, NULL, 4, 'Alfornada Cavern, South Province Area Four, West Province Area Two<br>Fixed: South Province Area Six<br>Tera Raid Battles: 2 Star Raid Battles'),
(307, NULL, 5, 'Alfornada Cavern, South Province Area Four, West Province Area Two<br>Fixed: South Province Area Six<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Medicham
(308, NULL, 1, NULL),
(308, NULL, 2, NULL),
(308, NULL, 3, NULL),
(308, NULL, 4, 'Alfornada Cavern<br>Fixed: South Province Area Six<br>Tera Raid Battles: 6 Star Raid Battles'),
(308, NULL, 5, 'Alfornada Cavern<br>Fixed: South Province Area Six<br>Tera Raid Battles: 6 Star Raid Battles'),
-- Electrike
(309, NULL, 1, 'Route 4, Dappled Grove, Dusty Bowl, East Lake Axewell, Giant''s Seat, Rolling Fields, South Lake Miloch, Watchtower Ruins, West Lake Axewell<br>Max Raid Battles: Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank'),
(309, NULL, 2, 'Route 4, Dappled Grove, Dusty Bowl, East Lake Axewell, Giant''s Seat, Rolling Fields, South Lake Miloch, Watchtower Ruins, West Lake Axewell<br>Max Raid Battles: Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank'),
(309, NULL, 3, NULL),
(309, NULL, 4, NULL),
(309, NULL, 5, NULL),
-- Manectric
(310, NULL, 1, 'Axew''s Eye, Giant''s Cap, Giant''s Seat, Rolling Fields<br>Max Raid Battles: Giant''s Cap, Motostoke Riverbank, Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea'),
(310, NULL, 2, 'Axew''s Eye, Giant''s Cap, Giant''s Seat, Rolling Fields<br>Max Raid Battles: Giant''s Cap, Motostoke Riverbank, Fields of Honor, Forest of Focus, Challenge Beach, Honeycalm Sea'),
(310, NULL, 3, NULL),
(310, NULL, 4, NULL),
(310, NULL, 5, NULL),
-- Plusle
(311, NULL, 1, NULL),
(311, NULL, 2, NULL),
(311, NULL, 3, NULL),
(311, NULL, 4, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(311, NULL, 5, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Minun
(312, NULL, 1, NULL),
(312, NULL, 2, NULL),
(312, NULL, 3, NULL),
(312, NULL, 4, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(312, NULL, 5, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Volbeat
(313, NULL, 1, NULL),
(313, NULL, 2, NULL),
(313, NULL, 3, NULL),
(313, NULL, 4, 'Apple Hills, Fellhorn Gorge, Kitakami Road, Kitakami Wilds, Loyalty Plaza, Mossfell Confluence, Reveler''s Road, Timeless Woods, Wistful Fields<br>Tera Raid Battles: 2 Star Raid Battles, 4 Star Raid Battles'),
(313, NULL, 5, 'Apple Hills, Fellhorn Gorge, Kitakami Road, Kitakami Wilds, Loyalty Plaza, Mossfell Confluence, Reveler''s Road, Timeless Woods, Wistful Fields<br>Tera Raid Battles: 2 Star Raid Battles, 4 Star Raid Battles'),
-- Illumise
(314, NULL, 1, NULL),
(314, NULL, 2, NULL),
(314, NULL, 3, NULL),
(314, NULL, 4, 'Apple Hills, Fellhorn Gorge, Kitakami Road, Kitakami Wilds, Loyalty Plaza, Mossfell Confluence, Reveler''s Road, Timeless Woods, Wistful Fields<br>Tera Raid Battles: 2 Star Raid Battles, 4 Star Raid Battles'),
(314, NULL, 5, 'Apple Hills, Fellhorn Gorge, Kitakami Road, Kitakami Wilds, Loyalty Plaza, Mossfell Confluence, Reveler''s Road, Timeless Woods, Wistful Fields<br>Tera Raid Battles: 2 Star Raid Battles, 4 Star Raid Battles'),
-- Roselia
(315, NULL, 1, 'Axew''s Eye, Dusty Bowl, Giant''s Mirror, Rolling Fields, South Lake Miloch<br>Max Raid Battles: Bridge Field, Dappled Grove, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Motostoke Riverbank, North Lake Miloch, Stony Wilderness, Forest of Focus, Training Lowlands<br>Dynamax Adventures'),
(315, NULL, 2, 'Axew''s Eye, Dusty Bowl, Giant''s Mirror, Rolling Fields, South Lake Miloch<br>Max Raid Battles: Bridge Field, Dappled Grove, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Motostoke Riverbank, North Lake Miloch, Stony Wilderness, Forest of Focus, Training Lowlands<br>Dynamax Adventures'),
(315, NULL, 3, 'Crimson Mirelands: Gapejaw Bog, Cloudpool Ridge or nearby<br>Coronet Highlands: Fabled Spring or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(315, NULL, 4, NULL),
(315, NULL, 5, NULL),
-- Gulpin
(316, NULL, 1, NULL),
(316, NULL, 2, NULL),
(316, NULL, 3, NULL),
(316, NULL, 4, 'Trade from Pokémon Violet'),
(316, NULL, 5, 'East Province Area One, South Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Swalot
(317, NULL, 1, NULL),
(317, NULL, 2, NULL),
(317, NULL, 3, NULL),
(317, NULL, 4, 'Trade from Pokémon Violet'),
(317, NULL, 5, 'Casseroya Lake<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Carvanha
(318, NULL, 1, 'Training Lowlands<br>Max Raid Battles: Soothing Wetlands, Challenge Road, Workout Sea, Honeycalm Sea'),
(318, NULL, 2, 'Training Lowlands<br>Max Raid Battles: Soothing Wetlands, Challenge Road, Workout Sea, Honeycalm Sea'),
(318, NULL, 3, NULL),
(318, NULL, 4, NULL),
(318, NULL, 5, NULL),
-- Sharpedo
(319, NULL, 1, 'Training Lowlands, Stepping-Stone Sea, Insular Sea, Honeycalm Sea<br>Max Raid Battles: Soothing Wetlands, Challenge Road, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea<br>Dynamax Adventures'),
(319, NULL, 2, 'Training Lowlands, Stepping-Stone Sea, Insular Sea, Honeycalm Sea<br>Max Raid Battles: Soothing Wetlands, Challenge Road, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea<br>Dynamax Adventures'),
(319, NULL, 3, NULL),
(319, NULL, 4, NULL),
(319, NULL, 5, NULL),
-- Wailmer
(320, NULL, 1, 'Route 9, Motostoke Riverbank, Honeycalm Sea, Honeycalm Island, Frigid Sea<br>Max Raid Battles: Bridge Field, East Lake Axewell, Lake of Outrage, North Lake Miloch, South Lake Miloch, West Lake Axewell, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea<br>Dynamax Adventures'),
(320, NULL, 2, 'Route 9, Motostoke Riverbank, Honeycalm Sea, Honeycalm Island, Frigid Sea<br>Max Raid Battles: Bridge Field, East Lake Axewell, Lake of Outrage, North Lake Miloch, South Lake Miloch, West Lake Axewell, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea<br>Dynamax Adventures'),
(320, NULL, 3, NULL),
(320, NULL, 4, NULL),
(320, NULL, 5, NULL),
-- Wailord
(321, NULL, 1, 'Route 9, Workout Sea<br>Max Raid Battles: Bridge Field, East Lake Axewell, Lake of Outrage, North Lake Miloch, South Lake Miloch, West Lake Axewell, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea'),
(321, NULL, 2, 'Route 9, Workout Sea<br>Max Raid Battles: Bridge Field, East Lake Axewell, Lake of Outrage, North Lake Miloch, South Lake Miloch, West Lake Axewell, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea'),
(321, NULL, 3, NULL),
(321, NULL, 4, NULL),
(321, NULL, 5, NULL),
-- Numel
(322, NULL, 1, NULL),
(322, NULL, 2, NULL),
(322, NULL, 3, NULL),
(322, NULL, 4, 'Area Zero, West Province Area One, Coastal Biome, Polar Biome, Torchlit Labyrinth<br>Tera Raid Battles: 3 Star Raid Battles'),
(322, NULL, 5, 'Area Zero, West Province Area One, Coastal Biome, Polar Biome, Torchlit Labyrinth<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Camerupt
(323, NULL, 1, NULL),
(323, NULL, 2, NULL),
(323, NULL, 3, NULL),
(323, NULL, 4, 'Area Zero, North Province Area Two, Coastal Biome, Polar Biome, Torchlit Labyrinth<br>Tera Raid Battles: 5 Star Raid Battles'),
(323, NULL, 5, 'Area Zero, North Province Area Two, Coastal Biome, Polar Biome, Torchlit Labyrinth<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Torkoal
(324, NULL, 1, 'Route 6, Giant''s Cap, Giant''s Mirror, Motostoke Riverbank, Warm-Up Tunnel, Potbottom Desert<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert<br>Dynamax Adventures'),
(324, NULL, 2, 'Route 6, Giant''s Cap, Giant''s Mirror, Motostoke Riverbank, Warm-Up Tunnel, Potbottom Desert<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert<br>Dynamax Adventures'),
(324, NULL, 3, NULL),
(324, NULL, 4, 'East Province Area Three, Coastal Biome, Torchlit Labyrinth<br>Fixed: West Province Area One, Costal Biome<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
(324, NULL, 5, 'East Province Area Three, Coastal Biome, Torchlit Labyrinth<br>Fixed: West Province Area One, Costal Biome<br>Tera Raid Battles: 4 Star Raid Battles , 6 Star Raid Battles'),
-- Spoink
(325, NULL, 1, NULL),
(325, NULL, 2, NULL),
(325, NULL, 3, NULL),
(325, NULL, 4, 'South Province Area Three, Chilling Waterhead, Infernal Pass, Oni Mountain, Paradise Barrens, Wistful Fields<br>Fixed: Infernal Pass<br>Tera Raid Battles: 2 Star Raid Battles'),
(325, NULL, 5, 'South Province Area Three, Chilling Waterhead, Infernal Pass, Oni Mountain, Paradise Barrens, Wistful Fields<br>Fixed: Infernal Pass<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Grumpig
(326, NULL, 1, NULL),
(326, NULL, 2, NULL),
(326, NULL, 3, NULL),
(326, NULL, 4, 'Dalizapa Passage, North Province Area One, North Province Area Two<br>Fixed South Province Area Four<br>Tera Raid Battles: 4 Star Raid Battles'),
(326, NULL, 5, 'Dalizapa Passage, North Province Area One, North Province Area Two<br>Fixed South Province Area Four<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Spinda
(327, NULL, 1, NULL),
(327, NULL, 2, NULL),
(327, NULL, 3, NULL),
(327, NULL, 4, NULL),
(327, NULL, 5, NULL),
-- Trapinch
(328, NULL, 1, 'Route 6<br>Max Raid Battles: Axew''s Eye, Dusty Bowl, Rolling Fields, Challenge Beach, Courageous Cavern, Stepping-Stone Sea'),
(328, NULL, 2, 'Route 6<br>Max Raid Battles: Axew''s Eye, Dusty Bowl, Rolling Fields, Challenge Beach, Courageous Cavern, Stepping-Stone Sea'),
(328, NULL, 3, NULL),
(328, NULL, 4, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
(328, NULL, 5, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Vibrava
(329, NULL, 1, 'Max Raid Battles: Dusty Bowl, Rolling Fields'),
(329, NULL, 2, 'Max Raid Battles: Axew''s Eye, Dusty Bowl, Rolling Fields'),
(329, NULL, 3, NULL),
(329, NULL, 4, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(329, NULL, 5, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Flygon
(330, NULL, 1, 'Dusty Bowl, Lake of Outrage<br>Max Raid Battles: Dusty Bowl, Rolling Fields, Challenge Beach, Courageous Cavern, Stepping-Stone Sea'),
(330, NULL, 2, 'Dusty Bowl, Lake of Outrage<br>Max Raid Battles: Dusty Bowl, Rolling Fields, Challenge Beach, Courageous Cavern, Stepping-Stone Sea'),
(330, NULL, 3, NULL),
(330, NULL, 4, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(330, NULL, 5, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Cacnea
(331, NULL, 1, NULL),
(331, NULL, 2, NULL),
(331, NULL, 3, NULL),
(331, NULL, 4, 'Asado Desert<br>Tera Raid Battles: 2 Star Raid Battles'),
(331, NULL, 5, 'Asado Desert<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Cacturne
(332, NULL, 1, NULL),
(332, NULL, 2, NULL),
(332, NULL, 3, NULL),
(332, NULL, 4, 'Fixed: Asado Desert<br>Tera Raid Battles: 4 Star Raid Battles'),
(332, NULL, 5, 'Fixed: Asado Desert<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Swablu
(333, NULL, 1, 'Slippery Slope, Frostpoint Field, Giant''s Bed, Path to the Peak, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Slippery Slope, Frostpoint Field, Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(333, NULL, 2, 'Slippery Slope, Frostpoint Field, Giant''s Bed, Path to the Peak, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Slippery Slope, Frostpoint Field, Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(333, NULL, 3, NULL),
(333, NULL, 4, 'East Province Area One, South Province Area Five, South Province Area Three, South Province Area Four, South Province Area Six, West Province Area One, Caynon Biome<br>Fixed: Casseroya Lake, West Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
(333, NULL, 5, 'East Province Area One, South Province Area Five, South Province Area Three, South Province Area Four, South Province Area Six, West Province Area One, Caynon Biome<br>Fixed: Casseroya Lake, West Province Area One<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Altaria
(334, NULL, 1, 'Giant''s Bed, Path to the Peak, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Max Raid Battles: Slippery Slope, Frostpoint Field, Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake, Dyna Tree Hill<br>Dynamax Adventures'),
(334, NULL, 2, 'Giant''s Bed, Path to the Peak, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Max Raid Battles: Slippery Slope, Frostpoint Field, Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake, Dyna Tree Hill<br>Dynamax Adventures'),
(334, NULL, 3, NULL),
(334, NULL, 4, 'Casseroya Lake, North Province Area One, North Province Area Two, South Province Area Six, West Province Area Three, Canyon Biome<br>Fixed: Casseroya Lake, South Province Area Six, West Province Area One, Canyon Biome<br>Tera Raid Battles: 5 Star Raid Battles'),
(334, NULL, 5, 'Casseroya Lake, North Province Area One, North Province Area Two, South Province Area Six, West Province Area Three, Canyon Biome<br>Fixed: Casseroya Lake, South Province Area Six, West Province Area One, Canyon Biome<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Zangoose
(335, NULL, 1, NULL),
(335, NULL, 2, NULL),
(335, NULL, 3, NULL),
(335, NULL, 4, 'South Province Area Three, South Province Area Five, Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 3 Star Raid Battles, 4 Star Raid Battles'),
(335, NULL, 5, 'South Province Area Three, South Province Area Five, Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 3 Star Raid Battles, 4 Star Raid Battles'),
-- Seviper
(336, NULL, 1, NULL),
(336, NULL, 2, NULL),
(336, NULL, 3, NULL),
(336, NULL, 4, 'South Province Area Three, South Province Area Five, Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 3 Star Raid Battles, 4 Star Raid Battles'),
(336, NULL, 5, 'South Province Area Three, South Province Area Five, Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 3 Star Raid Battles, 4 Star Raid Battles'),
-- Lunatone
(337, NULL, 1, 'Trade from Pokémon Shield'),
(337, NULL, 2, 'Route 8, Giant''s Cap<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins'),
(337, NULL, 3, NULL),
(337, NULL, 4, NULL),
(337, NULL, 5, NULL),
-- Solrock
(338, NULL, 1, 'Route 8, Giant''s Cap<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins'),
(338, NULL, 2, 'Trade from Pokémon Sword'),
(338, NULL, 3, NULL),
(338, NULL, 4, NULL),
(338, NULL, 5, NULL),
-- Barboach
(339, NULL, 1, 'Galar Mine No. 2, Motostoke, North Lake Miloch, Slumbering Weald, South Lake Miloch, Stony Wilderness, Soothing Wetlands, Brawlers'' Cave, Giant''s Bed, Giant''s Foot, Roaring-Sea Caves, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dusty Bowl, Rolling Fields, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern'),
(339, NULL, 2, 'Galar Mine No. 2, Motostoke, North Lake Miloch, Slumbering Weald, South Lake Miloch, Stony Wilderness, Soothing Wetlands, Brawlers'' Cave, Giant''s Bed, Giant''s Foot, Roaring-Sea Caves, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dusty Bowl, Rolling Fields, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern'),
(339, NULL, 3, 'Crimson Mirelands: Gapejaw Bog, Lake Valor or nearby<br>Coronet Highlands: Wayward Cave or nearby'),
(339, NULL, 4, 'East Province Area Three, South Province Area Two, South Province Area Four, South Province Area Five, Tagtree Thicket, West Province Area Two, Crystal Pool, Fellhorn Gorge, Oni Mountain<br>Fixed: Mossfell Confluence<br>Tera Raid Battles: 1 Star Raid Battles'),
(339, NULL, 5, 'East Province Area Three, South Province Area Two, South Province Area Four, South Province Area Five, Tagtree Thicket, West Province Area Two, Crystal Pool, Fellhorn Gorge, Oni Mountain<br>Fixed: Mossfell Confluence<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Whiscash
(340, NULL, 1, 'Slumbering Weald, South Lake Miloch, Soothing Wetlands, Brawlers'' Cave, Courageous Cavern, Giant''s Bed, Giant''s Foot, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dusty Bowl, Rolling Fields, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern, Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(340, NULL, 2, 'Slumbering Weald, South Lake Miloch, Soothing Wetlands, Brawlers'' Cave, Courageous Cavern, Giant''s Bed, Giant''s Foot, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dusty Bowl, Rolling Fields, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern, Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(340, NULL, 3, 'Crimson Mirelands: Gapejaw Bog, Lake Valor or nearby<br>Coronet Highlands: Wayward Cave or nearby'),
(340, NULL, 4, 'Glaseado Mountain, North Province Area One, South Province Area Six, Tagtree Thicket, West Province Area Three, Fellhorn Gorge, Kitakami Wilds<br>Fixed: Oni Mountain<br>Tera Raid Battles: 4 Star Raid Battles'),
(340, NULL, 5, 'Glaseado Mountain, North Province Area One, South Province Area Six, Tagtree Thicket, West Province Area Three, Fellhorn Gorge, Kitakami Wilds<br>Fixed: Oni Mountain<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Corphish
(341, NULL, 1, 'Galar Mine No. 2, Giant''s Cap, South Lake Miloch, Soothing Wetlands, Forest of Focus, Challenge Beach, Training Lowlands<br>Max Raid Battles: Dusty Bowl, Giant''s Mirror, South Lake Miloch, West Lake Axewell, Fields of Honor, Soothing Wetlands, Courageous Cavern'),
(341, NULL, 2, 'Galar Mine No. 2, Giant''s Cap, South Lake Miloch, Soothing Wetlands, Forest of Focus, Challenge Beach, Training Lowlands<br>Max Raid Battles: Dusty Bowl, Giant''s Mirror, South Lake Miloch, West Lake Axewell, Fields of Honor, Soothing Wetlands, Courageous Cavern'),
(341, NULL, 3, NULL),
(341, NULL, 4, 'Fellhorn Gorge, Kitakami Road, Mossfell Confluence, Reveler''s Road<br>Tera Raid Battles: 2 Star Raid Battles'),
(341, NULL, 5, 'Fellhorn Gorge, Kitakami Road, Mossfell Confluence, Reveler''s Road<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Crawdaunt
(342, NULL, 1, 'Axew''s Eye, Giant''s Seat, South Lake Miloch, Turffield, Forest of Focus, Challenge Beach, Training Lowlands<br>Max Raid Battles: Dusty Bowl, Giant''s Mirror, South Lake Miloch, Stony Wilderness, West Lake Axewell, Fields of Honor, Soothing Wetlands, Courageous Cavern<br>Dynamax Adventures'),
(342, NULL, 2, 'Axew''s Eye, Giant''s Seat, South Lake Miloch, Turffield, Forest of Focus, Challenge Beach, Training Lowlands<br>Max Raid Battles: Dusty Bowl, Giant''s Mirror, South Lake Miloch, Stony Wilderness, West Lake Axewell, Fields of Honor, Soothing Wetlands, Courageous Cavern<br>Dynamax Adventures'),
(342, NULL, 3, NULL),
(342, NULL, 4, 'Fellhorn Gorge<br>Tera Raid Battles: 4 Star Raid Battles, 6 Star Raid Battles'),
(342, NULL, 5, 'Fellhorn Gorge<br>Tera Raid Battles: 4 Star Raid Battles, 6 Star Raid Battles'),
-- Baltoy
(343, NULL, 1, 'Axew''s Eye, Bridge Field, Dappled Grove, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness, West Lake Axewell<br>Max Raid Battles: Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake'),
(343, NULL, 2, 'Axew''s Eye, Bridge Field, Dappled Grove, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness, West Lake Axewell<br>Max Raid Battles: Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness'),
(343, NULL, 3, NULL),
(343, NULL, 4, NULL),
(343, NULL, 5, NULL),
-- Claydol
(344, NULL, 1, 'Axew''s Eye, Bridge Field, Dappled Grove, Dusty Bowl, Lake of Outrage, Stony Wilderness, Giant''s Foot, Three-Point Pass<br>Max Raid Battles: Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake<br>Dynamax Adventures'),
(344, NULL, 2, 'Axew''s Eye, Bridge Field, Dappled Grove, Dusty Bowl, Lake of Outrage, Stony Wilderness, Giant''s Foot, Three-Point Pass<br>Max Raid Battles: Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake<br>Dynamax Adventures'),
(344, NULL, 3, NULL),
(344, NULL, 4, NULL),
(344, NULL, 5, NULL),
-- Lileep
(345, NULL, 1, 'Giant''s Bed, Giant''s Foot<br>Max Raid Battles: Slippery Slope, Giant''s Bed, Crown Shrine, Giant''s Foot, Ballimere Lake'),
(345, NULL, 2, 'Giant''s Bed, Giant''s Foot<br>Max Raid Battles: Slippery Slope, Giant''s Bed, Snowslide Slope, Crown Shrine, Giant''s Foot, Ballimere Lake'),
(345, NULL, 3, NULL),
(345, NULL, 4, NULL),
(345, NULL, 5, NULL),
-- Cradily
(346, NULL, 1, 'Max Raid Battles: Slippery Slope, Giant''s Bed, Snowslide Slope, Crown Shrine, Giant''s Foot, Ballimere Lake<br>Dynamax Adventures'),
(346, NULL, 2, 'Max Raid Battles: Slippery Slope, Giant''s Bed, Snowslide Slope, Crown Shrine, Giant''s Foot, Ballimere Lake<br>Dynamax Adventures'),
(346, NULL, 3, NULL),
(346, NULL, 4, NULL),
(346, NULL, 5, NULL),
-- Anorith
(347, NULL, 1, 'Ballimere Lake<br>Max Raid Battles: Slippery Slope, Giant''s Bed, Snowslide Slope, Crown Shrine, Giant''s Foot, Ballimere Lake'),
(347, NULL, 2, 'Ballimere Lake<br>Slippery Slope, Giant''s Bed, Crown Shrine, Giant''s Foot, Ballimere Lake'),
(347, NULL, 3, NULL),
(347, NULL, 4, NULL),
(347, NULL, 5, NULL),
-- Armaldo
(348, NULL, 1, 'Ballimere Lake<br>Max Raid Battles: Slippery Slope, Giant''s Bed, Snowslide Slope, Crown Shrine, Giant''s Foot, Ballimere Lake<br>Dynamax Adventures'),
(348, NULL, 2, 'Ballimere Lake<br>Max Raid Battles: Slippery Slope, Giant''s Bed, Snowslide Slope, Crown Shrine, Giant''s Foot, Ballimere Lake<br>Dynamax Adventures'),
(348, NULL, 3, NULL),
(348, NULL, 4, NULL),
(348, NULL, 5, NULL),
-- Feebas
(349, NULL, 1, 'Route 2, Giant''s Bed, Giant''s Foot, Roaring-Sea Caves, Ballimere Lake<br>Max Raid Battles: Bridge Field, East Lake Axewell, Lake of Outrage, West Lake Axewell, Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(349, NULL, 2, 'Route 2, Giant''s Bed, Giant''s Foot, Roaring-Sea Caves, Ballimere Lake<br>Max Raid Battles: Bridge Field, East Lake Axewell, Lake of Outrage, West Lake Axewell, Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(349, NULL, 3, NULL),
(349, NULL, 4, 'Crystal Pool, Oni Mountain<br>Tera Raid Battles: 2 Star Raid Battles, 3 Star Raid Battles'),
(349, NULL, 5, 'Crystal Pool, Oni Mountain<br>Tera Raid Battles: 2 Star Raid Battles, 3 Star Raid Battles'),
-- Milotic
(350, NULL, 1, 'Lake of Outrage, South Lake Miloch, Giant''s Bed<br>Max Raid Battles: Bridge Field, East Lake Axewell, Lake of Outrage, West Lake Axewell, Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(350, NULL, 2, 'Lake of Outrage, South Lake Miloch, Giant''s Bed<br>Max Raid Battles: Bridge Field, East Lake Axewell, Lake of Outrage, West Lake Axewell, Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(350, NULL, 3, NULL),
(350, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(350, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Castform
(351, NULL, 1, NULL),
(351, NULL, 2, NULL),
(351, NULL, 3, NULL),
(351, NULL, 4, NULL),
(351, NULL, 5, NULL),
-- Kecleon
(352, NULL, 1, NULL),
(352, NULL, 2, NULL),
(352, NULL, 3, NULL),
(352, NULL, 4, NULL),
(352, NULL, 5, NULL),
-- Shuppet
(353, NULL, 1, NULL),
(353, NULL, 2, NULL),
(353, NULL, 3, NULL),
(353, NULL, 4, 'East Province Area One, East Province Area Two, East Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
(353, NULL, 5, 'East Province Area One, East Province Area Two, East Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Banette
(354, NULL, 1, NULL),
(354, NULL, 2, NULL),
(354, NULL, 3, NULL),
(354, NULL, 4, 'Alfornada Cavern, Glaseado Mountain<br>Tera Raid Battles: 4 Star Raid Battles'),
(354, NULL, 5, 'Alfornada Cavern, Glaseado Mountain<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Duskull
(355, NULL, 1, 'Route 6, Dusty Bowl, Giant''s Cap, Giant''s Seat, Motostoke Riverbank, Watchtower Ruins<br>Max Raid Battles: Giant''s Mirror, South Lake Miloch, Stony Wilderness, Watchtower Ruins'),
(355, NULL, 2, 'Route 6, Dusty Bowl, Giant''s Cap, Giant''s Seat, Motostoke Riverbank, Watchtower Ruins<br>Max Raid Battles: Giant''s Mirror, South Lake Miloch, Stony Wilderness, Watchtower Ruins'),
(355, NULL, 3, 'Cobalt Coastlands: Deadwood Haunt or nearby<br>Alabaster Icelands: Avalanche Slopes, Arena''s Approach or nearby<br>Coronet Highlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(355, NULL, 4, 'Chilling Waterhead, Crystal Pool, Fellhorn Gorge, Infernal Pass, Kitakami Wilds, Oni Mountain, Timeless Woods<br>Tera Raid Battles: 2 Star Raid Battles'),
(355, NULL, 5, 'Chilling Waterhead, Crystal Pool, Fellhorn Gorge, Infernal Pass, Kitakami Wilds, Oni Mountain, Timeless Woods<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Dusclops
(356, NULL, 1, 'Route 8, Giant''s Seat, Watchtower Ruins<br>Max Raid Battles: Giant''s Mirror, South Lake Miloch, Stony Wilderness, Watchtower Ruins<br>Dynamax Adventures'),
(356, NULL, 2, 'Route 8, Giant''s Seat, Watchtower Ruins<br>Max Raid Battles: Giant''s Mirror, South Lake Miloch, Stony Wilderness, Watchtower Ruins<br>Dynamax Adventures'),
(356, NULL, 3, 'Cobalt Coastlands: Deadwood Haunt or nearby<br>Alabaster Icelands: Avalanche Slopes, Arena''s Approach or nearby<br>Coronet Highlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(356, NULL, 4, 'Kitakami Wilds, Timeless Woods<br>Fixed: Kitakami Wilds<br>Tera Raid Battles: 4 Star Raid Battles'),
(356, NULL, 5, 'Kitakami Wilds, Timeless Woods<br>Fixed: Kitakami Wilds<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Tropius
(357, NULL, 1, NULL),
(357, NULL, 2, NULL),
(357, NULL, 3, NULL),
(357, NULL, 4, 'Casseroya Lake, West Province Area Three<br>Fixed: Casseroya Lake, West Province Area Two<br>Tera Raid Battles: 4 Star Raid Battles'),
(357, NULL, 5, 'Casseroya Lake, West Province Area Three<br>Fixed: Casseroya Lake, West Province Area Two<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Chimecho
(358, NULL, 1, NULL),
(358, NULL, 2, NULL),
(358, NULL, 3, 'Coronet Highlands: Celestica Trail or nearby<br>Alabaster Icelands: Lake Acuity or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(358, NULL, 4, 'Crystal Pool, Infernal Pass, Oni Mountain<br>Fixed: Infernal Pass, Kitakami Road<br>Tera Raid Battles: 4 Star Raid Battles'),
(358, NULL, 5, 'Crystal Pool, Infernal Pass, Oni Mountain<br>Fixed: Infernal Pass, Kitakami Road<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Absol
(359, NULL, 1, 'Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Path to the Peak, Giant''s Foot, Frigid Sea, Three-Point Pass<br>Max Raid Battles: Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea<br>Dynamax Adventures'),
(359, NULL, 2, 'Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Path to the Peak, Giant''s Foot, Frigid Sea, Three-Point Pass<br>Max Raid Battles: Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea<br>Dynamax Adventures'),
(359, NULL, 3, NULL),
(359, NULL, 4, NULL),
(359, NULL, 5, NULL),
-- Wynaut
(360, NULL, 1, 'Max Raid Battles: Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness'),
(360, NULL, 2, 'Max Raid Battles: Hammerlocke Hills, Motostoke Riverbank, Stony Wilderness'),
(360, NULL, 3, NULL),
(360, NULL, 4, NULL),
(360, NULL, 5, NULL),
-- Snorunt
(361, NULL, 1, 'Route 8, Dappled Grove, East Lake Axewell, Giant''s Cap, Giant''s Seat, Hammerlocke Hills, North Lake Miloch, Rolling Fields, South Lake Miloch, Watchtower Ruins, West Lake Axewell, Giant''s Bed, Snowslide Slope, Tunnel to the Top, Giant''s Foot<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Stony Wilderness, Slippery Slope, Old Cemetery, Snowslide Slope, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(361, NULL, 2, 'Route 8, Dappled Grove, East Lake Axewell, Giant''s Cap, Giant''s Seat, Hammerlocke Hills, North Lake Miloch, Rolling Fields, South Lake Miloch, Watchtower Ruins, West Lake Axewell, Giant''s Bed, Snowslide Slope, Tunnel to the Top, Giant''s Foot<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Giant''s Seat, Hammerlocke Hills, Stony Wilderness, Slippery Slope, Old Cemetery, Snowslide Slope, Giant''s Foot, Frigid Sea, Ballimere Lake'),
(361, NULL, 3, 'Alabaster Icelands: Whiteout Valley, Bonechill Wastes, Avalanche Slopes, Avalugg''s Legacy or nearby<br>Alabaster Icelands: Massive Mass Outbreak'),
(361, NULL, 4, 'Dalizapa Passage, Glaseado Mountain, Chilling Waterhead, Oni Mountain<br>Tera Raid Battles: 2 Star Raid Battles'),
(361, NULL, 5, 'Dalizapa Passage, Glaseado Mountain, Chilling Waterhead, Oni Mountain<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Glalie
(362, NULL, 1, 'Route 9, Route 10, Giant''s Cap, Giant''s Seat, Lake of Outrage, Watchtower Ruins, Slippery Slope, Giant''s Bed, Snowslide Slope<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Stony Wilderness, Slippery Slope, Old Cemetery, Snowslide Slope, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(362, NULL, 2, 'Route 9, Route 10, Giant''s Cap, Giant''s Seat, Lake of Outrage, Watchtower Ruins, Slippery Slope, Giant''s Bed, Snowslide Slope<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Giant''s Seat, Hammerlocke Hills, Stony Wilderness, Slippery Slope, Old Cemetery, Snowslide Slope, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(362, NULL, 3, 'Alabaster Icelands: Bonechill Wastes, Avalugg''s Legacy, Avalanche Slopes, Snowpoint Temple or nearby<br>Alabaster Icelands: Massive Mass Outbreak'),
(362, NULL, 4, 'Glaseado Mountain<br>Tera Raid Battles: 5 Star Raid Battles'),
(362, NULL, 5, 'Glaseado Mountain<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Spheal
(363, NULL, 1, 'Frigid Sea<br>Max Raid Battles: Giant''s Bed, Frigid Sea'),
(363, NULL, 2, 'Frigid Sea<br>Max Raid Battles: Giant''s Bed, Frigid Sea'),
(363, NULL, 3, 'Cobalt Coastlands: Ginkgo Landing or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Cobalt Coastlands: Massive Mass Outbreak'),
(363, NULL, 4, NULL),
(363, NULL, 5, NULL),
-- Sealeo
(364, NULL, 1, 'Frigid Sea<br>nMax Raid Battles: Giant''s Bed, Frigid Sea<br>Dynamax Adventures'),
(364, NULL, 2, 'Frigid Sea<br>nMax Raid Battles: Giant''s Bed, Frigid Sea<br>Dynamax Adventures'),
(364, NULL, 3, 'Cobalt Coastlands: Islespy Shore or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Cobalt Coastlands: Massive Mass Outbreak'),
(364, NULL, 4, NULL),
(364, NULL, 5, NULL),
-- Walrein
(365, NULL, 1, 'Frigid Sea<br>nMax Raid Battles: Giant''s Bed, Frigid Sea'),
(365, NULL, 2, 'Frigid Sea<br>nMax Raid Battles: Giant''s Bed, Frigid Sea'),
(365, NULL, 3, 'Cobalt Coastlands: Ginkgo Landing, Islespy Shore or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(365, NULL, 4, NULL),
(365, NULL, 5, NULL),
-- Clamperl
(366, NULL, 1, NULL),
(366, NULL, 2, NULL),
(366, NULL, 3, NULL),
(366, NULL, 4, NULL),
(366, NULL, 5, NULL),
-- Huntail
(367, NULL, 1, NULL),
(367, NULL, 2, NULL),
(367, NULL, 3, NULL),
(367, NULL, 4, NULL),
(367, NULL, 5, NULL),
-- Gorebyss
(368, NULL, 1, NULL),
(368, NULL, 2, NULL),
(368, NULL, 3, NULL),
(368, NULL, 4, NULL),
(368, NULL, 5, NULL),
-- Relicanth
(369, NULL, 1, 'Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(369, NULL, 2, 'Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(369, NULL, 3, NULL),
(369, NULL, 4, NULL),
(369, NULL, 5, NULL),
-- Luvdisc
(370, NULL, 1, NULL),
(370, NULL, 2, NULL),
(370, NULL, 3, NULL),
(370, NULL, 4, 'East Paldean Sea, South Paldean Sea, West Paldean Sea, Coastal Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
(370, NULL, 5, 'East Paldean Sea, South Paldean Sea, West Paldean Sea, Coastal Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Bagon
(371, NULL, 1, 'Tunnel to the Top<br>Max Raid Battles: Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(371, NULL, 2, 'Trade from Pokémon Sword'),
(371, NULL, 3, NULL),
(371, NULL, 4, 'Trade from Pokémon Violet'),
(371, NULL, 5, 'Alfornada Cavern, Dalizapa Passage, East Province Area Three, Glaseado Mountain, South Province Area One, South Province Area Three, West Province Area Two<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Shelgon
(372, NULL, 1, 'Max Raid Battles: Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(372, NULL, 2, 'Trade from Pokémon Sword'),
(372, NULL, 3, NULL),
(372, NULL, 4, 'Trade from Pokémon Violet'),
(372, NULL, 5, 'Alfornada Cavern<br>Fixed: North Province Area Two<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Salamence
(373, NULL, 1, 'Tunnel to the Top, Path to the Peak<br>Max Raid Battles: Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(373, NULL, 2, 'Trade from Pokémon Sword'),
(373, NULL, 3, NULL),
(373, NULL, 4, 'Trade from Pokémon Violet'),
(373, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Beldum
(374, NULL, 1, 'Snowslide Slope<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea'),
(374, NULL, 2, 'Snowslide Slope<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea'),
(374, NULL, 3, NULL),
(374, NULL, 4, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(374, NULL, 5, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Metang
(375, NULL, 1, 'Snowslide Slope<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(375, NULL, 2, 'Snowslide Slope<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(375, NULL, 3, NULL),
(375, NULL, 4, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(375, NULL, 5, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Metagross
(376, NULL, 1, 'Snowslide Slope<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Ballimere Lake'),
(376, NULL, 2, 'Snowslide Slope<br>Max Raid Battles: Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea, Ballimere Lake'),
(376, NULL, 3, NULL),
(376, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(376, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Regirock
(377, NULL, 1, 'Rock Peak Ruins'),
(377, NULL, 2, 'Rock Peak Ruins'),
(377, NULL, 3, NULL),
(377, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(377, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Regice
(378, NULL, 1, 'Iceberg Ruins'),
(378, NULL, 2, 'Iceberg Ruins'),
(378, NULL, 3, NULL),
(378, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(378, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Registeel
(379, NULL, 1, 'Iron Ruins'),
(379, NULL, 2, 'Iron Ruins'),
(379, NULL, 3, NULL),
(379, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(379, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Latias
(380, NULL, 1, 'Trade from Pokémon Shield'),
(380, NULL, 2, 'Dynamax Adventures'),
(380, NULL, 3, NULL),
(380, NULL, 4, 'South Province Area Four - Requires Snack from Snacksworth'),
(380, NULL, 5, 'South Province Area Four - Requires Snack from Snacksworth'),
-- Latios
(381, NULL, 1, 'Dynamax Adventures'),
(381, NULL, 2, 'Trade from Pokémon Sword'),
(381, NULL, 3, NULL),
(381, NULL, 4, 'North Province Area Two - Requires Snack from Snacksworth'),
(381, NULL, 5, 'North Province Area Two - Requires Snack from Snacksworth'),
-- Kyogre
(382, NULL, 1, 'Trade from Pokémon Shield'),
(382, NULL, 2, 'Dynamax Adventures'),
(382, NULL, 3, NULL),
(382, NULL, 4, 'North Paldean Sea - Requires Snack from Snacksworth'),
(382, NULL, 5, 'North Paldean Sea - Requires Snack from Snacksworth'),
-- Groudon
(383, NULL, 1, 'Dynamax Adventures'),
(383, NULL, 2, 'Trade from Pokémon Sword'),
(383, NULL, 3, NULL),
(383, NULL, 4, 'Alfornado Cavern - Requires Snack from Snacksworth'),
(383, NULL, 5, 'Alfornado Cavern - Requires Snack from Snacksworth'),
-- Rayquaza
(384, NULL, 1, 'Dynamax Adventures'),
(384, NULL, 2, 'Dynamax Adventures'),
(384, NULL, 3, NULL),
(384, NULL, 4, 'Great Crater of Paldea - Requires Snack from Snacksworth'),
(384, NULL, 5, 'Great Crater of Paldea - Requires Snack from Snacksworth'),
-- Jirachi
(385, NULL, 1, 'Transfer through Pokémon HOME or through events'),
(385, NULL, 2, 'Transfer through Pokémon HOME or through events'),
(385, NULL, 3, NULL),
(385, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(385, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Deoxys
(386, NULL, 1, NULL),
(386, NULL, 2, NULL),
(386, NULL, 3, NULL),
(386, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(386, NULL, 5, 'Transfer from Pokémon HOME or obtain from event');

COMMIT TRANSACTION;