BEGIN TRANSACTION;

INSERT INTO Pokemon_Location (pokedex_number, region_id, game_id, location_name)
VALUES 

-- Victini
(494, NULL, 1, 'Transfer from Pokémon HOME or obtain from event'),
(494, NULL, 2, 'Transfer from Pokémon HOME or obtain from event'),
(494, NULL, 3, NULL),
(494, NULL, 4, NULL),
(494, NULL, 5, NULL),
-- Snivy
(495, NULL, 1, NULL),
(495, NULL, 2, NULL),
(495, NULL, 3, NULL),
(495, NULL, 4, 'Savanna Biome'),
(495, NULL, 5, 'Savanna Biome'),
-- Servine
(496, NULL, 1, NULL),
(496, NULL, 2, NULL),
(496, NULL, 3, NULL),
(496, NULL, 4, 'Evolve Snivy'),
(496, NULL, 5, 'Evolve Snivy'),
-- Serperior
(497, NULL, 1, NULL),
(497, NULL, 2, NULL),
(497, NULL, 3, NULL),
(497, NULL, 4, 'Evolve Servine'),
(497, NULL, 5, 'Evolve Servine'),
-- Tepig
(498, NULL, 1, NULL),
(498, NULL, 2, NULL),
(498, NULL, 3, NULL),
(498, NULL, 4, 'Canyon Biome'),
(498, NULL, 5, 'Canyon Biome'),
-- Pignite
(499, NULL, 1, NULL),
(499, NULL, 2, NULL),
(499, NULL, 3, NULL),
(499, NULL, 4, 'Evolve Tepig'),
(499, NULL, 5, 'Evolve Tepig'),
-- Emboar
(500, NULL, 1, NULL),
(500, NULL, 2, NULL),
(500, NULL, 3, NULL),
(500, NULL, 4, 'Evolve Pignite'),
(500, NULL, 5, 'Evolve Pignite'),
-- Oshawott
(501, NULL, 1, NULL),
(501, NULL, 2, NULL),
(501, NULL, 3, 'Gift from Laventon, Space-time Distortion in Alabaster Icelands<br>Alabaster Icelands: Massive Mass Outbreak'),
(501, NULL, 4, 'Polar Biome'),
(501, NULL, 5, 'Polar Biome'),
-- Dewott
(502, NULL, 1, NULL),
(502, NULL, 2, NULL),
(502, NULL, 3, 'Space-time Distortion in Alabaster Icelands<br>Alabaster Icelands: Massive Mass Outbreak'),
(502, NULL, 4, 'Evolve Oshawott'),
(502, NULL, 5, 'Evolve Oshawott'),
-- Samurott
(503, NULL, 1, NULL),
(503, NULL, 2, NULL),
(503, NULL, 3, NULL),
(503, NULL, 4, 'Evolve Dewott'),
(503, NULL, 5, 'Evolve Dewott'),
-- Hisuian Samurott
(503, 3, 1, NULL),
(503, 3, 2, NULL),
(503, 3, 3, 'Space-time Distortion in Alabaster Icelands<br>Alabaster Icelands: Massive Mass Outbreak'),
(503, 3, 4, 'Transfer from Pokémon HOME'),
(503, 3, 5, 'Transfer from Pokémon HOME'),
-- Patrat
(504, NULL, 1, NULL),
(504, NULL, 2, NULL),
(504, NULL, 3, NULL),
(504, NULL, 4, NULL),
(504, NULL, 5, NULL),
-- Watchog
(505, NULL, 1, NULL),
(505, NULL, 2, NULL),
(505, NULL, 3, NULL),
(505, NULL, 4, NULL),
(505, NULL, 5, NULL),
-- Lillipup
(506, NULL, 1, 'Training Lowlands<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea'),
(506, NULL, 2, 'Training Lowlands<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea'),
(506, NULL, 3, NULL),
(506, NULL, 4, NULL),
(506, NULL, 5, NULL),
-- Herdier
(507, NULL, 1, 'Training Lowlands<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea'),
(507, NULL, 2, 'Training Lowlands<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea'),
(507, NULL, 3, NULL),
(507, NULL, 4, NULL),
(507, NULL, 5, NULL),
-- Stoutland
(508, NULL, 1, 'Training Lowlands<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea<br>Dynamax Adventures'),
(508, NULL, 2, 'Training Lowlands<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea<br>Dynamax Adventures'),
(508, NULL, 3, NULL),
(508, NULL, 4, NULL),
(508, NULL, 5, NULL),
-- Purrloin
(509, NULL, 1, 'Route 2, Dappled Grove, East Lake Axewell, Motostoke Riverbank, North Lake Miloch, Watchtower Ruins, West Lake Axewell<br>Max Raid Battles: Dusty Bowl, Giant''s Mirror, Stony Wilderness, West Lake Axewell'),
(509, NULL, 2, 'Route 2, Dappled Grove, East Lake Axewell, Motostoke Riverbank, North Lake Miloch, Watchtower Ruins, West Lake Axewell<br>Max Raid Battles: Dusty Bowl, Giant''s Mirror, Stony Wilderness, West Lake Axewell'),
(509, NULL, 3, NULL),
(509, NULL, 4, NULL),
(509, NULL, 5, NULL),
-- Liepard
(510, NULL, 1, 'Route 7, Route 9, Axew''s Eye, Bridge Field, Giant''s Cap, Giant''s Seat, North Lake Miloch<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Stony Wilderness, West Lake Axewell, Soothing Wetlands, Challenge Road, Workout Sea, Honeycalm Sea, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea<br>Dynamax Adventures'),
(510, NULL, 2, 'Route 7, Route 9, Axew''s Eye, Bridge Field, Giant''s Cap, Giant''s Seat, North Lake Miloch<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Stony Wilderness, West Lake Axewell, Soothing Wetlands, Challenge Road, Workout Sea, Honeycalm Sea, Frostpoint Field, Giant''s Bed, Snowslide Slope, Giant''s Foot, Frigid Sea<br>Dynamax Adventures'),
(510, NULL, 3, NULL),
(510, NULL, 4, NULL),
(510, NULL, 5, NULL),
-- Pansage
(511, NULL, 1, NULL),
(511, NULL, 2, NULL),
(511, NULL, 3, NULL),
(511, NULL, 4, NULL),
(511, NULL, 5, NULL),
-- Simisage
(512, NULL, 1, NULL),
(512, NULL, 2, NULL),
(512, NULL, 3, NULL),
(512, NULL, 4, NULL),
(512, NULL, 5, NULL),
-- Pansear
(513, NULL, 1, NULL),
(513, NULL, 2, NULL),
(513, NULL, 3, NULL),
(513, NULL, 4, NULL),
(513, NULL, 5, NULL),
-- Simisear
(514, NULL, 1, NULL),
(514, NULL, 2, NULL),
(514, NULL, 3, NULL),
(514, NULL, 4, NULL),
(514, NULL, 5, NULL),
-- Panpour
(515, NULL, 1, NULL),
(515, NULL, 2, NULL),
(515, NULL, 3, NULL),
(515, NULL, 4, NULL),
(515, NULL, 5, NULL),
-- Simipour
(516, NULL, 1, NULL),
(516, NULL, 2, NULL),
(516, NULL, 3, NULL),
(516, NULL, 4, NULL),
(516, NULL, 5, NULL),
-- Munna
(517, NULL, 1, 'Axew''s Eye, Bridge Field, East Lake Axewell, Giant''s Cap, Giant''s Seat, Rolling Fields, Slumbering Weald, Stony Wilderness<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins'),
(517, NULL, 2, 'Axew''s Eye, Bridge Field, East Lake Axewell, Giant''s Cap, Giant''s Seat, Rolling Fields, Slumbering Weald, Stony Wilderness<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins'),
(517, NULL, 3, NULL),
(517, NULL, 4, NULL),
(517, NULL, 5, NULL),
-- Musharna
(518, NULL, 1, 'Bridge Field, Giant''s Seat<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins, Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea<br>Dynamax Adventures'),
(518, NULL, 2, 'Bridge Field, Giant''s Seat<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins, Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea<br>Dynamax Adventures'),
(518, NULL, 3, NULL),
(518, NULL, 4, NULL),
(518, NULL, 5, NULL),
-- Pidove
(519, NULL, 1, 'East Lake Axewell, North Lake Miloch, Rolling Fields, Watchtower Ruins<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea'),
(519, NULL, 2, 'East Lake Axewell, North Lake Miloch, Rolling Fields, Watchtower Ruins<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea'),
(519, NULL, 3, NULL),
(519, NULL, 4, NULL),
(519, NULL, 5, NULL),
-- Tranquill
(520, NULL, 1, 'Bridge Field, Giant''s Mirror, Giant''s Seat, Stony Wilderness<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea'),
(520, NULL, 2, 'Bridge Field, Giant''s Mirror, Giant''s Seat, Stony Wilderness<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea'),
(520, NULL, 3, NULL),
(520, NULL, 4, NULL),
(520, NULL, 5, NULL),
-- Unfezant
(521, NULL, 1, 'Axew''s Eye, Giant''s Mirror, Hammerlocke Hills, Stony Wilderness<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea<br>Dynamax Adventures'),
(521, NULL, 2, 'Axew''s Eye, Giant''s Mirror, Hammerlocke Hills, Stony Wilderness<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea<br>Dynamax Adventures'),
(521, NULL, 3, NULL),
(521, NULL, 4, NULL),
(521, NULL, 5, NULL),
-- Blitzle
(522, NULL, 1, NULL),
(522, NULL, 2, NULL),
(522, NULL, 3, NULL),
(522, NULL, 4, 'Savanna Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
(522, NULL, 5, 'Savanna Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Zebstrika
(523, NULL, 1, NULL),
(523, NULL, 2, NULL),
(523, NULL, 3, NULL),
(523, NULL, 4, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(523, NULL, 5, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Roggenrola
(524, NULL, 1, 'Galar Mine, Motostoke Outskirts, Rolling Fields, Stony Wilderness, Challenge Road<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Rolling Fields, Stony Wilderness, Fields of Honor, Training Lowlands, Potbottom Desert'),
(524, NULL, 2, 'Galar Mine, Motostoke Outskirts, Rolling Fields, Stony Wilderness, Challenge Road<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Rolling Fields, Stony Wilderness, Fields of Honor, Training Lowlands, Potbottom Desert'),
(524, NULL, 3, NULL),
(524, NULL, 4, NULL),
(524, NULL, 5, NULL),
-- Boldore
(525, NULL, 1, 'Route 8, Giant''s Cap, Giant''s Mirror, Lake of Outrage, Stony Wilderness<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Rolling Fields, Stony Wilderness, Fields of Honor, Training Lowlands, Potbottom Desert<br>Dynamax Adventures'),
(525, NULL, 2, 'Route 8, Giant''s Cap, Giant''s Mirror, Lake of Outrage, Stony Wilderness<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Rolling Fields, Stony Wilderness, Fields of Honor, Training Lowlands, Potbottom Desert<br>Dynamax Adventures'),
(525, NULL, 3, NULL),
(525, NULL, 4, NULL),
(525, NULL, 5, NULL),
-- Gigalith
(526, NULL, 1, 'Dusty Bowl, Brawlers''s Cave<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Rolling Fields, Stony Wilderness, Fields of Honor, Training Lowlands, Potbottom Desert'),
(526, NULL, 2, 'Dusty Bowl, Brawlers''s Cave<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Rolling Fields, Stony Wilderness, Fields of Honor, Training Lowlands, Potbottom Desert'),
(526, NULL, 3, NULL),
(526, NULL, 4, NULL),
(526, NULL, 5, NULL),
-- Woobat
(527, NULL, 1, 'Bridge Field, Galar Mine, Giant''s Mirror, Watchtower Ruins, Brawlers'' Cave, Courageous Cavern<br>Max Raid Battles: East Lake Axewell, Hammerlocke Hills, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Watchtower Ruins, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(527, NULL, 2, 'Bridge Field, Galar Mine, Giant''s Mirror, Watchtower Ruins, Brawlers'' Cave, Courageous Cavern<br>Max Raid Battles: East Lake Axewell, Hammerlocke Hills, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Watchtower Ruins, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill'),
(527, NULL, 3, NULL),
(527, NULL, 4, NULL),
(527, NULL, 5, NULL),
-- Swoobat
(528, NULL, 1, 'Challenge Beach, Brawlers'' Cave, Courageous Cavern, Training Lowlands<br>Max Raid Battles: East Lake Axewell, Hammerlocke Hills, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Watchtower Ruins, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill<br>Dynamax Adventures'),
(528, NULL, 2, 'Challenge Beach, Brawlers'' Cave, Courageous Cavern, Training Lowlands<br>Max Raid Battles: East Lake Axewell, Hammerlocke Hills, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Watchtower Ruins, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Frostpoint Field, Giant''s Bed, Frigid Sea, Ballimere Lake, Dyna Tree Hill<br>Dynamax Adventures'),
(528, NULL, 3, NULL),
(528, NULL, 4, NULL),
(528, NULL, 5, NULL),
-- Drilbur
(529, NULL, 1, 'Dusty Bowl, Galar Mine, Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Stony Wilderness<br>Max Raid Battles: Bridge Field, Rolling Fields, Potbottom Desert'),
(529, NULL, 2, 'Dusty Bowl, Galar Mine, Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Stony Wilderness<br>Max Raid Battles: Bridge Field, Rolling Fields, Potbottom Desert'),
(529, NULL, 3, NULL),
(529, NULL, 4, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Fixed: Canyon Biome, Savanna Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(529, NULL, 5, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Fixed: Canyon Biome, Savanna Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Excadrill
(530, NULL, 1, 'Giant''s Cap, Giant''s Mirror, Lake of Outrage<br>Max Raid Battles: Bridge Field, Rolling Fields, Potbottom Desert'),
(530, NULL, 2, 'Giant''s Cap, Giant''s Mirror, Lake of Outrage<br>Max Raid Battles: Bridge Field, Rolling Fields, Potbottom Desert'),
(530, NULL, 3, NULL),
(530, NULL, 4, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(530, NULL, 5, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Audino
(531, NULL, 1, 'Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Tunnel to the Top, Path to the Peak, Giant''s Foot, Roaring-Sea Caves, Frigid Sea, Three-Point Pass, Ballimere Lake, Lakeside Cave<br>Max Raid Battles: Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Path to the Peak, Crown Shrine, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake, Dyna Tree Hill<br>Dynamax Adventures'),
(531, NULL, 2, 'Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Tunnel to the Top, Path to the Peak, Giant''s Foot, Roaring-Sea Caves, Frigid Sea, Three-Point Pass, Ballimere Lake, Lakeside Cave<br>Max Raid Battles: Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Path to the Peak, Crown Shrine, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake, Dyna Tree Hill<br>Dynamax Adventures'),
(531, NULL, 3, NULL),
(531, NULL, 4, NULL),
(531, NULL, 5, NULL),
-- Timburr
(532, NULL, 1, 'Galar Mine<br>Max Raid Battles: Rolling Fields, South Lake Miloch, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(532, NULL, 2, 'Galar Mine<br>Max Raid Battles: Rolling Fields, South Lake Miloch, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(532, NULL, 3, NULL),
(532, NULL, 4, 'Apple Hills, Crystal Pool, Fellhorn Gorge, Infernal Pass, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Tera Raid Battles: 2 Star Raid Battles'),
(532, NULL, 5, 'Apple Hills, Crystal Pool, Fellhorn Gorge, Infernal Pass, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Oni''s Maw, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Gurdurr
(533, NULL, 1, 'Route 8, Dusty Bowl, Stony Wilderness, Giant''s Bed, Giant''s Foot<br>Max Raid Battles: Rolling Fields, South Lake Miloch, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(533, NULL, 2, 'Route 8, Dusty Bowl, Stony Wilderness, Giant''s Bed, Giant''s Foot<br>Max Raid Battles: Rolling Fields, South Lake Miloch, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(533, NULL, 3, NULL),
(533, NULL, 4, 'Fellhorn Gorge, Mossfell Confluence<br>Fixed: Mossfell Confluence, Paradise Barrens, Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
(533, NULL, 5, 'Fellhorn Gorge, Mossfell Confluence<br>Fixed: Mossfell Confluence, Paradise Barrens, Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Conkeldurr
(534, NULL, 1, 'Motostoke Riverbank, Giant''s Bed, Giant''s Foot<br>Max Raid Battles: Rolling Fields, South Lake Miloch, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(534, NULL, 2, 'Motostoke Riverbank, Giant''s Bed, Giant''s Foot<br>Max Raid Battles: Rolling Fields, South Lake Miloch, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(534, NULL, 3, NULL),
(534, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(534, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Tympole
(535, NULL, 1, 'Dappled Grove, North Lake Miloch, South Lake Miloch, Watchtower Ruins, West Lake Axewell<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach'),
(535, NULL, 2, 'Dappled Grove, North Lake Miloch, South Lake Miloch, Watchtower Ruins, West Lake Axewell<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach'),
(535, NULL, 3, NULL),
(535, NULL, 4, NULL),
(535, NULL, 5, NULL),
-- Palpitoad
(536, NULL, 1, 'Bridge Field, Dusty Bowl, Giant''s Cap, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, North Lake Miloch, West Lake Axewell<br>Max Raid Battles: Bridge Field, Dusty Bowl, North Lake Miloch, Rolling Fields, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach<br>Dynamax Adventures'),
(536, NULL, 2, 'Bridge Field, Dusty Bowl, Giant''s Cap, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, North Lake Miloch, West Lake Axewell<br>Max Raid Battles: Bridge Field, Dusty Bowl, North Lake Miloch, Rolling Fields, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach<br>Dynamax Adventures'),
(536, NULL, 3, NULL),
(536, NULL, 4, NULL),
(536, NULL, 5, NULL),
-- Seismitoad
(537, NULL, 1, 'Route 7, Axew''s Eye, Bridge Field, Dappled Grove, Dusty Bowl, Giant''s Cap, Giant''s Mirror, Lake of Outrage<br>Max Raid Battles: Bridge Field, Dusty Bowl, North Lake Miloch, Rolling Fields, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach<br>Dynamax Adventures'),
(537, NULL, 2, 'Route 7, Axew''s Eye, Bridge Field, Dappled Grove, Dusty Bowl, Giant''s Cap, Giant''s Mirror, Lake of Outrage<br>Max Raid Battles: Bridge Field, Dusty Bowl, North Lake Miloch, Rolling Fields, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach<br>Dynamax Adventures'),
(537, NULL, 3, NULL),
(537, NULL, 4, NULL),
(537, NULL, 5, NULL),
-- Throh
(538, NULL, 1, 'Trade in Circhester'),
(538, NULL, 2, 'Route 8, Bridge Field, Giant''s Mirror, Motostoke Outskirts, Motostoke Riverbank<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea'),
(538, NULL, 3, NULL),
(538, NULL, 4, NULL),
(538, NULL, 5, NULL),
-- Sawk
(539, NULL, 1, 'Route 8, Bridge Field, Giant''s Mirror, Motostoke Outskirts, Motostoke Riverbank<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea'),
(539, NULL, 2, 'Trade in Circhester'),
(539, NULL, 3, NULL),
(539, NULL, 4, NULL),
(539, NULL, 5, NULL),
-- Sewaddle
(540, NULL, 1, NULL),
(540, NULL, 2, NULL),
(540, NULL, 3, NULL),
(540, NULL, 4, 'Apple Hills, Kitakami Road, Loyalty Plaza, Mossfell Confluence, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
(540, NULL, 5, 'Apple Hills, Kitakami Road, Loyalty Plaza, Mossfell Confluence, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Swadloon
(541, NULL, 1, NULL),
(541, NULL, 2, NULL),
(541, NULL, 3, NULL),
(541, NULL, 4, 'Mossfell Confluence, Wistful Fields<br>Fixed: Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
(541, NULL, 5, 'Mossfell Confluence, Wistful Fields<br>Fixed: Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Leavanny
(542, NULL, 1, NULL),
(542, NULL, 2, NULL),
(542, NULL, 3, NULL),
(542, NULL, 4, 'Mossfell Confluence, Wistful Fields<br>Fixed: Wistful Fields<br>Tera Raid Battles: 4 Star Raid Battles, 6 Star Raid Battles'),
(542, NULL, 5, 'Mossfell Confluence, Wistful Fields<br>Fixed: Wistful Fields<br>Tera Raid Battles: 4 Star Raid Battles, 6 Star Raid Battles'),
-- Venipede
(543, NULL, 1, 'Forest of Focus<br>Max Raid Battles: Soothing Wetlands, Forest of Focus, Training Lowlands, Stepping-Stone Sea'),
(543, NULL, 2, 'Forest of Focus<br>Max Raid Battles: Soothing Wetlands, Forest of Focus, Training Lowlands, Stepping-Stone Sea'),
(543, NULL, 3, NULL),
(543, NULL, 4, NULL),
(543, NULL, 5, NULL),
-- Whirlipede
(544, NULL, 1, 'Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Training Lowlands, Workout Sea, Stepping-Stone Sea'),
(544, NULL, 2, 'Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Training Lowlands, Workout Sea, Stepping-Stone Sea'),
(544, NULL, 3, NULL),
(544, NULL, 4, NULL),
(544, NULL, 5, NULL),
-- Scolipede
(545, NULL, 1, 'Forest of Focus<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Training Lowlands, Workout Sea, Stepping-Stone Sea<br>Dynamax Adventures'),
(545, NULL, 2, 'Forest of Focus<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Training Lowlands, Workout Sea, Stepping-Stone Sea<br>Dynamax Adventures'),
(545, NULL, 3, NULL),
(545, NULL, 4, NULL),
(545, NULL, 5, NULL),
-- Cottonee
(546, NULL, 1, 'Stony Wilderness, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(546, NULL, 2, 'Stony Wilderness, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(546, NULL, 3, NULL),
(546, NULL, 4, 'Coastal Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
(546, NULL, 5, 'Coastal Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Whimsicott
(547, NULL, 1, 'Ballimere Lake<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(547, NULL, 2, 'Ballimere Lake<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(547, NULL, 3, NULL),
(547, NULL, 4, 'Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles, 6 Star Raid Battles'),
(547, NULL, 5, 'Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles, 6 Star Raid Battles'),
-- Petilil
(548, NULL, 1, 'Honeycalm Island<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Training Lowlands, Insular Sea'),
(548, NULL, 2, 'Honeycalm Island<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Training Lowlands, Insular Sea'),
(548, NULL, 3, 'Crimson Mirelands: Cottonsedge Prairie, Holm of Trials or nearby<br>Crimson Mirelands: Massive Mass Outbreak'),
(548, NULL, 4, 'South Province Area Four, West Province Area One, Kitakami Hall, Mossfell Confluence, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
(548, NULL, 5, 'South Province Area Four, West Province Area One, Kitakami Hall, Mossfell Confluence, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Lilligant
(549, NULL, 1, 'Soothing Wetlands, Challenge Beach, Training Lowlands, Honeycalm Island<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Training Lowlands, Insular Sea<br>Dynamax Adventures'),
(549, NULL, 2, 'Soothing Wetlands, Challenge Beach, Training Lowlands, Honeycalm Island<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Training Lowlands, Insular Sea<br>Dynamax Adventures'),
(549, NULL, 3, NULL),
(549, NULL, 4, 'North Province Area Three, South Province Area Six<br>Fixed: South Province Area Four, West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
(549, NULL, 5, 'North Province Area Three, South Province Area Six<br>Fixed: South Province Area Four, West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Hisuian Lilligant
(549, 3, 1, NULL),
(549, 3, 2, NULL),
(549, 3, 3, 'Crimson Mirelands: Massive Mass Outbreak'),
(549, 3, 4, 'Transfer from Pokémon HOME'),
(549, 3, 5, 'Transfer from Pokémon HOME'),
-- Basculin
(550, NULL, 1, 'Hulbury, Motostoke Riverbank, North Lake Miloch, Giant''s Bed, Snowslide Slope, Giant''s Foot, Roaring-Sea Caves, Frigid Sea, Ballimere Lake<br>Max Raid Battles: Bridge Field, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Lake of Outrage, North Lake Miloch, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern, Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(550, NULL, 2, 'Hulbury, Motostoke Riverbank, North Lake Miloch, Giant''s Bed, Snowslide Slope, Giant''s Foot, Roaring-Sea Caves, Frigid Sea, Ballimere Lake<br>Max Raid Battles: Bridge Field, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Lake of Outrage, North Lake Miloch, South Lake Miloch, West Lake Axewell, Soothing Wetlands, Forest of Focus, Challenge Beach, Courageous Cavern, Giant''s Bed, Giant''s Foot, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(550, NULL, 3, 'Cobalt Coastlands: Tranquility Cove, Islespy Shore<br>Coronet Highlands: Fabled Spring or nearby<br>Alabaster Icelands: Lake Acuity, Heart''s Crag or nearby<br>Cobalt Coastlands: Massive Mass Outbreak'),
(550, NULL, 4, 'East Province Area Two, East Province Area Three, Glaseado Mountain, South Province Area One, South Province Area Three, South Province Area Four, South Province Area Five, South Province Area Six, West Province Area One, West Province Area Two, West Province Area Three, Timeless Woods<br>Tera Raid Battles: 3 Star Raid Battles'),
(550, NULL, 5, 'East Province Area Two, East Province Area Three, Glaseado Mountain, South Province Area One, South Province Area Three, South Province Area Four, South Province Area Five, South Province Area Six, West Province Area One, West Province Area Two, West Province Area Three, Timeless Woods<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Sandile
(551, NULL, 1, 'Potbottom Desert<br>Max Raid Battles: Challenge Beach, Courageous Cavern, Potbottom Desert, Stepping-Stone Sea'),
(551, NULL, 2, 'Potbottom Desert<br>Max Raid Battles: Challenge Beach, Courageous Cavern, Potbottom Desert, Stepping-Stone Sea'),
(551, NULL, 3, NULL),
(551, NULL, 4, 'Asado Desert, Savanna Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
(551, NULL, 5, 'Asado Desert, Savanna Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Krokorok
(552, NULL, 1, 'Potbottom Desert<br>Max Raid Battles: Soothing Wetlands, Challenge Beach, Challenge Road, Courageous Cavern, Potbottom Desert, Workout Sea, Stepping-Stone Sea, Honeycalm Sea'),
(552, NULL, 2, 'Potbottom Desert<br>Max Raid Battles: Soothing Wetlands, Challenge Beach, Challenge Road, Courageous Cavern, Potbottom Desert, Workout Sea, Stepping-Stone Sea, Honeycalm Sea'),
(552, NULL, 3, NULL),
(552, NULL, 4, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(552, NULL, 5, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Krookodile
(553, NULL, 1, 'Potbottom Desert<br>Max Raid Battles: Soothing Wetlands, Challenge Beach, Challenge Road, Courageous Cavern, Potbottom Desert, Workout Sea, Stepping-Stone Sea, Honeycalm Sea'),
(553, NULL, 2, 'Potbottom Desert<br>Max Raid Battles: Soothing Wetlands, Challenge Beach, Challenge Road, Courageous Cavern, Potbottom Desert, Workout Sea, Stepping-Stone Sea, Honeycalm Sea'),
(553, NULL, 3, NULL),
(553, NULL, 4, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 5 Star Raid Battles'),
(553, NULL, 5, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Darumaka
(554, NULL, 1, 'Trade from Regina in Isle of Armor Area'),
(554, NULL, 2, 'Trade from Pokémon Sword'),
(554, NULL, 3, NULL),
(554, NULL, 4, NULL),
(554, NULL, 5, NULL),
-- Galarian Darumaka
(554, 2, 1, 'Route 8, Route 10, Snowslide Slope<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Slippery Slope, Snowslide Slope, Frigid Sea'),
(554, 2, 2, 'Trade from Pokémon Sword'),
(554, 2, 3, NULL),
(554, 2, 4, NULL),
(554, 2, 5, NULL),
-- Darmanitan
(555, NULL, 1, 'Evolve Darumaka'),
(555, NULL, 2, 'Trade from Pokémon Sword'),
(555, NULL, 3, NULL),
(555, NULL, 4, NULL),
(555, NULL, 5, NULL),
-- Galarian Darmanitan
(555, 2, 1, 'Snowslide Slope<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Slippery Slope, Snowslide Slope, Frigid Sea'),
(555, 2, 2, 'Trade from Pokémon Sword'),
(555, 2, 3, NULL),
(555, 2, 4, NULL),
(555, 2, 5, NULL),
-- Maractus
(556, NULL, 1, 'Route 6, Bridge Field, Hammerlocke Hills, Stony Wilderness<br>Max Raid Battles: Dappled Grove, Giant''s Mirror, Fields of Honor, Soothing Wetlands, Training Lowlands, Insular Sea<br>Dynamax Adventures'),
(556, NULL, 2, 'Route 6, Bridge Field, Hammerlocke Hills, Stony Wilderness<br>Max Raid Battles: Dappled Grove, Giant''s Mirror, Fields of Honor, Soothing Wetlands, Training Lowlands, Insular Sea<br>Dynamax Adventures'),
(556, NULL, 3, NULL),
(556, NULL, 4, NULL),
(556, NULL, 5, NULL),
-- Dwebble
(557, NULL, 1, 'East Lake Axewell, Giant''s Seat, Hammerlocke Hills, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness, Watchtower Ruins, West Lake Axewell, Courageous Cavern, Loop Lagoon<br>Max Raid Battles: Bridge Field, Dappled Grove, Dusty Bowl, Giant''s Seat, Rolling Fields, South Lake Miloch, Stony Wilderness, Fields of Honor, Forest of Focus, Training Lowlands, Workout Sea'),
(557, NULL, 2, 'East Lake Axewell, Giant''s Seat, Hammerlocke Hills, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness, Watchtower Ruins, West Lake Axewell, Courageous Cavern, Loop Lagoon<br>Max Raid Battles: Bridge Field, Dappled Grove, Dusty Bowl, Giant''s Seat, Rolling Fields, South Lake Miloch, Stony Wilderness, Fields of Honor, Forest of Focus, Training Lowlands, Workout Sea'),
(557, NULL, 3, NULL),
(557, NULL, 4, NULL),
(557, NULL, 5, NULL),
-- Crustle
(558, NULL, 1, 'Route 8, Axew''s Eye, Rolling Fields, South Lake Miloch, Stony Wilderness, Challenge Road, Courageous Cavern, Training Lowlands<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Rolling Fields, Stony Wilderness, Fields of Honor, Forest of Focus, Training Lowlands, Potbottom Desert, Workout Sea<br>Dynamax Adventures'),
(558, NULL, 2, 'Route 8, Axew''s Eye, Rolling Fields, South Lake Miloch, Stony Wilderness, Challenge Road, Courageous Cavern, Training Lowlands<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Rolling Fields, Stony Wilderness, Fields of Honor, Forest of Focus, Training Lowlands, Potbottom Desert, Workout Sea<br>Dynamax Adventures'),
(558, NULL, 3, NULL),
(558, NULL, 4, NULL),
(558, NULL, 5, NULL),
-- Scraggy
(559, NULL, 1, 'Bridge Field, Dusty Bowl, Galar Mine No. 2, Giant''s Cap, Motostoke Outskirts, Stony Wilderness<br>Max Raid Battles: Bridge Field, Dusty Bowl, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness, West Lake Axewell, Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea'),
(559, NULL, 2, 'Trade from Pokémon Sword'),
(559, NULL, 3, NULL),
(559, NULL, 4, 'Canyon Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
(559, NULL, 5, 'Canyon Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Scrafty
(560, NULL, 1, 'Challenge Road, Training Lowlands<br>Max Raid Battles: Bridge Field, Dusty Bowl, North Lake Miloch, Rolling Fields, South Lake Miloch, Stony Wilderness, West Lake Axewell, Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea'),
(560, NULL, 2, 'Trade from Pokémon Sword'),
(560, NULL, 3, NULL),
(560, NULL, 4, 'Canyon Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(560, NULL, 5, 'Canyon Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Sigilyph
(561, NULL, 1, 'Dusty Bowl, Lake of Outrage, Motostoke Riverbank, Stony Wilderness<br>Max Raid Battles: Bridge Field, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Rolling Fields, Stony Wilderness<br>Dynamax Adventures'),
(561, NULL, 2, 'Dusty Bowl, Lake of Outrage, Motostoke Riverbank, Stony Wilderness<br>Max Raid Battles: Bridge Field, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Rolling Fields, Stony Wilderness<br>Dynamax Adventures'),
(561, NULL, 3, NULL),
(561, NULL, 4, NULL),
(561, NULL, 5, NULL),
-- Yamask
(562, NULL, 1, 'Trade in Ballonlea'),
(562, NULL, 2, 'Trade in Ballonlea'),
(562, NULL, 3, NULL),
(562, NULL, 4, NULL),
(562, NULL, 5, NULL),
-- Galarian Yamask
(562, 2, 1, 'Route 6<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Rolling Fields, South Lake Miloch, Stony Wilderness, Watchtower Ruins'),
(562, 2, 2, 'Route 6<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Rolling Fields, South Lake Miloch, Stony Wilderness, Watchtower Ruins'),
(562, 2, 3, NULL),
(562, 2, 4, NULL),
(562, 2, 5, NULL),
-- Cofagrigus
(563, NULL, 1, 'Evolve Yamask'),
(563, NULL, 2, 'Evolve Yamask'),
(563, NULL, 3, NULL),
(563, NULL, 4, NULL),
(563, NULL, 5, NULL),
-- Tirtouga
(564, NULL, 1, 'Frigid Sea'),
(564, NULL, 2, 'Frigid Sea'),
(564, NULL, 3, NULL),
(564, NULL, 4, NULL),
(564, NULL, 5, NULL),
-- Carracosta
(565, NULL, 1, 'Frigid Sea'),
(565, NULL, 2, 'Frigid Sea'),
(565, NULL, 3, NULL),
(565, NULL, 4, NULL),
(565, NULL, 5, NULL),
-- Archen
(566, NULL, 1, 'Giant''s Foot'),
(566, NULL, 2, 'Giant''s Foot'),
(566, NULL, 3, NULL),
(566, NULL, 4, NULL),
(566, NULL, 5, NULL),
-- Archeops
(567, NULL, 1, 'Evolve Archen'),
(567, NULL, 2, 'Evolve Archen'),
(567, NULL, 3, NULL),
(567, NULL, 4, NULL),
(567, NULL, 5, NULL),
-- Trubbish
(568, NULL, 1, 'Route 3<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Motostoke Riverbank, North Lake Miloch, Giant''s Bed, Frigid Sea, Ballimere Lake'),
(568, NULL, 2, 'Route 3<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Motostoke Riverbank, North Lake Miloch, Giant''s Bed, Frigid Sea, Ballimere Lake'),
(568, NULL, 3, NULL),
(568, NULL, 4, NULL),
(568, NULL, 5, NULL),
-- Garbodor
(569, NULL, 1, 'Bridge Field, Lake of Outrage<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Motostoke Riverbank, North Lake Miloch, Giant''s Bed, Frigid Sea, Ballimere Lake<br>Gigantamax Raid Battles: East Lake Axewell, Giant''s Bed, Frigid Sea, Ballimere Lake'),
(569, NULL, 2, 'Bridge Field, Lake of Outrage<br>Max Raid Battles: East Lake Axewell, Giant''s Cap, Motostoke Riverbank, North Lake Miloch, Giant''s Bed, Frigid Sea, Ballimere Lake<br>Gigantamax Raid Battles: East Lake Axewell, Giant''s Bed, Frigid Sea, Ballimere Lake'),
(569, NULL, 3, NULL),
(569, NULL, 4, NULL),
(569, NULL, 5, NULL),
-- Zorua
(570, NULL, 1, 'Fields of Honor, Soothing Wetlands, Forest of Focus<br>Max Raid Battles: Soothing Wetlands, Challenge Road, Workout Sea, Honeycalm Sea'),
(570, NULL, 2, 'Fields of Honor, Soothing Wetlands, Forest of Focus<br>Max Raid Battles: Soothing Wetlands, Challenge Road, Workout Sea, Honeycalm Sea'),
(570, NULL, 3, NULL),
(570, NULL, 4, 'Tagtree Thicket, West Province Area Three (May disguise as other Pokémon)<br>Tera Raid Battles: 3 Star Raid Battles'),
(570, NULL, 5, 'Tagtree Thicket, West Province Area Three (May disguise as other Pokémon)<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Hisuian Zorua
(570, 3, 1, NULL),
(570, 3, 2, NULL),
(570, 3, 3, 'Alabaster Icelands: Bonechill Wastes, Icepeak Cavern or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(570, 3, 4, 'Transfer from Pokémon HOME'),
(570, 3, 5, 'Transfer from Pokémon HOME'),
-- Zoroark
(571, NULL, 1, 'Loop Lagoon, Insular Sea<br>Max Raid Battles: Soothing Wetlands, Challenge Road, Workout Sea, Honeycalm Sea'),
(571, NULL, 2, 'Loop Lagoon, Insular Sea<br>Max Raid Battles: Soothing Wetlands, Challenge Road, Workout Sea, Honeycalm Sea'),
(571, NULL, 3, NULL),
(571, NULL, 4, 'Socarrat Trail (May disguise as other Pokémon)<br>Tera Raid Battles: 5 Star Raid Battles'),
(571, NULL, 5, 'Socarrat Trail (May disguise as other Pokémon)<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Hisuian Zoroark
(571, 3, 1, NULL),
(571, 3, 2, NULL),
(571, 3, 3, 'Alabaster Icelands: Bonechill Wastes, Icepeak Cavern or nearby<br>Obsidian Fieldlands: Massive Mass Outbreak<br>Alabaster Icelands: Massive Mass Outbreak'),
(571, 3, 4, 'Transfer from Pokémon HOME'),
(571, 3, 5, 'Transfer from Pokémon HOME'),
-- Minccino
(572, NULL, 1, 'Route 5, East Lake Axewell, Giant''s Cap, Rolling Fields<br>Max Raid Battles: East Lake Axewell, Rolling Fields'),
(572, NULL, 2, 'Route 5, East Lake Axewell, Giant''s Cap, Rolling Fields<br>Max Raid Battles: East Lake Axewell, Rolling Fields'),
(572, NULL, 3, NULL),
(572, NULL, 4, 'Canyon Biome, Polar Biome<br>Fixed: Canyon Biome, Polar Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
(572, NULL, 5, 'Canyon Biome, Polar Biome<br>Fixed: Canyon Biome, Polar Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Cinccino
(573, NULL, 1, 'Giant''s Cap<br>Max Raid Battles: East Lake Axewell, Rolling Fields, Soothing Wetlands, Courageous Cavern, Training Lowlands<br>Dynamax Adventures'),
(573, NULL, 2, 'Giant''s Cap<br>Max Raid Battles: East Lake Axewell, Rolling Fields, Soothing Wetlands, Courageous Cavern, Training Lowlands<br>Dynamax Adventures'),
(573, NULL, 3, NULL),
(573, NULL, 4, 'Canyon Biome, Polar Biome<br>Fixed: Canyon Biome'),
(573, NULL, 5, 'Canyon Biome, Polar Biome<br>Fixed: Canyon Biome'),
-- Gothita
(574, NULL, 1, 'Giant''s Cap, Slippery Slope, Frostpoint Field<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake'),
(574, NULL, 2, 'Trade from Pokémon Sword'),
(574, NULL, 3, NULL),
(574, NULL, 4, 'East Province Area Three, Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
(574, NULL, 5, 'East Province Area Three, Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Gothorita
(575, NULL, 1, 'Dusty Bowl, Giant''s Cap, Slippery Slope, Frostpoint Field<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake'),
(575, NULL, 2, 'Trade from Pokémon Sword'),
(575, NULL, 3, NULL),
(575, NULL, 4, 'South Province Area Six, Coastal Biome, Torchlit Labyrinth<br>Tera Raid Battles: 3 Star Raid Battles'),
(575, NULL, 5, 'South Province Area Six, Coastal Biome, Torchlit Labyrinth<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Gothitelle
(576, NULL, 1, 'Lake of Outrage, Slippery Slope, Frostpoint Field<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake'),
(576, NULL, 2, 'Trade from Pokémon Sword'),
(576, NULL, 3, NULL),
(576, NULL, 4, 'South Province Area Six, Coastal Biome, Torchlit Labyrinth<br>Tera Raid Battles: 5 Star Raid Battles'),
(576, NULL, 5, 'South Province Area Six, Coastal Biome, Torchlit Labyrinth<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Solosis
(577, NULL, 1, 'Trade from Pokémon Shield'),
(577, NULL, 2, 'Giant''s Cap, Slippery Slope, Frostpoint Field<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake'),
(577, NULL, 3, NULL),
(577, NULL, 4, 'Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
(577, NULL, 5, 'Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Duosion
(578, NULL, 1, 'Trade from Pokémon Shield'),
(578, NULL, 2, 'Dusty Bowl, Slippery Slope, Frostpoint Field<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake'),
(578, NULL, 3, NULL),
(578, NULL, 4, 'Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(578, NULL, 5, 'Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Reuniclus
(579, NULL, 1, 'Trade from Pokémon Shield'),
(579, NULL, 2, 'Lake of Outrage, Slippery Slope, Frostpoint Field<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins, Giant''s Bed, Snowslide Slope, Path to the Peak, Ballimere Lake'),
(579, NULL, 3, NULL),
(579, NULL, 4, 'Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(579, NULL, 5, 'Polar Biome<br>Fixed: Polar Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Ducklett
(580, NULL, 1, NULL),
(580, NULL, 2, NULL),
(580, NULL, 3, NULL),
(580, NULL, 4, 'Fellhorn Gorge, Kitakami Wilds, Mossfell Confluence, Oni Mountain<br>Fixed: Mossfell Confluence<br>Tera Raid Battles: 1 Star Raid Battles'),
(580, NULL, 5, 'Fellhorn Gorge, Kitakami Wilds, Mossfell Confluence, Oni Mountain<br>Fixed: Mossfell Confluence<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Swanna
(581, NULL, 1, NULL),
(581, NULL, 2, NULL),
(581, NULL, 3, NULL),
(581, NULL, 4, 'Fixed: Fellhorn Gorge, Kitakami Wilds<br>Tera Raid Battles: 4 Star Raid Battles'),
(581, NULL, 5, 'Fixed: Fellhorn Gorge, Kitakami Wilds<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Vanillite
(582, NULL, 1, 'Bridge Field, Dappled Grove, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, Rolling Fields, South Lake Miloch, West Lake Axewell, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Stony Wilderness'),
(582, NULL, 2, 'Bridge Field, Dappled Grove, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, Rolling Fields, South Lake Miloch, West Lake Axewell, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Stony Wilderness'),
(582, NULL, 3, NULL),
(582, NULL, 4, NULL),
(582, NULL, 5, NULL),
-- Vanillish
(583, NULL, 1, 'Route 8, Route 10, Axew''s Eye, Dappled Grove, Dusty Bowl, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Giant''s Foot, Roaring-Sea Caves, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Dusty Bowl, Hammerlocke Hills<br>Dynamax Adventures'),
(583, NULL, 2, 'Route 8, Route 10, Axew''s Eye, Dappled Grove, Dusty Bowl, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Giant''s Foot, Roaring-Sea Caves, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Dusty Bowl, Hammerlocke Hills<br>Dynamax Adventures'),
(583, NULL, 3, NULL),
(583, NULL, 4, NULL),
(583, NULL, 5, NULL),
-- Vanilluxe
(584, NULL, 1, 'Route 10, Bridge Field, Lake of Outrage, South Lake Miloch, Frostpoint Field, Giant''s Bed, Snowslide Slope, Ballimere Lake<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Stony Wilderness, Giant''s Bed, Frigid Sea'),
(584, NULL, 2, 'Route 10, Bridge Field, Lake of Outrage, South Lake Miloch, Frostpoint Field, Giant''s Bed, Snowslide Slope, Ballimere Lake<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Giant''s Seat, Hammerlocke Hills, Stony Wilderness, Giant''s Bed, Frigid Sea'),
(584, NULL, 3, NULL),
(584, NULL, 4, NULL),
(584, NULL, 5, NULL),
-- Deerling
(585, NULL, 1, NULL),
(585, NULL, 2, NULL),
(585, NULL, 3, NULL),
(585, NULL, 4, 'South Province Area One, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five, East Province Area One, East Province Area Two, West Province Area Two, West Province Area Three, Dalizapa Passage, Glaseado Mountain, Canyon Biome, , Coastal Biome, Polar Biome, Savanna Biome, Torchlit Labyrinth<br>Tera Raid Battles: 1 Star Raid Battles'),
(585, NULL, 5, 'South Province Area One, South Province Area Two, South Province Area Three, South Province Area Four, South Province Area Five, East Province Area One, East Province Area Two, West Province Area Two, West Province Area Three, Dalizapa Passage, Glaseado Mountain, Canyon Biome, , Coastal Biome, Polar Biome, Savanna Biome, Torchlit Labyrinth<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Sawsbuck
(586, NULL, 1, NULL),
(586, NULL, 2, NULL),
(586, NULL, 3, NULL),
(586, NULL, 4, 'Socarrat Trail, West Province Area Three, Dalizapa Passage, Glaseado Mountain, North Province Area One, Canyon Biome, , Coastal Biome, Polar Biome, Savanna Biome, Torchlit Labyrinth<br>Fixed: South Province Area Four, Glaseado Mountain, Canyon Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(586, NULL, 5, 'Socarrat Trail, West Province Area Three, Dalizapa Passage, Glaseado Mountain, North Province Area One, Canyon Biome, , Coastal Biome, Polar Biome, Savanna Biome, Torchlit Labyrinth<br>Fixed: South Province Area Four, Glaseado Mountain, Canyon Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Emolga
(587, NULL, 1, 'Forest of Focus<br>Max Raid Battles: Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea<br>Dynamax Adventures'),
(587, NULL, 2, 'Forest of Focus<br>Max Raid Battles: Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea<br>Dynamax Adventures'),
(587, NULL, 3, NULL),
(587, NULL, 4, NULL),
(587, NULL, 5, NULL),
-- Karrablast
(588, NULL, 1, 'Route 7, Bridge Field, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Forest of Focus, Training Lowlands, Old Cemetery<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch'),
(588, NULL, 2, 'Route 7, Bridge Field, Giant''s Cap, Hammerlocke Hills, Motostoke Riverbank, Forest of Focus, Training Lowlands, Old Cemetery<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch'),
(588, NULL, 3, NULL),
(588, NULL, 4, NULL),
(588, NULL, 5, NULL),
-- Escavalier
(589, NULL, 1, 'Forest of Focus, Training Lowlands<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch, Fields of Honor, Forest of Focus, Workout Sea<br>Dynamax Adventures'),
(589, NULL, 2, 'Forest of Focus, Training Lowlands<br>Max Raid Battles: Fields of Honor, Forest of Focus, Workout Sea<br>Dynamax Adventures'),
(589, NULL, 3, NULL),
(589, NULL, 4, NULL),
(589, NULL, 5, NULL),
-- Foongus
(590, NULL, 1, 'Forest of Focus<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Training Lowlands, Insular Sea'),
(590, NULL, 2, 'Forest of Focus<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Training Lowlands, Insular Sea'),
(590, NULL, 3, NULL),
(590, NULL, 4, 'North Province Area Two, Tagtree Thicket, West Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
(590, NULL, 5, 'North Province Area Two, Tagtree Thicket, West Province Area Three<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Amoonguss
(591, NULL, 1, 'Forest of Focus<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Training Lowlands, Stepping-Stone Sea, Insular Sea<br>Dynamax Adventures'),
(591, NULL, 2, 'Forest of Focus<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Training Lowlands, Stepping-Stone Sea, Insular Sea<br>Dynamax Adventures'),
(591, NULL, 3, NULL),
(591, NULL, 4, 'North Province Area Two, Socarrat Trail<br>Fixed: North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(591, NULL, 5, 'North Province Area Two, Socarrat Trail<br>Fixed: North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Frillish
(592, NULL, 1, 'Bridge Field, East Lake Axewell, Giant''s Mirror, North Lake Miloch, West Lake Axewell, Stepping-Stone Sea<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins, Challenge Beach, Courageous Cavern, Stepping-Stone Sea'),
(592, NULL, 2, 'Bridge Field, East Lake Axewell, Giant''s Mirror, North Lake Miloch, West Lake Axewell, Stepping-Stone Sea<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins, Challenge Beach, Courageous Cavern, Stepping-Stone Sea'),
(592, NULL, 3, NULL),
(592, NULL, 4, NULL),
(592, NULL, 5, NULL),
-- Jellicent
(593, NULL, 1, 'Route 9, Bridge Field, East Lake Axewell, Lake of Outrage, North Lake Miloch, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: Giant''s Mirror, Stony Wilderness, Watchtower Ruins, West Lake Axewell, Challenge Beach, Courageous Cavern, Stepping-Stone Sea<br>Dynamax Adventures'),
(593, NULL, 2, 'Route 9, Bridge Field, East Lake Axewell, Lake of Outrage, North Lake Miloch, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: Giant''s Mirror, Stony Wilderness, Watchtower Ruins, West Lake Axewell, Challenge Beach, Courageous Cavern, Stepping-Stone Sea<br>Dynamax Adventures'),
(593, NULL, 3, NULL),
(593, NULL, 4, NULL),
(593, NULL, 5, NULL),
-- Alomomola
(594, NULL, 1, NULL),
(594, NULL, 2, NULL),
(594, NULL, 3, NULL),
(594, NULL, 4, 'North Paldean Sea, Canyon Biome, , Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(594, NULL, 5, 'North Paldean Sea, Canyon Biome, , Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Joltik
(595, NULL, 1, 'Route 4, Dappled Grove, East Lake Axewell, Giant''s Cap, Giant''s Mirror, North Lake Miloch, Rolling Fields, South Lake Miloch, West Lake Axewell<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, Rolling Fields, South Lake Miloch, Training Lowlands, Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(595, NULL, 2, 'Route 4, Dappled Grove, East Lake Axewell, Giant''s Cap, Giant''s Mirror, North Lake Miloch, Rolling Fields, South Lake Miloch, West Lake Axewell<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, Rolling Fields, South Lake Miloch, Training Lowlands, Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(595, NULL, 3, NULL),
(595, NULL, 4, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
(595, NULL, 5, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Galvantula
(596, NULL, 1, 'Route 7, Giant''s Cap, Giant''s Seat, Lake of Outrage, South Lake Miloch, Giant''s Bed, Old Cemetery, Giant''s Foot, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Cap, Lake of Outrage, Motostoke Riverbank, Rolling Fields, South Lake Miloch, Training Lowlands, Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Dynamax Adventures'),
(596, NULL, 2, 'Route 7, Giant''s Cap, Giant''s Seat, Lake of Outrage, South Lake Miloch, Giant''s Bed, Old Cemetery, Giant''s Foot, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Cap, Lake of Outrage, Motostoke Riverbank, Rolling Fields, South Lake Miloch, Training Lowlands, Frostpoint Field, Giant''s Bed, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Dynamax Adventures'),
(596, NULL, 3, NULL),
(596, NULL, 4, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Fixed: Chargestone Cavern<br>Tera Raid Battles: 4 Star Raid Battles'),
(596, NULL, 5, 'Canyon Biome, Chargestone Cavern, Polar Biome<br>Fixed: Chargestone Cavern<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Ferroseed
(597, NULL, 1, 'Route 4, Bridge Field, Motostoke Riverbank, Stony Wilderness, Lakeside Cave<br>Max Raid Battles: Bridge Field, Dappled Grove, Dusty Bowl, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Stony Wilderness'),
(597, NULL, 2, 'Route 4, Bridge Field, Motostoke Riverbank, Stony Wilderness, Lakeside Cave<br>Max Raid Battles: Bridge Field, Dappled Grove, Dusty Bowl, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Stony Wilderness'),
(597, NULL, 3, NULL),
(597, NULL, 4, NULL),
(597, NULL, 5, NULL),
-- Ferrothorn
(598, NULL, 1, 'Bridge Field, Dusty Bowl, Lakeside Cave<br>Max Raid Battles: Bridge Field, Dappled Grove, Dusty Bowl, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Stony Wilderness, Slippery Slope, Giant''s Bed, Crown Shrine, Giant''s Foot, Ballimere Lake'),
(598, NULL, 2, 'Bridge Field, Dusty Bowl, Lakeside Cave<br>Max Raid Battles: Bridge Field, Dappled Grove, Dusty Bowl, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Stony Wilderness, Slippery Slope, Giant''s Bed, Crown Shrine, Giant''s Foot, Ballimere Lake'),
(598, NULL, 3, NULL),
(598, NULL, 4, NULL),
(598, NULL, 5, NULL),
-- Klink
(599, NULL, 1, 'Route 3, Axew''s Eye, Dappled Grove, Hammerlocke Hills, North Lake Miloch, South Lake Miloch, West Lake Axewell<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Hammerlocke Hills, Stony Wilderness'),
(599, NULL, 2, 'Route 3, Axew''s Eye, Dappled Grove, Hammerlocke Hills, North Lake Miloch, South Lake Miloch, West Lake Axewell<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Hammerlocke Hills, Stony Wilderness'),
(599, NULL, 3, NULL),
(599, NULL, 4, NULL),
(599, NULL, 5, NULL),
-- Klang
(600, NULL, 1, 'Route 10, Dusty Bowl, Hammerlocke Hills<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Hammerlocke Hills<br>Dynamax Adventures'),
(600, NULL, 2, 'Route 10, Dusty Bowl, Hammerlocke Hills<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Hammerlocke Hills<br>Dynamax Adventures'),
(600, NULL, 3, NULL),
(600, NULL, 4, NULL),
(600, NULL, 5, NULL),
-- Klinklang
(601, NULL, 1, 'Hammerlocke Hills, Lake of Outrage<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Hammerlocke Hills, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea<br>Dynamax Adventures'),
(601, NULL, 2, 'Hammerlocke Hills, Lake of Outrage<br>Max Raid Battles: Dusty Bowl, Giant''s Seat, Hammerlocke Hills, Brawlers'' Cave, Courageous Cavern, Stepping-Stone Sea<br>Dynamax Adventures'),
(601, NULL, 3, NULL),
(601, NULL, 4, NULL),
(601, NULL, 5, NULL),
-- Tynamo
(602, NULL, 1, NULL),
(602, NULL, 2, NULL),
(602, NULL, 3, NULL),
(602, NULL, 4, 'North Paldean Sea, West Paldean Sea, Chilling Waterhead, Oni Mountain, Canyon Biome, Chargestone Cavern, Polar Biome, Savanna Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
(602, NULL, 5, 'North Paldean Sea, West Paldean Sea, Chilling Waterhead, Oni Mountain, Canyon Biome, Chargestone Cavern, Polar Biome, Savanna Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Eelektrik
(603, NULL, 1, NULL),
(603, NULL, 2, NULL),
(603, NULL, 3, NULL),
(603, NULL, 4, 'North Paldean Sea, South Paldean Sea, West Paldean Sea, Kitakami Wilds, Timeless Woods, Canyon Biome, Chargestone Cavern, Polar Biome, Savanna Biome<br>Fixed: Kitakami Wilds, Chargestone Cavern<br>Tera Raid Battles: 4 Star Raid Battles'),
(603, NULL, 5, 'North Paldean Sea, South Paldean Sea, West Paldean Sea, Kitakami Wilds, Timeless Woods, Canyon Biome, Chargestone Cavern, Polar Biome, Savanna Biome<br>Fixed: Kitakami Wilds, Chargestone Cavern<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Eelektross
(604, NULL, 1, NULL),
(604, NULL, 2, NULL),
(604, NULL, 3, NULL),
(604, NULL, 4, 'Canyon Biome, Chargestone Cavern, Polar Biome, Savanna Biome<br>Fixed: North Province Area One, Chargestone Cavern<br>Tera Raid Battles: 5 Star Raid Battles'),
(604, NULL, 5, 'Canyon Biome, Chargestone Cavern, Polar Biome, Savanna Biome<br>Fixed: North Province Area One, Chargestone Cavern<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Elgyem
(605, NULL, 1, 'Bridge Field, Motostoke Riverbank<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins, Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea'),
(605, NULL, 2, 'Bridge Field, Motostoke Riverbank<br>Max Raid Battles: Stony Wilderness, Watchtower Ruins, Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea'),
(605, NULL, 3, NULL),
(605, NULL, 4, NULL),
(605, NULL, 5, NULL),
-- Beheeyem
(606, NULL, 1, 'Bridge Field, Lake of Outrage<br>Max Raid Battles: Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea<br>Dynamax Adventures'),
(606, NULL, 2, 'Bridge Field, Lake of Outrage<br>Max Raid Battles: Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea<br>Dynamax Adventures'),
(606, NULL, 3, NULL),
(606, NULL, 4, NULL),
(606, NULL, 5, NULL),
-- Litwick
(607, NULL, 1, 'Bridge Field, Motostoke, Motostoke Riverbank<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert'),
(607, NULL, 2, 'Bridge Field, Motostoke, Motostoke Riverbank<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert'),
(607, NULL, 3, NULL),
(607, NULL, 4, 'Crystal Pool, Infernal Pass, Kitakami Wilds, Oni Mountain, Timeless Woods<br>Fixed: Infernal Pass<br>Tera Raid Battles: 2 Star Raid Battles'),
(607, NULL, 5, 'Crystal Pool, Infernal Pass, Kitakami Wilds, Oni Mountain, Timeless Woods<br>Fixed: Infernal Pass<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Lampent
(608, NULL, 1, 'Lake of Outrage, Giant''s Bed, Old Cemetery<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Giant''s Bed, Snowslide Slope, Ballimere Lake<br>Dynamax Adventures'),
(608, NULL, 2, 'Lake of Outrage, Giant''s Bed, Old Cemetery<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Giant''s Bed, Snowslide Slope, Ballimere Lake<br>Dynamax Adventures'),
(608, NULL, 3, NULL),
(608, NULL, 4, 'Timeless Woods<br>Fixed: Infernal Pass<br>Tera Raid Battles: 4 Star Raid Battles'),
(608, NULL, 5, 'Timeless Woods<br>Fixed: Infernal Pass<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Chandelure
(609, NULL, 1, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Stony Wilderness, Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert, Giant''s Bed, Snowslide Slope, Ballimere Lake'),
(609, NULL, 2, 'Lake of Outrage, Giant''s Bed<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Stony Wilderness, Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert, Giant''s Bed, Snowslide Slope, Ballimere Lake'),
(609, NULL, 3, NULL),
(609, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(609, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Axew
(610, NULL, 1, 'Route 6, Axew''s Eye, Hammerlocke Hills<br>Max Raid Battles: Axew''s Eye, Rolling Fields'),
(610, NULL, 2, 'Route 6, Axew''s Eye, Hammerlocke Hills<br>Max Raid Battles: Axew''s Eye, Rolling Fields'),
(610, NULL, 3, NULL),
(610, NULL, 4, 'Dalizapa Passage, North Province Area One, South Province Area Three, South Province Area Five, Canyon Biome, Polar Biome<br>Fixed: West Province Area One<br>Tera Raid Battles: 3 Star Raid Battles'),
(610, NULL, 5, 'Dalizapa Passage, North Province Area One, South Province Area Three, South Province Area Five, Canyon Biome, Polar Biome<br>Fixed: West Province Area One<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Fraxure
(611, NULL, 1, 'Max Raid Battles: Axew''s Eye, Rolling Fields<br>Dynamax Adventures'),
(611, NULL, 2, 'Max Raid Battles: Rolling Fields<br>Dynamax Adventures'),
(611, NULL, 3, NULL),
(611, NULL, 4, 'Dalizapa Passage, North Province Area One, Canyon Biome, Polar Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(611, NULL, 5, 'Dalizapa Passage, North Province Area One, Canyon Biome, Polar Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Haxorus
(612, NULL, 1, 'Axew''s Eye, Lake of Outrage<br>Max Raid Battles: Axew''s Eye, Rolling Fields'),
(612, NULL, 2, 'Axew''s Eye, Lake of Outrage<br>Max Raid Battles: Rolling Fields'),
(612, NULL, 3, NULL),
(612, NULL, 4, 'Fixed: Canyon Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(612, NULL, 5, 'Fixed: Canyon Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Cubchoo
(613, NULL, 1, 'Route 10, Bridge Field, Dusty Bowl, Giant''s Mirror, Hammerlocke Hills, Stony Wilderness<br>Max Raid Battles: Stony Wilderness, Giant''s Bed, Frigid Sea'),
(613, NULL, 2, 'Route 10, Bridge Field, Dusty Bowl, Giant''s Mirror, Hammerlocke Hills, Stony Wilderness<br>Max Raid Battles: Stony Wilderness, Dusty Bowl, Giant''s Cap, Giant''s Seat, Stony Wilderness'),
(613, NULL, 3, NULL),
(613, NULL, 4, 'Dalizapa Passage, Glaseado Mountain, Polar Biome<br>Fixed: Glaseado Mountain, Polar Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(613, NULL, 5, 'Dalizapa Passage, Glaseado Mountain, Polar Biome<br>Fixed: Glaseado Mountain, Polar Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Beartic
(614, NULL, 1, 'Route 10, Bridge Field, Giant''s Cap, Snowslide Slope, Frigid Sea<br>Max Raid Battles: Stony Wilderness, Insular Sea, Giant''s Bed, Frigid Sea<br>Dynamax Adventures'),
(614, NULL, 2, 'Route 10, Bridge Field, Giant''s Cap, Snowslide Slope, Frigid Sea<br>Max Raid Battles: Stony Wilderness, Insular Sea, Giant''s Bed, Frigid Sea<br>Dynamax Adventures'),
(614, NULL, 3, NULL),
(614, NULL, 4, 'Glaseado Mountain, Polar Biome<br>Fixed: Glaseado Mountain, Polar Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(614, NULL, 5, 'Glaseado Mountain, Polar Biome<br>Fixed: Glaseado Mountain, Polar Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Cryogonal
(615, NULL, 1, 'Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Frigid Sea<br>Dynamax Adventures'),
(615, NULL, 2, 'Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Giant''s Bed, Frigid Sea<br>Dynamax Adventures'),
(615, NULL, 3, NULL),
(615, NULL, 4, 'Glaseado Mountain<br>Tera Raid Battles: 4 Star Raid Battles'),
(615, NULL, 5, 'Glaseado Mountain<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Shelmet
(616, NULL, 1, 'Route 7, Bridge Field, Hammerlocke Hills, Motostoke Riverbank, Soothing Wetlands, Forest of Focus, Training Lowlands, Giant''s Bed<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch'),
(616, NULL, 2, 'Route 7, Bridge Field, Hammerlocke Hills, Motostoke Riverbank, Soothing Wetlands, Forest of Focus, Training Lowlands, Giant''s Bed<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch'),
(616, NULL, 3, NULL),
(616, NULL, 4, NULL),
(616, NULL, 5, NULL),
-- Accelgor
(617, NULL, 1, 'Forest of Focus, Training Lowlands<br>Max Raid Battles: Fields of Honor, Forest of Focus, Workout Sea<br>Dynamax Adventures'),
(617, NULL, 2, 'Forest of Focus, Training Lowlands<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch, Fields of Honor, Forest of Focus, Workout Sea<br>Dynamax Adventures'),
(617, NULL, 3, NULL),
(617, NULL, 4, NULL),
(617, NULL, 5, NULL),
-- Stunfisk
(618, NULL, 1, 'Trade from Regina in Isle of Armor Are'),
(618, NULL, 2, 'Trade from Regina in Isle of Armor Are'),
(618, NULL, 3, NULL),
(618, NULL, 4, NULL),
(618, NULL, 5, NULL),
-- Galarian Stunfisk
(618, 2, 1, 'Dusty Bowl, Galar Mine No. 2, Lake of Outrage, Slumbering Weald<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Seat, Rolling Fields, Stony Wilderness<br>Dynamax Adventures'),
(618, 2, 2, 'Dusty Bowl, Galar Mine No. 2, Lake of Outrage, Slumbering Weald<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Seat, Rolling Fields, Stony Wilderness<br>Dynamax Adventures'),
(618, 2, 3, NULL),
(618, 2, 4, NULL),
(618, 2, 5, NULL),
-- Mienfoo
(619, NULL, 1, 'Challenge Road<br>Max Raid Battles: Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea'),
(619, NULL, 2, 'Challenge Road<br>Max Raid Battles: Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea'),
(619, NULL, 3, NULL),
(619, NULL, 4, 'Apple Hills, Chilling Waterhead, Kitakami Road, Oni Mountain, Paradise Barrens, Wistful Fields<br>Fixed: Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
(619, NULL, 5, 'Apple Hills, Chilling Waterhead, Kitakami Road, Oni Mountain, Paradise Barrens, Wistful Fields<br>Fixed: Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Mienshao
(620, NULL, 1, 'Challenge Road<br>Max Raid Battles: Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea<br>Dynamax Adventures'),
(620, NULL, 2, 'Challenge Road<br>Max Raid Battles: Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea<br>Dynamax Adventures'),
(620, NULL, 3, NULL),
(620, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(620, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Druddigon
(621, NULL, 1, 'Brawlers'' Cave, Courageous Cavern, Snowslide Slope, Tunnel to the Top, Path to the Peak, Three-Point Pass<br>Max Raid Battles: Loop Lagoon, Workout Sea, Honeycalm Sea, Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Dynamax Adventures'),
(621, NULL, 2, 'Brawlers'' Cave, Courageous Cavern, Snowslide Slope, Tunnel to the Top, Path to the Peak, Three-Point Pass<br>Max Raid Battles: Loop Lagoon, Workout Sea, Honeycalm Sea, Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Dynamax Adventures'),
(621, NULL, 3, NULL),
(621, NULL, 4, NULL),
(621, NULL, 5, NULL),
-- Golett
(622, NULL, 1, 'Route 8, Dappled Grove, Giant''s Cap, Giant''s Seat, North Lake Miloch, Rolling Fields, Stony Wilderness, Watchtower Ruins<br>Max Raid Battles: Bridge Field, Dusty Bowl, Rolling Fields, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(622, NULL, 2, 'Route 8, Dappled Grove, Giant''s Cap, Giant''s Seat, North Lake Miloch, Rolling Fields, Stony Wilderness, Watchtower Ruins<br>Max Raid Battles: Bridge Field, Dusty Bowl, Rolling Fields, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake'),
(622, NULL, 3, NULL),
(622, NULL, 4, 'Canyon Biome, Polar Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(622, NULL, 5, 'Canyon Biome, Polar Biome<br>Fixed: Canyon Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Golurk
(623, NULL, 1, 'Dusty Bowl, Giant''s Seat, Lake of Outrage, Stony Wilderness, Watchtower Ruins, Three-Point Pass<br>Max Raid Battles: Bridge Field, Dusty Bowl, Rolling Fields, Challenge Beach, Courageous Cavern, Stepping-Stone Sea, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(623, NULL, 2, 'Dusty Bowl, Giant''s Seat, Lake of Outrage, Stony Wilderness, Watchtower Ruins, Three-Point Pass<br>Max Raid Battles: Bridge Field, Dusty Bowl, Rolling Fields, Challenge Beach, Courageous Cavern, Stepping-Stone Sea, Frostpoint Field, Giant''s Bed, Snowslide Slope, Frigid Sea, Ballimere Lake<br>Dynamax Adventures'),
(623, NULL, 3, NULL),
(623, NULL, 4, 'Canyon Biome, Polar Biome<br>Fixed: Canyon Biome, Polar Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(623, NULL, 5, 'Canyon Biome, Polar Biome<br>Fixed: Canyon Biome, Polar Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Pawniard
(624, NULL, 1, 'Route 8, Giant''s Cap, Giant''s Mirror, Motostoke Outskirts, Motostoke Riverbank, Stony Wilderness, Soothing Wetlands, Forest of Focus, Challenge Road, Potbottom Desert<br>Max Raid Battles: Dusty Bowl, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Stony Wilderness, West Lake Axewell, Soothing Wetlands, Brawlers'' Cave, Challenge Road, Courageous Cavern, Workout Sea, Stepping-Stone Sea, Honeycalm Sea'),
(624, NULL, 2, 'Route 8, Giant''s Cap, Giant''s Mirror, Motostoke Outskirts, Motostoke Riverbank, Stony Wilderness, Soothing Wetlands, Forest of Focus, Challenge Road, Potbottom Desert<br>Max Raid Battles: Dusty Bowl, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Stony Wilderness, West Lake Axewell, Soothing Wetlands, Brawlers'' Cave, Challenge Road, Courageous Cavern, Workout Sea, Stepping-Stone Sea, Honeycalm Sea'),
(624, NULL, 3, NULL),
(624, NULL, 4, 'East Province Area Three, Inlet Grotto, North Province Area Two, South Province Area Five, Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Timeless Woods, Wistful Fields<br>Tera Raid Battles: 2 Star Raid Battles'),
(624, NULL, 5, 'East Province Area Three, Inlet Grotto, North Province Area Two, South Province Area Five, Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Timeless Woods, Wistful Fields<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Bisharp
(625, NULL, 1, 'Giant''s Seat, Lake of Outrage, Challenge Road, Training Lowlands<br>Max Raid Battles: Dusty Bowl, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Stony Wilderness, West Lake Axewell, Soothing Wetlands, Brawlers'' Cave, Challenge Road, Courageous Cavern, Workout Sea, Stepping-Stone Sea, Honeycalm Sea<br>Dynamax Adventures'),
(625, NULL, 2, 'Giant''s Seat, Lake of Outrage, Challenge Road, Training Lowlands<br>Max Raid Battles: Dusty Bowl, Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Stony Wilderness, West Lake Axewell, Soothing Wetlands, Brawlers'' Cave, Challenge Road, Courageous Cavern, Workout Sea, Stepping-Stone Sea, Honeycalm Sea<br>Dynamax Adventures'),
(625, NULL, 3, NULL),
(625, NULL, 4, 'Area Zero, North Province Area Two, Timeless Woods<br>Tera Raid Battles: 4 Star Raid Battles'),
(625, NULL, 5, 'Area Zero, North Province Area Two, Timeless Woods<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Bouffalant
(626, NULL, 1, 'Soothing Wetlands<br>Max Raid Battles: Soothing Wetlands, Courageous Cavern, Training Lowlands<br>Dynamax Adventures'),
(626, NULL, 2, 'Soothing Wetlands<br>Max Raid Battles: Soothing Wetlands, Courageous Cavern, Training Lowlands<br>Dynamax Adventures'),
(626, NULL, 3, NULL),
(626, NULL, 4, NULL),
(626, NULL, 5, NULL),
-- Rufflet
(627, NULL, 1, 'Route 8, Bridge Field, Stony Wilderness, Potbottom Desert<br>Max Raid Battles: East Lake Axewell, Rolling Fields, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea'),
(627, NULL, 2, 'Trade from Pokémon Sword'),
(627, NULL, 3, 'Alabaster Icelands: Lake Acuity, Heart''s Crag or nearby<br>Alabaster Icelands: Massive Mass Outbreak'),
(627, NULL, 4, 'Asado Desert, Dalizapa Passage, East Province Area Three, Glaseado Mountain, North Province Area One, North Province Area Two, South Province Area One, South Province Area Three, South Province Area Four, South Province Area Six, Savanna Biome<br>Fixed: South Province Area Four<br>Tera Raid Battles: 3 Star Raid Battles'),
(627, NULL, 5, 'Asado Desert, Dalizapa Passage, East Province Area Three, Glaseado Mountain, North Province Area One, North Province Area Two, South Province Area One, South Province Area Three, South Province Area Four, South Province Area Six, Savanna Biome<br>Fixed: South Province Area Four<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Braviary
(628, NULL, 1, 'Dusty Bowl, Lake of Outrage, Challenge Road, Potbottom Desert<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea'),
(628, NULL, 2, 'Trade from Pokémon Sword'),
(628, NULL, 3, NULL),
(628, NULL, 4, 'Asado Desert, Savanna Biome<br>Fixed: Asado Desert, North Province Area One, Savanna Biome<br>Tera Raid Battles: 5 Star Raid Battles'),
(628, NULL, 5, 'Asado Desert, Savanna Biome<br>Fixed: Asado Desert, North Province Area One, Savanna Biome<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Hisuian Braviary
(628, 3, 1, NULL),
(628, 3, 2, NULL),
(628, 3, 3, 'Alabaster Icelands: Lake Acuity or nearby<br>Alabaster Icelands: Massive Mass Outbreak'),
(628, 3, 4, 'Transfer from Pokémon HOME'),
(628, 3, 5, 'Transfer from Pokémon HOME'),
-- Vullaby
(629, NULL, 1, 'Trade from Pokémon Shield'),
(629, NULL, 2, 'Route 8, Bridge Field, Stony Wilderness, Potbottom Desert<br>Max Raid Battles: East Lake Axewell, Rolling Fields, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea'),
(629, NULL, 3, NULL),
(629, NULL, 4, 'Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Paradise Barrens, Wistful Fields, Savanna Biome<br>Fixed: Fellhorn Gorge, Paradise Barrens, Savanna Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(629, NULL, 5, 'Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Paradise Barrens, Wistful Fields, Savanna Biome<br>Fixed: Fellhorn Gorge, Paradise Barrens, Savanna Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Mandibuzz
(630, NULL, 1, 'Trade from Pokémon Shield'),
(630, NULL, 2, 'Dusty Bowl, Lake of Outrage, Challenge Road, Potbottom Desert<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Challenge Road, Loop Lagoon, Workout Sea, Stepping-Stone Sea'),
(630, NULL, 3, NULL),
(630, NULL, 4, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(630, NULL, 5, 'Savanna Biome<br>Fixed: Savanna Biome<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Heatmor
(631, NULL, 1, 'Route 6, Giant''s Mirror, Lake of Outrage, Giant''s Bed, Old Cemetery, Three-Point Pass<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Giant''s Bed, Snowslide Slope, Ballimere Lake<br>Dynamax Adventures'),
(631, NULL, 2, 'Route 6, Giant''s Mirror, Lake of Outrage, Giant''s Bed, Old Cemetery, Three-Point Pass<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Giant''s Bed, Snowslide Slope, Ballimere Lake<br>Dynamax Adventures'),
(631, NULL, 3, NULL),
(631, NULL, 4, NULL),
(631, NULL, 5, NULL),
-- Durant
(632, NULL, 1, 'Route 6, Giant''s Mirror, Lake of Outrage, Giant''s Bed, Old Cemetery, Three-Point Pass<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Seat, Hammerlocke Hills, Rolling Fields, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea<br>Dynamax Adventures'),
(632, NULL, 2, 'Route 6, Giant''s Mirror, Lake of Outrage, Giant''s Bed, Old Cemetery, Three-Point Pass<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Seat, Hammerlocke Hills, Rolling Fields, Giant''s Bed, Snowslide Slope, Path to the Peak, Frigid Sea<br>Dynamax Adventures'),
(632, NULL, 3, NULL),
(632, NULL, 4, NULL),
(632, NULL, 5, NULL),
-- Deino
(633, NULL, 1, 'Lake of Outrage, Roaring-Sea Caves'),
(633, NULL, 2, 'Trade from Pokémon Sword'),
(633, NULL, 3, NULL),
(633, NULL, 4, 'Alfornada Cavern, Dalizapa Passage, Glaseado Mountain, North Province Area Two<br>Tera Raid Battles: 3 Star Raid Battles'),
(633, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Zweilous
(634, NULL, 1, 'Lake of Outrage<br>Max Raid Battles: Dusty Bowl, Giant''s Mirror'),
(634, NULL, 2, 'Trade from Pokémon Sword'),
(634, NULL, 3, NULL),
(634, NULL, 4, 'Area Zero, Glaseado Mountain, North Province Area Two<br>Tera Raid Battles: 4 Star Raid Battles'),
(634, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Hydreigon
(635, NULL, 1, 'Roaring-Sea Caves<br>Max Raid Battles: Bridge Field, Dusty Bowl, Giant''s Mirror, Stony Wilderness, West Lake Axewell'),
(635, NULL, 2, 'Trade from Pokémon Sword'),
(635, NULL, 3, NULL),
(635, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(635, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Larvesta
(636, NULL, 1, 'Forest of Focus, Loop Lagoon<br>Max Raid Battles: Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert'),
(636, NULL, 2, 'Forest of Focus, Loop Lagoon<br>Max Raid Battles: Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert'),
(636, NULL, 3, NULL),
(636, NULL, 4, 'Asado Desert<br>Tera Raid Battles: 3 Star Raid Battles'),
(636, NULL, 5, 'Asado Desert<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Volcarona
(637, NULL, 1, 'Challenge Beach, Insular Sea, Potbottom Desert<br>Max Raid Battles: Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert'),
(637, NULL, 2, 'Challenge Beach, Insular Sea, Potbottom Desert<br>Max Raid Battles: Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert'),
(637, NULL, 3, NULL),
(637, NULL, 4, 'Area Zero<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(637, NULL, 5, 'Area Zero<br>Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Cobalion
(638, NULL, 1, 'Frigid Sea'),
(638, NULL, 2, 'Frigid Sea'),
(638, NULL, 3, NULL),
(638, NULL, 4, 'North Province Area Two - Requires Snack from Snacksworth'),
(638, NULL, 5, 'North Province Area Two - Requires Snack from Snacksworth'),
-- Terrakion
(639, NULL, 1, 'Lakeside Cave'),
(639, NULL, 2, 'Lakeside Cave'),
(639, NULL, 3, NULL),
(639, NULL, 4, 'West Province Area One - Requires Snack from Snacksworth'),
(639, NULL, 5, 'West Province Area One - Requires Snack from Snacksworth'),
-- Virizion
(640, NULL, 1, 'Giant''s Bed'),
(640, NULL, 2, 'Giant''s Bed'),
(640, NULL, 3, NULL),
(640, NULL, 4, 'Tagtree Thicket - Requires Snack from Snacksworth'),
(640, NULL, 5, 'Tagtree Thicket - Requires Snack from Snacksworth'),
-- Tornadus
(641, NULL, 1, 'Dynamax Adventures'),
(641, NULL, 2, 'Trade from Pokémon Sword'),
(641, NULL, 3, 'Alabaster Icelands: Bonechill Wastes'),
(641, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(641, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Thundurus
(642, NULL, 1, 'Trade from Pokémon Shield'),
(642, NULL, 2, 'Dynamax Adventures'),
(642, NULL, 3, 'Cobalt Coastlands'),
(642, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(642, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Reshiram
(643, NULL, 1, 'Dynamax Adventures'),
(643, NULL, 2, 'Trade from Pokémon Sword'),
(643, NULL, 3, NULL),
(643, NULL, 4, 'East Province Area Two - Requires Snack from Snacksworth'),
(643, NULL, 5, 'East Province Area Two - Requires Snack from Snacksworth'),
-- Zekrom
(644, NULL, 1, 'Trade from Pokémon Shield'),
(644, NULL, 2, 'Dynamax Adventures'),
(644, NULL, 3, NULL),
(644, NULL, 4, 'South Province Area Five - Requires Snack from Snacksworth'),
(644, NULL, 5, 'South Province Area Five - Requires Snack from Snacksworth'),
-- Landorus
(645, NULL, 1, 'Dynamax Adventures'),
(645, NULL, 2, 'Dynamax Adventures'),
(645, NULL, 3, 'Obsidian Fieldlands: Ramanas Island'),
(645, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(645, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Kyurem
(646, NULL, 1, 'Dynamax Adventures'),
(646, NULL, 2, 'Dynamax Adventures'),
(646, NULL, 3, NULL),
(646, NULL, 4, 'Dalizapa Passage - Requires Snack from Snacksworth'),
(646, NULL, 5, 'Dalizapa Passage - Requires Snack from Snacksworth'),
-- Keldeo
(647, NULL, 1, 'Ballimere Lake'),
(647, NULL, 2, 'Ballimere Lake'),
(647, NULL, 3, NULL),
(647, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(647, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Meloetta
(648, NULL, 1, NULL),
(648, NULL, 2, NULL),
(648, NULL, 3, NULL),
(648, NULL, 4, 'Coastal Biome - Spin in middle of cyclone and turn camera on to Sepia Filter'),
(648, NULL, 5, 'Coastal Biome - Spin in middle of cyclone and turn camera on to Sepia Filter'),
-- Genesect
(649, NULL, 1, 'Transfer from Pokémon HOME or obtain from event'),
(649, NULL, 2, 'Transfer from Pokémon HOME or obtain from event'),
(649, NULL, 3, NULL),
(649, NULL, 4, NULL),
(649, NULL, 5, NULL);

COMMIT TRANSACTION;