BEGIN TRANSACTION;

INSERT INTO Pokemon_Location (pokedex_number, region_id, game_id, location_name)
VALUES 

-- Rowlet
(722, NULL, 1, 'Gift from Diglett Master (if Grookey picked)'),
(722, NULL, 2, 'Gift from Diglett Master (if Grookey picked)'),
(722, NULL, 3, 'Gift from Laventon<br>Space-time Distortion in Coronet Highlands or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(722, NULL, 4, 'Savanna Biome'),
(722, NULL, 5, 'Savanna Biome'),
-- Dartrix
(723, NULL, 1, 'Evolve Rowlet'),
(723, NULL, 2, 'Evolve Rowlet'),
(723, NULL, 3, 'Space-time Distortion in Coronet Highlands or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(723, NULL, 4, 'Evolve Rowlet'),
(723, NULL, 5, 'Evolve Rowlet'),
-- Decidueye
(724, NULL, 1, 'Evolve Dartrix'),
(724, NULL, 2, 'Evolve Dartrix'),
(724, NULL, 3, NULL),
(724, NULL, 4, 'Evolve Dartrix'),
(724, NULL, 5, 'Evolve Dartrix'),
-- Hisuian Decidueye
(724, 3, 1, NULL),
(724, 3, 2, NULL),
(724, 3, 3, 'Space-time Distortion in Coronet Highlands or nearby<br>Coronet Highlands: Massive Mass Outbreak'),
(724, 3, 4, 'Transfer through Pokémon HOME'),
(724, 3, 5, 'Transfer through Pokémon HOME'),
-- Litten
(725, NULL, 1, 'Gift from Diglett Master (if Scorbunny picked)'),
(725, NULL, 2, 'Gift from Diglett Master (if Scorbunny picked)'),
(725, NULL, 3, NULL),
(725, NULL, 4, 'Canyon Biome'),
(725, NULL, 5, 'Canyon Biome'),
-- Torracat
(726, NULL, 1, 'Evolve Litten'),
(726, NULL, 2, 'Evolve Litten'),
(726, NULL, 3, NULL),
(726, NULL, 4, 'Evolve Litten'),
(726, NULL, 5, 'Evolve Litten'),
-- Incineroar
(727, NULL, 1, 'Evolve Torracat'),
(727, NULL, 2, 'Evolve Torracat'),
(727, NULL, 3, NULL),
(727, NULL, 4, 'Evolve Torracat'),
(727, NULL, 5, 'Evolve Torracat'),
-- Popplio
(728, NULL, 1, 'Gift from Diglett Master (if Sobble picked)'),
(728, NULL, 2, 'Gift from Diglett Master (if Sobble picked)'),
(728, NULL, 3, NULL),
(728, NULL, 4, 'Coastal Biome'),
(728, NULL, 5, 'Coastal Biome'),
-- Brionne
(729, NULL, 1, 'Evolve Popplio'),
(729, NULL, 2, 'Evolve Popplio'),
(729, NULL, 3, NULL),
(729, NULL, 4, 'Evolve Popplio'),
(729, NULL, 5, 'Evolve Popplio'),
-- Primarina
(730, NULL, 1, 'Evolve Brionne'),
(730, NULL, 2, 'Evolve Brionne'),
(730, NULL, 3, NULL),
(730, NULL, 4, 'Evolve Brionne'),
(730, NULL, 5, 'Evolve Brionne'),
-- Pikipek
(731, NULL, 1, NULL),
(731, NULL, 2, NULL),
(731, NULL, 3, NULL),
(731, NULL, 4, 'Coastal Biome, Torchlit Labyrinth<br>Tera Raid Battles: 1 Star Raid Battles'),
(731, NULL, 5, 'Coastal Biome, Torchlit Labyrinth<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Trumbeak
(732, NULL, 1, NULL),
(732, NULL, 2, NULL),
(732, NULL, 3, NULL),
(732, NULL, 4, 'Coastal Biome, Torchlit Labyrinth<br>Fixed: Canyon Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(732, NULL, 5, 'Coastal Biome, Torchlit Labyrinth<br>Fixed: Canyon Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Toucannon
(733, NULL, 1, NULL),
(733, NULL, 2, NULL),
(733, NULL, 3, NULL),
(733, NULL, 4, 'Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome'),
(733, NULL, 5, 'Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome'),
-- Yungoos
(734, NULL, 1, NULL),
(734, NULL, 2, NULL),
(734, NULL, 3, NULL),
(734, NULL, 4, 'Asado Desert, East Province Area One, East Province Area Two, East Province Area Three, Inlet Grotto, South Province Area One, South Province Area Three, South Province Area Four, South Province Area Five, West Province Area One, West Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
(734, NULL, 5, 'Asado Desert, East Province Area One, East Province Area Two, East Province Area Three, Inlet Grotto, South Province Area One, South Province Area Three, South Province Area Four, South Province Area Five, West Province Area One, West Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Gumshoos
(735, NULL, 1, NULL),
(735, NULL, 2, NULL),
(735, NULL, 3, NULL),
(735, NULL, 4, 'Alfornada Cavern, Asado Desert, Dalizapa Passage, East Province Area One, East Province Area Two, East Province Area Three, Glaseado Mountain, Inlet Grotto, North Province Area One, South Province Area Three, South Province Area Five, South Province Area Six, Tagtree Thicket, West Province Area One, West Province Area Two, West Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles'),
(735, NULL, 5, 'Alfornada Cavern, Asado Desert, Dalizapa Passage, East Province Area One, East Province Area Two, East Province Area Three, Glaseado Mountain, Inlet Grotto, North Province Area One, South Province Area Three, South Province Area Five, South Province Area Six, Tagtree Thicket, West Province Area One, West Province Area Two, West Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Grubbin
(736, NULL, 1, 'Route 1, Dappled Grove, East Lake Axewell, North Lake Miloch, Slumbering Weald, Watchtower Ruins<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields'),
(736, NULL, 2, 'Route 1, Dappled Grove, East Lake Axewell, North Lake Miloch, Slumbering Weald, Watchtower Ruins<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields'),
(736, NULL, 3, NULL),
(736, NULL, 4, 'Apple Hills, Fellhorn Gorge, Kitakami Road, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
(736, NULL, 5, 'Apple Hills, Fellhorn Gorge, Kitakami Road, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Charjabug
(737, NULL, 1, 'Axew''s Eye, Dusty Bowl, Hammerlocke Hills<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Cap, Motostoke Riverbank, Rolling Fields<br>Dynamax Adventures'),
(737, NULL, 2, 'Axew''s Eye, Dusty Bowl, Hammerlocke Hills<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Cap, Motostoke Riverbank, Rolling Fields<br>Dynamax Adventures'),
(737, NULL, 3, NULL),
(737, NULL, 4, 'Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
(737, NULL, 5, 'Fellhorn Gorge, Kitakami Wilds, Oni Mountain, Paradise Barrens, Timeless Woods, Wistful Fields<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Vikavolt
(738, NULL, 1, 'Giant''s Mirror, Giant''s Seat<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Cap, Giant''s Mirror, Motostoke Riverbank, Rolling Fields'),
(738, NULL, 2, 'Giant''s Mirror, Giant''s Seat<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Cap, Giant''s Mirror, Motostoke Riverbank, Rolling Fields'),
(738, NULL, 3, NULL),
(738, NULL, 4, 'Fixed: Kitakami Wilds<br>Tera Raid Battles: 5 Star Raid Battles'),
(738, NULL, 5, 'Fixed: Kitakami Wilds<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Crabrawler
(739, NULL, 1, NULL),
(739, NULL, 2, NULL),
(739, NULL, 3, NULL),
(739, NULL, 4, 'East Province Area Two, Glaseado Mountain, South Province Area Five, West Province Area One, West Province Area Two, Coastal Biome, Polar Biome<br>Fixed: East Province Area Two, Coastal Biome, Polar Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
(739, NULL, 5, 'East Province Area Two, Glaseado Mountain, South Province Area Five, West Province Area One, West Province Area Two, Coastal Biome, Polar Biome<br>Fixed: East Province Area Two, Coastal Biome, Polar Biome<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Crabominable
(740, NULL, 1, NULL),
(740, NULL, 2, NULL),
(740, NULL, 3, NULL),
(740, NULL, 4, 'Glaseado Mountain, Polar Biome<br>Fixed: East Province Area Two<br>Tera Raid Battles: 4 Star Raid Battles'),
(740, NULL, 5, 'Glaseado Mountain, Polar Biome<br>Fixed: East Province Area Two<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Oricorio
(741, NULL, 1, NULL),
(741, NULL, 2, NULL),
(741, NULL, 3, NULL),
(741, NULL, 4, 'East Province Area One, South Province Area One, Wistful Fields, Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(741, NULL, 5, 'East Province Area One, South Province Area One, Wistful Fields, Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Cutiefly
(742, NULL, 1, 'Route 4, Bridge Field, Giant''s Mirror, Motostoke Riverbank<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Rolling Fields, South Lake Miloch, Training Lowlands'),
(742, NULL, 2, 'Route 4, Bridge Field, Giant''s Mirror, Motostoke Riverbank<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Rolling Fields, South Lake Miloch, Training Lowlands'),
(742, NULL, 3, NULL),
(742, NULL, 4, 'Kitakami Road, Mossfell Confluence, Paradise Barrens, Wistful Fields<br>Fixed: Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
(742, NULL, 5, 'Kitakami Road, Mossfell Confluence, Paradise Barrens, Wistful Fields<br>Fixed: Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Ribombee
(743, NULL, 1, 'Bridge Field, Motostoke Riverbank, Stony Wilderness<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Rolling Fields, South Lake Miloch, Training Lowlands<br>Dynamax Adventures'),
(743, NULL, 2, 'Bridge Field, Motostoke Riverbank, Stony Wilderness<br>Max Raid Battles: Bridge Field, Hammerlocke Hills, Rolling Fields, South Lake Miloch, Training Lowlands<br>Dynamax Adventures'),
(743, NULL, 3, NULL),
(743, NULL, 4, 'Mossfell Confluence<br>Fixed: Wistful Fields<br>Tera Raid Battles: 4 Star Raid Battles'),
(743, NULL, 5, 'Mossfell Confluence<br>Fixed: Wistful Fields<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Rockruff
(744, NULL, 1, 'Fields of Honor, Soothing Wetlands, Challenge Road, Loop Lagoon<br>Max Raid Battles: Fields of Honor, Challenge Road, Training Lowlands, Potbottom Desert'),
(744, NULL, 2, 'Fields of Honor, Soothing Wetlands, Challenge Road, Loop Lagoon<br>Max Raid Battles: Fields of Honor, Challenge Road, Training Lowlands, Potbottom Desert'),
(744, NULL, 3, NULL),
(744, NULL, 4, 'East Province Area Two, South Province Area One, South Province Area Four, West Province Area One, Chilling Waterhead, Crystal Pool, Fellhorn Gorge, Infernal Pass, Kitakami Hall, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Fixed: West Province Area Three, Chilling Waterhead, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
(744, NULL, 5, 'East Province Area Two, South Province Area One, South Province Area Four, West Province Area One, Chilling Waterhead, Crystal Pool, Fellhorn Gorge, Infernal Pass, Kitakami Hall, Kitakami Wilds, Mossfell Confluence, Oni Mountain, Paradise Barrens, Reveler''s Road, Wistful Fields<br>Fixed: West Province Area Three, Chilling Waterhead, Wistful Fields<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Lycanroc
(745, NULL, 1, 'Challenge Road<br>Max Raid Battles: Fields of Honor, Challenge Road, Training Lowlands, Potbottom Desert<br>Dynamax Adventures'),
(745, NULL, 2, 'Challenge Road<br>Max Raid Battles: Fields of Honor, Challenge Road, Training Lowlands, Potbottom Desert<br>Dynamax Adventures'),
(745, NULL, 3, NULL),
(745, NULL, 4, 'Alfornada Cavern, Dalizapa Passage, Glaseado Mountain, North Province Area One, Area Zero, Fellhorn Gorge, Kitakami Wilds, Oni Mountain<br>Tera Raid Battles: 4 Star Raid Battles, 6 Star Raid Battles'),
(745, NULL, 5, 'Alfornada Cavern, Dalizapa Passage, Glaseado Mountain, North Province Area One, Area Zero, Fellhorn Gorge, Kitakami Wilds, Oni Mountain<br>Tera Raid Battles: 4 Star Raid Battles, 6 Star Raid Battles'),
-- Wishiwashi
(746, NULL, 1, 'Route 9, Axew''s Eye, East Lake Axewell, Hulbury, West Lake Axewell, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: Bridge Field, Dusty Bowl, East Lake Axewell, Giant''s Cap, Lake of Outrage, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea'),
(746, NULL, 2, 'Route 9, Axew''s Eye, East Lake Axewell, Hulbury, West Lake Axewell, Stepping-Stone Sea, Insular Sea, Honeycalm Sea, Honeycalm Island<br>Max Raid Battles: Bridge Field, Dusty Bowl, East Lake Axewell, Giant''s Cap, Lake of Outrage, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon, Workout Sea, Stepping-Stone Sea, Insular Sea, Honeycalm Sea'),
(746, NULL, 3, NULL),
(746, NULL, 4, NULL),
(746, NULL, 5, NULL),
-- Mareanie
(747, NULL, 1, 'Route 9, Giant''s Mirror, Motostoke Riverbank, Loop Lagoon<br>Max Raid Battles: Bridge Field, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Loop Lagoon, Training Lowlands, Stepping-Stone Sea'),
(747, NULL, 2, 'Route 9, Giant''s Mirror, Motostoke Riverbank, Loop Lagoon<br>Max Raid Battles: Bridge Field, East Lake Axewell, Giant''s Mirror, Lake of Outrage, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Loop Lagoon, Training Lowlands, Stepping-Stone Sea'),
(747, NULL, 3, NULL),
(747, NULL, 4, 'East Paldean Sea<br>Tera Raid Battles: 3 Star Raid Battles'),
(747, NULL, 5, 'East Paldean Sea<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Toxapex
(748, NULL, 1, 'Route 9, Fields of Honor, Challenge Beach, Loop Lagoon<br>Max Raid Battles: Bridge Field, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Loop Lagoon, Training Lowlands, Stepping-Stone Sea'),
(748, NULL, 2, 'Route 9, Fields of Honor, Challenge Beach, Loop Lagoon<br>Max Raid Battles: Bridge Field, East Lake Axewell, Giant''s Mirror, Lake of Outrage, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Loop Lagoon, Training Lowlands, Stepping-Stone Sea'),
(748, NULL, 3, NULL),
(748, NULL, 4, 'Fixed: East Paldean Sea<br>Tera Raid Battles: 6 Star Raid Battles'),
(748, NULL, 5, 'Fixed: East Paldean Sea<br>Tera Raid Battles: 6 Star Raid Battles'),
-- Mudbray
(749, NULL, 1, 'Route 3, Dappled Grove, East Lake Axewell, Giant''s Cap, Giant''s Seat, North Lake Miloch, Rolling Fields, South Lake Miloch, West Lake Axewell<br>Max Raid Battles: Bridge Field, Rolling Fields'),
(749, NULL, 2, 'Route 3, Dappled Grove, East Lake Axewell, Giant''s Cap, Giant''s Seat, North Lake Miloch, Rolling Fields, South Lake Miloch, West Lake Axewell<br>Max Raid Battles: Bridge Field, Rolling Fields'),
(749, NULL, 3, NULL),
(749, NULL, 4, 'Dalizapa Passage, East Province Area Two, South Province Area One, South Province Area Two, South Province Area Five, West Province Area One, Paradise Barrens, Wistful Fields<br>Fixed: Paradise Barrens<br>Tera Raid Battles: 2 Star Raid Battles'),
(749, NULL, 5, 'Dalizapa Passage, East Province Area Two, South Province Area One, South Province Area Two, South Province Area Five, West Province Area One, Paradise Barrens, Wistful Fields<br>Fixed: Paradise Barrens<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Mudsdale
(750, NULL, 1, 'Axew''s Eye, Dusty Bowl, East Lake Axewell, Giant''s Seat, Rolling Fields<br>Max Raid Battles: Bridge Field, Rolling Fields<br>Dynamax Adventures'),
(750, NULL, 2, 'Axew''s Eye, Dusty Bowl, East Lake Axewell, Giant''s Seat, Rolling Fields<br>Max Raid Battles: Bridge Field, Rolling Fields<br>Dynamax Adventures'),
(750, NULL, 3, NULL),
(750, NULL, 4, 'Dalizapa Passage, Glaseado Mountain, North Province Area One, South Province Area Six<br>Tera Raid Battles: 5 Star Raid Battles'),
(750, NULL, 5, 'Dalizapa Passage, Glaseado Mountain, North Province Area One, South Province Area Six<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Dewpider
(751, NULL, 1, 'Route 5, Motostoke Riverbank, Stony Wilderness, Giant''s Bed, Old Cemetery, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dappled Grove, Dusty Bowl, Lake of Outrage, Rolling Fields, South Lake Miloch, West Lake Axewell, Fields of Honor, Soothing Wetlands, Courageous Cavern'),
(751, NULL, 2, 'Route 5, Motostoke Riverbank, Stony Wilderness, Giant''s Bed, Old Cemetery, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dappled Grove, Dusty Bowl, Lake of Outrage, Rolling Fields, South Lake Miloch, West Lake Axewell, Fields of Honor, Soothing Wetlands, Courageous Cavern'),
(751, NULL, 3, NULL),
(751, NULL, 4, 'Coastal Biome, Savanna Biome, Torchlit Labyrinth<br>Tera Raid Battles: 2 Star Raid Battles'),
(751, NULL, 5, 'Coastal Biome, Savanna Biome, Torchlit Labyrinth<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Araquanid
(752, NULL, 1, 'Lake of Outrage, Stony Wilderness, Giant''s Bed, Old Cemetery, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dappled Grove, Dusty Bowl, Lake of Outrage, Rolling Fields, South Lake Miloch, West Lake Axewell, Fields of Honor, Soothing Wetlands, Courageous Cavern, Slippery Slope, Giant''s Bed, Crown Shrine, Giant''s Foot, Ballimere Lake<br>Dynamax Adventures'),
(752, NULL, 2, 'Lake of Outrage, Stony Wilderness, Giant''s Bed, Old Cemetery, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Bridge Field, Dappled Grove, Dusty Bowl, Lake of Outrage, Rolling Fields, South Lake Miloch, West Lake Axewell, Fields of Honor, Soothing Wetlands, Courageous Cavern, Slippery Slope, Giant''s Bed, Crown Shrine, Giant''s Foot, Ballimere Lake<br>Dynamax Adventures'),
(752, NULL, 3, NULL),
(752, NULL, 4, 'Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
(752, NULL, 5, 'Coastal Biome, Torchlit Labyrinth<br>Fixed: Coastal Biome<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Fomantis
(753, NULL, 1, 'Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Training Lowlands<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Training Lowlands, Insular Sea'),
(753, NULL, 2, 'Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Training Lowlands<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Training Lowlands, Insular Sea'),
(753, NULL, 3, NULL),
(753, NULL, 4, 'South Province Area One, Tagtree Thicket, Apple Hills, Kitakami Hall, Kitakami Road, Kitakami Wilds, Loyalty Plaza, Mossfell Confluence, Oni Mountain, Paradise Barrens, Reveler''s Road, Timeless Woods<br>Tera Raid Battles: 1 Star Raid Battles'),
(753, NULL, 5, 'South Province Area One, Tagtree Thicket, Apple Hills, Kitakami Hall, Kitakami Road, Kitakami Wilds, Loyalty Plaza, Mossfell Confluence, Oni Mountain, Paradise Barrens, Reveler''s Road, Timeless Woods<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Lurantis
(754, NULL, 1, 'Forest of Focus, Challenge Beach<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Training Lowlands, Insular Sea<br>Dynamax Adventures'),
(754, NULL, 2, 'Forest of Focus, Challenge Beach<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Training Lowlands, Insular Sea<br>Dynamax Adventures'),
(754, NULL, 3, NULL),
(754, NULL, 4, 'North Province Area One, North Province Area Two, North Province Area Three, Socarrat Trail, Kitakami Wilds, Timeless Woods<br>Fixed: Casseroya Lake, Kitakami Wilds<br>Tera Raid Battles: 4 Star Raid Battles'),
(754, NULL, 5, 'North Province Area One, North Province Area Two, North Province Area Three, Socarrat Trail, Kitakami Wilds, Timeless Woods<br>Fixed: Casseroya Lake, Kitakami Wilds<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Morelull
(755, NULL, 1, 'Giant''s Mirror, Hammerlocke Hills<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Hammerlocke Hills, Rolling Fields, Stony Wilderness, Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea'),
(755, NULL, 2, 'Giant''s Mirror, Hammerlocke Hills<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Hammerlocke Hills, Rolling Fields, Stony Wilderness, Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea'),
(755, NULL, 3, NULL),
(755, NULL, 4, NULL),
(755, NULL, 5, NULL),
-- Shiinotic
(756, NULL, 1, 'Glimwood Tangle, Lake of Outrage<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Hammerlocke Hills, Rolling Fields, Stony Wilderness, Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea<br>Dynamax Adventures'),
(756, NULL, 2, 'Glimwood Tangle, Lake of Outrage<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Hammerlocke Hills, Rolling Fields, Stony Wilderness, Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea<br>Dynamax Adventures'),
(756, NULL, 3, NULL),
(756, NULL, 4, NULL),
(756, NULL, 5, NULL),
-- Salandit
(757, NULL, 1, 'Stony Wilderness, Challenge Road<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert'),
(757, NULL, 2, 'Motostoke Outskirts, Motostoke Riverbank, Stony Wilderness, Challenge Road<br>Max Raid Battles: Dusty Bowl, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, Stony Wilderness, Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert'),
(757, NULL, 3, NULL),
(757, NULL, 4, 'Alfornada Cavern, Dalizapa Passage, East Province Area Two, East Province Area Three, Glaseado Mountain, West Province Area One, West Province Area Two, Apple Hills, Crystal Pool, Oni Mountain, Oni''s Maw, Reveler''s Road<br>Fixed: East Province Area One, Oni''s Maw<br>Tera Raid Battles: 2 Star Raid Battles'),
(757, NULL, 5, 'Alfornada Cavern, Dalizapa Passage, East Province Area Two, East Province Area Three, Glaseado Mountain, West Province Area One, West Province Area Two, Apple Hills, Crystal Pool, Oni Mountain, Oni''s Maw, Reveler''s Road<br>Fixed: East Province Area One, Oni''s Maw<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Salazzle
(758, NULL, 1, 'Challenge Road<br>Max Raid Battles: Dusty Bowl, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Stony Wilderness, Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert<br>Dynamax Adventures'),
(758, NULL, 2, 'Challenge Road<br>Max Raid Battles: Dusty Bowl, East Lake Axewell, Giant''s Cap, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, North Lake Miloch, Stony Wilderness, Fields of Honor, Challenge Beach, Loop Lagoon, Potbottom Desert<br>Dynamax Adventures'),
(758, NULL, 3, NULL),
(758, NULL, 4, 'Alfornada Cavern, Dalizapa Passage, North Province Area One, North Province Area Two, North Province Area Three<br>Fixed: South Province Area Four'),
(758, NULL, 5, 'Alfornada Cavern, Dalizapa Passage, North Province Area One, North Province Area Two, North Province Area Three<br>Fixed: South Province Area Four'),
-- Stufful
(759, NULL, 1, 'Route 5, Bridge Field, Dappled Grove, East Lake Axewell, Giant''s Seat, Hammerlocke Hills, North Lake Miloch<br>Max Raid Battles: Dusty Bowl, East Lake Axewell, North Lake Miloch, Rolling Fields, Stony Wilderness, Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea'),
(759, NULL, 2, 'Route 5, Bridge Field, Dappled Grove, East Lake Axewell, Giant''s Seat, Hammerlocke Hills, North Lake Miloch<br>Max Raid Battles: Dusty Bowl, East Lake Axewell, North Lake Miloch, Rolling Fields, Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea'),
(759, NULL, 3, NULL),
(759, NULL, 4, NULL),
(759, NULL, 5, NULL),
-- Bewear
(760, NULL, 1, 'Axew''s Eye, Bridge Field, Dappled Grove, Giant''s Seat, Lake of Outrage, West Lake Axewell<br>Max Raid Battles: Dusty Bowl, East Lake Axewell, North Lake Miloch, Rolling Fields, Stony Wilderness, Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea<br>Dynamax Adventures'),
(760, NULL, 2, 'Axew''s Eye, Bridge Field, Dappled Grove, Giant''s Seat, Lake of Outrage, West Lake Axewell<br>Max Raid Battles: Dusty Bowl, East Lake Axewell, North Lake Miloch, Rolling Fields, Stony Wilderness, Fields of Honor, Soothing Wetlands, Stepping-Stone Sea, Insular Sea<br>Dynamax Adventures'),
(760, NULL, 3, NULL),
(760, NULL, 4, NULL),
(760, NULL, 5, NULL),
-- Bounsweet
(761, NULL, 1, 'Dappled Grove, East Lake Axewell, Rolling Fields, Stony Wilderness, Watchtower Ruins, West Lake Axewell<br>Max Raid Battles: Dappled Grove, Giant''s Mirror'),
(761, NULL, 2, 'Dappled Grove, East Lake Axewell, Rolling Fields, Stony Wilderness, Watchtower Ruins, West Lake Axewell<br>Max Raid Battles: Dappled Grove, Giant''s Mirror'),
(761, NULL, 3, NULL),
(761, NULL, 4, 'East Province Area One, East Province Area Two, South Province Area One, South Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
(761, NULL, 5, 'East Province Area One, East Province Area Two, South Province Area One, South Province Area Two<br>Tera Raid Battles: 1 Star Raid Battles'),
-- Steenee
(762, NULL, 1, 'Axew''s Eye<br>Max Raid Battles: Dappled Grove, Giant''s Mirror, Loop Lagoon'),
(762, NULL, 2, 'Axew''s Eye<br>Max Raid Battles: Dappled Grove, Giant''s Mirror, Loop Lagoon'),
(762, NULL, 3, NULL),
(762, NULL, 4, 'East Province Area One, East Province Area Two<br>Fixed: West Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles'),
(762, NULL, 5, 'East Province Area One, East Province Area Two<br>Fixed: West Province Area Three<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Tsareena
(763, NULL, 1, 'Stony Wilderness<br>Max Raid Battles: Dappled Grove, Giant''s Mirror, Loop Lagoon<br>Dynamax Adventures'),
(763, NULL, 2, 'Stony Wilderness<br>Max Raid Battles: Dappled Grove, Giant''s Mirror, Loop Lagoon<br>Dynamax Adventures'),
(763, NULL, 3, NULL),
(763, NULL, 4, 'Fixed: Casseroya Lake<br>Tera Raid Battles: 5 Star Raid Battles'),
(763, NULL, 5, 'Fixed: Casseroya Lake<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Comfey
(764, NULL, 1, 'Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Training Lowlands, Insular Sea, Honeycalm Island<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea<br>Dynamax Adventures'),
(764, NULL, 2, 'Fields of Honor, Soothing Wetlands, Forest of Focus, Challenge Beach, Training Lowlands, Insular Sea, Honeycalm Island<br>Max Raid Battles: Fields of Honor, Soothing Wetlands, Forest of Focus, Insular Sea<br>Dynamax Adventures'),
(764, NULL, 3, NULL),
(764, NULL, 4, 'Coastal Biome<br>Fixed: Coastal Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(764, NULL, 5, 'Coastal Biome<br>Fixed: Coastal Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Oranguru
(765, NULL, 1, 'Dynamax Adventures'),
(765, NULL, 2, 'Glimwood Tangle, Forest of Focus<br>Max Raid Battles: Bridge Field, East Lake Axewell, Motostoke Riverbank, Rolling Fields, Stony Wilderness, Soothing Wetlands, Challenge Beach, Training Lowlands, Stepping-Stone Sea<br>Dynamax Adventures'),
(765, NULL, 3, NULL),
(765, NULL, 4, 'North Province Area Two, Tagtree Thicket<br>Tera Raid Battles: 3 Star Raid Battles , 5 Star Raid Battles'),
(765, NULL, 5, 'Trade from Pokémon Scarlet'),
-- Passimian
(766, NULL, 1, 'Glimwood Tangle, Forest of Focus<br>Max Raid Battles: Dusty Bowl, North Lake Miloch, Rolling Fields, Fields of Honor, Challenge Beach, Challenge Road, Honeycalm Sea'),
(766, NULL, 2, 'Dynamax Adventures'),
(766, NULL, 3, NULL),
(766, NULL, 4, 'Trade from Pokémon Violet'),
(766, NULL, 5, 'North Province Area Two, Tagtree Thicket<br>Tera Raid Battles: 3 Star Raid Battles , 5 Star Raid Battles'),
-- Wimpod
(767, NULL, 1, 'Bridge Field, Galar Mine No. 2, Giant''s Mirror, Hammerlocke Hills, Motostoke Riverbank, Courageous Cavern<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch'),
(767, NULL, 2, 'Bridge Field, Galar Mine No. 2, Giant''s Mirror, Hammerlocke Hills, Motostoke Riverbank, Courageous Cavern<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch'),
(767, NULL, 3, NULL),
(767, NULL, 4, NULL),
(767, NULL, 5, NULL),
-- Golisopod
(768, NULL, 1, 'Bridge Field, Giant''s Cap, Lake of Outrage, Challenge Beach, Courageous Cavern<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch'),
(768, NULL, 2, 'Bridge Field, Giant''s Cap, Lake of Outrage, Challenge Beach, Courageous Cavern<br>Max Raid Battles: Bridge Field, Dappled Grove, Rolling Fields, South Lake Miloch'),
(768, NULL, 3, NULL),
(768, NULL, 4, NULL),
(768, NULL, 5, NULL),
-- Sandygast
(769, NULL, 1, 'Loop Lagoon<br>Max Raid Battles: Challenge Beach, Courageous Cavern, Stepping-Stone Sea'),
(769, NULL, 2, 'Loop Lagoon<br>Max Raid Battles: Challenge Beach, Courageous Cavern, Stepping-Stone Sea'),
(769, NULL, 3, NULL),
(769, NULL, 4, 'East Province Area Two, South Province Area Five, West Province Area Two<br>Fixed: Asado Desert<br>Tera Raid Battles: 2 Star Raid Battles'),
(769, NULL, 5, 'East Province Area Two, South Province Area Five, West Province Area Two<br>Fixed: Asado Desert<br>Tera Raid Battles: 2 Star Raid Battles'),
-- Palossand
(770, NULL, 1, 'Loop Lagoon<br>Max Raid Battles: Challenge Beach, Courageous Cavern, Stepping-Stone Sea<br>Dynamax Adventures'),
(770, NULL, 2, 'Loop Lagoon<br>Max Raid Battles: Challenge Beach, Courageous Cavern, Stepping-Stone Sea<br>Dynamax Adventures'),
(770, NULL, 3, NULL),
(770, NULL, 4, 'West Province Area Two'),
(770, NULL, 5, 'West Province Area Two'),
-- Pyukumuku
(771, NULL, 1, 'Route 9, Giant''s Seat, South Lake Miloch<br>Max Raid Battles: Bridge Field, Dusty Bowl, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Lake of Outrage, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon<br>Dynamax Adventures'),
(771, NULL, 2, 'Route 9, Giant''s Seat, South Lake Miloch<br>Max Raid Battles: Bridge Field, Dusty Bowl, East Lake Axewell, Giant''s Cap, Giant''s Mirror, Lake of Outrage, North Lake Miloch, South Lake Miloch, West Lake Axewell, Fields of Honor, Challenge Beach, Loop Lagoon<br>Dynamax Adventures'),
(771, NULL, 3, NULL),
(771, NULL, 4, NULL),
(771, NULL, 5, NULL),
-- Type: Null
(772, NULL, 1, 'Gift in Battle Tower'),
(772, NULL, 2, 'Gift in Battle Tower'),
(772, NULL, 3, NULL),
(772, NULL, 4, NULL),
(772, NULL, 5, NULL),
-- Silvally
(773, NULL, 1, 'Evolve Type: Null'),
(773, NULL, 2, 'Evolve Type: Null'),
(773, NULL, 3, NULL),
(773, NULL, 4, NULL),
(773, NULL, 5, NULL),
-- Minior
(774, NULL, 1, NULL),
(774, NULL, 2, NULL),
(774, NULL, 3, NULL),
(774, NULL, 4, 'Canyon Biome, Chargestone Cavern, Coastal Biome, Polar Biome, Torchlit Labyrinth<br>Fixed: Canyon Biome, Polar Biome<br>Tera Raid Battles: 5 Star Raid Battles'),
(774, NULL, 5, 'Canyon Biome, Chargestone Cavern, Coastal Biome, Polar Biome, Torchlit Labyrinth<br>Fixed: Canyon Biome, Polar Biome<br>Tera Raid Battles: 5 Star Raid Battles'),
-- Komala
(775, NULL, 1, NULL),
(775, NULL, 2, NULL),
(775, NULL, 3, NULL),
(775, NULL, 4, 'East Province Area One, East Province Area Two, South Province Area One, Tagtree Thicket, West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
(775, NULL, 5, 'East Province Area One, East Province Area Two, South Province Area One, Tagtree Thicket, West Province Area Three<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Turtonator
(776, NULL, 1, 'Lake of Outrage<br>Max Raid Battles: Axew''s Eye, Dusty Bowl, Hammerlocke Hills, Rolling Fields, Stony Wilderness, Workout Sea, Honeycalm Sea, Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(776, NULL, 2, 'Trade from Pokémon Sword'),
(776, NULL, 3, NULL),
(776, NULL, 4, NULL),
(776, NULL, 5, NULL),
-- Togedemaru
(777, NULL, 1, 'Route 8, Lake of Outrage<br>Max Raid Battles: Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, Stony Wilderness<br>Dynamax Adventures'),
(777, NULL, 2, 'Route 8, Lake of Outrage<br>Max Raid Battles: Giant''s Mirror, Giant''s Seat, Hammerlocke Hills, Lake of Outrage, Motostoke Riverbank, Stony Wilderness<br>Dynamax Adventures'),
(777, NULL, 3, NULL),
(777, NULL, 4, NULL),
(777, NULL, 5, NULL),
-- Mimikyu
(778, NULL, 1, 'Bridge Field, Giant''s Mirror, Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Hammerlocke Hills, Rolling Fields, Battles: Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Dynamax Adventures'),
(778, NULL, 2, 'Bridge Field, Giant''s Mirror, Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Snowslide Slope, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Max Raid Battles: Hammerlocke Hills, Rolling Fields, Battles: Slippery Slope, Frostpoint Field, Giant''s Bed, Old Cemetery, Giant''s Foot, Frigid Sea, Three-Point Pass, Ballimere Lake<br>Dynamax Adventures'),
(778, NULL, 3, NULL),
(778, NULL, 4, 'East Province Area Two, Tagtree Thicket, West Province Area Three, Chilling Waterhead, Infernal Pass, Kitakami Wilds, Oni Mountain, Timeless Woods<br>Fixed: North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
(778, NULL, 5, 'East Province Area Two, Tagtree Thicket, West Province Area Three, Chilling Waterhead, Infernal Pass, Kitakami Wilds, Oni Mountain, Timeless Woods<br>Fixed: North Province Area Two<br>Tera Raid Battles: 5 Star Raid Battles , 6 Star Raid Battles'),
-- Bruxish
(779, NULL, 1, NULL),
(779, NULL, 2, NULL),
(779, NULL, 3, NULL),
(779, NULL, 4, 'East Paldean Sea, West Paldean Sea, Savanna Biome<br>Fixed: Canyon Biome, Coastal Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
(779, NULL, 5, 'East Paldean Sea, West Paldean Sea, Savanna Biome<br>Fixed: Canyon Biome, Coastal Biome<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Drampa
(780, NULL, 1, 'Trade from Pokémon Shield'),
(780, NULL, 2, 'Lake of Outrage<br>Max Raid Battles: Axew''s Eye, Rolling Fields, Workout Sea, Honeycalm Sea, Giant''s Bed, Path to the Peak, Frigid Sea, Three-Point Pass, Ballimere Lake'),
(780, NULL, 3, NULL),
(780, NULL, 4, NULL),
(780, NULL, 5, NULL),
-- Dhelmise
(781, NULL, 1, 'Route 9, Challenge Beach, Frigid Sea<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness'),
(781, NULL, 2, 'Route 9, Challenge Beach, Frigid Sea<br>Max Raid Battles: Bridge Field, Dappled Grove, Giant''s Mirror, Stony Wilderness'),
(781, NULL, 3, NULL),
(781, NULL, 4, NULL),
(781, NULL, 5, NULL),
-- Jangmo-o
(782, NULL, 1, 'Lake of Outrage, Challenge Road, Training Lowlands, Potbottom Desert<br>Max Raid Battles: Axew''s Eye, Rolling Fields, Loop Lagoon, Workout Sea, Honeycalm Sea'),
(782, NULL, 2, 'Trade from Pokémon Sword'),
(782, NULL, 3, NULL),
(782, NULL, 4, 'Kitakami Wilds, Paradise Barrens, Wistful Fields<br>Fixed: Paradise Barrens<br>Tera Raid Battles: 3 Star Raid Battles'),
(782, NULL, 5, 'Kitakami Wilds, Paradise Barrens, Wistful Fields<br>Fixed: Paradise Barrens<br>Tera Raid Battles: 3 Star Raid Battles'),
-- Hakamo-o
(783, NULL, 1, 'Lake of Outrage<br>Max Raid Battles: Axew''s Eye, Rolling Fields, Loop Lagoon, Workout Sea, Honeycalm Sea'),
(783, NULL, 2, 'Trade from Pokémon Sword'),
(783, NULL, 3, NULL),
(783, NULL, 4, 'Kitakami Wilds<br>Fixed: Oni Mountain<br>Tera Raid Battles: 4 Star Raid Battles'),
(783, NULL, 5, 'Kitakami Wilds<br>Fixed: Oni Mountain<br>Tera Raid Battles: 4 Star Raid Battles'),
-- Kommo-o
(784, NULL, 1, 'Dusty Bowl<br>Max Raid Battles: Axew''s Eye, Rolling Fields, Loop Lagoon, Workout Sea, Honeycalm Sea'),
(784, NULL, 2, 'Trade from Pokémon Sword'),
(784, NULL, 3, NULL),
(784, NULL, 4, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
(784, NULL, 5, 'Tera Raid Battles: 5 Star Raid Battles, 6 Star Raid Battles'),
-- Tapu Koko
(785, NULL, 1, 'Dynamax Adventures'),
(785, NULL, 2, 'Dynamax Adventures'),
(785, NULL, 3, NULL),
(785, NULL, 4, NULL),
(785, NULL, 5, NULL),
-- Tapu Lele
(786, NULL, 1, 'Dynamax Adventures'),
(786, NULL, 2, 'Dynamax Adventures'),
(786, NULL, 3, NULL),
(786, NULL, 4, NULL),
(786, NULL, 5, NULL),
-- Tapu Bulu
(787, NULL, 1, 'Dynamax Adventures'),
(787, NULL, 2, 'Dynamax Adventures'),
(787, NULL, 3, NULL),
(787, NULL, 4, NULL),
(787, NULL, 5, NULL),
-- Tapu Fini
(788, NULL, 1, 'Dynamax Adventures'),
(788, NULL, 2, 'Dynamax Adventures'),
(788, NULL, 3, NULL),
(788, NULL, 4, NULL),
(788, NULL, 5, NULL),
-- Cosmog
(789, NULL, 1, 'Freezington'),
(789, NULL, 2, 'Freezington'),
(789, NULL, 3, NULL),
(789, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(789, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Cosmoem
(790, NULL, 1, 'Evolve Cosmog'),
(790, NULL, 2, 'Evolve Cosmog'),
(790, NULL, 3, NULL),
(790, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(790, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Solgaleo
(791, NULL, 1, 'Dynamax Adventures'),
(791, NULL, 2, 'Trade from Pokémon Sword'),
(791, NULL, 3, NULL),
(791, NULL, 4, 'Pokémon League - Requires Snack from Snacksworth'),
(791, NULL, 5, 'Pokémon League - Requires Snack from Snacksworth'),
-- Lunala
(792, NULL, 1, 'Trade from Pokémon Shield'),
(792, NULL, 2, 'Dynamax Adventures'),
(792, NULL, 3, NULL),
(792, NULL, 4, 'Casseroya Lake - Requires Snack from Snacksworth'),
(792, NULL, 5, 'Casseroya Lake - Requires Snack from Snacksworth'),
-- Nihilego
(793, NULL, 1, 'Dynamax Adventures'),
(793, NULL, 2, 'Dynamax Adventures'),
(793, NULL, 3, NULL),
(793, NULL, 4, NULL),
(793, NULL, 5, NULL),
-- Buzzwole
(794, NULL, 1, 'Dynamax Adventures'),
(794, NULL, 2, 'Dynamax Adventures'),
(794, NULL, 3, NULL),
(794, NULL, 4, NULL),
(794, NULL, 5, NULL),
-- Pheromosa
(795, NULL, 1, 'Dynamax Adventures'),
(795, NULL, 2, 'Dynamax Adventures'),
(795, NULL, 3, NULL),
(795, NULL, 4, NULL),
(795, NULL, 5, NULL),
-- Xurkitree
(796, NULL, 1, 'Dynamax Adventures'),
(796, NULL, 2, 'Dynamax Adventures'),
(796, NULL, 3, NULL),
(796, NULL, 4, NULL),
(796, NULL, 5, NULL),
-- Celesteela
(797, NULL, 1, 'Dynamax Adventures'),
(797, NULL, 2, 'Dynamax Adventures'),
(797, NULL, 3, NULL),
(797, NULL, 4, NULL),
(797, NULL, 5, NULL),
-- Kartana
(798, NULL, 1, 'Dynamax Adventures'),
(798, NULL, 2, 'Dynamax Adventures'),
(798, NULL, 3, NULL),
(798, NULL, 4, NULL),
(798, NULL, 5, NULL),
-- Guzzlord
(799, NULL, 1, 'Dynamax Adventures'),
(799, NULL, 2, 'Dynamax Adventures'),
(799, NULL, 3, NULL),
(799, NULL, 4, NULL),
(799, NULL, 5, NULL),
-- Necrozma
(800, NULL, 1, 'Dynamax Adventures'),
(800, NULL, 2, 'Dynamax Adventures'),
(800, NULL, 3, NULL),
(800, NULL, 4, 'Socarrat Trail - Requires Snack from Snacksworth'),
(800, NULL, 5, 'Socarrat Trail - Requires Snack from Snacksworth'),
-- Magearna
(801, NULL, 1, 'Event Only'),
(801, NULL, 2, 'Event Only'),
(801, NULL, 3, NULL),
(801, NULL, 4, 'Transfer from Pokémon HOME or obtain from event'),
(801, NULL, 5, 'Transfer from Pokémon HOME or obtain from event'),
-- Marshadow
(802, NULL, 1, 'Transfer from Pokémon HOME or obtain from event'),
(802, NULL, 2, 'Transfer from Pokémon HOME or obtain from event'),
(802, NULL, 3, NULL),
(802, NULL, 4, NULL),
(802, NULL, 5, NULL),
-- Poipole
(803, NULL, 1, 'Max Lair'),
(803, NULL, 2, 'Max Lair'),
(803, NULL, 3, NULL),
(803, NULL, 4, NULL),
(803, NULL, 5, NULL),
-- Naganadel
(804, NULL, 1, 'Evolve Poipole'),
(804, NULL, 2, 'Evolve Poipole'),
(804, NULL, 3, NULL),
(804, NULL, 4, NULL),
(804, NULL, 5, NULL),
-- Stakataka
(805, NULL, 1, 'Dynamax Adventures'),
(805, NULL, 2, 'Dynamax Adventures'),
(805, NULL, 3, NULL),
(805, NULL, 4, NULL),
(805, NULL, 5, NULL),
-- Blacephalon
(806, NULL, 1, 'Dynamax Adventures'),
(806, NULL, 2, 'Dynamax Adventures'),
(806, NULL, 3, NULL),
(806, NULL, 4, NULL),
(806, NULL, 5, NULL),
-- Zeraora
(807, NULL, 1, 'Transfer through Pokémon HOME or through events'),
(807, NULL, 2, 'Transfer through Pokémon HOME or through events'),
(807, NULL, 3, NULL),
(807, NULL, 4, NULL),
(807, NULL, 5, NULL),
-- Meltan
(808, NULL, 1, 'Transfer through Pokémon HOME or through events'),
(808, NULL, 2, 'Transfer through Pokémon HOME or through events'),
(808, NULL, 3, NULL),
(808, NULL, 4, NULL),
(808, NULL, 5, NULL),
-- Melmetal
(809, NULL, 1, 'Transfer through Pokémon HOME or through events'),
(809, NULL, 2, 'Transfer through Pokémon HOME or through events'),
(809, NULL, 3, NULL),
(809, NULL, 4, NULL),
(809, NULL, 5, NULL);

COMMIT TRANSACTION;